### ISSUE TITLE
Error "401 Authorization required" when querying methods involving relations

### ISSUE THREAD

**Issue by samuele-artuso** [strongloop/loopback#426] opened 2014-07-31 20:28 UTC
I've recently migrated an application to LoopBack 2.0.

All my models require user authentication and have these ACLs:

```
    "acls": [
      {
        "accessType": "*",
        "permission": "DENY",
        "principalType": "ROLE",
        "principalId": "$everyone"
      },
      {
        "accessType": "READ",
        "permission": "ALLOW",
        "principalType": "ROLE",
        "principalId": "$authenticated"
      }
    ]
```

I have a model called `issues`. After logging in through the POST method `/Users/login`:
 * I don't have any problems when calling the GET method `/issues`. I get a list of issues as expected;
 * When I query a method involving a relation between two models (e.g. GET `/issues/{id}/categories`), I get the error `401 Authorization required`. The same model used to work in Loopback 1.0.

Any clues?

**Comment by SwadhyayStudios** [comment] 2015-01-31 18:26
Is this resolved ? I am still having the same issue
The last thread doesn't help

**Comment by SwadhyayStudios** [comment] 2015-01-31 18:41
[ { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'DENY' },
  { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW',
    property: 'create' },
  { principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW',
    property: 'deleteById' },
  { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW',
    property: 'login' },
  { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW',
    property: 'logout' },
  { principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW',
    property: 'findById' },
  { principalType: 'ROLE',
    principalId: '$owner',
    permission: 'ALLOW',
    property: 'updateAttributes' },
  { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW',
    property: 'confirm' },
  { principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW',
    property: 'resetPassword',
    accessType: 'EXECUTE' },
  { accessType: '*',
    principalType: 'ROLE',
    principalId: '$everyone',
    permission: 'ALLOW' } ]

**Comment by rubentorresbonet** [comment] 2015-02-07 13:16
Something that helped me with ACL and relations is to run "DEBUG=loopback:security:* slc run" and then check the property it is trying to access.
At first I tried adding ACL to the "orders" property (since it was like  /users/2/orders) but it seems like the ACL resolver tried to access this property: __get__orders.
I set that in my json acl file and it is working like a charm.

Example:
  "acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "__get__orders"
    }

**Comment by superkhau** [comment] 2015-02-26 05:08
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by LetsDoIt-** [comment] 2015-02-26 06:07
@rubentorresbonet  the acl that you defined with the property __get__orders is for which model? 
Is it for the user model or for the orders model?

**Comment by rubentorresbonet** [comment] 2015-02-26 07:59
@LetsDoIt- Have a look here: http://docs.strongloop.com/display/public/LB/Restricting+access+to+related+models

**Comment by jdhiro** [comment] 2015-08-02 21:17
@rubentorresbonet Holy cow, that worked! I had to use the property "__get__customer" for a relationship named "customer". Thanks!

`DEBUG=loopback:security:* slc run` really helped me understand what was happening with the ACLs.

This can't possibly be the intended design.

**Comment by csvan** [comment] 2015-09-10 07:09
Agree with @jdhiro that from a design perspective, this is very uncomfortable. Would it not be better to introduce a single declaration in order to to set R/W/X privileges on a single relation, just as we can do for other built-in methods?

**Comment by csvan** [comment] 2015-09-10 07:10
By the way, the link to the documentation for accessing related models provided above is broken, the correct one is here:

https://docs.strongloop.com/display/public/LB/Accessing+related+models

**Comment by mike-aungsan** [comment] 2015-10-23 01:28
I spent a few hours on this too. Doc is not clear. It should clearly mention that default is denied

**Comment by superkhau** [comment] 2015-10-23 02:14
@crandmck ^

**Comment by vnathalye** [comment] 2015-10-23 11:07
While trying CoffeeShop example given at [https://docs.strongloop.com/display/LB/Getting+started+part+II](https://docs.strongloop.com/display/LB/Getting+started+part+II) I'm getting 401 only while editing the review. I've the ACLs defined as given @ [https://docs.strongloop.com/display/public/LB/Define+access+controls](https://docs.strongloop.com/display/public/LB/Define+access+controls)

So the following ACL entry is failing:
>    {
>      "accessType": "WRITE",
>      "principalType": "ROLE",
>      "principalId": "$owner",
>      "permission": "ALLOW"
>    }

If I change $owner to $authenticated, then I don't get 401. So there seems to be some problem in isOwner().
I've tried using `DEBUG=loopback:security:*` and it gives following output

>  loopback:security:access-context ---AccessContext--- +1ms
>  loopback:security:access-context principals: +3ms
>  loopback:security:access-context principal: {"type":"USER","id":"562a105037cfea381ac14fbb"} +2ms
>  loopback:security:access-context modelName Review +3ms
>  loopback:security:access-context modelId 562a105037cfea381ac14fbe +1ms
>  loopback:security:access-context property upsert +1ms
>  loopback:security:access-context method upsert +2ms
>  loopback:security:access-context accessType WRITE +1ms
>  loopback:security:access-context accessToken: +2ms
>  loopback:security:access-context   id "EoEwOGWIWLNfw4DLgxf9ga2zCoFht974DgCccMFkQLmLrmnQJ64eHJidDIf4e8dh" +1ms
>  loopback:security:access-context   ttl 1209600 +3ms
>  loopback:security:access-context getUserId() 562a105037cfea381ac14fbb +2ms
>  loopback:security:access-context isAuthenticated() true +3ms
>  loopback:security:role Custom resolver found for role $everyone +0ms
>  loopback:security:role isInRole(): $everyone +2ms
>  loopback:security:access-context ---AccessContext--- +1ms
>  loopback:security:access-context principals: +1ms
>  loopback:security:access-context principal: {"type":"USER","id":"562a105037cfea381ac14fbb"} +1ms
>  loopback:security:access-context modelName Review +2ms
>  loopback:security:access-context modelId 562a105037cfea381ac14fbe +1ms
>  loopback:security:access-context property upsert +1ms
>  loopback:security:access-context method upsert +3ms
>  loopback:security:access-context accessType WRITE +1ms
>  loopback:security:access-context accessToken: +1ms
>  loopback:security:access-context   id "EoEwOGWIWLNfw4DLgxf9ga2zCoFht974DgCccMFkQLmLrmnQJ64eHJidDIf4e8dh" +2ms
>  loopback:security:access-context   ttl 1209600 +2ms
>  loopback:security:access-context getUserId() 562a105037cfea381ac14fbb +2ms
>  loopback:security:access-context isAuthenticated() true +1ms
>  loopback:security:role Custom resolver found for role $everyone +1ms
>  loopback:security:role isInRole(): $owner +2ms
>  loopback:security:access-context ---AccessContext--- +1ms
>  loopback:security:access-context principals: +2ms
>  loopback:security:access-context principal: {"type":"USER","id":"562a105037cfea381ac14fbb"} +2ms
>  loopback:security:access-context modelName Review +2ms
>  loopback:security:access-context modelId 562a105037cfea381ac14fbe +2ms
>  loopback:security:access-context property upsert +1ms
>  loopback:security:access-context method upsert +1ms
>  loopback:security:access-context accessType WRITE +2ms
>  loopback:security:access-context accessToken: +1ms
>  loopback:security:access-context   id "EoEwOGWIWLNfw4DLgxf9ga2zCoFht974DgCccMFkQLmLrmnQJ64eHJidDIf4e8dh" +2ms
>  loopback:security:access-context   ttl 1209600 +2ms
>  loopback:security:access-context getUserId() 562a105037cfea381ac14fbb +1ms
>  loopback:security:access-context isAuthenticated() true +2ms
>  loopback:security:role Custom resolver found for role $owner +2ms
>  loopback:security:role **isOwner()**: Review **562a105037cfea381ac14fbe** userId: **562a105037cfea381ac14fbb** +2ms
>  loopback:security:role Model found: {"date":"2015-10-19T10:47:44.791Z","rating":5,"comments":"A very good coffee shop.","id":"**562a105037cfea381ac14fbe**","coffeeShopId":"562a105037cfea381ac14fb8","publisherId":"**562a105037cfea381ac14fbb**"} +5ms
>  loopback:security:role Checking relation reviewer to Reviewer: {"name":"reviewer","type":"belongsTo","modelFrom":"Review","keyFrom":"pulisherId","modelTo":"Reviewer","keyTo":"id","multiple":false} +4ms
>  loopback:security:acl The following ACLs were searched:  +4ms
>  loopback:security:acl ---ACL--- +1ms
>  loopback:security:acl model Review +2ms
>  loopback:security:acl property * +1ms
>  loopback:security:acl principalType ROLE +1ms
>  loopback:security:acl principalId $everyone +1ms
>  loopback:security:acl accessType * +1ms
>  loopback:security:acl permission DENY +2ms
>  loopback:security:acl with score: +1ms 7495
>  loopback:security:acl ---ACL--- +1ms
>  loopback:security:acl model Review +1ms
>  loopback:security:acl property * +1ms
>  loopback:security:acl principalType ROLE +1ms
>  loopback:security:acl principalId $everyone +2ms
>  loopback:security:acl accessType READ +1ms
>  loopback:security:acl permission ALLOW +1ms
>  loopback:security:acl with score: +1ms -1
>  loopback:security:acl ---Resolved--- +1ms
>  loopback:security:access-context ---AccessRequest--- +1ms
>  loopback:security:access-context  model Review +2ms
>  loopback:security:access-context  property upsert +1ms
>  loopback:security:access-context  accessType WRITE +1ms
>  loopback:security:access-context  permission DENY +1ms
>  loopback:security:access-context  isWildcard() false +2ms
>  loopback:security:access-context  isAllowed() **false** +2ms

**Comment by crandmck** [comment] 2015-10-28 23:36
@mike-aungsan I added a note to https://docs.strongloop.com/display/LB/Accessing+related+models#Accessingrelatedmodels-note.
Please let me know if there's any issue with it.

**Comment by mike-aungsan** [comment] 2015-10-28 23:58
@crandmck Many Thanks

**Comment by superkhau** [comment] 2016-02-04 19:48
Are you guys still running into issues? Can I close this?

**Comment by jdhiro** [comment] 2016-02-04 19:54
The design seems undesirable, but as long as the design is documented (and it looks like it is from @crandmck post), I don't see a problem closing it. I worked around it in my project -- no longer an immediate concern.

**Comment by superkhau** [comment] 2016-02-04 20:00
@jdhiro Sounds good. Please open a new issue if you guys are still running into issues. Better yet, submit a patch and we can go from there.

**Closed by superkhau** 2016-02-04 20:00 UTC
Labels: doc

**Comment by gekko68** [comment] 2016-02-04 20:10
Yes - i do 

sorry for this question but how do I enable the debug view  ?

"You can run the application with DEBUG enabled:

$ DEBUG=loopback:security:* node . "

Thanks,

**Comment by superkhau** [comment] 2016-02-04 20:40
>sorry for this question but how do I enable the debug view ?

What do you mean debug view? Run `DEBUG=loopback:security:* node .` when starting your loopback app.

**Comment by gekko68** [comment] 2016-02-05 08:49
Hi,
got it working. Thx. U just run the application DEBUG=loopback:security:* node . on commandline .

**Comment by emazzu** [comment] 2017-10-26 00:00
somebody can help me ? with the same themes ?

**Comment by emazzu** [comment] 2017-10-26 00:00
if somebody can help me, I send the problem !!!

**Comment by crandmck** [comment] 2017-10-26 17:37
https://loopback.io/doc/en/contrib/Reporting-issues.html#dont-use-an-issue-to-ask-a-question

**Comment by emazzu** [comment] 2017-10-26 18:40
Execuse me, but on gitter nobody responds, and I cant resolve the problem, I dont know what I can do !!!

**Comment by princecharmx** [comment] 2017-11-03 14:32
@emazzu  @crandmck , i think this problem has come again in the latest repo. @raymondfeng , please look into it. This exposes the security loophole for the app in production. https://github.com/strongloop/loopback/issues/3518

**Comment by princecharmx** [comment] 2017-11-23 09:39
@emazzu , @crandmck @raymondfeng  , this problem is only with custom access token. I reverted to loopback AccessToken model than it started working as intended.
