### ISSUE TITLE
Bug with filter include in scoped endpoints

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback#2113] opened 2016-03-01 22:49 UTC
pick this model

```
{
  "name": "Dish",
  "plural": "Dishes",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "mysql": {
      "table": "Dishes"
    }
  },
  "scopes": {
    "frontend": {
      "where": {
        "draft": false
      },
      "include": "category",
      "order": "order ASC"
    }
  },
  "scope": {
    "order": "order ASC"
  },
  "properties": {
    "price": {
      "type": "number"
    },
    "draft": {
      "type": "boolean"
    },
    "order": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
    "langs": {
      "type": "hasMany",
      "model": "DishLang",
      "foreignKey": "langOwnerId"
    },
    "category": {
      "type": "belongsTo",
      "model": "DishCategory",
      "foreignKey": "categoryId"
    }
  },
  "acls": [],
  "methods": {}
}
```

when I query this endpoint with this filter all goes right -->
/dishes?filter={ "include":"langs" }

but when i call 
/dishes/frontend?filter={ "include":"langs" }
i got this error

```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Relation \"langs\" is not defined for DishCategory model",
    "stack": "Error: Relation \"langs\" is not defined for DishCategory model\n    at processIncludeItem (D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\lib\\include.js:204:10)\n    at D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\lib\\include.js:173:5\n    at D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:157:13\n    at _each (D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:57:9)\n    at Object.async.each (D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:156:9)\n    at Function.Inclusion.include (D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\lib\\include.js:172:9)\n    at subIncludesTask (D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\lib\\include.js:803:30)\n    at D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:723:21\n    at D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:391:17\n    at D:\\Giovanni Bruno\\Repo\\SF-La-Francesca-Api\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:157:13"
  }
}
```

**Comment by giowe** [comment] 2016-03-02 06:50
deleting the  "include": "category" key in "frontend" scope the problem disappear. I think the bug appears when the system tryes to merge Filter inclusions with pre-existent scopes inclusions

**Comment by jannyHou** [comment] 2016-04-05 20:31
@giowe I created a simple app to reproduce your problem but the scenario works for me:
```
{
  "name": "test",
  "base": "PersistedModel",
  "idInjection": true,
  "scopes": {
    "myscope": {
      "where": {
        "isName": false
      },
      "include": "testtwo"
    }
  },
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "isName": {
      "type": "boolean"
    }
  },
  "validations": [],
  "relations": {
    "testsubs": {
      "type": "hasMany",
      "model": "testsub",
      "foreignKey": ""
    },
    "testtwo": {
      "type": "belongsTo",
      "model": "testtwo",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}

```
Go to explorer:
/tests/myscope?filter={ "include":"testsubs" }
The response body is an empty array since I didn't put any sample data. But no errors like you reported.
Could you try it again? If you still have problem, please fork https://github.com/strongloop/loopback-sandbox and replace with your code, thanks!

**Comment by jannyHou** [comment] 2016-11-03 20:53
I am closing it since I could not reproduce. Please feel free to reopen it with a sample code. Thanks.

**Closed by jannyHou** 2016-11-03 20:53 UTC
Labels: triage, waiting
