### ISSUE TITLE
Getting current user id fails on server but works in local

### ISSUE THREAD

**Issue by kpasokhi** [strongloop/loopback#1921] opened 2015-12-29 03:18 UTC
I'm trying to get current user id based on [Using current context](https://docs.strongloop.com/display/public/LB/Using+current+context) wiki article. I've changed the code to this:
```javascript
app.use(loopback.context());
app.use(loopback.token());

app.use(function setCurrentUser(req, res, next) {
  if (!req.accessToken) {
    return next();
  } else {
    var loopbackContext = loopback.getCurrentContext();
    if (loopbackContext) {
      loopbackContext.set('uid', req.accessToken.userId);
    }
    next();
  }
});
```

in model.js:
```javascript
	function getCurrentUserId() {
	    var ctx = loopback.getCurrentContext();
	    var userId = ctx && ctx.get('uid');
	    return userId;
	}
```
I also set enableHttpContext to true. The problem is it works on my local machine but it doesn't  work on the server. I tried running with production node environment in local and nothing changed.
Thanks in advance

**Comment by jannyHou** [comment] 2016-01-08 21:02
hey @kpasokhi I am trying to reproduce your issue but it's hard to do it without detail information of your server....can you provide more info about your server?
eg. node, npm, strongloop version, etc.
Thank you!

**Comment by jannyHou** [comment] 2016-04-05 20:44
I am closing it since info provided is not enough to reproduce the issue.
If anyone run into similar issue or could provide more details, please feel free to reopen it:)
Thanks for understanding

**Closed by jannyHou** 2016-04-05 20:44 UTC
Labels: triage, waiting
