### ISSUE TITLE
Add utility functions for queries: startsWith, endsWith, contains

### ISSUE THREAD

**Issue by slawo** [strongloop/loopback#964] opened 2015-01-01 22:06 UTC
Every-time, or nearly, I have a search form on a text field there are only 2 kinds operations which happen `UPPER(someField) LIKE UPPER(%?)` and `UPPER(someField) LIKE UPPER(%?%)`. This is a near constant in all projects.

Therefore it would be very interesting to have very simple operators to do this kind of searches: 

 - `contains` and case insensitive `icontains`
 - `starts` and case insensitive `istarts`

And for good mesure:

 - `ends` and case insensitive `iends`

Those functions are way simpler to implement across all databases than a standardised wildcard for `like` and a (hypothetical) case insensitive `ilike`.
This would simplify the querying from the client side as there would be only one syntax for those simple searches where the current syntax for `like` is dependent on the backend.

**Comment by wpjunior** [comment] 2015-01-02 09:23
+1

**Comment by raymondfeng** [comment] 2015-02-05 23:58
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/385. A new `regexp` operator should cover these use cases.

**Closed by raymondfeng** 2015-02-05 23:58 UTC
Labels: feature

**Comment by slawo** [comment] 2015-02-06 10:16
Not necessarily. While using regexp would cover this in most cases it will not in fact work  in setups where regular expressions are not enabled on the backend.

More important is the fact that they are very simple to implement and add immediate value to the framework

**Comment by slawo** [comment] 2015-02-11 11:49
@raymondfeng: Not necessarily. While using regexp would cover this in most cases it will not in fact work in setups where regular expressions are not enabled on the backend.

More important is the fact that they are very simple to implement and add immediate value to the framework

**Comment by slawo** [comment] 2015-02-25 11:26
@raymondfeng Actually could you reopen this issue? regexp is not available with sqlite by default, making this a real issue for adapting additional connectors where regexp is not available. 

Those functions might seem redundant but they are not and they don't add much clutter/overhead to the library.
