### ISSUE TITLE
Case-sensitivity of 'arg' in remoteMethod

### ISSUE THREAD

**Issue by james-relyea** [strongloop/loopback#2517] opened 2016-07-19 18:18 UTC
[Loopback documentation](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Argumentdescriptions) states that the type property of an argument for a remote method "_must be a Loopback type_".

The documentation for [Loopback types](https://docs.strongloop.com/display/public/LB/LoopBack+types) further states that the type is case-_insensitive_.

However, I used _Boolean_ as a type for the following argument parameter in my remoteMethod:

`{arg: 'favourite', type: "Boolean", required: true}`

And it resulted in the _favourite_ value always being set to true regardless of what the formData specified.

When I used _boolean_ for the type, it set the value accordingly. I presume the strong-remoting/shared-method library only uses lowercase for the types?

The documentation should be updated to address this inconsistency with type declarations.

**Comment by superkhau** [comment] 2016-07-19 19:26
@crandmck ^

**Comment by crandmck** [comment] 2016-07-19 23:48
The note in the docs is explicit:
>  The type name is case-insensitive; so for example you can use either "Number" or "number."

That is, I was specifically told to add this at some point...

So either:
1. It was true when I added it, but that has changed and it's no longer true.
1. There is a bug, and it _should_ be true, but is not (at least for Boolean).

@superkhau Do we have any tests or examples that would indicate which of the above is the case?
@raymondfeng Any comments?  Are type names intended to be case-insensitive, as documented?

**Comment by james-relyea** [comment] 2016-07-20 18:30
Just sharing some more info on this. This is a test model I used:

```
 module.exports = function(Test) {
  Test.favourite = function(favourite, favourite2, cb) {
    cb(null, {favourite: favourite, favourite2: favourite2});
  };

  Test.remoteMethod('favourite', {
    accepts: [
      {arg: 'favourite', type: 'boolean'},
      {arg: 'favourite2', type: 'Boolean'}
    ],
    returns: [
      {arg: 'favourite', type: 'boolean'},
      {arg: 'favourite2', type: 'Boolean'}
    ]
  });
};
```

Running the following request with a value of _false_ for both _favourite_ and _favourite2_:
`curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Accept: application/json" -d "favourite=false&favourite2=false" "http://localhost:3000/api/tests/favourite"`

I see this in the log:
```
strong-remoting:shared-method - favourite - invoke with +15ms [ false, true, [Function: callback] ]
strong-remoting:shared-method - favourite - result {"favourite":{"favourite":false,"favourite2":true}} +2ms
````

And this is the response body:
```
{
  "favourite": {
    "favourite": false,
    "favourite2": true
  }
}
```

**Comment by superkhau** [comment] 2016-07-20 21:28
>Do we have any tests or examples that would indicate which of the above is the case?

Not sure, but I'm fairly sure the intent was to keep it case-insensitive.

@james-relyea Can you try to setting type to Boolean (without the double quotes). It's probably being set to true because it thinks the value is a String. Anyways, it sounds like a bug but I would like to confirm if that is the case. Please provide a sample repo so we can clone it on our end to verify. @richardpringle @gunjpan I'll leave it up to you guys to take this over.

**Comment by james-relyea** [comment] 2016-07-21 03:59
I tried with `type: Boolean` and it seems to set its type to object. Throws an error:

```
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "invalid value for argument 'favourite2' of type 'object': false. Received type was boolean. Error: favourite2 must be object",
    "statusCode": 400,
    "stack": "Error: invalid value for argument 'favourite2' of type 'object': false. Received type was boolean. Error: favourite2 must be object\n    at new badArgumentError (/Users/jrelyea/issue-2517/node_modules/strong-remoting/lib/shared-method.js:277:13)\n    at coerceAccepts (/Users/jrelyea/issue-2517/node_modules/strong-remoting/lib/shared-method.js:333:13)\n    at SharedMethod.invoke (/Users/jrelyea/issue-2517/node_modules/strong-remoting/lib/shared-method.js:226:16)\n    at HttpContext.invoke (/Users/jrelyea/issue-2517/node_modules/strong-remoting/lib/http-context.js:390:12)\n    at phaseInvoke (/Users/jrelyea/issue-2517/node_modules/strong-remoting/lib/remote-objects.js:654:9)\n    at runHandler (/Users/jrelyea/issue-2517/node_modules/loopback-phase/lib/phase.js:135:5)\n    at iterate (/Users/jrelyea/issue-2517/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/Users/jrelyea/issue-2517/node_modules/async/lib/async.js:162:9)\n    at runHandlers (/Users/jrelyea/issue-2517/node_modules/loopback-phase/lib/phase.js:144:13)\n    at iterate (/Users/jrelyea/issue-2517/node_modules/async/lib/async.js:146:13)"
  }
}
```

**Comment by richardpringle** [comment] 2016-07-21 15:51
@crandmck: this is a confirmed bug, not a doc issue

**Comment by richardpringle** [comment] 2016-07-21 15:57
Creating a new issue in `Strong-remoting`: strongloop/strong-remoting#326

**Comment by richardpringle** [comment] 2016-09-13 18:08
fixed by https://github.com/strongloop/strong-remoting/commit/6aaafd054c48677180945e19e459246ba3027156

**Closed** 2016-09-13 18:08 UTC
Labels: bug, remoting
