### ISSUE TITLE
Error when confirm a user registration (Users/confirm)

### ISSUE THREAD

**Issue by baldiri** [strongloop/loopback#2217] opened 2016-04-10 20:06 UTC
After receive an email when i register as new user, i try to confirm email address with the link inside mail but i get next error:

{"error":{"name":"Error","status":500,"message":"ER_FIELD_SPECIFIED_TWICE: Column 'lastUpdated' specified twice","code":"ER_FIELD_SPECIFIED_TWICE","errno":1110,"sqlState":"42000","index":0,"stack":"Error: ER_FIELD_SPECIFIED_TWICE: Column 'lastUpdated' specified twice\n    at Query.Sequence._packetToError (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)\n    at Query.ErrorPacket (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)\n    at Protocol._parsePacket (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)\n    at Parser.write (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)\n    at Protocol.write (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n    at Socket.<anonymous> (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:96:28)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    --------------------\n    at Protocol._enqueue (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)\n    at PoolConnection.query (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Connection.js:201:25)\n    at runQuery (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/lib/mysql.js:146:16)\n    at executeWithConnection (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/lib/mysql.js:188:7)\n    at Ping.onOperationComplete (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/Pool.js:99:5)\n    at Ping.<anonymous> (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback/node_modules/continuation-local-storage/context.js:76:17)\n    at bound (domain.js:287:14)\n    at Ping.runBound [as _callback] (domain.js:300:12)\n    at Ping.Sequence.end (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)\n    at Ping.Sequence.OkPacket (/Users/baldiri/Documents/Node/loopback-vecu/node_modules/loopback-connector-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)"}}

i think i'm using last version of loopback-connector-mysql, 2.2.1, but always i get the mentioned error.

i get same error when i confirm a new user through api explorer¿?¿

Any ideas? 

Thanks a lot in advance!

**Comment by loay** [comment] 2016-04-21 22:07
Hi @baldiri 
Can you please provide a link  to your app so I can reproduce the error and work on it?
Thanks.

**Comment by baldiri** [comment] 2016-04-22 07:47
Hi @loay

my app is a closed system, what i mean is that you must log in first and then when you are logged, you can create new users who must validate email address.

I have no problem to give you access to app so you can reproduce the problem but i would like to send you url and values to login through email. Where can i email you?

Thanks in advance!

**Comment by loay** [comment] 2016-06-17 16:02
Hi @baldiri 
This issue should be fixed now. Please give it a try. 
In case it doesn't work, , please create a private gist and share it with me. It is best to keep the discussion going somewhere.

**Comment by loay** [comment] 2016-06-17 16:48
Please feel free to leave a comment if the issue persists and I will re-open the issue.

**Closed by loay** 2016-06-17 16:48 UTC
Labels: triage

**Comment by mayorbrain** [comment] 2016-08-03 11:02
Hi @loay  May I know what the problem was? I am experiencing the same issue

**Comment by loay** [comment] 2016-08-03 19:16
Hi @mayorbrain 
Can you please share a link to your github repo? Thanks.

**Comment by emazzu** [comment] 2016-08-09 20:13
One question ?

The documentation says that   LoopBack sets values for emailVerified and verificationToken.

But I don't understand if the email is sendind by loopback automatically ?? or not ??


/users
POST	Allow	
Add user instance and persist to data source. Inherited from PersistedModel API.
JSON object (in request body) providing User object properties: username, password, email. LoopBack sets values for emailVerified and verificationToken.
NOTE: A value for username is not required, but a value for email is. LoopBack validates a unique value for password is provided. LoopBack does not automatically maintain values of the created and lastUpdated properties; you can set them manually if you wish.
