### ISSUE TITLE
Model Validation on inheritance

### ISSUE THREAD

**Issue by Kr0san89** [strongloop/loopback#1500] opened 2015-07-03 08:00 UTC
Hello,

i'm wondering why the validation is not working on inheritance of Models

I have two models one inheritance from the other. The Overall inheritance is fine, but the validation rules are not working on the inheritanced Model. Can you implement this? Would spare a lot of Code duplication.

thanks

**Comment by Nutelac** [comment] 2015-07-10 17:32
Duplicate of https://github.com/strongloop/loopback/issues/1485.

**Closed** 2015-08-13 21:26 UTC
Labels: feature
