### ISSUE TITLE
Not all methods implemented when using remote connector

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#491] opened 2014-08-24 14:15 UTC
Running in the browser, with a remote dataSource, I see errors like: 

Cannot call Todo.destroy(). The destroy method has not been setup.

**Comment by bitmage** [comment] 2015-03-24 01:07
I'm still not able to call Model.deleteById() or instance.delete().  npm ls:

```text
├─┬ loopback@2.14.0
│ ├── loopback-connector-remote@1.0.3
│ ├─┬ strong-remoting@2.14.0
```

When I call:

```javascript
lbclient.models.MyModel.destroyById(1, function(err, result){console.log('err:', err, 'result:', result)})
```

I get:

```text
"Error: Cannot call MyModel.deleteById(). The deleteById method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
    at throwNotAttached (persisted-model.js:56)
    at Function.deleteById (persisted-model.js:278)
    ...
```

Find and save functionality work fine however.

Where does this code need to be implemented?

**Comment by bajtos** [comment] 2015-03-24 11:02
"deleteById" is registered here: https://github.com/strongloop/loopback/blob/df770455eb84a3b1919a1d71c2002206967d1e52/lib/persisted-model.js#L617-L624

"deleteAll" is intentionally described as `shared: false`, because deleting all records is a pretty dangerous operation 

"prototype.delete" does not seem to be registered with remoting.

The "deleteById" problem is most likely caused by https://github.com/strongloop/loopback-connector-remote/issues/14.

**Comment by bajtos** [comment] 2015-03-24 11:03
@bitmage Workaround: call `lbclient.models.MyModel.deleteById` instead.

**Comment by gruzilla** [comment] 2015-06-29 19:05
i tried the workaround and it still does not work.

unfortunately i'm unsure if i configured something in the wrong way?


```
├─┬ loopback@2.18.0
│ ├── loopback-connector-remote@1.0.3
│ ├─┬ strong-remoting@2.19.0
```

```
app.models.WorklogSession.deleteById(2)
browser.bundle.js:62657 Uncaught TypeError: Cannot read property 'apply' of undefined
```

```
worklogs[0].delete()
browser.bundle.js:56148 Uncaught Error: Cannot call WorklogSession.destroy(). The destroy method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
    at throwNotAttached (http://localhost:3000/js/browser.bundle.js:56148:11)
    at ModelConstructor.module.exports.PersistedModel.destroy (http://localhost:3000/js/browser.bundle.js:56497:5)
    at <anonymous>:2:19
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

server/model-config.json
```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models"
    ]
  },
  "WorklogSession": {
    "dataSource": "db",
    "public": true
  },
```

lbclient/model-config.json
```
{
  "_meta": {
    "sources": [
      "../common/models",
      "./models"
    ]
  },
  "WorklogSession": {
    "dataSource": "remote"
  },
```

common/models/worklog-session.json
```
{
  "name": "WorklogSession",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
........stripped........
  },
  "validations": [],
  "relations": {
........stripped........
  },
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    },
    {
      "accessType": "REPLICATE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ],
  "methods": []
}
```

**Comment by bitmage** [comment] 2015-06-29 20:24
DeleteById is not a good solution for me.  In my case I am clearing data in setup/teardown steps for testing.  DeleteById would require a lot of unnecessary querying and iteration.

If a method is dangerous, print a warning, don't disable it.  In addition to being dangerous it's also useful.

**Comment by raymondfeng** [comment] 2015-06-29 20:28
You should be able to set up the remoting in your model class as follows:
```js
MyModel.remoteMethod('destroyAll', {
    isStatic: true,
    description: 'Delete all matching records',
    accessType: 'WRITE',
    accepts: {arg: 'where', type: 'object', description: 'filter.where object'},
    http: {verb: 'del', path: '/'}
  });
```

**Comment by bitmage** [comment] 2015-06-30 00:58
Oh my bad.  I totally didn't re-read the ticket.  Disregard my comment about testing.  Any workaround that would allow DeleteById to work from client side would be sufficent for me.

**Comment by gruzilla** [comment] 2015-06-30 15:53
I also have to apologize.

this **does** work:
```javascript
app.models.WorklogSession.deleteById(3, function() {console.log('done')})
```

**Comment by billinghamj** [comment] 2015-07-28 10:17
This line seems like it might be causing this issue:

https://github.com/strongloop/loopback-connector-remote/blob/71521b12a3e0800114ffeb79f29a87491e2bb87f/lib/relations.js#L205

it is currently:

```js
scope.deleteById = destroyById = function
```

should it not be this?

```js
scope.deleteById = scope.destroyById = function
```

**Comment by billinghamj** [comment] 2015-07-28 10:19
Also what's the difference between doing `instance.delete()` and `instance.destroy()`? Delete seems to work for me, whereas destroy throws this error:

```Error: Cannot call model.destroy(). The destroy method has not been setup. The PersistedModel has not been correctly attached to a DataSource!```

**Comment by jbcpollak** [comment] 2016-10-20 19:34
I just ran into this with `destroyAll()` - I can't believe this is still open 2 years later:

```
    Error: Cannot call Model.destroyAll(). The destroyAll method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
        at throwNotAttached (/Users/jpollak/src/task_coordinator/node_modules/loopback/lib/persisted-model.js:68:11)
        at Function.destroyAll (/Users/jpollak/src/task_coordinator/node_modules/loopback/lib/persisted-model.js:306:5)
```

**Comment by jbcpollak** [comment] 2016-10-20 20:00
@raymondfeng using your workaround I get this error message:

```
    Error: Shared class  "Model" has no method handling DELETE /
        at restRemoteMethodNotFound (/Users/jpollak/src/map_manager/node_modules/strong-remoting/lib/rest-adapter.js:345:17)
        at Layer.handle [as handle_request] (/Users/jpollak/src/map_manager/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/Users/jpollak/src/map_manager/node_modules/express/lib/router/index.js:312:13)
        at /Users/jpollak/src/map_manager/node_modules/express/lib/router/index.js:280:7
        at Function.process_params (/Users/jpollak/src/map_manager/node_modules/express/lib/router/index.js:330:12)
```

**Comment by superkhau** [comment] 2016-10-20 20:56
@deepakrkris @gunjpan PTAL

**Comment by gunjpan** [comment] 2016-10-21 13:22
@superkhau : This seems to be resolved, see the update above. 
@jbcpollak : Glad it worked for you.  As @bajtos  mentioned earlier: 
>"deleteAll" is intentionally described as shared: false, because deleting all records is a pretty dangerous operation 

and  so `destroyAll()`, being an alias for `deleteAll()`, unavailable.

@fabien : 
Re:
 >Cannot call Todo.destroy(). The destroy method has not been setup. 

This seems to be reported and fixed at : https://github.com/strongloop/loopback-connector-remote/issues/14

Is this good to close?

cc/ @deepakrkris

**Comment by jbcpollak** [comment] 2016-10-25 18:45
Thanks. I understand it is functioning as intended, however I would say
deleteAll should be public at the data access layer and access should be
managed by the security layer. If it was disabled by the security layer by
default I would understand
.

As is, it is confusing and breaks the convention.

Anyway, thanks for the clarification.

**Comment by bajtos** [comment] 2020-03-10 14:51
Closing as resolved per the comment https://github.com/strongloop/loopback/issues/491#issuecomment-255375163

**Closed by bajtos** 2020-03-10 14:51 UTC
Labels: doc, p1
