### ISSUE TITLE
Migrating MySQL and Mongo on the same project crush

### ISSUE THREAD

**Issue by khlilturki97** [strongloop/loopback#4325] opened 2020-05-18 11:04 UTC
I followed [this tutorial](https://loopback.io/doc/en/lb4/todo-list-tutorial-sqldb.html) and everything worked fine. I managed to work with relations on MySQL db.

In my use case, i had to add another datasource based on Mongo and i had a bug while migrating

> Unable to migrate models not associated with this data source

i had to translate it from french, the original text is 

> Impossible de migrer les modèles non associés à cette source de données

i digged a little in `RepositoryMixin` class, and found out that the problem came from `migrateSchema` method

i overrided the method (copy past x) ) and changed 

```
for (const b of dsBindings) {
  const ds = await this.get(b.key);
  if (operation in ds && typeof ds[operation] === 'function') {
    debug('Migrating dataSource %s', b.key);
    await ds[operation](options.models);
  }
  else {
    debug('Skipping migration of dataSource %s', b.key);
  }
}
```

to 

```
for (const b of dsBindings) {
      const ds = await this.get(b.key);
      // console.log(ds);
      // @ts-ignore
      if (operation in ds && typeof ds[operation] === 'function') {
        console.log('Migrating dataSource %s', b.key);
        // @ts-ignore
        if (!options?.models || options?.models.length === 0) {
          // @ts-ignore
          await ds[operation](options.models);
        } else {
          const models = [];
          for (const model of options?.models) {
            // @ts-ignore
            if (Object.keys(ds.definitions).includes(model)) {
              models.push(model);
            }
          }
          // @ts-ignore
          await ds[operation](models);
        }
      } else {
        // debug('Skipping migration of dataSource %s', b.key);
      }
    }
```

i hope this bug will be fixed soon

**Comment by deepakrkris** [comment] 2020-05-18 17:52
duplicate of https://github.com/strongloop/loopback-next/issues/5479

**Closed by deepakrkris** 2020-05-18 17:52 UTC
Labels: bug
