### ISSUE TITLE
search/find with relation not working properly

### ISSUE THREAD

**Issue by salvob** [strongloop/loopback#1950] opened 2016-01-08 11:03 UTC
I would like to properly filter certain data the request is as follows:
```javascript
{
  "filter": {
    "include": [
      {
        "relation": "customer",
        "scope": {
          "fields": [
            "name"
          ]
        }
      },
      {
        "relation": "agent",
        "scope": {
          "fields": [
            "name"
          ],
          "where": {
            "name": {
              "like": "Mark",
              "options": "i"
            }
          }
        }
      }
    ]
  }
}
```

The response is:
```javascript
[
  {
    "total": 44,
    "id": "568ba2e30f69b5ce0bbb9f8a",
    "agentId": "56392faf17dc53300b3d0983",
    "customerId": "565d8ab025a318ea3431b7ad",
    "customer": {
      "name": "Prime Ltd",
      "id": "565d8ab025a318ea3431b7ad"
    },
    "agent": {
      "name": "Mark",
      "id": "56392faf17dc53300b3d0983"
    }
  },
  {
    "total": 48,
    "id": "568ba2db0f69b5ce0bbb9f89",
    "agentId": "5638917a41e37947069dd9a9",
    "customerId": "563891ca41e37947069dd9aa",
    "customer": {
      "name": "Client Ltd",
      "id": "563891ca41e37947069dd9aa"
    }
  }
]
```
The second record should not be visible. Why is it visible ? How can I do to properly filter ?

**Comment by alFReD-NSH** [comment] 2016-01-09 13:44
I see you wrote `nome` not `name` in the filter.

**Comment by salvob** [comment] 2016-01-10 13:02
I'm sorry, transcription error. The request is correct but the results are not correct

**Comment by jannyHou** [comment] 2016-01-11 05:08
hey @salvob I reproduced your issue and I think you get the second record because you are using `include` filter, not `where`.
`include` only determines what information are included in your result, since you are using `find()`, the result would contain all of your record instances. And your filter only determines what information are displayed in each record instance.
Please see our doc of the definition and usage of FILTERS [here](https://docs.strongloop.com/display/public/LB/Querying+data)

And as a workaround, I think you might filter the results(an array of json objects) you get from `find()`, discard those records whose agent name is not fit. 

And Thank you @alFReD-NSH ! I will take a look at your issue about the filter in `hasManyThrough`, but I guess it's the same one as [issue](https://github.com/strongloop/loopback-datasource-juggler/issues/166) reported here.

**Comment by jannyHou** [comment] 2016-01-17 19:11
I am closing this issue to since the question is solved. The point is users could not use information from related models as the criteria to query the main model because at this moment we don't support join.
Feel free to reopen it if you are still confused. Thanks!

**Closed by jannyHou** 2016-01-17 19:11 UTC
Labels: triage
