### ISSUE TITLE
defaultPermission option not working

### ISSUE THREAD

**Issue by mamartins** [strongloop/loopback#2556] opened 2016-07-27 14:10 UTC
I have an Client model that extends default user model. I wanted to deny all requests to that user unless added explicitly and with
`````
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
`````
added on my Client model actions like create are still available unless I specifically deny them. I found that I could add the option ````defaultPermission```` to solve that but I've added it to my Client model and create is still possible.

`````
  "options": {
    "caseSensitiveEmail": false,
    "defaultPermission": "DENY"
  },
`````

Is this the intended behaviour?

Thanks

**Comment by gunjpan** [comment] 2016-08-10 19:20
IMO, that is the intended behavior. Think about it this way: let's say a user visits the website for the first time and wants to register him/herself, at this time, if you restrict the API Call to unknown users, they won't be able to create an account. 

Hope that helps. I'm closing this for now. Should you need any further assistance, please feel free to comment, incl. my GH handle, and I'll be happy to help. Thank you :)

**Closed by gunjpan** 2016-08-10 19:20 UTC
Labels: question

**Comment by mamartins** [comment] 2016-08-31 09:29
So, the defaultPermission option is intended to do what?

I don't see any problem on denying all my requests unless the ones I want, event for an user. If I am denying some that I shouldn't I'll soon learn that after testing and will open them. Much more easy than having to manually deny all except one or two.
