### ISSUE TITLE
Model migration error - Loopback-workspace

### ISSUE THREAD

**Issue by mbeauchamp7** [strongloop/loopback#2157] opened 2016-03-18 14:50 UTC
I was migrating a user model extended by the User model in my postgresql database with the slc arc gui and it worked fine but I keep getting this error pointing to the loopback-workspace directory.

![migrateerror](https://cloud.githubusercontent.com/assets/15185355/13881361/10181dee-ecf7-11e5-8bd3-5cfea5dbd1f8.png)

Thanks

**Comment by jannyHou** [comment] 2016-03-21 19:17
@mbeauchamp7 I think it's fixed by https://github.com/strongloop/loopback-workspace/commit/b08f5d4296e3dc617652c751111e623cf5cc9931
could you check if the latest code in workspace works for you?

**Comment by superkhau** [comment] 2016-03-22 16:16
@mbeauchamp7 Are you still running into issues? Can we close this?

**Comment by jannyHou** [comment] 2016-11-04 20:01
I am closing it since we could not reproduce it. Feel free to reopen it with a sample box or any updated details.

**Closed by jannyHou** 2016-11-04 20:01 UTC
Labels: triage, waiting
