### ISSUE TITLE
Model validation for enum and optional child with required fields

### ISSUE THREAD

**Issue by srihakum** [strongloop/loopback#2480] opened 2016-06-29 07:07 UTC
1. Currently model properties can have attributes like required and enum, however the value for model instance is not validated by default against enumerated list, is there a way where we can achieve this.
2. Models having properties which are optional (not marked as required) and are of type defined in other models. If the child properties contain required attributes and when a model instance is created there is no validation of optional child property having required properties. The requirement is we would like to validate the child of its required attributed properties only if child is available in the main model instance.

**Comment by loay** [comment] 2016-07-14 21:34
Hi @srihakum 

You can validate using this option:
https://docs.strongloop.com/display/public/LB/Validating+model+data

As for the child part, let me see if I understand correctly with an example: 
Parent: `Vehicle` and attributes: `price`: required, `color`: optional
child: `car` and attributes: `color`: required. 
so you are saying that the `color` attribute needs to be validates for the car but it is not since it is not validated for the vehicle ?? 

Again, let me know if the above mentioned document for validation helps.

**Comment by davidcheung** [comment] 2016-11-04 19:17
@srihakum is this still an issue, you can take a look at [this issue](https://github.com/strongloop/loopback-datasource-juggler/issues/541#issuecomment-216531138), you can allow validation to `allowNull` values, closing this issue now, please ping me in this issue or open a new issue with steps to reproduce.

**Closed by davidcheung** 2016-11-04 19:17 UTC
Labels: triage, waiting
