### ISSUE TITLE
Configuration using only config.local.js without config.json

### ISSUE THREAD

**Issue by laurentdesmet** [strongloop/loopback#2354] opened 2016-05-19 14:08 UTC
Currently, it is not possible to setup the main configuration using only `config.local.js` without a `config.json` file. Because some parts of the configuration are dynamically set in my case, I need to use `config.local.js` anyway. So it would be nice if I can put the complete configuration here, because now it is divided in two places: `config.json` and `config.local.json`.

The same remark is valid for `datasources.json` and `middleware.json`. I know this will lead to problems if you want to use the `slc` tool, but not everyone is using this one, so it would be great if you could opt out.

**Comment by davidcheung** [comment] 2016-05-24 17:39
Hi @laurentdesmet, this sounds like a valid use case, to clarify exactly the problem is

would the following describe your scenario?
Currently `config.local.json` must be present for `config.local.js` to work? but there is no `config.js` for `config.json`


related https://github.com/strongloop/loopback-boot/issues/101#issuecomment-153196601, https://github.com/strongloop/loopback-boot/pull/181, https://github.com/strongloop/loopback/issues/2103

**Comment by laurentdesmet** [comment] 2016-05-27 07:47
Hi

`config.local.js`works without `config.local.json`being present, but it doesn't work when `config.json`is not present. The exact scenario that I'm describing is that you can have exactly one config file, where your complete configuration is defined. You can do this now, with a `config.json` file, but this doesn't allow you to set your configuration dynamically at runtime using for example environment variables. A `config.js` file  (without `config.json`file) would be a solution for this. This seems indeed very related to #2103.

**Comment by davidcheung** [comment] 2016-05-27 23:56
Hmmm I believe that's expected behavior, not sure how much benefit one would get being able to opt-out. 

wouldn't you be able to overide those variables?
is you main concern the extra file that you're not using? or its the confusion it causes, or it is affecting the functionality?  Trying to see how to correctly label this issue, you could also create an issue at [loopback-boot](https://github.com/strongloop/loopback-boot/issues) as a feature request then we can start a discussion there.

**Comment by laurentdesmet** [comment] 2016-05-28 07:26
I like to have my configuration in one place, then I have only one place where I should look for it. If I need to set it dynamically anyway, then I would like to put everything in a `config.js` file. Because if you still need a `config.json`file, then I would make an empty JSON file and specify everything in `config.js`.

Spreading your configuration over multiple files leads to the problem that you need to examine all these files to know the value of a property.

**Comment by laurentdesmet** [comment] 2016-05-28 07:32
Actually, I just found out this issue (https://github.com/strongloop/loopback-boot/issues/190) that also would be a solution to my specific use case. Because some properties of my `config.json` are dynamically set using environment variables, such a syntax would make this possible without the need of a `config.js`file.

**Comment by davidcheung** [comment] 2016-05-30 18:37
agreed, the current way could definitely be improved
>Spreading your configuration over multiple files leads to the problem that you need to examine all these files to know the value of a property.


@laurentdesmet  I would like to close this issue if (strongloop/loopback-boot#190) can address this, please dont hesitate to make comments on the loopback-boot issue for potential issues or suggested behaviors or features, or reopen if you feel appropriate,  thanks!
>Actually, I just found out this issue (strongloop/loopback-boot#190) that also would be a solution to my specific use case. Because some properties of my config.json are dynamically set using environment variables, such a syntax would make this possible without the need of a config.jsfile.

**Closed by davidcheung** 2016-05-30 18:37 UTC
Labels: triage, waiting
