### ISSUE TITLE
The "scope" definition in the .json model files does not always work

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#2675] opened 2016-08-25 22:19 UTC
Hi,

I've noticed that occasionally the "scope" definition that we define in the model .json file does not always work. For example: 

```
{
  "name": "Fee",
  "http": {
    "path": "fee"
  },
  "options": {
    "idInjection": false,
    "mysql": {
      "table": "fee"
    },
    "relations": {
     ...
    }
  },
  "scope": {
    "where": {
      "agencyId": null
    },
    "include": [{
      "relation": "feeDescriptions"
    }, {
      "relation": "feePrices",
      "scope": {
        "include": "priceRules"
      }
    }]
  }
```

We've run into cases where it works fine locally, but in production it will OCCASIONALLY work / not work. Could this be related to loopback's current issue with loopback.getCurrentContext() ? We've experienced this in the past where because loopback.getCurrentContext() will occasionally break we are unable to fully reproduce some bugs.

**Comment by raymondfeng** [comment] 2016-08-25 23:16
The implementation of `scope` does not use `loopback.getCurrentContext` at all. When you say `not work`, what does it exactly mean?

**Comment by stringbeans** [comment] 2016-08-25 23:26
Sorry, let me be more clear...

In our code we're doing something like so...

```
Fee.findById(someId, function(err, fee){});
```

I should expect to always get back the relations predefined in the scope attribute in the .json file. On our development environment I do always get it back, however on our production environment we sometimes do and sometimes don't. Sometimes when I restart the production server it will work but only temporarily.

I've ruled out the possibility that it was data related by pointing my local development to our production database and I'm never able to reproduce the issue.

**Comment by jannyHou** [comment] 2016-09-08 22:42
Hey @stringbeans I understand that occasional occurred issue is pretty annoying and if you can tell me how to reproduce it I am glad to help. But since I have don't know your development/production evn it's pretty hard for us to debug it.

When a bug happens occasionally, it's  probably caused by race condition, there are several issues in loopback reporting race condition bug, maybe you can search and see is there any clues. 

Another suggestion is comparing your dev and production evn to see is there any difference could introduce an unstable factor.

Good luck! 
I am closing issue here to keep git issues clear for bug/features. Please mention me if you have any finding in those race condition issues. Thanks for understanding!

**Closed by jannyHou** 2016-09-08 22:42 UTC
Labels: juggler-relations, triage

**Comment by stringbeans** [comment] 2016-09-09 17:40
@jannyHou Thanks Janny! I understand how hard it is to debug something that is hard/impossible to reproduce. That's exactly the situation we're in where unfortunately we're only able to see it occur on production but not in development. We will continue digging for the issue.

**Comment by stringbeans** [comment] 2016-09-14 23:10
Just wanted to mention, this issue turned out to be the cause!

https://github.com/strongloop/loopback/issues/2748
