### ISSUE TITLE
embedOne don't work

### ISSUE THREAD

**Issue by A11oW** [strongloop/loopback#2244] opened 2016-04-19 09:24 UTC
Hello. 

I try embed one model in another model, but that ain't happening
I have two table in PostgreSQL `restriction` and `region`
and two models:

```
{
  "name": "restrictions",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "postgresql": {
    "schema": "public",
    "table": "restriction"
  },
  "properties": {
    "sum": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 53,
      "scale": null,
      "postgresql": {
        "columnName": "max_credit_sum",
        "dataType": "double precision",
        "dataLength": null,
        "dataPrecision": 53,
        "dataScale": null,
        "nullable": "YES"
      },
      "_selectable": true
    },
    …
  },
  "validations": [],
  "relations": {
    "region": {
      "type": "embedsOne",
      "model": "regions",
      "property": "region_id",
      "options": {
        "validate": true,
        "forceId": true
      }
    }
  },
  "acls": [],
  "methods": {}
}

```

```
{
  "name": "regions",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "postgresql": {
    "schema": "public",
    "table": "region"
  },
  "properties": {
    "name": {
      "type": "String",
      "required": true,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "name",
        "dataType": "text",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "NO"
      },
      "_selectable": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

If I am requesting some 'restriction', I get such answer:

```
{
  "version_id": 3,
  "max_credit_sum": null,
  "max_estate_cost": null,
  "min_credit_sum": null,
  "id": 1,
  "region_id": 2
}
```

But I expect to receive a response:

```
{
  "version_id": 3,
  "max_credit_sum": null,
  "max_estate_cost": null,
  "min_credit_sum": null,
  "id": 1,
  "region": {
    "name": "some name region",
    "id": 2
  } 
}
```

What I do wrong?

**Comment by A11oW** [comment] 2016-04-22 12:31
Hmm apparently I need use `restrictions?filter[include]=region`.
can I use request without filter and response will be with region?

**Comment by jannyHou** [comment] 2016-04-22 14:00
@A11oW I am trying to reproduce your problem, if it's a embedsOne relation, you don't need to use filter to get it.
Please check this relation example https://github.com/strongloop/loopback-example-relations to see how to use embedsOne relation.

I will reply you after I try your code, BTW, for a better debug, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code? Thanks!

**Comment by jannyHou** [comment] 2016-11-03 20:26
I am closing this issue since I could not reproduce it. Please feel free to reopen it if you still run into same issue. Thanks!

**Closed by jannyHou** 2016-11-03 20:26 UTC
Labels: triage, waiting
