### ISSUE TITLE
Can I assign custom data to Error object ? 

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2799] opened 2016-09-28 08:35 UTC
Hi everyone, 

I've used a middleware to validate the api requests, when there is an error occur I want to add a custom data to it, for example : I want to adding a new key with name 'errorCode' and the value is string defined by my system.

So the error response is something like
`{
  "error": {
    "statusCode": 401,
    "name": "Error",
    "message": "System is under deactivated mode.",
    "status": 401,
    "errorCode": "system_is_under_deactivated_mode"
  }
}
`

I've tested the code locally and it worked pretty fine, but when deploy on the remote server (azure api app) it ignored all my custom keys set to Error object.

Can someone please take a look ? Thanks so much!

**Comment by dongmai** [comment] 2016-09-28 09:11
Seems use next(err) in middleware somehow remove all my custom keys on error object. I have to handle response error myself as in strong-remoting/lib/rest-adapter.js. And it worked fine now.


Hope anyone can explain this. Thanks.

**Comment by loay** [comment] 2016-09-28 12:58
Hi @dongmai 
I have to see the code in order to debug and see where the problem is but in general and depending on the callback function and its structure, you can use something like that: 
if (err) return callback(err); and that should return the err. 
If next is being used in your code, then same thing: if (err) return next(err);
Again, I can't really judge without seeing the code itself and how to reproduce it, so if you are still having an issue, please post a link to a test project. 
Thanks.

**Comment by dongmai** [comment] 2016-09-29 04:23
Where should I put the test project ?

**Comment by loay** [comment] 2016-09-29 16:44
Hi @dongmai 
Please follow instructions here: https://github.com/strongloop/loopback/wiki/Reporting-issues
Thanks

**Comment by loay** [comment] 2016-10-19 14:28
I am glad you figured it out, but I am just wondering how does your middleware look like, was it something like:

```
  var err = new Error();
  err =  { "statusCode": 401, "name": "Error", "message": "System is under deactivated mode.", "status": 401, "errorCode": "system_is_under_deactivated_mode" }; 
  next(err);
```
Since it is working now, I will close the issue but if the same thing persists, please leave a message and I will re-open the case. Thanks.

**Closed by loay** 2016-10-19 14:28 UTC
Labels: triage

**Comment by gbhipolitoglyph** [comment] 2018-07-23 09:30
sorry I didn't get the solution. how do I put extra data in error object? thanks

**Comment by virkt25** [comment] 2018-07-31 04:59
Are you using `strong-error-handler`? As per the **Note** in docs here: https://loopback.io/doc/en/lb3/Error-object.html

> Any other properties of the error object are copied to the error output, unless you are using strong-error-handler, in which case you may need to [whitelist the properties you wish to add](https://github.com/strongloop/strong-error-handler#safe-error-fields)

Hope that helps.
