### ISSUE TITLE
strict: 'filter' does not ignore unknown properties

### ISSUE THREAD

**Issue by ernie58** [strongloop/loopback#3482] opened 2017-07-11 16:02 UTC
I've made a repro case here:
https://github.com/ernie58/loopback-sandbox/

When I put strict:'filter' on my models in the definition file, and I try to update a model via the loopback explorer (PATCH model/:id),  unknown properties cause a validation error, instead they should be ignored. This is my definition file:
```
{
  "name": "Task",
  "base": "PersistedModel",
  "idInjection": true,
  "forceId": false,
  "strict": "filter",
  "indexes": {},
  "mixins": {},
  "scope": {},
  "validateUpsert": true,
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": []
}
```
 
# Description/Steps to reproduce
  - clone https://github.com/ernie58/loopback-sandbox and run `yarn install`
  - run `node server/server.js`
  - go to loopback explorer or run the curl command below
  - try to update the task model with JSON containing unknown properties:  
```
curl -X PATCH --header "Content-Type: application/json" --header "Accept: application/json" -d "{\"foo\":\"bar\", \"name\":\"some-task\"}" "http://0.0.0.0:3000/api/Tasks/1"
```

# Expected result
 unknown properties should get ignored, the name of the task should get updated

# actual result
```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Task` instance is not valid. Details: `foo` is not defined in the model (value: undefined).",
    "details": {
      "context": "Task",
      "codes": {
        "foo": [
          "unknown-property"
        ]
      },
      "messages": {
        "foo": [
          "is not defined in the model"
        ]
      }
    }
  }
}
```

# Additional information
I did work in the default loopback version provided with the sandbox, it broke when I updated to latest loopback 3  

linux x64 6.10.0

yarn list --prod --depth 0 | grep loopback
├─ eslint-config-loopback@4.0.0
├─ loopback-boot@2.25.0
├─ loopback-component-explorer@2.7.0
├─ loopback-connector-mysql@5.0.0
├─ loopback-connector-remote@3.1.1
├─ loopback-connector@4.2.1
├─ loopback-datasource-juggler@2.55.0
├─ loopback-datatype-geopoint@1.0.0
├─ loopback-phase@3.0.0
├─ loopback-swagger@2.9.0
├─ loopback@3.8.0

**Comment by ernie58** [comment] 2017-07-13 15:14
I'm not sure but could this line be the culprit:
https://github.com/strongloop/loopback-datasource-juggler/blob/b9129e69739ab703ae28f4ca84ea86849dd9a068/lib/dao.js#L3208

`strict` as a `string`evaluates to true, which in turn triggers a strict check.

https://github.com/strongloop/loopback-datasource-juggler/blob/b9129e69739ab703ae28f4ca84ea86849dd9a068/lib/dao.js#L96
Here it adds props to the __unknownProperties anyway

When the isValid function is called, it then returns false because of here:
https://github.com/strongloop/loopback-datasource-juggler/blob/3b45c76d0fd3364c55a55720d685b5596fb578d1/lib/validations.js#L507

**Comment by ssh24** [comment] 2017-07-17 20:21
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/1419.

**Closed by ssh24** 2017-07-17 20:21 UTC

**Comment by jamesjjk** [comment] 2020-05-11 11:05
Loopback-data-source juggler does not observe the setting "strict": true, for PATCH model/:id.
Version 3.35.0 is still effected.
