### ISSUE TITLE
How to get additional Fields in User Login Method

### ISSUE THREAD

**Issue by rahulrsingh09** [strongloop/loopback#3641] opened 2017-10-05 17:56 UTC
Presently i get the Four default fields in a Loopback login method 

```
{
  "id": "LoXj3QXFepPP7qGiHaWPd7GCjAdenxZVvJwaIM652pSG1SJvqB9fHTU0UdMEiaCL",
  "ttl": 1440,
  "created": "2017-10-05T17:48:42.849Z",
  "userId": 1908
}
```

Now i want to get another field of the user Model acc_id but how to get that this is a overridden user model

**Comment by landervs** [comment] 2017-10-06 08:06
You can extend the base User model. Read about it here: https://loopback.io/doc/en/lb2/Extending-built-in-models.html

**Comment by rahulrsingh09** [comment] 2017-10-06 08:21
@landervs I have extended the User model currently and i have the following Relation but i cannot include the Data of a related module ```{"include":<model>} ```
always throws error says ```include.toLowerCase() is not a function in loopbacks module```

**Comment by landervs** [comment] 2017-10-06 09:00
/UrlToEndPoint?filter[include]=model works fine for me.

See https://loopback.io/doc/en/lb3/Include-filter.html

**Comment by rahulrsingh09** [comment] 2017-10-06 11:17
I want to Include it as a part of a remote method code 

```
return user.login(credentials, function(loginErr, loginToken) {
~```

**Comment by phortonssf** [comment] 2017-10-10 23:21
I am trying to do the same retrieve the related data to the user on login seems far more logical then another http call.

**Comment by bajtos** [comment] 2017-10-13 13:45
Please note that `User.login` method is returning the access token created for the new session, not the user instance. As @landervs mentioned in their comment above, you can add `?filter[include]=user` to your login URL in order to include full data of the logged-in user in the response. See https://github.com/strongloop/loopback/pull/163 which implemented this feature, and the unit-test showing how to use it: https://github.com/strongloop/loopback/blob/f30159cd23370c43adb5ed6875c50cb86da92a77/test/user.test.js#L833-L849

Right now, it's not possible to fetch any additional relations besides the user, see #1477 which is tracking that feature request. I am closing this as a duplicate of #1477.

**Closed by bajtos** 2017-10-13 13:45 UTC
