### ISSUE TITLE
PUT /[ModelName]s doesn't trigger any Model Hooks.

### ISSUE THREAD

**Issue by projectxmaker** [strongloop/loopback#612] opened 2014-10-03 07:50 UTC
Hi,

I have a simple model as following:

tag.json
```html
{
  "name": "Tag",
  "plural": "Tags",
  "base": "PersistedModel",
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

tag.js
```html
module.exports = function(Tag) {

  Tag.beforeValidate = function(next, Tag) {
    console.log('beforeValidate');
    next();
  }

  Tag.afterValidate = function(next, Tag) {
    console.log('afterValidate');
    next();
  }

  Tag.beforeSave = function(next, Tag) {
    console.log('beforeSave');
    next();
  }

  Tag.afterSave = function(next, Tag) {
    console.log('afterSave');
    next();
  }

  Tag.beforeCreate = function(next, Tag) {
    console.log('beforeCreate');
    next();
  }

  Tag.afterCreate = function(next, Tag) {
    console.log('afterCreate');
    next();
  }

  Tag.beforeUpdate = function(next, Tag) {
    console.log('beforeUpdate');
    next();
  }

  Tag.afterUpdate = function(next, Tag) {
    console.log('afterUpdate');
    next();
  }



  Tag.beforeDestroy = function(next, Tag) {
    console.log('beforeDestroy');
    next();
  }

  Tag.afterDestroy = function(next, Tag) {
    console.log('afterDestroy');
    next();
  }
  
  Tag.setup = function() {
    // name - chars in length from 3 - 20
    Tag.validatesLengthOf('name', {min: 2, max: 20, message: 'Name is invalid'});

    // name must be unique
    Tag.validatesUniquenessOf('name');
  }

  Tag.setup();
};

```

I use loopback-explorer to do request to end-point PUT /Tags, there's no Model hooks print output to console.

but when I do request to end-point PUT /Tags/(id), it triggers some Model hooks as following

```html
beforeValidate
afterValidate
beforeSave
beforeUpdate
afterUpdate
afterSave
```

I use strongloop v2.9.1, loopback v2.2.0 and loopback-explorer v1.2.11.

it is a bug of loopback or loopback-explorer ?

any help is appreciated.

**Comment by bajtos** [comment] 2015-02-03 12:34
Closing as a duplicate of strongloop/loopback-datasource-juggler#159.

Note that we are moving away from `beforeSave/afterSave` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

**Closed by bajtos** 2015-02-03 12:34 UTC
Labels: bug, replication
