### ISSUE TITLE
Logout does not clear localStorage (AngularJS) when backend logout fails

### ISSUE THREAD

**Issue by thovden** [strongloop/loopback#1081] opened 2015-02-09 16:41 UTC
This happens e.g., when the client presents an invalid authorization token to the REST API, which will respond 500, and the interceptor that clears localStorage will not run. 

To reproduce (using angularJS-generated model bindings)

1. Log in using the AngularJS SDK-generated support code
2. Edit the authorization token in the client browser - e.g., localStorage.$LoopBack$accessTokenId = "foo"
3. Try to Log out in the client. The server will now respond 500 "invalid token" (or similar)

The interceptor code will not run, leaving the invalid token in localStorage, meaning we're stuck. User.isAuthenticated() will respond true, but calls will not be authorized. We need the interceptor to run even if the server presents a 500 invalid token. For the AngularJS SDK code:

```javascript
        "logout": {
          interceptor: {
            response: function(response) {
              LoopBackAuth.clearUser();
              LoopBackAuth.clearStorage();
              return response.resource;
            }
          },
```

**Comment by superkhau** [comment] 2015-02-25 07:21
Can you provide a repo with steps-to-reproduce? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by loay** [comment] 2016-02-11 19:01
Hi @thovden 
There were couple of fixes in that issue: https://github.com/strongloop/loopback/issues/1669
Any luck with those?
Thanks.

**Comment by thovden** [comment] 2016-02-12 13:12
Thanks for the update - haven't tried those fixes - will do.

**Comment by bradwbradw** [comment] 2016-03-10 17:08
My workaround is to use the $promise.catch block to manually remove the local storage item if a token has expired.  Ideally Loopback could handle this, though, because then I could test properly.  The test environment won't be able to access `window` functions.

```

      logoutTheUser: function () {
        return User.logout().$promise
          .then(function(){
                $state.go('base', {}, {reload: true});
          })
          .catch(function(){
                $log.error('token expired, cannot call logout because of loopback bug');
                window.localStorage.removeItem('$LoopBack$accessTokenId');
                window.localStorage.removeItem('$LoopBack$currentUserId');
                $state.go('base', {}, {reload: true});
            });
      },

```

**Comment by mrbatista** [comment] 2016-03-10 17:13
See [this](https://github.com/strongloop/loopback-sdk-angular/pull/17) PR that solve the problem.

**Comment by richardpringle** [comment] 2016-05-09 15:47
Looks like this has been solved: closing. If the issue persists, please re-open this issue and **mention me** in a comment so I can take a look right away.

@mrbatista, thanks for your contribution!

**Closed by richardpringle** 2016-05-09 15:47 UTC
Labels: triage, waiting
