### ISSUE TITLE
Cant get current accesToken in operation hook

### ISSUE THREAD

**Issue by swfredrik** [strongloop/loopback#2871] opened 2016-10-18 18:06 UTC
How can I get the current user in an operation hook? I've tried the guide using context vice versa but can't get it to work. Also reading that the loopback-contex is depricated. 

https://docs.strongloop.com/display/public/LB/Using+current+context#Usingcurrentcontext-Configurecontextpropagation

Here is my operation hook: 
 Model.observe('before save', function (ctx, next) {
ctx.accessToken....
}

**Comment by fabien** [comment] 2016-10-21 16:18
Normally, you'd use something like this:

```
Model.observe('before save', function (ctx, next) {
  // Note: ctx !== currentCtx
  var currentCtx = LoopBackContext.getCurrentContext();
  var accessToken = currentCtx && currentCtx.get('accessToken');
});
```

However, `loopback-context` is deprecated, and for good reason. I was bitten hard by depending on this functionality, from when it was first introduced in mid-2014. Seemed a great idea back then - just spent a couple of weeks (!) fixing all the occurrences in my(fairly large) code-base ...

**Comment by vijay22sai** [comment] 2016-12-26 12:46
@fabien Is there anyway to access http request object inside an operation hook? How did you fix issues with loopback-context? I tried using cls-hooked but faced same issues as cls. I am looking for a workaround to replace loopback-context with a better mechanism. I am thinking of setting all context variables on req.context and consuming those values in other chain of functions. But I couldn't access http request object in operation hooks.

Can you please guide me on these lines. It would be of a great help, Thanks.

**Comment by josieusa** [comment] 2016-12-28 09:00
@vijay22sai Hello,
regarding the package `cls-hooked` you mentioned, I'm curious about *how* did you use it.
The up-to-date approach for `cls-hooked` is this PR, and it's only waiting for merge (you can already try it, see the link for more info):
https://github.com/strongloop/loopback-context/pull/11
The trick is to require `cls-hooked` before *everything*, but my PR adds some more stuff.
Let me know if it works for you, thanks.

**Comment by vijay22sai** [comment] 2016-12-28 09:32
@josieusa Thanks for your suggestions.

I tried to use your proposed [PR](https://github.com/strongloop/loopback-context/pull/11) as mentioned [here](https://github.com/strongloop/loopback-context/pull/11#issuecomment-269439642). But still it didn't solve the concurrency issue which i have been facing. 

Here is the code snippet to reproduce the issue. let me know if anything wrong in the usage.

here i have a /test endpoint which gets requestId in query object. this code works fine as expected at concurrency level 10.
`package.json => "loopback-context": "github:josieusa/loopback-context#feature/cls-hooked-3",`

```
const LoopBackContext = require('loopback-context');
app.use((req, res, next) => {
  console.log('SET query: ', req.query);
  LoopBackContext.getCurrentContext().set('query', req.query);
  next();
});

app.get('/test', (req, res, next) => {
  const promise = new Promise((resolve, reject) => {
    setImmediate(() => {
      resolve();
    });
  });

  promise.then(() => {
    console.log('get query: ', LoopBackContext.getCurrentContext().get('query'));
    res.status(200).send('ok');
  });
});
```

Now, when i replace ES6 promise with a [when.js](https://github.com/cujojs/when) promise, context is getting messed up. At concurrency 10, only 1 or 2 requests are having original context and for other requests, context is wrong (here context is logged query). code is below.

```
const LoopBackContext = require('loopback-context');
const when = require('when');
app.use((req, res, next) => {
  console.log('SET query: ', req.query);
  LoopBackContext.getCurrentContext().set('query', req.query);
  next();
});

app.get('/test', (req, res, next) => {
  const promise = when.promise((resolve, reject) => {
    setImmediate(() => {
      resolve();
    });
  });

  promise.then(() => {
    console.log('get query: ', LoopBackContext.getCurrentContext().get('query'));
    res.status(200).send('ok');
  });
});
```

Please let me know if there is anything wrong in my usage, Thanks.

**Comment by josieusa** [comment] 2016-12-28 10:09
@vijay22sai Thanks, I'll take a look.
Meanwhile, you may double-check if you followed the **updated** README:
https://github.com/josieusa/loopback-context/blob/feature/cls-hooked-3/README.md
Thanks

**Comment by josieusa** [comment] 2016-12-28 11:25
@vijay22sai I can confirm that I get the same output :(
It's strange because, if you write your async code using a different library than `when`, for example `async`, the problem disappears (it's even tested: see https://github.com/josieusa/loopback-context/blob/feature/cls-hooked-3/test/main.test.js#L107).
I'll take care of opening an issue in `loopback-context` to keep track of the problem, and reproducing the bug using `loopback-sandbox`. Thanks a lot for pointing out the issue.

**Comment by vijay22sai** [comment] 2016-12-28 11:43
@josieusa, Thanks for confirming the issue. Please let me know once you created the issue so that i can keep an eye on it. Also you may know that `loopback-context` is deprecated and https://github.com/strongloop/loopback/pull/3023 is replacing it. I am waiting for https://github.com/strongloop/loopback/pull/3048 patch because i am using loopback 2.x version in my application.

Were you able to get correct context in operation hooks as well? Can you test that once? Thanks a lot.

**Comment by vijay22sai** [comment] 2016-12-28 12:49
@josieusa Thanks for creating an issue on `loopback-context` repo. BTW what promises library you use for async flow which works with `cls-hooked`? I am a heavy user of `when`. I want mainly this kind of functionality: `when.all(bunchOfPromisesArray).resolve(resolverFunction)`
Could you suggest similar promise library which also works with `cls-hooked`, Thanks.

**Comment by josieusa** [comment] 2016-12-28 13:18
@vijay22sai Yes, I just tested for you that`bluebird` passes your concurrency test (I'm going to reproduce it in the aforementioned issue). I didn't test its [`Promise.all`](http://bluebirdjs.com/docs/api/promise.all.html) method though (similar to `when.all`), so beware. Maybe, before using it in production, you would want to test if [`Promise.all`](http://bluebirdjs.com/docs/api/promise.all.html) works when using my fork (if you haven't read it yet, remember to read the [updated README](https://github.com/josieusa/loopback-context/blob/feature/cls-hooked-3/README.md)).

**Comment by vijay22sai** [comment] 2016-12-28 13:28
@josieusa Thank you very much 👍 . I will test it myself and update you.

**Comment by vijay22sai** [comment] 2016-12-29 06:01
@josieusa By using your `PR` and with `bluebird@3.4.7`, I have solved loopback-context bugs. I tested `Promise.all` of `bluebird` and it works great with context. Tested it at high concurrency (10-50 requests) and everything works great. Thanks a lot for your inputs.

I will port to use [official solution](https://github.com/strongloop/loopback/pull/3023) whenever it is mature and stable meanwhile I will continue using your forked version. please keep me in a loop if anything interesting is happening around this area, Thank you.

**Comment by josieusa** [comment] 2017-01-02 15:10
@vijay22sai I posted an alternative solution on strongloop/loopback-context#17

**Comment by bajtos** [comment] 2017-01-09 12:53
FWIW, #3048 has been released today. I am closing this issue, please open a new one in loopback-context if there is anything more to discuss in relation to the old `getCurrentContext` API.

**Closed by bajtos** 2017-01-09 12:53 UTC
