### ISSUE TITLE
Defining a default scope causes a hard limit of 1000 results with large datasets

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback#1393] opened 2015-05-14 16:53 UTC
With the following default scope defined on a Model:

```json
  "scope": {
    "order": "date DESC"
  },
```

I experience an unexpected hard limit of 1000 results to be returned from Rest GET calls. This only appears to happen when the dataset is large (over 10k records). 

I have raised the json limits in config.json, so thats not the problem.

If my dataset is under about 10k records, then I am able to fetch the whole thing at once using a simple GET to the rest endpoint

As soon as my dataset grows above that size, all GET requests to the same endpoint only return 1000 records.

Yet a call to the /count method clearly shows that there is more data.

I have not set a limit of 1000 anywhere

If I try to override that by setting a rally high limit as part of the GET querystring (eg ?filter[limit]=25000), I still only get 1000 records back.

If I remove the default scope mentioned above, then everything begins to work as it should - a call to GET returns the full dataset, and I can set any specific limit that I like using the limit option on the querystring.

So - the presence of a default scope defined in the model.json file seems to be causing a hard limit of 1000 results, even though the default scope in question does not actually specify a limit.

**Comment by raymondfeng** [comment] 2015-05-14 17:27
You can add console.log to loopback-datasource-juggler/lib/dao.js find() to see what filter is passed to the connector.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by mrfelton** [comment] 2015-05-15 12:36
I have tracked the cause of this problem and provided a solution in https://github.com/strongloop/loopback-connector-mongodb/issues/129

**Comment by loay** [comment] 2016-04-08 12:36
@mrfelton 
There were some comments about your PR by @raymondfeng . can you please have a look at them and fix that, so we can merge your PR? Thanks.

**Comment by loay** [comment] 2016-07-14 19:27
Closing this one as a duplicate of this one: https://github.com/strongloop/loopback-connector-mongodb/issues/129
We will keep the #129 as it has the PR attached to it. 
@mrfelton Please address comments about your PR https://github.com/strongloop/loopback-connector-mongodb/pull/130 so we can merge it. Thanks.

**Closed by loay** 2016-07-14 19:27 UTC
Labels: triage
