### ISSUE TITLE
[Docs] Incorrect callback arguments in PersistedModel#findOrCreate

### ISSUE THREAD

**Issue by Jhoanegar** [strongloop/loopback#1528] opened 2015-07-16 21:03 UTC
Hi, I was reading the docs and I found that the documentation for the `findOrCreate` method in `PersistedModel` is wrong. It states that the callback function has 2 arguments, `error ` and `instance`, as you can see here.
http://apidocs.strongloop.com/loopback/v/2.14.0/#persistedmodel-findorcreate

According to my tests, the callback function actually gets three arguments, `(error, created, instance)`, where `created` is `true` if the instance was just created or `false` if it was found.

I'm using loopback's version `2.14.0` but, unless the signature changed in the latest version, I see the same mistake in the latest docs. That or I'm overlooking something.

Keep the awesome work.
Cheers.

**Comment by kevintechie** [comment] 2015-09-28 21:17
Actually, the order of the arguments in the callback is (err, instance, created).

**Comment by superkhau** [comment] 2015-09-28 23:08
@Jhoanegar Did @kevintechie resolve your issue? is this good to close?

**Comment by crandmck** [comment] 2015-11-20 22:50
This is still an issue: https://apidocs.strongloop.com/loopback/v/2.25.0/#persistedmodel-findorcreate

**Comment by alankyshum** [comment] 2015-12-07 14:34
Having exactly the same issue, and this issue is quite frustrating, as I expect `instance` to be null if not found and new record is inserted.

> Tested on `loopback 2.25.0`

**Comment by crandmck** [comment] 2015-12-07 18:27
@superkhau Can you confirm that the callback function gets three arguments, `(error, created, instance)`, where `created` is `true` if the instance was just created or `false` if it was found.
If, so I'll update the docs accordingly.

**Comment by superkhau** [comment] 2015-12-07 19:54
`findOrCreate(query, data, cb)` - https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L127

@Jhoanegar @kevintechie @alankyshum Which connectors are you guys using? Can you guy provide sample projects for me to confirm the issue on my end? I need to verify the bug based on your specific use cases.

**Comment by kevintechie** [comment] 2015-12-08 18:44
The issue is not the findOrCreate signature, but rather the parameters passed to the callback.

I have included some sample code that demos the callback parameters. The code initializes database tables and then adds a user.

I've used the variable name `user` in place of `instance` in the callback parameters.

```
'use strict';
var async = require('async');
var server = require('./../server');
var log = require('debug')('boot:sample-data');
var ds = server.dataSources.mysqlDs;

var lbTables = [ 'accessToken', 'ACL', 'RoleMapping', 'Role', 'UserCredential', 'UserIdentity', 'User' ];

var User = server.models.User;

var initialUser = {
  email:       'testuser@example.com',
  password:    'test123',
  username:    'testuser',
  active:      true
};

async.series([

  function (next) {

    ds.automigrate(lbTables, function (er) {
      if (er) {
        throw er;
      }

      log('Looback tables [' + lbTables + '] created in ', ds.adapter.name);

      next(null, 'created tables');
    });
  },

  function (next) {

    User.findOrCreate(
      { where: { email: initialUser.email } },
      initialUser,
// callback
      function (err, user, created) {
        if (err) {
          throw err;
        }

        created ? log('created user:', user) : log('found user:', user);

      }
    );
  },

  function (next) {
    ds.disconnect();
    next(null, 'closed db');
  }
]);
```

I'm using the MySql database connector in this code, but I've also used the in-memory database and have the same experience.

**Comment by kevintechie** [comment] 2015-12-08 19:13
I believe the callback is called in the loopback-datasource-juggler; specifically lines 672 through 685.:

https://github.com/strongloop/loopback-datasource-juggler/blob/80c3bd9d419e501d5b7beb0a623c8b1eaefdc258/lib/dao.js#L599

Specifically lines 672 through 685.

**Comment by noderat** [comment] 2016-01-22 03:19
Documentation should be updated to reflect that a complete where filter such as `{ where: { name: "foo" } }` should be passed, not just `{ name: "foo" }`

The callback accepts 3 arguments error(Error), instance(obj), and created(bool).

Confirmed syntax with [loopback-datasource-juggler](https://www.npmjs.com/package/loopback-datasource-juggler) 2.44.0

Example:
```js
app.models.user.findOrCreate(
  { where: { username: 'foo' } },  // Where filter
  { username: 'foo', password: 'bar' },  // Data to insert
  function(error, instance, created) {  // Callback
    if (error) throw error;
    if (created) {
      console.log('Object already exists: \n', instance);
    } else {
      console.log('Already existed.');
    }
  });
```

**Comment by noderat** [comment] 2016-01-22 03:46
Created #1983 to update documentation

**Comment by crandmck** [comment] 2016-01-22 16:52
Thanks for the PR, @noderat. Apparently this fell through the cracks and never got moved out of triage.

**Comment by superkhau** [comment] 2016-02-03 02:59
Closing since #1983 has been merged already. Please open a new issue if you guy are still running into problems.

**Closed by superkhau** 2016-02-03 02:59 UTC
Labels: doc
