### ISSUE TITLE
localhost and hosted versions are different

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback#2907] opened 2016-10-29 03:23 UTC
### Bug or feature request

- [x] Bug
- [ ] Feature request
### Description of feature (or steps to reproduce if bug)

Just deploy the loopback instance and discovered that both localhost version and the actual hosted version are different. That happened to one of the api call. The environment is using mongo adapter the latest one. I have developed the remote call as well as the normal call from the url 

`/api/basemaps/?filter[where][owner]=xxxxx`

both did not get proper result from the hosted version but it is working normally in the localhost. All other api calls are working correctly on the hosted version.
### Link to sample repo to reproduce issue (if bug)

```
 basemap.get_by_owner = function (owner, cb) {
    var where_cond = {
      "owner": owner
    };
    basemap.find({
      where: where_cond,
      order: "createtime DESC",
      limit: 1000,
      skip: 0
    }, function (err, results) {
      if (_.isError(err)) {
        return cb(err);
      }
      cb(null, results);
    });

  };


 basemap.remoteMethod("get_by_owner", {
    description: ["Cron job to the list locally.."],
    accepts: [{
      arg: "owner",
      type: "string",
      http: {source: "path"},
      required: true,
      description: "list the items by the owner"
    }],
    returns: {
      arg: "luckylist", type: "array", root: true, description: "Return value"
    },
    http: {verb: "get", path: "/get_by_owner/:owner"}
  });



```
### Expected result

The same from the localhost call
### Actual result (if bug)

There is nothing produced from the result array and I only got this result:
`[]`
### Additional information (Node.js version, LoopBack version, etc)

"node": "5.11.1"
"loopback": "2.34.1",

**Comment by jjhesk** [comment] 2016-10-30 03:58
The cause is from [here](https://github.com/strongloop/loopback-connector-mongodb/issues/52)

**Comment by jannyHou** [comment] 2016-11-04 15:55
I am trying to reproduce it , if confirmed a bug we will take a look.

**Comment by jannyHou** [comment] 2016-11-04 19:11
@jjhesk I tried similar things on my end but it works for me:

Scenario:
 - A model called `Test` attached to mongodb
 - Create an instance `{id: 12345678, name: 'testInstance'}`
 - http://0.0.0.0:3000/api/Tests?filter[where][id]=12345678 will return you the result.
 - http://0.0.0.0:3000/api/Statuses?filter[where][name]=testInstance also returns you the result

Please take a look of your doc regarding the rest syntax when you query data: http://loopback.io/doc/en/lb2/Querying-data.html#rest-syntax, maybe you fail because your syntax has some problem.

If you still run into the bug, please fork https://github.com/strongloop/loopback-sandbox and replace with your code.

**Comment by jannyHou** [comment] 2016-11-23 15:42
@jjhesk any update on this issue? Can you share more info about "hosted versions"? What's the difference between local version and hosted versions?

**Comment by jjhesk** [comment] 2016-11-28 00:40
yes. The issue is still outstanding. I had to manually using external program to convert the id into object id before storing into the db.

**Comment by jannyHou** [comment] 2016-11-28 16:27
@jjhesk Since I could not reproduce it on my localhost explorer, can you share more info about "hosted version"? Thanks.

**Comment by jannyHou** [comment] 2016-12-07 15:09
I am still not able to reproduce the error. Closing it now and I notice that this issue is mentioned in
https://github.com/strongloop/loopback-connector-mongodb/issues/302
Let's keep discussion there since you already know that it's a mongodb bug :)

**Closed by jannyHou** 2016-12-07 15:09 UTC
Labels: #plan, triage, waiting

**Comment by jjhesk** [comment] 2016-12-14 11:14
it is confirmed that this bug is related to [issue](http://stackoverflow.com/questions/21867199/loopback-mongodb-connector-modification-to-support-slug-ids) and not sure this patch is fixed at this [issue](https://github.com/strongloop/loopback-connector-mongodb/pull/15)

**Comment by jjhesk** [comment] 2016-12-14 11:16
it is confirmed that this bug is related to [issue](http://stackoverflow.com/questions/21867199/loopback-mongodb-connector-modification-to-support-slug-ids) and not sure this patch is fixed at this [issue](https://github.com/strongloop/loopback-connector-mongodb/pull/15)
