### ISSUE TITLE
Remote method argument of type Model loses relations

### ISSUE THREAD

**Issue by fuzzball1980** [strongloop/loopback#2400] opened 2016-06-03 04:27 UTC
Hi guys.. I'm lost with something that I have not seen before, I don't know if it is a bug or I'm missing something...

I have a Remote method that take an Issue Object as a parameter, the Issue Model defines a couple of properties and 2 relations, for some reason the issue argument lose the relations when arrive at the remote method. If at the client I add more objects with different names they are passed without problems (So I believe the problem is just with the relations defined in the model.json)

I have added a beforeRemote hook and at this point the relations are present on the body of the request like:

ProcessMagazine.getMagazineFileInfo {"name":"Edición Mayo","code":"EMAY2016","summary":null,"year":null,"number":null,"sku":null,"free":false,"releaseAt":"2016-05-25T03:00:00.000Z","exportedAt":null,"id":1,"magazineId":1,"createdAt":"2016-05-23T04:21:19.302Z","updatedAt":"2016-06-02T23:38:10.760Z","deletedAt":null,"_isDeleted":false,"uploadId":22,"**magazine**":{"name":"Parati","code":"PRTI","id":1,"publisherId":1,"createdAt":"2016-05-23T03:57:16.527Z","updatedAt":"2016-05-23T03:57:16.527Z","deletedAt":null,"_isDeleted":false},"**upload**":{"name":"847cb29b-843a-4a69-9931-b534f58ec903.pdf","originalName":"Polo 60 Sep-Oct.pdf","type":"application/pdf","container":"files","url":"/api/containers/files/download/847cb29b-843a-4a69-9931-b534f58ec903.pdf","id":22,"createdAt":"2016-06-02T23:38:09.164Z","updatedAt":"2016-06-02T23:38:09.164Z","deletedAt":null,"_isDeleted":false}}

and in the remote method parameter it arrives without the relations

Issue: {"name":"Edición Mayo","code":"EMAY2016","summary":null,"year":null,"number":null,"sku":null,"free":false,"releaseAt":"2016-05-25T03:00:00.000Z","exportedAt":null,"id":1,"magazineId":1,"createdAt":"2016-05-23T04:21:19.302Z","updatedAt":"2016-06-02T23:38:10.760Z","deletedAt":null,"_isDeleted":false,"uploadId":22}

```
module.exports = function(ProcessMagazine) {
  var loopback = require('loopback');
  var app = require('../../server/server');

  ProcessMagazine.beforeRemote('**', function(ctx, instance, next) {
    console.log(ctx.methodString, JSON.stringify(ctx.req.body));

    next();
  });

  ProcessMagazine.getMagazineFileInfo = function(issue, cb) {
    console.log('Issue: ' + JSON.stringify(issue));

      var result = {
        status: 200,
        message: 'OK'
      }
      cb(null, result);
    });
  }

  ProcessMagazine.remoteMethod(
    'getMagazineFileInfo', {
      accepts: [{
        arg: 'issue',
        type: 'Issue',
        description: 'Get Magazine PDF metadata',
        http: {
          source: 'body'
        },
        required: true
      }],
      returns: {
        arg: 'response',
        type: 'object'
      },
      http: {
        verb: 'post'
      }
    }
  );
};
```

Issue Model

```
{
  "name": "Issue",
  "plural": "Issues",
  "base": "PersistedModel",
  "scope": {
    "include": []
  },
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "code": {
      "type": "string",
      "required": true
    },
    "summary": {
      "type": "string"
    },
    "year": {
      "type": "number",
      "required": false,
      "length": 32
    },
    "number": {
      "type": "string",
      "required": false,
      "length": 4
    },
    "sku": {
      "type": "string",
      "required": false
    },
    "free": {
      "type": "boolean",
      "required": false
    },
    "releaseAt": {
      "type": "date",
      "required": false
    },
    "exportedAt": {
      "type": "date",
      "required": false
    }
  },
  "mixins": {
    "TimeStamp": true,
    "SoftDelete": true,
    "Audit": {
      "saveAction": true,
      "deleteAction": true,
      "accessAction": false
    }
  },
  "validations": [],
  "relations": {
    "magazine": {
      "type": "belongsTo",
      "model": "Magazine",
      "foreignKey": "magazineId"
    },
    "upload": {
      "type": "belongsTo",
      "model": "Upload",
      "foreignKey": "uploadId"
    }
  },
  "acls": [{
    "accessType": "*",
    "principalType": "ROLE",
    "principalId": "admin",
    "permission": "ALLOW"
  }, {
    "accessType": "READ",
    "principalType": "ROLE",
    "principalId": "$unauthenticated",
    "permission": "DENY"
  }, {
    "accessType": "READ",
    "principalType": "ROLE",
    "principalId": "$authenticated",
    "permission": "ALLOW"
  }, {
    "accessType": "*",
    "principalType": "ROLE",
    "principalId": "$everyone",
    "permission": "DENY"
  }],
  "methods": {}
}
```

**Comment by richardpringle** [comment] 2016-06-04 01:48
Hey @fuzzball1980, could you provide a sample repo instead? [LoopBack-sandbox](https://github.com/strongloop/loopback-sandbox)

Fork it, write the steps to reproduce in the readme, and provide the link in a comment here and I will try and figure out what the problem is.

**Comment by fuzzball1980** [comment] 2016-06-04 17:56
@richardpringle thank you from taking the time to check this issue

https://github.com/fuzzball1980/loopback-sandbox.git

Like I say in the comment above, the problem happens only with the relations declared on the Model, If I replicate the upload or magazine property with another name (other than the relation name) it pass to the remote method without problem.

JSON Example

`{"name":"Edición Mayo","code":"EMAY2016","summary":null,"year":null,"number":null,"sku":null,"free":false,"releaseAt":"2016-05-25T03:00:00.000Z","exportedAt":null,"id":1,"magazineId":1,"createdAt":"2016-05-23T04:21:19.302Z","updatedAt":"2016-06-02T23:38:10.760Z","deletedAt":null,"_isDeleted":false,"uploadId":22,"magazine":{"name":"Parati","code":"PRTI","id":1,"publisherId":1,"createdAt":"2016-05-23T03:57:16.527Z","updatedAt":"2016-05-23T03:57:16.527Z","deletedAt":null,"_isDeleted":false},"upload":{"name":"847cb29b-843a-4a69-9931-b534f58ec903.pdf","originalName":"Polo 60 Sep-Oct.pdf","type":"application/pdf","container":"files","url":"/api/containers/files/download/847cb29b-843a-4a69-9931-b534f58ec903.pdf","id":22,"createdAt":"2016-06-02T23:38:09.164Z","updatedAt":"2016-06-02T23:38:09.164Z","deletedAt":null,"_isDeleted":false},"uploadssss":{"name":"847cb29b-843a-4a69-9931-b534f58ec903.pdf","originalName":"Polo 60 Sep-Oct.pdf","type":"application/pdf","container":"files","url":"/api/containers/files/download/847cb29b-843a-4a69-9931-b534f58ec903.pdf","id":22,"createdAt":"2016-06-02T23:38:09.164Z","updatedAt":"2016-06-02T23:38:09.164Z","deletedAt":null,"_isDeleted":false}}`

**Comment by richardpringle** [comment] 2016-06-06 16:07
@fuzzball1980, I was actually not able to reproduce the issue. The output and the input were the same. I'm not exactly sure about the details of your use-case, but to me, it would make more sense to input an issue ID and lookup the issue within the remote-method. You add the `include` filter as well to include the relations.

```node
  ProcessMagazine.getMagazineFileInfo = function(issueId, cb) {
    var Issue = ProcessMagazine.app.models.Issue;
    Issue.findById(issueId, {include: ['magazine', 'upload']}, function(err, issueInstance) {
      cb(err, issueInstance);
    });
  }
```

But the above does not solve your problem. I do see another issue with your remote-method. If you check out the [API docs for `remoteMethod` argument](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Argumentdescriptions) you can see that the `type` should be a [LoopBack type](https://docs.strongloop.com/display/public/LB/LoopBack+types) instead of a model (`Issue` in your case). It should instead just be of type `object` since there is no model schema validation (as far as I know). 

Does any of this help? I know I haven't really answered your question of why the relations are disappearing but as I said, I could not reproduce the issue on my computer, the relations showed up in the log. Let me know if changing your design solves the issue.

**Comment by richardpringle** [comment] 2016-06-06 19:56
side note: 
If you do not include an ACL rule on `Media.findById` then I would expect that a user would be able to get the 404 because they could just as easily check `GET /media/{id}` before calling `GET /media/{id}/author`.

However, I added the ACL to deny-all for `findById` and you still run into the same issue. Just thought I would point this out anyway.

**Comment by fuzzball1980** [comment] 2016-06-06 22:09
@richardpringle I'm actually using an issueId  has a parameter and doing a lookup in my project, but implementing that method I found this issue, that I could't resolve yet.

I have a VM running on c9

https://ide.c9.io/fuzzball1980/loopback-acl

If you want to check it request access to the workspace!

About the last reply, are you talking about the same issue?
 
Thank you very much!

**Comment by richardpringle** [comment] 2016-06-07 01:58
@fuzzball1980... Thanks, the last comment was not meant for this issue....

**Comment by richardpringle** [comment] 2016-06-07 02:01
@fuzzball1980, did you pass the correct include filter on your lookup?

**Comment by fuzzball1980** [comment] 2016-06-07 02:56
yes, the problem is with the relations missing in the parameter object not
in the lookup.

Thanks

**Comment by richardpringle** [comment] 2016-06-07 14:21
Well, I could not reproduce the issue. Could you reproduce it locally or did you just run into it on c9?

**Comment by fuzzball1980** [comment] 2016-06-07 14:31
Well I use c9 as my development env, not running locally. But the workdpace
I shared with you is a clean loopback sandbox that reproduce the issue.

Hace yo been able to open the workspace? i didnt receive the request.

Thank you!

**Comment by richardpringle** [comment] 2016-06-07 15:04
@fuzzball1980, using someone else's VM to reproduce an issue is not valid in our QA process. We need complete control of the environment. 

I will leave this as an open issue for now in case anyone else runs into it.

I'm not too concerned as it is not best practice to be passing in full records with relations instead of looking them up (which you are already doing :wink:).

**Comment by fuzzball1980** [comment] 2016-06-07 15:40
ok, thanks!

**Comment by fuzzball1980** [comment] 2016-06-10 03:13
@richardpringle 

I have more details...

If in the remote method definition I put the arg type as a Custom Model for example Issue the relations are lost, but If I declare the arg type as a plain object the relations are conserved.

```
IssueKioskProperties.remoteMethod(
    'updateIssueKioskProperties', {
      accepts: [{
        arg: 'issue',
        type: 'object',
        http: {
          source: 'body'
        },
        required: true
      }],
      returns: {
        arg: 'response',
        type: 'object',
        root: true
      },
      http: {
        verb: 'post'
      }
    }
  );
```

**Comment by richardpringle** [comment] 2016-06-10 21:48
Okay cool!

Argument type shouldn't be a model class anyway. Safe to close this issue?

**Comment by fuzzball1980** [comment] 2016-06-10 22:06
Why not? It is nice to have the argument object  definition in the
strongloop explorer automatically :-)

Thanks!

**Comment by richardpringle** [comment] 2016-07-05 15:15
@fuzzball1980, sorry about the late reply... must have just missed the email.

In my personal opinion, you shouldn't have to insert entire records unless you are creating a record, in which case the LoopBack type would just be an *object* and the validation is performed for the `create` CRUD method anyway. Otherwise you should just be referring to records by ID. I like to keep my APIs as simple as possible.

Regardless of what I think when it comes to API best practices, LoopBack is not designed in such a way to use class definitions to describe an argument type for a remote-method. If you would like that, I suggest opening up a new feature request :smile:.

**Closed by richardpringle** 2016-07-05 15:15 UTC
Labels: triage, waiting
