### ISSUE TITLE
Unable to connect to Mongo DB Atlas using  mongodb+srv Protocol

### ISSUE THREAD

**Issue by ChristoJohn** [strongloop/loopback#4245] opened 2019-08-22 11:40 UTC
Connection Properties i tried in datasource.json 
```
mongoDb: {
     connector: 'mongodb',
     name: 'mongoDb',
     url:"mongodb+srv://#username:#password@cluster0-kvw6a.mongodb.net/test? 
           retryWrites=true&w=majority"

  }

```
while trying to query some data - getting this error 

```
Unhandled error for request GET /api/Customers/getProfile?access_token=cMGG6C8fB8el0vbchpAzeOoTpH0N7Kf9va4b5k9Z6GrNAwgh4AtqQKlRYOyiWtsB: MongoError: cannot do
raw queries on admin in atlas
    at Function.MongoError.create (C:\Users\User\Documents\GitHub\maharah\customer_server\node_modules\mongodb-core\lib\error.js:31:11)
    at queryCallback (C:\Users\User\Documents\GitHub\maharah\customer_server\node_modules\mongodb-core\lib\cursor.js:212:36)
    at C:\Users\User\Documents\GitHub\maharah\customer_server\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)

```

**Comment by dhmlau** [comment] 2019-08-22 21:16
Closing as duplicate of https://github.com/strongloop/loopback-connector-mongodb/issues/542.
@ChristoJohn, please see my reply in that ticket. Thanks!

**Closed by dhmlau** 2019-08-22 21:16 UTC

**Comment by ChristoJohn** [comment] 2019-08-23 09:06
I already tried with this but not working . 

In Connector Lib  if we specify url it will take that rt.
From  loopback-connector-mongodb/lib/mongodb.js
`  s.url = s.url || generateMongoDBURL(s);`

also generateMongoDBURL is not taking  mongodb+srv protocol
```
function generateMongoDBURL(options) {
  options.hostname = (options.hostname || options.host || '127.0.0.1');
  options.port = (options.port || 27017);
  options.database = (options.database || options.db || 'test');
  var username = options.username || options.user;
  if (username && options.password) {
    return 'mongodb://' + username + ':' + options.password + '@' + options.hostname + ':' + options.port + '/' + options.database;
  } else {
    return 'mongodb://' + options.hostname + ':' + options.port + '/' + options.database;
  }
}
```
