### ISSUE TITLE
Error on insertion of access token record on successful authentication

### ISSUE THREAD

**Issue by micrub** [strongloop/loopback#3815] opened 2018-02-24 15:35 UTC
# Error on insertion of access token record on successful authentication

* connection using postgresql data source
* build in model are auto generated using loopback auto migration routine
* there is a common Account model extended from build in User model.

On login request getting following error:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"email":"s%test.com", \ 
 "password":"test"}' 'http://localhost:5000/api/Accounts/login'
{
  "error": {
    "statusCode": 500,
    "name": "error",
    "message": "invalid input syntax for integer: \"NaN\"",
    "length": 85,
    "severity": "ERROR",
    "code": "22P02",
    "file": "numutils.c",
    "line": "62",
    "routine": "pg_atoi",
    "stack": "error: invalid input syntax for integer: \"NaN\"\n 
  }
}
```

Table CREATE sql:
```
CREATE TABLE public.accesstoken
(
  id integer NOT NULL DEFAULT nextval('accesstoken_id_seq'::regclass),
  ttl integer DEFAULT 1209600,
  scopes text,
  created timestamp with time zone,
  userid integer,
  CONSTRAINT accesstoken_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
```
Debug log shows:

```
Sat, 24 Feb 2018 14:38:03 GMT loopback:connector:postgresql SQL: INSERT INTO "public"."accesstoken"("id","ttl","created","userid") VALUES($1,$2,$3::TIMESTAMP WITH TIME ZONE,$4) RETURNING "id"
Parameters: [null,1209600,"2018-02-24T14:38:03.526Z",1]
Sat, 24 Feb 2018 14:38:03 GMT loopback:connector:postgresql error: invalid input syntax for integer: "NaN"
    at Connection.parseE (/home/some/bitbucket/some/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/home/some/bitbucket/some/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/home/some/bitbucket/some/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
Sat, 24 Feb 2018 14:38:03 GMT loopback:connector:sql Error: {"name":"error","length":85,"severity":"ERROR","code":"22P02","file":"numutils.c","line":"62","routine":"pg_atoi"} "INSERT INTO \"public\".\"accesstoken\"(\"id\",\"ttl\",\"created\",\"userid\") VALUES($1,$2,$3::TIMESTAMP WITH TIME ZONE,$4) RETURNING \"id\"" [null,1209600,"2018-02-24T14:38:03.526Z",1]
```

## packages

```
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^5.0.0",
    "loopback-connector-mongodb": "^1.18.1",
    "loopback-connector-postgresql": "^2.9.0
```

## ENV
`
psql (9.5.11, server 10.2 (Ubuntu 10.2-1.pgdg14.04+1))`

**Comment by micrub** [comment] 2018-02-24 15:51
Seems that needs to be moved to https://github.com/strongloop/loopback-connector-postgresql/issues

**Comment by dhmlau** [comment] 2018-02-27 15:50
Closing this as duplicate of https://github.com/strongloop/loopback-connector-postgresql/issues/321.

**Closed by dhmlau** 2018-02-27 15:50 UTC
