### ISSUE TITLE
The loopback#urlNotFound and loopback#errorHandler middleware file paths can not be resolved in test env

### ISSUE THREAD

**Issue by xixilive** [strongloop/loopback#2201] opened 2016-04-06 08:32 UTC
In my test env, it try to resolve paths from following positions:

- try resolve `loopback#urlNotFound` at node_modules/loopback/server/middleware/urlNotFound.js
- try resolve `loopback#errorHandler` at node_modules/loopback/server/middleware/errorHandler.js

and In fact, the correct filename are `url-not-found.js` and `error-handler.js`, In  development and production environments, They are works, why?

**Comment by loay** [comment] 2016-04-25 19:09
Are you getting an error message? or there is a specific problem?
I have a test file where I set
```
process.env.NODE_ENV = 'test'
```
and it works fine.. if you have a repo, you can refer me to for your case, it will help me sort this problem out. Thanks.

**Comment by loay** [comment] 2016-06-03 19:57
Hi @xixilive 
There is a new errorhandler in place so those problems will be fixed soon. 
Thanks for pointing out the issue.

**Closed by loay** 2016-06-03 19:57 UTC
Labels: triage

**Comment by supasate** [comment] 2017-03-30 06:25
Hi @loay, I faced the same issue when running test with `jest`.

```bash
  Cannot resolve path "loopback/server/middleware/urlNotFound"
      
      at resolveAppPath (node_modules/loopback-boot/lib/compiler.js:386:15)
```

Currently, I work around by renaming the file from `url-not-found.js` to `urlNotFound.js`. Should we fix it in `loopback-boot` to get the correct file name?

**Comment by bajtos** [comment] 2017-03-31 14:02
AFAIK, `loopback#urlNotFound` is usually resolved by loopback-boot to `require('loopback').urlNotFound`.  When `require('loopback')` does not export `urlNotFound` property, then loopback-boot is trying to treat the fragment as a filename. Here is the relevant source code in `2.x` branch: [lib/compiler.js](https://github.com/strongloop/loopback-boot/blob/cda21ea48196db0448014bc9642da1fc5c6b8768/lib/compiler.js#L570-L600).

I suspect `jest` is modifying the outcome of `require('loopback')` in such way that `require('loopback').urlNotFound` is no longer defined.

**Comment by supasate** [comment] 2017-03-31 19:26
It seems like `url-not-found` and `error-handler` are treated differently by [re-naming file names into camelCase properties]( https://github.com/strongloop/loopback/blob/0499d09d6b34aec87f4f05a576851ba3d5ac4dc6/lib/loopback.js#L149-L153).

So, can we just re-name the fragment back to the correct file name like the following?
```js
if (fragment) {
  if (fragment === 'urlNoFound') {
    fragment = 'url-not-found';
  }
  if (fragment === 'errorHandler') {
    fragment = 'error-handler';
  }
}
```

**Comment by bajtos** [comment] 2017-04-28 13:32
> can we just re-name the fragment back to the correct file name like the following?

Sorry, that does not make sense to me.

IMO, this issue needs more research. Why is the [code building loopback.urlNotFound](https://github.com/strongloop/loopback/blob/0499d09d6b34aec87f4f05a576851ba3d5ac4dc6/lib/loopback.js#L139-L154) not working in Jest, when it seems to work for everybody else?

**Comment by Bastorx** [comment] 2017-11-24 08:52
Yeah, the problem is the file is named url-not-found in node_modules (instead of urlNotFound), I copied-pasted and renamed urlNotFound the copy and it works. But edit the file in node_modules isn't a good solution.

Do you have a way to fix it ?

**Comment by elboletaire** [comment] 2017-11-26 14:11
>  There is a new errorhandler in place so those problems will be fixed soon.

Should we wait for loopback 4??

**Comment by bajtos** [comment] 2017-12-14 15:49
> > There is a new errorhandler in place so those problems will be fixed soon.

> Should we wait for loopback 4??

I am afraid that comment about a new error-handler was misleading. We do use [strong-error-handler](https://www.npmjs.com/package/strong-error-handler) instead of [errorhandler](https://www.npmjs.com/package/errorhandler), but the `urlNotFound` middleware is still required to convert "no path found" situation into a javascript error for the error-handling middleware to handle.

But yes, this problem will go away in LoopBack 4, because it's an entirely new code base and we are not exporting any `urlNotFound` entity so far.

**Comment by elboletaire** [comment] 2017-12-14 15:54
Yeah but, as you said, it's an entirely new code, so it's not a valid solution for the majority of us (I mean, the people in this issue).

In my case what I did was just add some hardcoded code to my `test.js` which copies these files to their expected locations if they not exist. Something like this:

~~~js
// Dirty trick to bypass the loopback-boot file naming issue...
const files = [
  {
    original: 'url-not-found',
    desired: 'urlNotFound',
  },
  {
    original: 'error-handler',
    desired: 'errorHandler',
  }
]

files.forEach((file) => {
  const base = path.resolve('./node_modules/loopback/server/middleware')
  const desired = `${base}/${file.desired}.js`
  if (!fs.existsSync(desired)) {
    fs.copyFileSync(`${base}/${file.original}.js`, desired)
  }
})
~~~

**Comment by bajtos** [comment] 2017-12-14 15:59
@elboletaire I feel your paint! Unfortunately we don't have bandwidth to investigate this issue ourselves. 

My recommendation is to load your test setup in a debugger, set breakpoint to loopback-boot's compiler's method `resolveMiddleware` (see my earlier https://github.com/strongloop/loopback/issues/2201#issuecomment-290720446), and find out why the module resolver behaves differently in the test environment.

**Comment by elboletaire** [comment] 2017-12-14 16:11
I have the same time than you. The dirty trick works, so I'm not gonna loose more time on it.

We'll see if loopback 4 fits our needs btw... because it's like a totally new framework... 😕

**Comment by PaddyMann** [comment] 2018-01-02 14:56
Just ran into this bag of fun.

Suggested solution for Loopback 3:
1. Copy code from `url-not-found.js`: https://github.com/strongloop/loopback/blob/master/server/middleware/url-not-found.js
2. Paste into your own `/middleware/url-not-found.js`
3. Update `middleware.json`, replacing `"loopback#urlNotFound": {}` with `"./middleware/url-not-found": {}`
4. Move onto the next issue... :)

**Comment by bajtos** [comment] 2018-01-08 15:16
> After a prolonged fight, this preset fixed all of the issues we were facing: https://github.com/negativetwelve/jest-preset-loopback

@PaddyMann This is awesome, thank you for figuring the solution and sharing it on GitHub. I'd love to give your Jest preset more publicity, could you perhaps send a pull request to add your project to our [Community Projects](http://loopback.io/doc/en/community/index.html) section on loopback.io? See the instructions [here](http://loopback.io/doc/en/community/How-to-add-a-project.html). If you can come up with a better place where to tell Jest users how to configure it for LoopBack projects then I am happy to consider it too!

**Comment by PaddyMann** [comment] 2018-01-08 15:25
@bajtos I can't take credit for this — after a prolonged fight, I was lucky enough to stumble across the good work by @negativetwelve 

Kudos to him!

**Comment by PaddyMann** [comment] 2018-01-08 15:28
This issue is the top search result when you hit the `loopback/server/middleware/urlNotFound` error (at least on the Strongloop site), so at least others should find it here in future.

**Comment by ewrayjohnson** [comment] 2020-08-10 14:54
I found configuring jest with testEnvironment: 'node' resolved the issue for me. Otherwise jest thinks it is running in a  browser by default.
