### ISSUE TITLE
strong-streaming:  404: there is no method to handle Get '/Contact44440484882943s'

### ISSUE THREAD

**Issue by penzhan8451** [strongloop/loopback#1367] opened 2015-05-06 12:42 UTC
I hit by an issue for model rest api.   For multi-tenant support,  I dynamically created new DS, and models for every user.  and Plural is also different for every user.  For example, user1 model rest url is like '.../api/UsersAAAAs', user2 will be '.../api/UsersBBBBBs'.    My connector module is put to loopbackProj/node-modules.  

When user1 and user2 both post a request to create their DS and Models (attach to their DS and APP, model only has different name and plural),  user1's model rest api will not  be effect,  user2 model rest  api can work. 

Could you please give me any comments?  Thanks very much!

sorry for vague description. I paste code here:
Step1:  User1 send post request, lookback will do:
```
var ds = server.dataSource(user1_id, dsconfig);
 Account = server.loopback.createModel({
   name: user1_id,
   properties: {
         ...
        },
        options: {
         ...
          plural: user1_id + 's',
          base: 'PersistedModel'
        }
			
 })

Step2:  Then, User2 send post request:

var ds = server.dataSource(user2_id, dsconfig);
Account = server.loopback.createModel({
   name: user2_id,
   properties: {
         ...
        },
        options: {
         ...
          plural: user2_id + 's',
          base: 'PersistedModel'
        }
			
 })
 
 
   Account.attachTo(ds);
   server.model(Account);
   ```
 Below is Result:  
 http://locahost:3000/api/(user2_id + 's')  can work, But http://locahost:3000/api/(user1_id + 's') does Not work,

**Comment by ritch** [comment] 2015-05-06 19:45
You might be running into a global model registry issue. I have added a flag to improve support for cases such as yours (multi-tenancy). Can you try using this flag?

Here is how to setup the flag:

```js
var app = loopback({localRegistry: true});
```

**Comment by penzhan8451** [comment] 2015-05-07 05:44
Thanks, I will try.

**Comment by superkhau** [comment] 2015-07-07 00:29
@penzhan8451 Did @ritch's solution fix your issue? Can I close this?

**Comment by loay** [comment] 2016-04-07 20:03
Hi @penzhan8451 
Closing issue. If the problem is still persisting, please feel free to leave a comment and I will re-open the issue. Thanks.

**Closed by loay** 2016-04-07 20:03 UTC
Labels: triage, waiting
