### ISSUE TITLE
Self through relationship hanging

### ISSUE THREAD

**Issue by tomcooksey** [strongloop/loopback#2247] opened 2016-04-20 21:01 UTC
Hi,

I have setup a has-many-through relationship recursively as follows: (it's the 'related' relationship we're interested in)

```
{
  "name": "MenuItem",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
    "I18n": {
      "i18nModel": "MenuItemI18N",
      "foreignKey": "item_id"
    },
    "Cascade": {
      "CategoriesToItems": "item_id",
      "ItemsToQuestions": "item_id",
      "PriceLevel": "item_id"
    },
    "Ownership": true,
    "Permissions": true,
    "Cache": {
      "cacheGroups": [
        "fandb"
      ],
      "name": "MenuItem"
    }
  },
  "scope": {
    "include": [
      "questions",
      "translations",
      "priceLevels",
      "related"
    ]
  },
  "properties": {
    "price": {
      "type": "string"
    },
    "category_id": {
      "type": "number"
    },
    "organisation_id": {
      "type": "number"
    },
    "price_type": {
      "type": "string"
    },
      "parent_id": {
          "type": "number"
      }
  },
  "validations": [],
  "relations": {
    "translations": {
      "type": "hasMany",
      "model": "MenuItemI18N",
      "foreignKey": "item_id"
    },
    "categories": {
      "type": "hasMany",
      "model": "MenuCategory",
      "foreignKey": "item_id",
      "through": "CategoriesToImages",
      "key_through": "category_id"
    },
    "questions": {
      "type": "hasMany",
      "model": "MenuQuestion",
      "foreignKey": "item_id",
      "through": "ItemsToQuestions",
      "keyThrough": "question_id",
      "scope": {}
    },
    "offers": {
      "type": "hasMany",
      "model": "Offer",
      "foreignKey": "item_id",
      "through": "OffersToItems",
      "keyThrough": "offer_id",
      "scope": {}
    },
    "priceLevels": {
      "type": "hasMany",
      "model": "PriceLevel",
      "foreignKey": "item_id"
    },
    "related": {
      "type": "hasMany",
      "model": "MenuItem",
      "foreignKey": "item_id",
      "through": "ItemsToItems",
      "keyThrough": "linked_item_id"
    }
  },
  "acls": [],
  "methods": {}
}
```
With a link table:

```
{
  "name": "ItemsToItems",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "item_id": {
      "type": "number"
    },
    "linked_item_id": {
      "type": "number"
    },
    "order": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
      "children": {
          "type": "belongsTo",
          "model": "MenuItem",
          "foreignKey": "linked_item_id"
      },
      "parent": {
          "type": "belongsTo",
          "model": "MenuItem",
          "foreignKey": "item_id"
      }
  },
  "acls": [],
  "methods": {}
}
```

But when I request this model the whole server just hangs, even when just accessing via the default API.

I must be setting this relationship up incorrectly but I am out of ideas!

**Comment by jannyHou** [comment] 2016-04-22 00:04
@tomcooksey I am trying to reproduce your problem, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and provide your code? Thanks!

**Comment by tomcooksey** [comment] 2016-04-22 12:57
Hmm, I have no idea as to why but this appears to have 'fixed it self'.  I forked the repo to produce an example and it worked then I checked my original app and it's working now...

I have no words!  Sorry for wasting your time.

**Comment by jannyHou** [comment] 2016-04-22 13:53
lol no worries, same thing always happens to everyone. Glad to know that you fix it!
> when I request this model the whole server just hangs

I saw this line so I suppose it's probably caused by missing `done` or something similar, not the relation. But anyway, congrats that it's solved.

Since it's fixed, I am closing issue here, please feel free to reopen it if you still have questions.

**Comment by tomcooksey** [comment] 2016-04-25 21:02
I actually found this was caused by a circular relationship, so item A was related to item B was related to Item A etc.

**Closed** 2016-04-28 18:38 UTC
Labels: triage
