### ISSUE TITLE
How to get 10 documents in each include relation  model

### ISSUE THREAD

**Issue by somu1251** [strongloop/loopback#3030] opened 2016-12-15 12:05 UTC
Example: 

Model name is category

My filter query is 
{"include": [{"relation": "videos", "scope": { "order": "created DESC",  "skip": 0, "limit": 10}}]}

I want latest 10 videos for each category. 

But using the above query getting only 10 videos from all the categories

**Comment by jannyHou** [comment] 2016-12-15 17:22
@somu1251 
what is your relation? Is it
- `Category` hasMany `Video`
- `Video` belongsTo `Category`
?
And are you calling api `Category.find()` with the filter? 
For better debug, please fork https://github.com/strongloop/loopback-sandbox and replace with your use case :)

`Category.find()` will return you all categories instances with the 10 videos you want included in each instance:
```js
[
  cate1: {
    videos: [];  // 10 videos
  },
  cate2: {
    videos: [];  // 10 videos
  }
]
```

**Comment by somu1251** [comment] 2016-12-15 17:38
Hey Janny,
Thanks for your quick response.

My model's relation is

* video belongs to category
* category hasAndBelongsTo video

Yes, I'm calling API Category.find() with the filter

{"include": [{"relation": "videos", "scope": { "order": "created DESC", "skip": 0, "limit": 10}}]}

Yes, I need response like this

[
  cate1: {
    videos: [];  // 10 videos
  },
  cate2: {
    videos: [];  // 10 videos
  }
]

help me on this

Thanks
Sandeep

**Comment by jannyHou** [comment] 2016-12-15 17:42
@somu1251 Try change "category hasAndBelongsTo video" to "category hasMany video"

**Comment by jannyHou** [comment] 2016-12-15 17:49
And an example of using `include` filter with `hasMany` relation:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/include.test.js#L546-L548
That test case is very similar to your scenario.

**Comment by somu1251** [comment] 2016-12-15 17:54
@somu1251 Try change "category hasAndBelongsTo video" to "category hasMany video"

Tried with hasMany Relation
getting only 10 videos for all categories

**Comment by somu1251** [comment] 2016-12-15 17:56
Actually, I want to get 10 videos for each category

**Comment by jannyHou** [comment] 2016-12-15 21:54
@somu1251 I am confused, what do you mean by `each category`? 
Can you post here what result you get from your api?

**Comment by somu1251** [comment] 2016-12-16 08:50
HI Jaany,

API is Category.find with below filter

{"include": [{"relation": "videos", "scope": { "order": "created DESC", "skip": 0, "limit": 2}}]}

with limit 2 videos in each category

I have 3 categories (comedy, fun, education)

I m getting below response

```
{
    "name": "comedy",
    "created": "2016-12-07T10:51:28.422Z",
    "lastUpdated": "2016-12-07T10:51:28.422Z",
    "videos": []
  },
  {
    "name": "education",
    "created": "2016-12-07T10:50:47.939Z",
    "lastUpdated": "2016-12-07T10:50:47.939Z",
    "videos": []
  },
  {
    "name": "fun",
    "created": "2016-12-07T10:51:17.914Z",
    "lastUpdated": "2016-12-07T10:51:17.914Z",
    "videos": [
      {
        "name": "ram1234",
        "id": "5852d7c74f9baf4032e29d46",
        "categoryId": "fun"
      },
      {
        "name": "ram1234",
        "id": "5852d7c64f9baf4032e29d45",
        "categoryId": "fun"
      }
    ]
  }
]

```

But, I want response 


```
 {
    "name": "comedy",
    "created": "2016-12-07T10:51:28.422Z",
    "lastUpdated": "2016-12-07T10:51:28.422Z",
    "videos": [{
        "name": "ram12345",
        "id": "5852d7c74f9baf4ddd2e29d32",
        "categoryId": "comedy"
      },
      {
        "name": "ram12346",
        "id": "5852d7c64f9baf4032es9d11",
        "categoryId": "comedy"
      }]
  },
  {
    "name": "education",
    "created": "2016-12-07T10:50:47.939Z",
    "lastUpdated": "2016-12-07T10:50:47.939Z",
    "videos": [{
        "name": "ram12349",
        "id": "5852d7c74f9baf4032e29d88",
        "categoryId": "education"
      },
      {
        "name": "ram12347",
        "id": "5852d7c64f9baf4032e29d77",
        "categoryId": "education"
      }]
  },
  {
    "name": "fun",
    "created": "2016-12-07T10:51:17.914Z",
    "lastUpdated": "2016-12-07T10:51:17.914Z",
    "videos": [
      {
        "name": "ram12341",
        "id": "5852d7c74f9baf4032e29d46",
        "categoryId": "fun"
      },
      {
        "name": "ram1234",
        "id": "5852d7c64f9baf4032e29d45",
        "categoryId": "fun"
      }
    ]
  }
]
```

**Comment by jannyHou** [comment] 2016-12-16 15:22
@somu1251 From the result it's more like video instances are not **related** to the first two category instances properly...not a problem of the filter.

A filter bug wouldn't result in some instances contain correct result but some not :p 

Please make sure you can see video instances 
```
 "videos": [{
        "name": "ram12345",
        "id": "5852d7c74f9baf4ddd2e29d32",
        "categoryId": "comedy"
      },
      {
        "name": "ram12346",
        "id": "5852d7c64f9baf4032es9d11",
        "categoryId": "comedy"
      }]
```
in function 
```js
category_instance_comedy.videos(function(err, videos){
 // you should be see video instances 
})
```

If it still doesn't work, please fork https://github.com/strongloop/loopback-sandbox and replace with your code & sample data. It's hard for me to move on without it.

**Comment by saikumara** [comment] 2017-01-20 14:08
@jannyHou Did you get any solution for this issue, I am struggling for this.

**Comment by jannyHou** [comment] 2017-01-25 22:14
@saikumara Sorry I still could not reproduce the error, at least with memory connector, please check the test I mentioned in comment https://github.com/strongloop/loopback/issues/3030#issuecomment-267394049

Let's take that test as example and modify the query to test our scenarios:

Scenario one:
```js
User.find({
      include: {relation: 'posts', scope: {
        limit: 1, // set limit as 1, so the expected result is each user includes at most one post
      }},
    }, function(){});
```

Get the expected result, please note that User CDE don't have posts so the result is empty array, not a bug:
[
{"name":"User A","age":21,"id":1,"posts":[{"title":"Post A","id":1,"userId":1}]},
{"name":"User B","age":22,"id":2,"posts":[{"title":"Post D","id":4,"userId":2}]},
{"name":"User C","age":23,"id":3,"posts":[]},
{"name":"User D","age":24,"id":4,"posts":[]},
{"name":"User E","age":25,"id":5,"posts":[]}
]

Scenario 2: 
```js
User.find({
      include: {relation: 'posts', scope: {
        limit: 10, // set limit as 10, so the expected result is each user includes at most ten post
      }},
    }, function(){});
```

Get the expected result, neither A nor B's results exceed 10, so results include all posts.
[{"name":"User A","age":21,"id":1,"posts":[{"title":"Post A","id":1,"userId":1},{"title":"Post B","id":2,"userId":1},{"title":"Post C","id":3,"userId":1}]},
{"name":"User B","age":22,"id":2,"posts":[{"title":"Post D","id":4,"userId":2}]},
{"name":"User C","age":23,"id":3,"posts":[]},
{"name":"User D","age":24,"id":4,"posts":[]},
{"name":"User E","age":25,"id":5,"posts":[]}]

**Comment by jannyHou** [comment] 2017-04-20 19:33
same one as https://github.com/strongloop/loopback/issues/1744, I am closing this one and let's keep discussion under issue#1744, thanks for understanding.

**Closed by jannyHou** 2017-04-20 19:33 UTC
Labels: blocked, triaging
