### ISSUE TITLE
Assertion Error with strong-globalize

### ISSUE THREAD

**Issue by tammylim** [strongloop/loopback#3958] opened 2018-07-27 15:05 UTC
Hi all, 

I have been using loopback for my server. 

Node v10.7.0
Loopback v4.2.0 (generator-loopback@5.8.2 loopback-workspace@4.3.0

There is an assertion error that pops up at random times when I run node .  

As shown below:

<img width="884" alt="screen shot 2018-07-27 at 15 56 34" src="https://user-images.githubusercontent.com/33103423/43328425-d8ec5f72-91b5-11e8-94f8-9d3f2ddf87a4.png">

To temporarily fix it, I uninstall and reinstall loop-back. The error goes away for a while, but it comes back again. I have not changed any of the code in the globalize.js file. 

Any help would be greatly appreciated!

**Comment by dhmlau** [comment] 2018-07-27 18:50
@tammylim , I tried to reproduce your problem but failed.  Could you please let us know how to reproduce the error?
Here is what i've tried:
- install latest version of loopback-cli
   i.e. generator-loopback@5.8.2 loopback-workspace@4.3.0 are installed.
- use `lb app` to scaffold a LB app, pick `hello-world`
    i.e. LB app is using loopback@3.21.0
- Run `node .`

**Comment by tammylim** [comment] 2018-07-28 16:17
@dhmlau,

First of all thanks for getting beck so quickly,

There are no specific steps to reproduce it. It just comes up occasionally when I run "node ." on my project.
I think it is related to #51 

But let me know if there is any other information I can provide regarding this

Tammy

**Comment by dhmlau** [comment] 2018-08-02 13:18
Um.. The PR https://github.com/strongloop/loopback/pull/51 with title `Refactor email model into mail connector` has merged in 2013.  Is it the one you're referring to?

**Comment by dhmlau** [comment] 2018-11-10 03:54
@tammylim , I'd like to follow up with you whether you're still running into the same problem.  If so, whether you have more information that can provide to us.  Thanks!

**Comment by dhmlau** [comment] 2019-02-08 23:01
Closing due to inactivity.  @tammylim, if you still encounter this issue, please let me know and I'll reopen this ticket. Thanks.

**Closed by dhmlau** 2019-02-08 23:01 UTC
