### ISSUE TITLE
Bug when using PersistedModel.find on boot script

### ISSUE THREAD

**Issue by dodiego** [strongloop/loopback#1598] opened 2015-08-16 03:14 UTC
So, i have two seed files, `server/boot/seed/category.js` and `server/boot/seed/interest.js`.
And i have a boot script `server/boot/migrations.js`.

The three files looks like this:

`server/boot/migrations.js`

```
var category = require('./seed/category');
var interest = require('./seed/interest');
var async = require('async');

module.exports = function(app) {
    var ds = app.dataSources['postgres'];

    if(ds.connected) {
        ds.automigrate();
    } else {
        ds.once('connected', function() {
            ds.automigrate(function (err) {
                if (!err) {
                    async.series([
                        category.seed,
                        interest.seed,
                    ], function (err) {
                        console.log(err);
                    });
                }
            });
        });
    }
};
```

`server/boot/seed/category.js`

````
var _       = require('lodash');
var app     = require('../../server');
var async = require('async');

module.exports.seed = function (callback) {

    var categoryNames = [ 'category 1', 'category 2', 'category 3' ];

    async.each(categoryNames, function (categoryName, callback) {
        app.models.category.create({
            name: categoryName
        }, callback)
    }, callback);
}
```

`server/boot/seed/interest.js`

```
var _ = require('lodash');
var app = require('../../server');
var async = require('async');

module.exports.seed = function (callback) {

    var interestsByCategory = {
        'category 1': [{
            name: 'interest 1'
        }, {
            name: 'interest 2'
        }, {
            name: 'interest 3'
        }],
        'category 2': [{
            name: 'interest 4'
        }, {
            name: 'interest 5'
        }, {
            name: 'interest 6'
        }]
    }

    app.models.category.find(function (categories) {
        async.each(categories, function (category, callback) {
            async.each(interestsByCategory[category.name], function (item, callback) {
                app.models.interest.create(item, callback);
            }, callback);
        }, callback);
    });
}
```

The problem is: the `categories` argument in `server/boot/seed/interest.js` is undefined. The seed of interests runs after the seed of categories, i checked in the database and the data is there, so i don't know why `categories` is undefined. I'm using postgresql and checked the data with pg_admin.

P.S: The funny thing is that i was able to solve this using `bluerbird` Promisification, when i use the promisified version (`app.models.category.findAsync`) i get the list of categories and everything works fine.

**Comment by superkhau** [comment] 2015-08-17 15:58
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by dodiego** [comment] 2015-08-17 17:09
Sure, here it is

https://github.com/dodiego/loopback-sandbox

**Comment by superkhau** [comment] 2016-02-03 02:34
@dodiego Are you still running into issues with this?

**Comment by superkhau** [comment] 2016-04-19 01:29
@dodiego I think the issue is you're using async functions without using async boot scripts.

```
module.exports = function(app, cb) {
  ...
};
```

Try that and let me know if you're still running into issues. In addition, you should use inclusion for what you're trying to do. I see parts of your code where you're trying to get specific properties of interest based on categories, etc. See https://docs.strongloop.com/display/APIC/Include+filter

Gonna close this for now. Please ping if you're still working on and running into issues.

**Closed by superkhau** 2016-04-19 01:29 UTC
Labels: triage
