### ISSUE TITLE
Authorization header is not acceptable for resolving $owner role in ACLs?

### ISSUE THREAD

**Issue by jubbens** [strongloop/loopback#2149] opened 2016-03-16 21:10 UTC
I am testing my API using Supertest and Mocha. I'm having problems getting a test to pass which involves logging in as a user, creating a new instance, and then deleting that instance. The purpose of this test is to verify that authenticated users are able to delete their own instances but I'm getting `401 UNAUTHORIZED` on the `DELETE` command.

I have a feeling that passing the access token via the `Authorization` header does not result in successfully resolving the token as the $owner. I've verified that the correct User Id is set in `ownerId` for the created instance.

Here is my test:

```
  it('should respond 200 on authenticated DELETE requests to Cars owned by the user', function(done) {
    agent
    .post('/api/users/login')
    .send({ email: 'test@email.com', password: 'myTestPassword', ttl: '1209600000' })
    .set('Accept', 'application/json')
    .set('Content-Type', 'application/json')
    .expect(200)
    .end(function(err, authRes) {
      if (err) {
        return done(err);
      }

      var token = authRes.body.id;

      agent
      .post('/api/Cars')
      .set('Authorization', token)
      .expect(200)
      .expect('Content-Type', /json/)
      .end(function(err, res) {
        if (err) {
          return done(err);
        }

        agent
        .delete('/api/Cars/1')
        .set('Authorization', token)
        .expect(200)
        .end(function(err, res) {
          if (err) {
            return done(err);
          } else {
            return done();
          }
        });
      });
    });
  });
```

And here is the ACL configuration for `Cars`:

```
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "content-provider",
      "permission": "ALLOW",
      "property": "create"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ],
```

**Comment by jubbens** [comment] 2016-03-17 14:04
I turned on `loopback:security:*` debugging messages and it appears to be correctly identifying the token as belonging to the user. However, I am still getting `401` on the API request.

```
  loopback:security:role isInRole(): $owner +0ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: +0ms
  loopback:security:access-context principal: {"type":"USER","id":2} +0ms
  loopback:security:access-context modelName Style +0ms
  loopback:security:access-context modelId 1 +0ms
  loopback:security:access-context property deleteById +0ms
  loopback:security:access-context method deleteById +0ms
  loopback:security:access-context accessType WRITE +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "fRfNFmF0mIgx6eRO86YIMAEHuzxajAUCmSIMCGPGsEXfpIPhNEWps93lw1tQHNps" +0ms
  loopback:security:access-context   ttl 31556926 +0ms
  loopback:security:access-context getUserId() 2 +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role Custom resolver found for role $owner +0ms
  loopback:security:role isOwner(): Car 1 userId: 2 +0ms
```

**Comment by richardpringle** [comment] 2016-03-18 13:41
Hey @jubbens, is it possible for you to put this example in a forked [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) for me so I can take a closer look? I do appreciate the code you have posted as well as the logs, but forking the sandbox just makes the debugging and error reproduction process go a lot faster for me.

I did try to reproduce the error, but I could not even POST to /api/Cars. I also tried playing around with the order of the ACLs to no avail.

Once you have the forked sandbox up, I will take another look and see how we can resolve this issue.

**Comment by richardpringle** [comment] 2016-03-18 14:55
@jubbens, upon further documentation review I have found the following:
>To qualify a $owner, the target model needs to have a belongsTo relation to the User model (or a model extends from User) and property matching the foreign key of the target model instance. The check for $owner is only performed for a remote method that has ':id' on the path, for example, GET /api/users/:id.

The above quote comes from [here](https://docs.strongloop.com/display/public/LB/Defining+and+using+roles).

To make the ACL work, create a belongsTo relationship between Car and User. Since you are only allowing the `content-provider` role to create Cars, you can inject the userId upon creation using an operation hook.

**Comment by jubbens** [comment] 2016-03-18 15:46
Hi @richardpringle thanks for looking into this for me.

I do indeed have a belongsTo relation and the foreign key is getting set correctly. I'm using middleware to inject the owner ID into the request.

I made a [sandbox](https://github.com/jubbens/loopback-sandbox) for the problem as you requested. It's inside the nested loopback-sandbox folder in that repo. You can just `npm test` to run the test.

**Comment by richardpringle** [comment] 2016-03-18 18:19
>... property matching the foreign key of the target model instance.

You have set `ownerId` instead of `userId` which is the default foreign key. You either need to change the name in the middleware function or change the foreign key to `"ownerId"`. 

I still could not get your test to pass though. I tested by hand with loopback-component-explorer and it worked fine (although that is passing in the access token as a query string, but it should produce the same results). 

There is something wrong with that test, I could not get the first `POST` creating a user to work.

**Comment by jubbens** [comment] 2016-03-18 18:24
@richardpringle Thanks for your help, I simply changed the injected id from ownerId to userId and the test passes for me now. My fault, I owe you a beer. :)

**Comment by richardpringle** [comment] 2016-03-18 18:27
Perfect! Closing.

**Closed by richardpringle** 2016-03-18 18:27 UTC
Labels: triage, waiting
