### ISSUE TITLE
Dead links to useful scripts in loopback postgres datasource docs

### ISSUE THREAD

**Issue by capnajax** [strongloop/loopback#1262] opened 2015-03-31 18:02 UTC
Dead links in the docs - http://docs.strongloop.com/display/public/LB/Connecting+to+PostgreSQL there's a reference to some very useful looking scripts - discover-schema.js, discover-and-build.js, but the links are dead, should link to scripts in https://github.com/strongloop/loopback-example-postgresql/tree/master/server/bin

**Comment by crandmck** [comment] 2015-03-31 18:33
Duplicate of https://github.com/strongloop-internal/scrum-loopback/issues/184

**Closed by crandmck** 2015-03-31 18:33 UTC
