### ISSUE TITLE
When i try to create a new user does not store password on MLAB mongo DB database

### ISSUE THREAD

**Issue by errepy** [strongloop/loopback#4045] opened 2018-10-29 12:44 UTC
Hello, i install a new api with the new updates, i choose to create the api with the default user registration and authentication. 
I connect my new API with MLAB using a mongo DB database to store the values.. 
When i create a new user, on the database, it only store some values form the JSON, username and email only, but i send 3 values, username email and password, but for some reason does not store the password and is not possible to login on the plataform. i want to know what is this happend and if is a bug or what. thank you

**Comment by matteo-pennisi** [comment] 2018-10-29 13:21
We are talking about this in #1314

**Comment by hacksparrow** [comment] 2018-10-29 18:57
Known issue, being tracked at https://github.com/strongloop/loopback-datasource-juggler/issues/1645.

**Comment by raymondfeng** [comment] 2018-10-29 19:32
Close as duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/1645

**Closed by raymondfeng** 2018-10-29 19:32 UTC
