### ISSUE TITLE
User.resetPassword does not return error when email is not found 

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1374] opened 2015-05-10 04:05 UTC
There's a miss in the User.resetPassword code where the callback does not clarify when a user isn't found for the supplied email. 

See my annotation in the code below and a suggested fix:
https://github.com/strongloop/loopback/blob/master/common/models/user.js#L479

```js
User.resetPassword = function(options, cb) {

...

    UserModel.findOne({ where: {email: options.email} }, function(err, user) {
      if (err) {
        cb(err);
      } else if (user) {
        // create a short lived access token for temp login to change password
        // TODO(ritch) - eventually this should only allow password change
        user.accessTokens.create({ttl: ttl}, function(err, accessToken) {
          if (err) {
            cb(err);
          } else {
            cb();
            UserModel.emit('resetPasswordRequest', {
              email: options.email,
              accessToken: accessToken,
              user: user
            });
          }
        });
      } else {
        cb(); // <<<<<<<<<<----- This does not clearly report that the user record was not found
      }
    });
...
};
```

Suggested fix:
```

UserModel.findOne({ where: {email: options.email} }, function(err, user) {
      if (err || !user) {
        return cb(err ||  'Email not found');
      }
      user.accessTokens.create({ttl: ttl}, function(err, accessToken) {
          if (err) {
            cb(err);
          } else {
            cb();
            UserModel.emit('resetPasswordRequest', {
              email: options.email,
              accessToken: accessToken,
              user: user
            });
          }
      });

});

```

Thanks!

**Comment by fabien** [comment] 2015-05-10 05:02
This is a possible security and certainly a privacy issue: anyone is able to figure out if you are a registered user just by trying out someone's email address and getting feedback. 

Duplicate of #947

**Closed by fabien** 2015-05-10 05:02 UTC

**Comment by simoami** [comment] 2015-05-11 16:23
Thanks, I didn't realize this what already brought up. Please see my comment:
https://github.com/strongloop/loopback/issues/947#issuecomment-100967746

**Comment by moneer99** [comment] 2015-06-14 05:01
I totally agree with you, Simoami.
If I tried to reset my password and accidentally wrote my email with a missing letter for example, I would be very annoyed if I saw "Reset mail sent successfully" and I didn't recieve that email without knowing the reason.
