### ISSUE TITLE
findById generated by relations(HasMany for example) doesn't accept a filter option

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#1923] opened 2015-12-29 08:23 UTC
findById generated by relations(HasMany for example) doesn't accept a filter option(to pass include option forexample), but it should since the findById in persisted model accepts a filter option.

**Comment by jannyHou** [comment] 2016-01-05 20:56
hey @alFReD-NSH,  Suppose we have two models:
`ModelA` hasMany `ModelB` as modelBs
`ModelB` belongsTo `ModelA` as modelA
If I understand correctly, "findById generated by relations" maps endpoint `GET modelAs/{id}/modelBs`, filters like `where` works here, eg. you can use {where: {"property_of_modelB": "value"}}
But for `include`, do you mean include nest models(eg. modelB hasMany modelC)?

**Comment by alFReD-NSH** [comment] 2016-01-06 11:07
> filters like where works here, eg. you can use {where: {"property_of_modelB": "value"}}

`where` filter also doesn't work. There's no documentation for the filters generated in api explorer. You can also check the code. Here's the [remote method definition](https://github.com/strongloop/loopback/blob/v2.26.2/lib/model.js#L506-L517) and [here's the actual function](https://github.com/strongloop/loopback-datasource-juggler/blob/v2.44.0/lib/relation-definition.js#L745-L798), which both don't accept a filter option, and in the function, it just builds the filter itself.

> But for include, do you mean include nest models(eg. modelB hasMany modelC)?

Yes, I want to something like this: `GET modelAs/{id}/modelBs/{fk}?filter[where][include]=modelCs`

**Comment by jannyHou** [comment] 2016-01-08 20:27
I created a [sandbox repo](https://github.com/jannyHou/loopback-sandbox) to test this, the filter `where` does work here:
1)`category` hasMany `game`
2)`game` belongsTo `category`
3) `game` has a boolean property called `mature`

In explorer, endpoint `GET categories/{id}/games` accepts filter `{"where": {"mature": true}}`:
http://localhost:3000/api/categories/1/games?filter[where][mature]=true

And if you continue define nested relations:
4) `game` hasMany `player`
5) `player` belongsTo `game`

you can use filter `include` in `GET categories/{id}/games`
http://localhost:3000/api/categories/1/games?filter[include]=players

The endpoint `GET modelAs/{id}/modelBs/{fk}?filter[include]=modelCs` you want is not available but as a workaround, you can use the following one:

applies filter `{"where": {"id": your_game_id}, "include": "players"}`to `GET categories/{id}/games`
http://localhost:3000/api/categories/1/games?filter[where][id]=1&[include]=players

**Comment by alFReD-NSH** [comment] 2016-01-09 13:42
Yes, `{"where": {"id": your_game_id}, "include": "players"}` I am using that as a workaround. I thought I should open an issue, because this was a surprise thinking that since I expected relations findById to be consistent with normal findById and also not much documentation on what it accepts.

**Comment by alFReD-NSH** [comment] 2016-01-10 07:02
I just realized that using `{"where": {"id": your_game_id}, "include": "players"}` wouldn't work if the relationship is `HasManyAndBelongsTo`.

**Comment by jannyHou** [comment] 2016-01-11 05:12
It's a similar issue to this one:
https://github.com/strongloop/loopback-datasource-juggler/issues/166
We will fix it in the near future. Thank you!

**Comment by jannyHou** [comment] 2016-01-11 23:49
hey @alFReD-NSH  I reproduced issue of `hasAndBelongsToMany`,
`order` doesn't but others are fine, please check my comments here for more details:
https://github.com/strongloop/loopback-datasource-juggler/issues/166#issuecomment-170733928
Thanks!

**Comment by alFReD-NSH** [comment] 2016-01-12 02:39
Did you try `{"where": {"id": your_game_id}, "include": "players"}`? The Id is ignored. Other fields can be used but id doesn't work.

**Comment by jannyHou** [comment] 2016-01-12 14:42
thanks @alFReD-NSH you are right, other fields work except `id`. I will fix it as well.

**Comment by jannyHou** [comment] 2016-01-13 15:56
Since finally it comes to a similar issue, I am closing this one to keep 'issue' page clean. 
Feel free to reopen it when you have other ideas!
And our [Filter Doc](https://docs.strongloop.com/display/public/LB/Querying+data) gives a guideline about how to use each filter.

**Closed by jannyHou** 2016-01-13 15:56 UTC
Labels: triage

**Comment by gocreating** [comment] 2018-07-03 02:55
So the `nested` `findById` does not support `filter[include]`?

My relations are:
- `Project` hasMany `Session`
- `Session` belongsTo `Project`
- `Session` hasMany `Dataset` through `SessionDataset`
- `Dataset` hasMany `Session` through `SessionDataset`

---

`GET /api/projects/<id>/sessions/<fk>?filter={"include": ["datasets"]}` is not working:
```
{
    "name": "test-session",
    "id": "5b33eac4691c423134268c0e"
}
```

but `GET /api/projects/<id>/sessions?filter={"where": {"id": "5b33eac4691c423134268c0e"}, "include": ["datasets"]}` will work:

```
[
    {
        "name": "test-session",
        "id": "5b33eac4691c423134268c0e",
        "datasets": [
            {
                "name": "a2703859-a2a3-40de-a12b-3bd820ff5ad3.png",
                "type": "image/png",
                "originalFilename": "logo.png",
                "size": 548855,
                "url": "/api/containers/raw-data/download/a2703859-a2a3-40de-a12b-3bd820ff5ad3.png",
                "created": "2018-06-27T19:04:55.965Z",
                "id": "5b33dfd72cbccf3cf0da874d",
                "projectId": "5b33df7c2cbccf3cf0da874c",
                "container": "raw-data"
            }
        ]
    }
]
```
