### ISSUE TITLE
Fast sequential POST calls to add a related model breaks relations

### ISSUE THREAD

**Issue by jubbens** [strongloop/loopback#2246] opened 2016-04-19 18:12 UTC
Let's say I have a model called `Cars` and a model called `Tags`, and a hasMany relation which gives me `/Cars/:id/Tags`. If I do quick successive `POST` calls to `/Cars/:id/Tags` (without waiting for each to return) it causes some relations to go missing. The `Tag` models are there, but some of them are not included under `tagIds` for the related `Car`. Random ones go missing.

Adding a 1s sleep between each REST call solves the issue.

**Comment by jannyHou** [comment] 2016-04-22 00:09
@jubbens Thanks for raising up this problem and providing solutions as well, I will see if I can reproduce it and is there any proper approach to handle this scenario.

**Comment by jannyHou** [comment] 2016-04-22 19:45
@jubbens I could not reproduce your problem..

I create an app, with two models: `test` and `subtest`:
`test` hasMany `subtest`
`subtest` belongsTo `test`

Add boot script:
```js
module.exports = function(server) {
  var Test = server.models.test;
  var SubTest = server.models.subtest;

  var sample = [
  {name: 'first'},
  {name: 'second'},
  {name: 'third'},
  {name: 'forth'},
  {name: 'fifth'}];

  Test.create({name: 'test1'}, function(err, test) {
  	// Create 5 subtests belongs to test
    test.subtests.create(sample, function(err, subtests) {
    	// Call subtests 20 times without waiting return
    	for (i=0; i<20; i++) {
	        Test.findById(1, {include: 'subtests'}, function(err, results) {
	        	results = JSON.stringify(results);
	        	results = JSON.parse(results);
	        	console.log("Endpoints>>>", results.subtests);
	        });
  	    }
    });
  });
}
``` 

The returned results are all correct. Do I miss any steps or misunderstand your question here?
Or can you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace with your code? Thanks.

**Comment by jubbens** [comment] 2016-04-23 14:38
Hi @jannyHou 

I'm making the requests via an `HTTP POST` from the iOS SDK. I'm also not sure if this is how the included model functions handle these calls, for example to `/Tests/1/Subtests`?

**Comment by jannyHou** [comment] 2016-04-25 14:21
@jubbens could you please fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace with your code? Or explain more about the steps of how to reproduce it? From your description, it seems like a race condition, but to be honest I am not familiar with ios sdk...it's good if it could be reproduced without touching ios, or I will forward it to expert developer of ios.

**Comment by jannyHou** [comment] 2016-11-04 20:36
I believe it's the same one as https://github.com/strongloop/loopback/issues/2048

Closing this issue and let's move discussion to the above issue.

**Closed by jannyHou** 2016-11-04 20:36 UTC
Labels: triage, waiting
