### ISSUE TITLE
npm test failing with "PhantomJS crashed error"

### ISSUE THREAD

**Issue by ghatwala** [strongloop/loopback#1977] opened 2016-01-20 08:10 UTC
Hi All,

I have phantom js running on my vm.
[root@pts00434-vm7 lp_original]# phantomjs --version
2.0.0
While i perform , npm test in the "loopback" cloned repository. i get the below
Running "karma:unit-once" (karma) task
DEBUG [config]: autoWatch set to false, because of singleRun
DEBUG [plugin]: Loading plugin karma-browserify.
DEBUG [plugin]: Loading plugin karma-mocha.
DEBUG [plugin]: Loading plugin karma-phantomjs-launcher.
DEBUG [plugin]: Loading plugin karma-chrome-launcher.
DEBUG [plugin]: Loading plugin karma-junit-reporter.
DEBUG [framework.browserify]: created browserify bundle: /root/strongloop_pckgs/lp_original/1ed272a8d6a7430cdbb545ddcf4666e3.browserify
DEBUG [framework.browserify]: add bundle to config.files at position 3
DEBUG [framework.browserify]: updating test/support.js in bundle
DEBUG [framework.browserify]: building bundle
DEBUG [framework.browserify]: updating test/loopback.test.js in bundle
DEBUG [framework.browserify]: updating test/model.test.js in bundle
DEBUG [framework.browserify]: updating test/geo-point.test.js in bundle
DEBUG [framework.browserify]: updating test/replication.test.js in bundle
DEBUG [framework.browserify]: updating test/change.test.js in bundle
DEBUG [framework.browserify]: updating test/checkpoint.test.js in bundle
DEBUG [framework.browserify]: updating test/app.test.js in bundle
DEBUG [framework.browserify]: bundling
INFO [framework.browserify]: bundle built
DEBUG [watcher]: Resolved files:
        /root/strongloop_pckgs/lp_original/node_modules/mocha/mocha.js
        /root/strongloop_pckgs/lp_original/node_modules/karma-mocha/lib/adapter.js
        /root/strongloop_pckgs/lp_original/node_modules/es5-shim/es5-shim.js
        /root/strongloop_pckgs/lp_original/1ed272a8d6a7430cdbb545ddcf4666e3.browserify
        /root/strongloop_pckgs/lp_original/test/support.js
        /root/strongloop_pckgs/lp_original/test/loopback.test.js
        /root/strongloop_pckgs/lp_original/test/model.test.js
        /root/strongloop_pckgs/lp_original/test/geo-point.test.js
        /root/strongloop_pckgs/lp_original/test/replication.test.js
        /root/strongloop_pckgs/lp_original/test/change.test.js
        /root/strongloop_pckgs/lp_original/test/checkpoint.test.js
        /root/strongloop_pckgs/lp_original/test/app.test.js
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.37 server started at http://localhost:9877/
INFO [launcher]: Starting browser PhantomJS
DEBUG [temp-dir]: Creating temp dir at /root/strongloop_pckgs/lp_original/karma-76520735
DEBUG [launcher]: /usr/bin/phantomjs /root/strongloop_pckgs/lp_original/karma-76520735/capture.js
â¤â¤â¤â¤â¤DEBUG [web-server]: serving: /root/strongloop_pckgs/lp_original/node_modules/karma/static/client.html
DEBUG [web-server]: serving: /root/strongloop_pckgs/lp_original/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/DM672BcKNsg28IEwEKmq
DEBUG [karma]: A browser has connected on socket DM672BcKNsg28IEwEKmq
INFO [PhantomJS 2.0.0 (Linux 0.0.0)]: Connected on socket DM672BcKNsg28IEwEKmq with id 76520735
DEBUG [launcher]: PhantomJS (id 76520735) captured in 0.862 secs
DEBUG [web-server]: serving: /root/strongloop_pckgs/lp_original/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/node_modules/mocha/mocha.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/model.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/node_modules/karma-mocha/lib/adapter.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/geo-point.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/replication.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/1ed272a8d6a7430cdbb545ddcf4666e3.browserify
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/node_modules/es5-shim/es5-shim.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/loopback.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/support.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/change.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/checkpoint.test.js
DEBUG [web-server]: serving (cached): /root/strongloop_pckgs/lp_original/test/app.test.js
DEBUG [PhantomJS 2.0.0 (Linux 0.0.0)]: Disconnected during run, waiting 10000ms for reconnecting.
DEBUG [launcher]: Process PhantomJS exited with code 0
ERROR [launcher]: PhantomJS crashed.

DEBUG [temp-dir]: Cleaning temp dir /root/strongloop_pckgs/lp_original/karma-76520735
INFO [launcher]: Trying to start PhantomJS again (1/2).

Can anyone comment on the above " PhantomJS crashed " errror  and any pointers on how to resolve the same ?

[root@pts00434-vm7 lp_original]# lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Model:                 IBM pSeries (emulated by qemu)
L1d cache:             64K
L1i cache:             32K
NUMA node0 CPU(s):     0-7
 This is my set up .... 

Regards,
Amit

**Comment by jannyHou** [comment] 2016-01-20 20:23
hey @ghatwala we are looking into a same issue in:
https://github.com/strongloop/loopback/issues/1898#issuecomment-173319350
Can you move to above issue for a further discussion? Thanks!

**Comment by superkhau** [comment] 2016-01-20 20:29
@ghatwala Closing since this is a duplicate of your other issue.

**Comment by superkhau** [comment] 2016-01-20 20:30
@jannyHou Thanks for referencing the original and marking as dupe.

**Closed by superkhau** 2016-01-20 20:29 UTC
Labels: duplicate, triage

**Comment by ghatwala** [comment] 2016-01-21 05:15
@superkhau , @jannyHou  - Thanks for working on this issue ... lemme know if you want to try some ways to debug this issue. I will be communicating on https://github.com/strongloop/loopback/issues/1898#issuecomment-173319350 . Closing this ticket from my end.
