### ISSUE TITLE
include in default scope does not work in model returned after created

### ISSUE THREAD

**Issue by kidwm** [strongloop/loopback#1110] opened 2015-02-19 18:38 UTC
It seemed to be not able to include data of other model in json gotten after sending POST to /api/models ?

**Comment by raymondfeng** [comment] 2015-02-19 19:45
Can you elaborate what you are trying to do?

**Comment by Nutelac** [comment] 2015-02-20 00:07
It is the same problem described here https://github.com/strongloop/loopback/issues/1094?

**Comment by kidwm** [comment] 2015-02-20 01:37
@Nutelac Yes, thank you!

**Comment by superkhau** [comment] 2015-02-25 06:39
Closing as duplicate of #1094. @kidwm Repoen if this is still an issue.

**Closed by superkhau** 2015-02-25 06:39 UTC
Labels: duplicate
