### ISSUE TITLE
model did not write to mongo database if enable mongodb authentication

### ISSUE THREAD

**Issue by meepeek** [strongloop/loopback#3874] opened 2018-05-06 20:18 UTC
# Description/Steps to reproduce

app.models.[model name].create did not write to mongodb if mongodb enabled authentication. The same code works when authentication disabled.

# Steps to reproduce
1. Create new loopback project (3.x)
2. Create datasource as following
```
  "mongo": {
    "host": "localhost",
    "port": 27017,
    "url": "",
    "database": "test",
    "password": "",
    "name": "mongo",
    "connector": "mongodb",
    "user": "me"
  }
```
3. Create file boot/test.js with following content
```
module.exports = async function(app) {
  console.log(await app.models.a.create({test:'123'}))
  console.log(await app.models.b.create({test:'234'}))
}
```
4. run project with "node ." command, it will write to the database correctly
5. go to mongo console, (type mongo in the command line) then use the following command to create new user
```
db.createUser( { user: "demo", pwd: "demo", roles: [ { role: "root", db: "admin" } ] } )
```
6. edit /etc/mongodb.conf as root, enable auth by uncomment line #auth = true
7. save conf and restart mongodb service
8. drop test database that was created
9. edit datasource.json as follow
```
  "mongo": {
    "host": "localhost",
    "port": 27017,
    "url": "mongodb://demo:demo@localhost:27017",
    "database": "test",
    "password": "demo",
    "name": "mongo",
    "connector": "mongodb",
    "user": "demo"
  }
```
10. run loopback project again, this time there will also be no error but the data will not be written in the database

**Comment by meepeek** [comment] 2018-05-06 20:34
loopback 2.x also has this problem as well, could it be the connector having problem ?

**Comment by dhmlau** [comment] 2018-05-07 20:44
@meepeek , I'm closing this ticket as it's a duplicate of another ticket you've created in `loopback`: https://github.com/strongloop/loopback/issues/3874.  Thanks.

**Closed by dhmlau** 2018-05-07 20:44 UTC
