### ISSUE TITLE
behavior or bug for where filter ?

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback#2413] opened 2016-06-08 15:13 UTC
# Context
`MyObject` extends `PersistedModel`
2+ instances in the database
Querying on this model with the node API `MyObject.find()` method using two properties

# Problem ?
if one of the properties has value `undefined`, the where filter matches the first object with the other property that matches.

Long story short, does a where filter matches the closest or is it supposed to do a fullmatch on multiple searched properties ? 

# Example
> db data

```
[{
   provider: 'strongloop',
   key: 'foo'
},
{
   provider: 'loopback',
   key: 'foo'
}]
```
Then with node API 
```  
MyObject.find({
  where: {
     provider: 'loopback',
     key: undefined
 },
 function(err, objs) { //...});
```
Returns the second object.
If this is normal behavior, I don't believe it is [documented](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-NodeAPI).
Otherwise I can make a repository for reproducing the issue. Let me know.

**Comment by BoLaMN** [comment] 2016-06-08 19:13
duplicate of #1009

**Comment by gunjpan** [comment] 2016-06-08 20:05
@Overdrivr : I believe that's a normal as in `where` filter, if you provide `key: undefined`, properties with `undefined` are discarded to create the query and that's why it will behave as following `where` filter:
```javascript
MyObject.find({
  where: {
     provider: 'loopback'
    }
 },function(err, objs) { //...});
```
@bajtos : Thoughts on whether this should be documented.

**Comment by Overdrivr** [comment] 2016-06-08 20:25
Makes sense, but I realize now I have given an incomplete view of the problem.

I had this issue while putting a wrong key inside the where filter. The model has properties `provider` and `provider_id`, and I put `provider` and `id` instead.

After realizing what was going on, I thought that maybe the node API should throw an error or return 0 instances.

**Comment by gunjpan** [comment] 2016-06-09 14:14
@Overdrivr : 
> I thought that maybe the node API should throw an error or return 0 instances.

I am pretty sure that node API returns an empty array in case of no matching instance found.
Please let me know if you've any further questions or is it good to close?

**Comment by Overdrivr** [comment] 2016-06-09 14:16
Let's close for now, I'll make a test repo and reopen if I find something
odd.

**Comment by gunjpan** [comment] 2016-06-09 14:28
@Overdrivr : Great! thank you :)

**Closed by gunjpan** 2016-06-09 14:28 UTC
Labels: triage
