### ISSUE TITLE
Cannot install strongloop using npm install -g strongloop

### ISSUE THREAD

**Issue by roopesh90** [strongloop/loopback#1073] opened 2015-02-05 12:11 UTC
I have installed strongloop on my local system with no issues, but when i try install the same on my remote using 
`npm install -g strongloop`
I get the following errors and the process exits
```
$ npm install -g strongloop
/
> heapdump@0.2.10 install /home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/heapdump/src/heapdump.o
  CXX(target) Release/obj.target/heapdump/src/platform-posix.o
  SOLINK_MODULE(target) Release/obj.target/heapdump.node
  SOLINK_MODULE(target) Release/obj.target/heapdump.node: Finished
  COPY Release/heapdump.node
make: Leaving directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
 
> strong-fork-syslog@1.2.3 install /home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

make: Entering directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
  SOLINK_MODULE(target) Release/obj.target/syslog.node
  SOLINK_MODULE(target) Release/obj.target/syslog.node: Finished
  COPY Release/syslog.node
make: Leaving directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
 
> strong-agent@1.3.2 install /home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

make: Entering directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  SOLINK_MODULE(target) Release/obj.target/strong-agent.node: Finished
  COPY Release/strong-agent.node
make: Leaving directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-agent/build'
npm WARN optional dep failed, continuing express@3.19.2
-
> ws@0.4.32 install /home/a7/npm-global/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws/build'
 
> ws@0.4.32 install /home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/a7/npm-global/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/ws/build'
npm ERR! EEXIST, open '/home/a7/.npm/99390cf3-a7-npm-mime-db-1-6-0-package-tgz.lock'
File exists: /home/a7/.npm/99390cf3-a7-npm-mime-db-1-6-0-package-tgz.lock
Move it away, and try again. 

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "strongloop"
npm ERR! cwd /home/a7
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path /home/a7/.npm/99390cf3-a7-npm-mime-db-1-6-0-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

**Comment by zanzamar** [comment] 2015-02-17 22:40
You can try `npm cache clear` then run the install again.

**Comment by roopesh90** [comment] 2015-02-18 09:28
Hey thanks for the reply @zanzamar.
unfortunately, it didn't work. Ended up with the same error

**Comment by ricardohbin** [comment] 2015-03-03 12:32
Did you try do the delete file file `/home/a7/.npm/99390cf3-a7-npm-mime-db-1-6-0-package-tgz.lock` as the error suggests?

**Comment by roopesh90** [comment] 2015-03-04 06:44
@ricardohbin the file gets deleted by npm after the execution automatically somehow. I cant find it.

**Comment by roopesh90** [comment] 2015-03-04 06:45
@ricardohbin the file gets deleted by npm after the execution automatically somehow. I cant find it.
and I closed the issue by mistake, apologies.

**Comment by roopesh90** [comment] 2015-03-04 06:46
@ricardohbin the file gets deleted by npm after the execution automatically somehow. I cant find it.
and I closed the issue by mistake, apologies.

**Comment by atajwala** [comment] 2015-03-12 02:07
I am seeing the same issue when installing strongloop on a gcloud hosted ubuntu micro instance.

**Comment by AaronBedward** [comment] 2015-03-12 13:01
Also having the issue, tried deleting npm-mime-db lock still the same issue
- Ubuntu 14.04

**Comment by petermac-** [comment] 2015-04-22 23:50
+1, same issue on Ubuntu 14.04. Tried deleting the file and running npm cache clear/clean to no avail.

**Comment by roopesh90** [comment] 2015-04-27 10:42
Friendly neighborhood dev advice:
Django became my saviour ;D

**Comment by roopesh90** [comment] 2015-12-30 16:03
Still for answers or solutions??

**Comment by superkhau** [comment] 2015-12-30 21:41
@cgole ^

**Comment by loay** [comment] 2016-02-11 03:19
Hi @roopesh90 
Is this being resolved?

**Comment by cleever** [comment] 2016-02-22 03:07
Sadly strongloop/loopback on ubuntu is completely brooken

**Comment by loay** [comment] 2016-02-22 20:12
I got it installed on an Ubuntu 14 server with the following
```
$ npm -v
2.14.7
$ node -v
v4.2.3
```
@cleever did you try `npm cache clear` then reinstalling? What version of npm and node are you using?
Can you print here the error message that you are getting. Thanks.

**Comment by roopesh90** [comment] 2016-04-13 13:13
Haven't gone back to the loopback implementation. Since i didn't get a solution and was in a time-crunch, I had to shift to Django.

**Comment by loay** [comment] 2016-04-13 18:03
@AaronBedward @cleever @petermac- 
How about you guys? Have you recently tried to install?
Thanks.

**Comment by superkhau** [comment] 2016-04-13 22:57
@cgole Ping, can you verify if installing strongloop on Ubuntu 14.04 is indeed broken?

**Comment by smartmouse** [comment] 2016-04-14 15:36
Looks like you are using node 0.10.36 version., pretty old , I think there are new node 0.10.x version.

**Comment by loay** [comment] 2016-04-14 15:56
So basically it is not broken on Ubuntu. a test was made and it installs fine. It could be an old node version. we will need more details on each case separately, however it is been confirmed that it is not broken.

**Comment by loay** [comment] 2016-04-14 18:39
another test is done. node 0.10 working for strongloop install as well on xlinux ubuntu

**Comment by superkhau** [comment] 2016-04-14 19:09
@loay Let's close this. If anyone is running into issues on Ubuntu 14.04 as of today, please create a new issue with your `node` and `npm` versions. We can solve each issue case-by-case.

**Closed by superkhau** 2016-04-14 19:09 UTC
Labels: bug, major
