### ISSUE TITLE
Include filter doesn't work with hasManyThrough relations

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1850] opened 2015-12-02 14:55 UTC
Using the example on https://docs.strongloop.com/display/public/LB/HasManyThrough+relations

Why the following code does not return all patients for the physician
```js
function physicianHandler(err, physician) {
  var patients = physician.patients(); // returns []
  ...    
}

Physician.findOne({where: {id: '...'}, include: 'patients' }, physicianHandler);
```

This would make things easier

**Comment by gunjpan** [comment] 2015-12-02 16:57
@rkmax : Hi, I'm looking into this issue.
-From the docs at : https://docs.strongloop.com/display/public/LB/HasManyThrough+relations
>__Methods added to the model__
Once you define a "hasManyThrough" relation, LoopBack adds methods with the relation name to the declaring model class’s prototype automatically, for example:  physician.patients.create(...). 

Example method: `physician.patients(filter, function(err, patients) {
  ...
});` finds the `patients` for the `physician`.
I suggest to try adding a `where` filter for above method like 
```physician.patients({where: {physicianId: '...'}, function(err, patients){
 ....
});```and see if it works.

I would like to dig-in more and it would be great if you could please provide me with a sample repo so that I can speedup investigation on `include` filter and promote is as a feature/bug if required.
Thank you.

**Comment by rkmax** [comment] 2015-12-02 17:30
Yes I agree without about the description in the documentation but also inthe [Include filter](https://docs.strongloop.com/display/public/LB/Include+filter) documentation

>An include filter enables you to include results from related models in a query, for example models that have belongsTo or **hasMany** relations, to optimize the number of requests.  See Creating model relations for more information.

I know we're talking about a hasManyThrough but if you look the model definition it's a hasMany relationship with a extra parameter in that case I think the documentation must aclare that do not work for hasManyThrough or even better include this functionality :smiley:

**Comment by gunjpan** [comment] 2015-12-07 15:25
@rkmax : Hey, I tried to reproduce the scenario on my end and I couldn't reproduce the issue. 
Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by gunjpan** [comment] 2016-01-08 16:14
@rkmax : Hi, I used one of the sample app created with LoopBack: [Appointment System](https://github.com/Amir-61/appointmentSystem). 
The app has `hasManyThough` relation implemented.

To see it in action: when the server is running for above app, go to URL (or find the findOne endpoint for Physicians model in explorer) :
`http://localhost:3000/explorer/#!/Physician/Physician_findOne`
and use following filter. It would return the `patients` related to the `physician`
>`{"where": {"id": "1"}, "include": "patients" }`

Please let me know your thoughts and if it resolves your concern, please verify to close the issue.

**Comment by rkmax** [comment] 2016-01-08 16:20
@gunjpan thank you. I'll double check the relations of my models. maybe I'm doing something wrong

**Comment by gunjpan** [comment] 2016-01-18 16:18
@rkmax : Hi, is this good to close now??

**Comment by rkmax** [comment] 2016-01-18 23:12
Yes it was a mistake on the relationships

**Comment by jerv13** [comment] 2016-01-20 23:12
What was the mistake?

**Comment by gunjpan** [comment] 2016-02-05 18:29
@rkmax Glad it worked. closing.

**Closed by gunjpan** 2016-02-05 18:29 UTC
Labels: discussion

**Comment by kamal0808** [comment] 2016-07-28 16:39
@rkmax - what was the mistake? going through the same issue here

**Comment by bagintz** [comment] 2018-03-23 19:31
@rkmax can you share your mistake if you remember, I am having the same problem

**Comment by bagintz** [comment] 2018-03-23 19:58
fwiw, I found my problem, I had a weird table structure that I had to override the "keyThrough" for.

**Comment by ewic** [comment] 2018-08-21 21:21
Thought I would through that I had the same issue.

The issue occurred because I had had to specify a "keyThrough" attribute to the relation that was set to the foreign key in the associative entity of the target table.

**Comment by khiemm** [comment] 2020-04-07 15:43
I think I have the same problem
I have `categories_product.json` and `product.productCategory()` return empty
```
"properties": {
    "categoryId": { //here
      "type": "number",
      "postgresql": {
        "columnName": "category_id"
      }
    },
    "productId": {
      "type": "number",
      "postgresql": {
        "columnName": "product_id"
      }
    }
  },
  "validations": [],
  "relations": {
    "productCategory": {
      "type": "belongsTo",
      "model": "ProductCategory",
      "foreignKey": "categoryId" //here
    },
    "product": {
      "type": "belongsTo",
      "model": "Product",
      "foreignKey": "productId"
    }
  }
```
and I fixed it
```
"properties": {
    "productCategoryId": { //here
      "type": "number",
      "postgresql": {
        "columnName": "product_category_id"
      }
    },
    "productId": {
      "type": "number",
      "postgresql": {
        "columnName": "product_id"
      }
    }
  },
  "validations": [],
  "relations": {
    "productCategory": {
      "type": "belongsTo",
      "model": "ProductCategory",
      "foreignKey": "productCategoryId" //here
    },
    "product": {
      "type": "belongsTo",
      "model": "Product",
      "foreignKey": "productId"
    }
  }
```
