### ISSUE TITLE
Can not call Model.create().The create method has not been setup.The PersistedModel has not been correctly attached to a DataSource

### ISSUE THREAD

**Issue by jiwansidhu** [strongloop/loopback#3564] opened 2017-08-14 18:10 UTC
Hello ..

I am using loopback 3 ..
I just created new loopback project  by following http://loopback.io/examples/. I have one model Product and i am already connected to my datasource(jiwan_db).Still i am receiving error - "can not call product.create().The create method has not been setup.The PersistedModel has not been correctly attached to a DataSource " .My explorer is working well. 

Is there more steps to do . Please give your advise. 

**Thanks in advance !!.**

My files are as follows 

# **model-config.json** :- 

{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "product": {
    "dataSource": "jiwan_db",
    "public": true
  }
}

# **datasources.json**

{
  "jiwan_db": {
    "host": "localhost",
    "port": 27017,
    "url": "",
    "database": "jiwan_db",
    "password": "",
    "name": "jiwan_db",
    "user": "",
    "connector": "mongodb"
  }
}

# **common/models/product.json**:-

'use strict';

module.exports = function(Product) {

 Product.create({name: 'stationery', qty: 1});

};

# **product.json**

{
  "name": "product",
  "plural": "products",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "qty": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

**Comment by kjdelisle** [comment] 2017-08-15 19:10
@jiwansidhu Would you be able to bring all of this together in an example application that demonstrates the problem? I noticed that you sanitized your configuration (which I understand!), but being able to run an app against a MongoDB instance in Docker or something to that effect would go a long way in helping us find the root cause of the problem.

**Comment by jiwansidhu** [comment] 2017-08-16 13:40
@kjdelisle thanks alot for reply and suggestion but i don't have experience with docker for now. I will try later for sure. Can you please give some options which cause this error.

FYI , when i create the data from explorer it works fine (afterRemote methods works fine ), i didn't understand why methods like create and find are not working from my model.

**Comment by kjdelisle** [comment] 2017-08-16 15:23
@jiwansidhu Sorry, to clarify: I don't necessarily mean that _you_ need to use Docker for anything; if you create a sample application and post it to GitHub, we can pull it down, connect it to a MongoDB database and see what the issue is.

If you were to additionally use Docker, like we do [for our unit testing in the mongodb connector](https://github.com/strongloop/loopback-connector-mongodb/blob/master/setup.sh), then you would know that your reproduction shows the problem before you give it to us.

**Comment by jiwansidhu** [comment] 2017-08-16 15:49
@kjdelisle  thanks for quick reply. I just upload zipped project folder on my account https://github.com/jiwansidhu/loopback-test . Please check and test on your side.

Thanks in advance and for update info for docker too.

**Comment by kjdelisle** [comment] 2017-08-16 15:52
@jiwansidhu I was hoping more for an unpacked repository, but that's okay! :P

**Comment by jiwansidhu** [comment] 2017-08-16 15:59
@kjdelisle heh..dont't mind. In hurry i zipped my folder and upload .

**Comment by kjdelisle** [comment] 2017-08-16 16:12
The issue is within your project.js file:
```
module.exports = function(Product) {
 Product.create({name: 'stationery', qty: 1});
};
```

Loopback already handles the basic CRUD operations for you; if you were to remove the call to `Product.create(...)` from within here, the operation would work as normal.
To see this, you can remove that line of code, start the application, then browse to `localhost:3000/explorer`. This will pull up an OpenAPI/Swagger explorer that you can use to test your REST endpoints. At this step, you can POST a new Product instance, and then GET it back to see the results.

If you're worried that it's not reaching the database, you can always connect to your MongoDB instance directly using your favourite client and check that the document was inserted afterwards.

The {model}.js files are meant primarily to allow you to control aspects of your CRUD workflow; if you want to apply more advanced _logical_ constraints to the creation, update, deletion or retrieval of models, you would do that here, using [operation hooks](http://loopback.io/doc/en/lb3/Operation-hooks.html)

For example, if you wanted to make sure that no one could submit a product whose quantity is non-negative, or not greater than two million, you could do that like so:

product.js
```
'use strict';

module.exports = function(Product) {
  Product.observe('before save', function(ctx, next) {
    var err = null;
    if (ctx.instance.qty < 0) {
      err = new Error('qty must be greater than zero');
      err.statusCode = 422;
    } else if (ctx.instance.qty > 2000000) {
      err = new Error('qty must be less than 2000000');
      err.statusCode = 422;
    }
    return next(err);
  });
};

```

**Comment by kjdelisle** [comment] 2017-08-16 16:13
cc @jiwansidhu  ^^^

**Comment by jiwansidhu** [comment] 2017-08-16 16:28
@kjdelisle thanks for quick solution. yeah that works when we remove create method but kevin, what does that means? 
As you said "The {model}.js files are meant primarily to allow you to control aspects of your CRUD workflow";       this is what i was trying to do i.e create the data from the model. 
 
also if we POST data from explorer and want to retrieve from that model like 

 Product.find({
          }, function (err, dataFound) {
            if (err) {
              console.log(err);
            } else {
              console.log(dataFound)
            }
          });


even then there was issue "find method is not set up....".

Can you please clarify when ever we try to do CRUD from model.js then we face this error.

Thanks

**Comment by kjdelisle** [comment] 2017-08-16 16:44
@jiwansidhu What I mean by that is that those js files aren't the place where you _perform_ your CRUD operations; they're just a stepping stone in the full request lifecycle with a typical LoopBack application.

Simplified breakdown:
Request comes in --> Loopback determines which model based on route format  --> optional extra steps can occur in that model's .js file (**this is what I did in my example**) --> juggler/connector methods are called to persist data, retrieve it, delete it, etc --> response is sent

You might want to review [the core concepts document](http://loopback.io/doc/en/lb3/LoopBack-core-concepts.html) as it seems like you're thinking of the operations as things you perform within the model's associated javascript modules, rather than as a place to perform _additional_ logic at certain parts of the workflow.

**Comment by kjdelisle** [comment] 2017-08-16 17:34
Since this is not an issue with the framework or a bug, I'll be closing this. If you'd like to ask others for help with learning loopback, you can visit the loopbackjs Google Groups page: https://groups.google.com/forum/#!forum/loopbackjs

**Closed by kjdelisle** 2017-08-16 17:34 UTC
Labels: triaging

**Comment by jiwansidhu** [comment] 2017-08-16 17:40
@kjdelisle  thanks alot kevin fo your help. I will join google groups in case i need further help.

**Comment by jpventura** [comment] 2017-12-06 16:06
@kjdelisle https://github.com/jpventura/loopback-petstore

**Comment by kjdelisle** [comment] 2017-12-07 13:53
@jpventura and I went over it together on Gitter and his particular use-case involves the swagger connector, which does things a bit differently (posting this here in case anyone was wondering about the subsequent reply).
