### ISSUE TITLE
Name cannot contain special characters

### ISSUE THREAD

**Issue by juanrhino** [strongloop/loopback#2410] opened 2016-06-07 19:56 UTC
I'm testing the loopback generator using the command slc loopback:model and following the example in http://loopback.io/examples/ and in the step Property Name: when I introduce almost anything the generator throws me the error: Name cannot contain special characters [object Object]firstname. The strange thing is that I'm not introducing anything special, but when I introduce some characters like 'a' or 's' (for example 'b' does not work) the system doesn't throw any exception (it works perfectly).

**Comment by gunjpan** [comment] 2016-06-07 21:19
Can you post the output of `slc -v` here for me?

**Comment by juanrhino** [comment] 2016-06-07 23:28
It shows me this:

strongloop v6.0.1 (node v0.12.7)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.2
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.21.0 (3c246d7)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

Maybe de node version is very old, I'm going to update it and tell you if something changes. It could be nice if the getting start guide tells you at least the minimum requirements (node and npm)

**Comment by gunjpan** [comment] 2016-06-08 14:51
@juanrhino : closing this as a duplicate of: https://github.com/strongloop/generator-loopback/issues/193 
That's the correct repo to track the progress.

**Closed by gunjpan** 2016-06-08 14:51 UTC
Labels: duplicate, wrong-repo
