### ISSUE TITLE
How to use `or` and `and` where filters together

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2463] opened 2016-06-22 22:41 UTC
Your documentation shows this but that doesn't make any sense. An array cannot have keys like that and it does not work as an object

Modules
- loopback: 2.29..0
- loopback-boot: 2.19.0
- looback-datasource-juggler: 2.46.1
- loopback-connector-postgresql: 2.5.0
- strong-remoting: 2.28.1

``` javascript

{
  "or": [
    "and": [ {"field1": "foo"}, {"field2": "bar"}  ],
    "field1": "morefoo"
   ]
}

```

I have tried this but it only runs whichever I put first in the object or / and

``` javascript
{
  "or": [
    {
      "tags": {
        "like": "%basics-1%"
      }
    },
    {
      "tags": {
        "like": "%basics-2%"
      }
    }
  ],
  "and": [
    {
      "level": 2
    },
    {
      "category": ""
    }
  ]
}
```

**Comment by gunjpan** [comment] 2016-06-23 20:52
@devotox : Re:
>An array cannot have keys like that and it does not work as an object

I agree, that's wrong syntax for an array. Correct & working syntax is:
```javascript
      {
        or: [
          { and: [{ field1: 'foo' }, { field2: 'bar' }] },
          { field1: 'morefoo' }
        ]
      }
```
Above has `and` condition is resolved as one of the values for `or` _(and it worked for me)_.

I've corrected it in the docs, please take a look at: [`and/or` filter](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-and/or). 

Closing this now, should you need further assistance with it, please feel free to reopen it; will be happy to assist. Thank you :)

**Comment by devotox** [comment] 2016-06-29 15:52
I did this exact thing and it did not work 

```javascript
         {
	    "and": [
			{ "or": [ { "tags": { "like": "%basics-1%" } }, { "tags": { "like": "%basics-2%" } } ]
	    }, {
	        "level": 2
	    }, {
	        "category": ""
	    }]
	}


```

aand got an internal server error `"Cannot read property 'type' of undefined"`

**Comment by devotox** [comment] 2016-06-29 15:55
I cannot seem to reopen this ticket

**Comment by devotox** [comment] 2016-06-29 15:58
Full Stack Trace
Postgres Back end
```
{
error: {
name: "TypeError",
status: 500,
message: "Cannot read property 'type' of undefined",
stack: "TypeError: Cannot read property 'type' of undefined at PostgreSQL.toColumnValue (/var/app/current/api/node_modules/loopback-connector-postgresql/lib/postgresql.js:452:11) at PostgreSQL.SQLConnector._buildWhere (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:813:26) at PostgreSQL.SQLConnector._buildWhere (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:752:36) at PostgreSQL.SQLConnector._buildWhere (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:752:36) at PostgreSQL.SQLConnector.buildWhere (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:638:26) at PostgreSQL.SQLConnector.buildSelect (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:1001:28) at PostgreSQL.find [as all] (/var/app/current/api/node_modules/loopback-connector/lib/sql.js:1058:19) at /var/app/current/api/node_modules/loopback-datasource-juggler/lib/dao.js:1773:19 at /var/app/current/api/node_modules/loopback-datasource-juggler/lib/observer.js:111:23 at /var/app/current/api/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:189:25 at Model.observe (/var/app/current/api/helpers/loopback/utils.js:16:43) at notifySingleObserver (/var/app/current/api/node_modules/loopback-datasource-juggler/lib/observer.js:103:22) at iterate (/var/app/current/api/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:181:13) at Object.async.eachSeries (/var/app/current/api/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:197:9) at doNotify (/var/app/current/api/node_modules/loopback-datasource-juggler/lib/observer.js:100:11) at doNotify (/var/app/current/api/node_modules/loopback-datasource-juggler/lib/observer.js:98:49)"
}
}
``

**Comment by gunjpan** [comment] 2016-06-29 20:16
@devotox: Looks like an issue with your backend -- `postgres` in this case, could you try executing a [native query](https://docs.strongloop.com/display/public/LB/Executing+native+SQL) and share the outcome if it works or not.

**Comment by devotox** [comment] 2016-06-30 13:44
SELECT * FROM "topic-item" WHERE level=1 AND category='' AND ( tags like '%basics-1%' OR tags like '%basics2%' )


Result
```
id	slug	label	description	media	topic_id	language_id	level	tags	category
0649b5dd-f08d-4ee3-8924-b70bc5df6221	three	Three	3	{}	b38cd8a0-298b-452c-85ae-7a099c6b7bd4	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	
20c0fcd2-28db-41ed-bbe7-3a94fb4bc7cd	ten	Ten	10	{}	b38cd8a0-298b-452c-85ae-7a099c6b7bd4	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	
0d1dafd8-85d6-4809-905a-2b0220e43f28	fifteen	Fifteen	15	{}	b38cd8a0-298b-452c-85ae-7a099c6b7bd4	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	
210c77c2-5bb8-4349-8f9f-6b715b1c3788	mouth	Mouth		{}	7c4b0ab4-7e7f-446b-a856-97203bb1b42a	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	
1272824f-db9b-4f02-96f7-94c965b318aa	stomach	Stomach		{}	7c4b0ab4-7e7f-446b-a856-97203bb1b42a	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	
14d5f980-0a31-4525-9cf8-b5626c73485c	shelf	Shelf		{}	1382cc2e-66a1-4b8f-b20b-19e71a0c1d75	b6820291-2992-4032-ab41-487ef0f786b3	1	basics-1	

```

**Comment by devotox** [comment] 2016-06-30 14:03
```javascript
dataSource.connector.execute("SELECT * FROM \"topic-item\" WHERE level=1 AND category='' AND ( tags like '%basics-1%' OR tags like '%basics2%' )", null, function(error, data) {
	console.log(data);
});
```



```javascript
[ Nodemon ] [ anonymous {
    id: '0649b5dd-f08d-4ee3-8924-b70bc5df6221',
    slug: 'three',
    label: 'Three',
    description: '3',
    media: {},
    topic_id: 'b38cd8a0-298b-452c-85ae-7a099c6b7bd4',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' },
  anonymous {
    id: '20c0fcd2-28db-41ed-bbe7-3a94fb4bc7cd',
    slug: 'ten',
    label: 'Ten',
    description: '10',
    media: {},
    topic_id: 'b38cd8a0-298b-452c-85ae-7a099c6b7bd4',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' },
  anonymous {
    id: '0d1dafd8-85d6-4809-905a-2b0220e43f28',
    slug: 'fifteen',
    label: 'Fifteen',
    description: '15',
    media: {},
    topic_id: 'b38cd8a0-298b-452c-85ae-7a099c6b7bd4',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' },
  anonymous {
    id: '210c77c2-5bb8-4349-8f9f-6b715b1c3788',
    slug: 'mouth',
    label: 'Mouth',
    description: '',
    media: {},
    topic_id: '7c4b0ab4-7e7f-446b-a856-97203bb1b42a',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' },
  anonymous {
    id: '1272824f-db9b-4f02-96f7-94c965b318aa',
    slug: 'stomach',
    label: 'Stomach',
    description: '',
    media: {},
    topic_id: '7c4b0ab4-7e7f-446b-a856-97203bb1b42a',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' },
  anonymous {
    id: '14d5f980-0a31-4525-9cf8-b5626c73485c',
    slug: 'shelf',
    label: 'Shelf',
    description: '',
    media: {},
    topic_id: '1382cc2e-66a1-4b8f-b20b-19e71a0c1d75',
    language_id: 'b6820291-2992-4032-ab41-487ef0f786b3',
    level: 1,
    tags: 'basics-1',
    category: '' } ]
```

**Comment by gunjpan** [comment] 2016-07-05 15:01
@devotox : looks like the cause may be model properties not being mapped to db table columns. Can you share your `<model>.json` file? If it doesn't have the mapping, try to map it as described [here](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Datamappingproperties).

**Comment by devotox** [comment] 2016-07-06 09:51
```json
{
  "name": "topic-item",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
	"validateUpsert": true
  },
  "properties": {
	"id": {
	  "type": "string",
	  "id": true,
	  "required": true,
	  "defaultFn": "uuidv4",
	  "postgresql": {
		"dataType": "uuid"
	  }
	},
	"slug": {
	  "type": "string",
	  "required": true
	},
	"label": {
	  "type": "string",
	  "required": true
	},
	"description": {
	  "type": "string"
	},
	"media": {
	  "type": "object",
	  "required": true
	},
	"level": {
	  "type": "number"
	},
	"tags": {
	  "type": "string"
	},
	"category": {
	  "type": "string"
	},
	"language_id": {
	  "type": "string",
	  "required": true,
	  "defaultFn": "uuidv4",
	  "postgresql": {
		"dataType": "uuid"
	  }
	},
	"topic_id": {
	  "type": "string",
	  "required": true,
	  "defaultFn": "uuidv4",
	  "postgresql": {
		"dataType": "uuid"
	  }
	}
  },
  "validations": [],
  "relations": {
	"language": {
	  "type": "belongsTo",
	  "model": "language",
	  "foreignKey": "language_id"
	},
	"topic": {
	  "type": "belongsTo",
	  "model": "topic",
	  "foreignKey": "topic_id"
	},
	"permissions": {
	  "type": "hasOne",
	  "model": "permissions",
	  "foreignKey": "topic_item_id"
	},
	"topic-item-translation-1": {
	  "type": "hasMany",
	  "model": "topic-item-translation",
	  "foreignKey": "topic_item_id_1"
	},
	"topic-item-translation-2": {
	  "type": "hasMany",
	  "model": "topic-item-translation",
	  "foreignKey": "topic_item_id_2"
	}
  },
  "acls": [],
  "methods": {}
}
```

**Comment by gunjpan** [comment] 2016-07-07 18:50
@devotox: Can't seem to get what's causing the error, from top of my head. I cloned your repo: `kids-vocab` and tried to debug it, couldn't get the server running. Could you please run your server enabling debug logs as:
`$DEBUG=loopback:connector:postgresql node <serverFileToRun>`
and see what's the translated `Query` from the filter.

@raymondfeng : Thoughts on what could be the cause of the error [here](https://github.com/strongloop/loopback/issues/2463#issuecomment-229402440)?

**Comment by devotox** [comment] 2016-07-09 23:46
Somehow it works now. But the SQL generated is wrong there is no OR clause

```
https://www.platform.local.com/api/topic-phrases?filter[where][and][0][level]=1&filter[where][and][1][category]=&filter[where][and][2][or][0][tags][like]=%basics-2%
```

```
Sat, 09 Jul 2016 23:44:32 GMT loopback:connector:postgresql SQL: SELECT "id","slug","label","description","media","level","tags","category","language_id","topic_id" FROM "public"."topic-phrase" WHERE ("level"=$1) AND ("category"=$2) ORDER BY "id"
Parameters: [1,""]

```

**Comment by devotox** [comment] 2016-07-13 08:06
Is there something i am doing wrong?

**Comment by devotox** [comment] 2016-07-16 08:38
Should i change up my filters?

**Comment by loay** [comment] 2017-01-30 19:44
Hi @devotox, is the issue still persisting? Thanks.

**Comment by loay** [comment] 2017-02-03 18:39
As per this previous comment https://github.com/strongloop/loopback/issues/2463#issuecomment-231562024 it seems to be working now. If you need any further help, please feel free to leave a comment and I will re-open the issue.

**Closed by loay** 2017-02-03 18:39 UTC
Labels: juggler-relations, triage
