### ISSUE TITLE
loopback.findModel method returns undefined

### ISSUE THREAD

**Issue by dmitrovskiy** [strongloop/loopback#1616] opened 2015-08-21 13:15 UTC
Hello. I have two models `person` and `post`. When I'm trying to get `post` model in `person` model for their events subscription I'm getting `undefined` value. 

```js
var Post = loopback.findModel('post');
```
Here is my `model-config.json`
```json
...
"person": {
    "dataSource": "db",
    "public": true
  },
"post": {
    "dataSource": "db",
    "public": true
  },
...
```

Can you explain please why does it happen?

**Comment by xangy** [comment] 2015-08-25 09:36
As per the documentation here : https://apidocs.strongloop.com/loopback/#loopback-findmodel-1 .
It is stated that it looks up a model class by name from all models created by loopback.createModel().
So, I think it doesn't work for models created by loopback cli. And hence should rather use "app.models" to get the model as described here : https://apidocs.strongloop.com/loopback/#app-models

**Comment by csvan** [comment] 2015-08-29 16:15
Where are you doing this lookup? All datasources and models need to be properly attached before you  can run it. Hence, you cannot run it directly in the body of your models customization method.

**Comment by jannyHou** [comment] 2015-11-10 16:10
Hi @dmitrovskiy , would you please provide the information of where you write your code ```var Post = loopback.findModel('post');``` like the path of your file or the folder contains it.

**Comment by jannyHou** [comment] 2016-04-05 20:41
I am closing it since info provided is not enough to reproduce the issue.
If anyone run into similar issue or could provide more details, please feel free to reopen it:)
Thanks for understanding.

**Closed by jannyHou** 2016-04-05 20:41 UTC
Labels: triage, waiting
