### ISSUE TITLE
"trim" and "lowercase" convertions and formatting properties not working

### ISSUE THREAD

**Issue by veekungx** [strongloop/loopback#523] opened 2014-09-01 16:32 UTC
{
      "name": "Post",
      "base": "PersistedModel",
      "properties": {
        "title": {
            "type": "string",
            "required": true,
            "trim": true,
            "lowercase": true
        }

    },
    "validations": [],
    "relations": {},
    "acls": [],
    "methods": []
}

the "trim" and "lowercase" on "title" properties not work when I post data to the API I got response with

{
  "title": "SDFSFSDF               ",
  "id": "54049e7fb36b19c817a00012"
}

Did I do something wrong or misunderstand ?

**Comment by crandmck** [comment] 2015-02-26 01:38
@raymondfeng Should this be labeled as a doc issue?  If so, can you clarify what needs to be changed or added to docs?

**Comment by OwenBrotherwood** [comment] 2015-05-19 17:19
@crandmck looks like this issue is lost in refactoring ...
I think what is being referenced to is http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file (not sure).
As to if the code contains what is in the doc is "interesting" @raymondfeng  would have to get back on the issue

**Comment by crandmck** [comment] 2015-05-19 22:49
From https://github.com/strongloop/loopback-datasource-juggler/issues/128, it looks like [property and conversion options](http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Conversionandformattingproperties) are not working / supported.  @raymondfeng can you confirm?  If that's true, I should remove that section from the docs (until it's fixed).

**Comment by BerkeleyTrue** [comment] 2015-08-06 01:29
This should definitely be removed

**Comment by crandmck** [comment] 2015-08-06 16:48
I "commented out" that section from http://docs.strongloop.com/display/LB/Model+definition+JSON+file, so it won't be visible to general viewers.

**Comment by crandmck** [comment] 2015-08-18 17:48
Going to close this since the issue is addressed.  Will need to add it back once those features are actually implemented.

**Closed by crandmck** 2015-08-18 17:48 UTC
Labels: bug, doc, duplicate
