### ISSUE TITLE
afterRemote Remote Hook does not work asynchronously

### ISSUE THREAD

**Issue by IvanAlegre** [strongloop/loopback#2574] opened 2016-08-01 15:05 UTC
I have the following code in the MyModel.js model definition file:

```js
MyModel.afterRemote('create', (ctx, instance, next) => {
  setTimeout(() => {
    console.log('It has executed?');
    next();
  }, 500);
});
```
And this does not work. It seems that Loopback is calling itself the next callback when the afterRemote function exits (after declaring the setTimeout). And it returns a response to the client before the async function has finished (and called next).

Not only that, If I call next asynchronously, I get an exception that i want to return a response for a second time.
```
POST /api/MyModel 200 178.815 ms - 214
It has executed?
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/code/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/code/node_modules/express/lib/response.js:164:12)
    at ServerResponse.json (/code/node_modules/express/lib/response.js:250:15)
    at ServerResponse.send (/code/node_modules/express/lib/response.js:152:21)
    at defaultHandler (/code/node_modules/strong-remoting/lib/rest-adapter.js:391:11)
    at restErrorHandler (/code/node_modules/strong-remoting/lib/rest-adapter.js:361:14)
    at Layer.handle_error (/code/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/code/node_modules/express/lib/router/index.js:310:13)
    at /code/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/code/node_modules/express/lib/router/index.js:330:12)
    at next (/code/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/code/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/code/node_modules/express/lib/router/index.js:310:13)
    at /code/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/code/node_modules/express/lib/router/index.js:330:12)
```

Is there anything that I'm doing wrong? Should I suppose that I cannot change the instance before returning a response?

I'm using the following versions of loopback components:
```
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.45.2",
```

Thanks in advance

**Comment by richardpringle** [comment] 2016-08-25 17:48
So for case as simple as this concerning timing of a remote method, I wouldn't think that LoopBack versions would make much of a difference, but I could not reproduce your issue, everything was working fine for me.

Could you fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce the issue in there (preferably just using the memory connector), then post the link in this issue?

**Comment by IvanAlegre** [comment] 2016-08-26 10:56
Thanks @richardpringle I'll fork and try in the sandbox as soon as possible :)

**Comment by IvanAlegre** [comment] 2016-08-30 08:51
I've forked and I got it work. The problem was that I had an Operational Hook ('after save') that returned a promise. If that hook does not return a promise, it works.

I've forked the sandbox and got it working/failing. It's here. Hope you can check it out and test.

https://github.com/IvanAlegre/loopback-sandbox/blob/master/common/models/event.js#L4

Thanks

**Comment by richardpringle** [comment] 2016-08-31 14:35
@IvanAlegre,

What's happening is you are triggering the middleware chain twice by calling `next()` when you return a promise. `next` is a callback, so you are actually using both promises and callbacks in that case. 

Remove the line and your example should work. 

I am closing the issue but please feel free to re-open (and mention me in a comment) if necessary.

**Closed by richardpringle** 2016-08-31 14:35 UTC
Labels: triage, waiting
