### ISSUE TITLE
problem creating a datasource with generator

### ISSUE THREAD

**Issue by codeyad** [strongloop/loopback#2265] opened 2016-04-27 19:18 UTC
hi, i wanna use the loopback-component-torage and when i try to create the DS i got this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'package' of undefined
    at module.exports.yeoman.generators.Base.extend.installConnector (/usr/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:196:24)
    at /usr/lib/node_modules/strongloop/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jannyHou** [comment] 2016-05-02 19:53
The error happens since when it calls `availableConnectors` to return the list of available connectors, `loopback-component-storage` is not included:
see  https://github.com/strongloop/generator-loopback/blob/master/datasource/index.js#L195

I think we should either add `loopback-component-storage` to available connectors or enable `availableConnectors` read custom connectors in project and return them as well in the list.

**Comment by jannyHou** [comment] 2016-05-02 19:59
@codeyad and anyone run into this issue, I think as a workaround, you can manually add that datasource entry in `datasource.json` instead of using generator to create it.

**Comment by bajtos** [comment] 2016-05-03 07:05
Here is the list of available connectors: https://github.com/strongloop/loopback-workspace/blob/ab5d905eb14a6dfc0948faf62f8ee1b42068c594/available-connectors.json

> I think we should either add loopback-component-storage to available connectors or enable availableConnectors read custom connectors in project and return them as well in the list.

Since we allow the user to enter arbitrary connector name, the generator should gracefully handle the case when a connector not in our list is selected. (Think about community-maintained connectors that we are not aware of yet.)

I am proposing the following changes:
 1. Modify the code looking up data in `availableConnectors` to handle the case when a custom (unknown) connector is selected. This may need changes in multiple places.
 2. When it's time to install the connector, and we don't have metadata from `availableConnectors`, then use the name provided by the user as the package name, e.g. `loopback-component-storage` in the example described above.
 3. The datasource generator also asks the user about configuration which is described in `availableConnectors`. Obviously, we don't have that metadata for a custom connector, thus we should skip these prompts and print a message instructing the user to configure the datasource manually by editing the JSON file.
 4. Once this is all done (and verified?), we can add loopback-component-storage to the list of known connectors in loopback-workspace and include metadata describing configuration options used by this component/connector.

**Comment by codeyad** [comment] 2016-05-03 18:16
@jannyHou the thing is that's one on the ways you can do it according to the doc, i haven't have problems with that before, prolly is the latest version of loopback that has changed it, anyways i think i did manually and also had a problem, gonna check it out again to see if its really possible that way.

**Comment by jannyHou** [comment] 2016-05-03 18:58
@codeyad oh...good to know that. Let me check is there any change broke it.

**Comment by rwngallego** [comment] 2016-05-25 05:19
I'm having this same issue

**Comment by codeyad** [comment] 2016-05-25 13:56
@rwngallego it looks like in the latest version something was changed cause i did several time in the past with previous versions.

**Comment by jannyHou** [comment] 2016-06-08 14:45
@codeyad i am trying to fix this bug and find out the working version.
Do you by any chance remember the last time when it worked? Thanks.

**Comment by codeyad** [comment] 2016-06-11 02:27
@jannyHou last project i have working with Component Storage has loopback version 2.14.0

**Comment by jannyHou** [comment] 2016-06-13 14:56
@codeyad Thanks! We implement some new features related to connector so it's not possible to regress. I have a pr to fix it: https://github.com/strongloop/generator-loopback/pull/199
Will update here after it's published.

**Comment by bajtos** [comment] 2016-06-21 08:10
Published in `generator-loopback@1.22.0`.

**Comment by marysgonzalez** [comment] 2016-08-17 12:47
I am trying to use it with the loopback-component-push and still getting this error, even adding it manually. I already follow this instructions: https://docs.strongloop.com/display/public/LB/Push+notifications

Everything is up to date.

**Comment by jannyHou** [comment] 2016-08-17 15:26
@marysgonzalez did you run into exactly same error as described in this issue?

I tried it on my local and it works fine:
```
jannyHous-MacBook-Pro:aclextend jannyhou$ slc loopback:datasource
? Enter the data-source name: mypush
? Select the connector for mypush: other
? Enter the connector name without the loopback-connector- prefix: loopback-comp
onent-push
? Install loopback-component-push Yes
Please manually add config for your custom connector loopback-component-push in server/datasources.json
npm WARN package.json aclextend@1.0.0 No README data
loopback-component-push@1.5.4 node_modules/loopback-component-push
├── async@1.5.2
├── mpns@2.1.0
├── node-cache@2.1.1
├── debug@2.2.0 (ms@0.7.1)
├── apn@1.6.2 (q@1.4.1)
├── lodash@3.10.1
└── node-gcm@0.9.15 (debug@0.8.1, request@2.74.0)
```

I am on generator-loopback@1.23.2, not the latest version but already includes the fix.
Please make sure you upgraded the generator-lb in your strongloop module or the one in global npm modules folder, depends on which one you are using.

**Comment by marysgonzalez** [comment] 2016-08-22 13:36
Now when I run slc loopback:datasource, I am getting this error:

```
TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/home/henrique/.nvm/versions/node/v5.8.0/lib/node_modules/generator-generator/node_modules/yeoman-generator/lib/base.js:232:45)
```
I updated, uninstalled and installed again yeoman several times without success.

**Comment by jannyHou** [comment] 2016-08-22 14:34
@marysgonzalez you need to reinstall generator-loopback not only yeoman.
Please run `npm install -g generator-loopback` or reinstall the generator-loopback in your strongloop project.

**Comment by marysgonzalez** [comment] 2016-08-22 17:35
Already done, so indeed with npm, yeoman, generator loopback. Still getting
the same issue.

2016-08-22 10:35 GMT-04:00 Janny <notifications@github.com>:

**Comment by jannyHou** [comment] 2016-08-22 19:09
@marysgonzalez hmm, interesting. What's your system and node & npm version? And if possible, could you try reinstall strongloop and see if that solves your problem?

**Comment by bajtos** [comment] 2017-03-23 17:47
@jannyHou is this issue still relevant?

**Comment by jannyHou** [comment] 2017-03-23 21:53
@bajtos I checked with the latest stongloop & node6, it still works fine:
```
jannyHous-MacBook-Pro:customdb jannyhou$ slc loopback:datasource
? Enter the data-source name: mypush
? Select the connector for mypush: other
? Enter the connector name without the loopback-connector- prefix: loopback-component-push
? Install loopback-component-push Yes
Please manually add config for your custom connector loopback-component-push in server/datasources.json
customdb@1.0.0 /Users/jannyhou/lb/triage/customdb
```

I am closing this issue since we couldn't reproduce the bug. 
Please feel free to reopen it if anyone still runs into same issue has has more details. Thanks.

**Closed by jannyHou** 2017-03-23 21:53 UTC
Labels: bug

**Comment by bajtos** [comment] 2017-03-24 08:49
Thank you, @jannyHou!
