### ISSUE TITLE
[mongodb] Error: failed to connect to ... happens several times

### ISSUE THREAD

**Issue by GustavoRPS** [strongloop/loopback#582] opened 2014-09-24 22:04 UTC
I'm getting the error message failed to connect to ... several times when I do queries and is intermitent.

What might be happening? My server not being over charged, neither bandwidth, cpu or connections.

**Comment by Amir-61** [comment] 2015-12-13 17:23
Hi @GustavoRPS,

Sorry to get back to this ticket too late! Could you please share a repo to reproduce the issue using [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)? Also in case you do not run into this issue with updating the the packages, please update us on that so we can close this ticket.

Thanks!

**Comment by Amir-61** [comment] 2015-12-20 21:40
@GustavoRPS I will be closing this ticket due to inactivity; please feel free to re-open it if you encounter  the same issue.

Thanks!

**Closed** 2015-12-20 21:40 UTC
Labels: question, triage, waiting
