### ISSUE TITLE
Update test cases to be port independent

### ISSUE THREAD

**Issue by gunjpan** [strongloop/loopback#2498] opened 2016-07-11 21:20 UTC
Current test cases run server on port 3000, when needed, which crashes other test cases that try to use the same port on same instance causing CI failures. 
Goal is to make test server apps port independent.
Parent issue: https://github.com/strongloop-internal/scrum-loopback/issues/932

**Comment by deepakrkris** [comment] 2016-08-10 12:43
@gunjpan @bajtos , I can understand the root cause of the issue. But what would be the intended direction, do you want to pass the port number as an argument to the test case ?

**Comment by bajtos** [comment] 2016-08-10 13:24
@deepakrkris  you need to listen on port `0` - that way the operating system assigns a unique unused port for your server. the slightly difficult part is how to update all clients to use the dynamically-generated port when making requests

**Comment by superkhau** [comment] 2016-11-29 05:16
Closing in favour of https://github.com/strongloop-internal/scrum-loopback/issues/876

**Closed by superkhau** 2016-11-29 05:16 UTC
Labels: #tob
