### ISSUE TITLE
Include relation filter crashes loopback

### ISSUE THREAD

**Issue by KevinMongiello** [strongloop/loopback#3233] opened 2017-02-24 22:54 UTC
# Description/Steps to reproduce

Minimal repo with which to reproduce bug:
https://github.com/KevinMongiello/loopback_include_bug

Steps to reproduce:
0a) Run mongodb
0b) Open up explorer  `http://localhost:3333/explorer` 
1) Create/Post a new author,
2) Create/Post a new 'post'
3) Open "GET" in author section
4) Paste this in filter `{"include": {"relation": "post", "scope": {"fields": "id"}} }`
5) hit enter / try it out
Loopback will crash with `TypeError: Cannot read property 'toString' of undefined`

# Expected result

Expected result is to return all authors with a property `posts` that only includes each post's id.
Actual result: Loopback crashes.

# Additional information

darwin x64 6.2.0

loopback_include_bug@1.0.0 /Users/kmong/CaliberMind/Work/scrap/bugs/loopback_include_bug
├── loopback@3.4.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-connector-mongodb@3.0.1

**Comment by deepakrkris** [comment] 2017-02-27 18:48
@KevinMongiello nice job with the sample repository! I am able to see the error. let me take a look at what is failing.

**Comment by deepakrkris** [comment] 2017-02-27 22:10
@KevinMongiello This would need a fix, I have temporary solution for the issue, if you query with ``` {"include": {"relation": "post", "scope": {"fields": ["id", "authorId"]}} } ``` the error wouldnt occur

**Comment by deepakrkris** [comment] 2017-02-27 22:21
@bajtos @superkhau the following line creates a filter with only the query fields {'post': {fields: 'id'}}, but does not add relation.keyFrom : `authorId`
https://github.com/strongloop/loopback-datasource-juggler/blob/76c73d55d28dfa150b9e004aeae12aafe0ce6475/lib/include.js#L311

so , the data retrieved does not have the authorId and later at line https://github.com/strongloop/loopback-datasource-juggler/blob/76c73d55d28dfa150b9e004aeae12aafe0ce6475/lib/include.js#L599 , we try to merge the relations with the parent data and it throws an error

**Comment by superkhau** [comment] 2017-02-27 23:17
I'm not familiar enough with this area of code, @raymondfeng can you chime in here?

**Comment by ebarault** [comment] 2017-02-28 00:10
I reported this issue à while ago: 
Please see https://github.com/strongloop/loopback-datasource-juggler/issues/779 

For now you need to manually include the foreign key in the scope of the incriminated relation for it to work, otherwise it crashes the app

**Comment by KevinMongiello** [comment] 2017-02-28 03:47
I've found that `{"include": {"relation": "post", "scope": {"fields": {"id": "true"} } } }` works, and I am successfully using this as a solution right now. @deepakrkris @ebarault

**Comment by bajtos** [comment] 2017-03-01 09:58
Thank you @ebarault for chiming in. I am closing this issue as a duplicate of strongloop/loopback-datasource-juggler#779  then.

**Closed by bajtos** 2017-03-01 09:58 UTC
Labels: bug
