### ISSUE TITLE
loopback.getCurrentContext() get wrong cause by cls need patch

### ISSUE THREAD

**Issue by violet-day** [strongloop/loopback#1974] opened 2016-01-19 06:54 UTC
Since loopback.context created by cls,I create rpeo for describe cls issue:
[loopback-cls-test/cls-q-test](https://github.com/violet-day/loopback-cls-test/tree/cls-q-test)

```bash
npm install
node test/test.js
```
Here is the logic:
* pass `userId` by `req.query` and save it in `currentContext` though  `server/boot/authentication.js`
* add mixin `userId` used to set userId from `currentContext` before save
* wish to see created modelInstance.userId to equal then `req.query.userId`,but boom~~~

I read this article [node-js-preserving-data-across-async-callbacks](https://datahero.com/blog/2014/05/22/node-js-preserving-data-across-async-callbacks/)

```js
  MemoryModel.test = function (data) {
    //return MemoryModel.create(data);
    //add q.delay will cause error
    return q.delay(100)
      .then(function () {
        return MemoryModel.create(data);
      });
  };
```

The `q` module need [cls-q](https://github.com/othiym23/cls-q) patch,but loopback don't support way to slove this problem.

**Comment by fabien** [comment] 2016-01-21 06:38
Thanks for reporting this - it seems to be a duplicate of #878

**Comment by loay** [comment] 2016-01-26 22:26
Hi @violet-day 
what's your node version? 
Apparently it is working for certain versions.
As fabien stated, the issue seems to be a bug and we are working to fix it ASAP
Regards,

**Comment by loay** [comment] 2016-02-11 16:46
Hello @violet-day @fabien 
I will close this issue since it is a duplicate of https://github.com/strongloop/loopback/issues/878
If you guys disagree and think it is a totally separate issue, please let me know and I will re-open this issue. Thanks.

**Closed by loay** 2016-02-11 16:46 UTC
Labels: duplicate, triage
