### ISSUE TITLE
Passing null JSON to optional string parameters converts null to 'null'

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback#1819] opened 2015-11-14 15:25 UTC
Hi,

I have an end point (remote method) with optional string parameters.

I am collecting the parameters from a view using angular and some of them are null.

When I pass the parameters which contain some JSON null parameters it is saved to database (postgresql) as string and the string is 'null' ..

Any clue why this is happening and this wasn't happening before BTW .. 

My current loopback versions from package.json file:

```
    "loopback": "^2.23.0",
    "loopback-boot": "^2.14.0",
    "loopback-component-oauth2": "2.0.0-beta3",
    "loopback-component-storage": "^1.3.1",
    "loopback-connector-postgresql": "^2.4.0",
    "loopback-connector-rest": "^1.10.1",
    "loopback-datasource-juggler": "2.30.1"
```

Thanks.

**Comment by ahmed-abdulmoniem** [comment] 2015-11-15 09:14
Any response guys?

**Comment by superkhau** [comment] 2015-11-16 04:14
Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by ahmed-abdulmoniem** [comment] 2015-11-16 09:02
@superkhau So this is not the new default behavior of strongloop?

**Comment by superkhau** [comment] 2015-11-16 17:02
I'm not sure what you mean yet. I'm trying to determine whether this is a backwards compatibility issue with LoopBack or something to do with your app. Can you provide sample repo?

**Comment by ahmed-abdulmoniem** [comment] 2015-11-17 07:58
@superkhau I will try but it will take some time .. 

As a simple explanation:

1 - I have a remote method which takes optional string parameters
2 - When I pass on those optional string parameters a `null` it is saved in database as a string (word) = `"null"`

My expected result: Is that when I pass `null` nothing should saved in database but actually the word  `null` is converted to a string and saved in database

**Comment by superkhau** [comment] 2015-11-17 17:53
> Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by Amir-61** [comment] 2015-12-16 23:15
@ahmed-abdulmoniem 

`"null"` does not seem right; it can be a bug; but in order to make sure this a real bug please provide a sample repo using our [sandbox](https://github.com/sharkinsspatial/loopback-sandbox).

Thanks!

**Comment by Amir-61** [comment] 2015-12-21 22:07
@ahmed-abdulmoniem Any update on this? If your problem is solved either by upgrading packages or.. Please let us know and we can close this ticket!

**Comment by ahmed-abdulmoniem** [comment] 2015-12-22 17:29
Actually no. I don't have an clue on how to reproduce the bug with your branch because my project contains a lot of infrastructure like using Amazon dynamo, postgres ... etc.

Still the problem exists and my workaround is that I didn't send the optional arguments to the end points!

**Comment by davidcheung** [comment] 2016-11-04 18:49
I would actually assume you would put default as `""` for string type. to reproduce i would assume the behavior will be same on any remoteMethod that is expecting a `String` argument. 

@ahmed-abdulmoniem looks like this issue has been inactive, is this still an issue?

**Comment by davidcheung** [comment] 2016-11-17 22:16
closing issue due to inactivity, if this issue still persist, please reopen

**Closed by davidcheung** 2016-11-17 22:16 UTC
Labels: triage, waiting

**Comment by devpascoe** [comment] 2017-08-25 01:07
Getting this issue. POST containing a property with null eg,
```
{"domainId":1,"message":"TEST 12345","picture":"","liked":false,"likesCount":0,"commentsCount":0,"profileId":30,"placeId":-1,"reported":0,"newComments":0,**"media":null**,"tags":[]}
```
Take note of the **media** property.
Here's the log of SQL:
```
loopback:connector:postgresql SQL: INSERT INTO "public"."post"("createdat","modifiedat","message","statustype","contenttype","picture",**"media"**,"likescount","commentscount","reported","domainid","profileid","placeid") VALUES($1::TIMESTAMP WITH TIME ZONE,$2::TIMESTAMP WITH TIME ZONE,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING "id"
  loopback:connector:postgresql Parameters: ["2017-08-25T00:57:43.931Z","2017-08-25T00:57:43.932Z","TEST 12345","status_update","status","",**"null"**,0,0,0,1,30,-1] +57ms
```
The response parses it back to a JSON null however because values stored in the postgres database are strings of null rather than <NULL> you can't filter queries that expect or exclude NULL.
This is the response
```
{"createdAt":"2017-08-25T00:57:43.931Z","modifiedAt":"2017-08-25T00:57:43.932Z","message":"test 543","statusType":"status_update","contentType":"status","picture":"",**"media":null**,"likesCount":0,"commentsCount":0,"reported":0,"id":509,"domainId":1,"profileId":30,"placeId":-1,"liked":false,"newComments":0,"tags":[]}
```
Using Loopback 3.9.0 juggler 3.6.1 and postgres connector 3.0.3

**Comment by gp27** [comment] 2017-09-09 12:30
I'm having the same problem here.
I got the `creationStatus` property is of type `Object` which is initally set to `null`.

`loopback:connector:mysql Data:  [ RowDataPacket {
    id: '0',
    name: 'Camp Test 1',
    fbSettings: '{}',
    `**creationStatus: null**`,
    created_time: 2017-08-31T11:14:25.000Z,
    status: 'PAUSED',
    lastUpdateTime: 1970-01-01T00:00:01.000Z,
    adAccountId: 'act_*****',
    offerId: null,
    groupId: 1 }, ... ]`

If I try to update my model instance, null gets converted to a string.

`loopback:connector:mysql SQL: INSERT INTO Campaign(id,name,fbSettings,`**creationStatus**`,created_time,status,lastUpdateTime,adAccountId,offerId,groupId) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE name=?,fbSettings=?,`**creationStatus**`=?,created_time=?,status=?,lastUpdateTime=?,adAccountId=?,offerId=?,groupId=?, params: ["0","a","{}",`**"null"**`,"2017-08-31T11:14:25.000Z","PAUSED","2017-09-09T12:05:02.526Z","act_*****",null,7,"a","{}",`**"null"**`,"2017-08-31T11:14:25.000Z","PAUSED","2017-09-09T12:05:02.526Z","act_*****",null,7] +185ms`

I'm using loopback 3.11.1 and loopback-connector-mysql 5.1.0

**Comment by BuzkoYaroslav** [comment] 2020-03-19 13:56
Does this issue has a chance to be resolved?
