### ISSUE TITLE
Possible bug: `Where` filter returns result for undefined value

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#969] opened 2015-01-04 05:36 UTC
```
var Application = app.models.Application;
    Application.find(
      {where: {masterKey: masterKey}},
      function(err, app) {
```

In the code above, when the value for masterKey is `undefined`, I receive an object as the result which should not have matched ... I think that is unintuitive and should be treated as a bug.

The fix should be to return either no results (my preference) or an error. What do you think?

**Comment by pulkitsinghal** [comment] 2015-01-04 05:44
Until a fix is available, I'm using a workaround for my use-case:
https://github.com/ShoppinPal/loopback-example-access-control/commit/b9e408120a6b948a75a5b7651534d698aadfd9f6

But I can imagine this being a problem for plenty of people, thoughts?

**Comment by OwenBrotherwood** [comment] 2015-05-19 17:48
@superkhau looks like an issue for an example
The workaround seems to apply to a file that is not currently in the example.

**Comment by bajtos** [comment] 2015-09-15 15:45
We have already modified delete operations to report the result in the callback - see https://github.com/strongloop/loopback-datasource-juggler/pull/679.

Exposing the result via REST requires some thinking on how to preserve backwards compatibility for existing clients. In juggler#679, we agreed that the best solution is to implement this change behind a feature flag that is disabled by default.

**Comment by bajtos** [comment] 2015-09-15 15:46
Ooops, ignore my previous comment, I posted it in a wrong issue.

**Comment by superkhau** [comment] 2015-11-30 22:55
@chandadharap Moving out of TOB, this issue is still triaging and hasn't been flushed out yet. Adding major label to make sure we keep and eye on it.

**Comment by superkhau** [comment] 2015-11-30 22:56
@pulkitsinghal or @OwenBrotherwood Can one of you guys provide a project for me to clone in order to reproduce the issue?

**Comment by OwenBrotherwood** [comment] 2015-12-01 07:38
@sumitha  if @pulkitsinghal does not have time, I will try.
Give a callout to me by end of year if nothing happened

**Comment by OwenBrotherwood** [comment] 2015-12-01 07:51
@superkhau @pulkitsinghal code is a clone of: 
https://github.com/strongloop/loopback-example-access-control
His fix, to the example code is:
https://github.com/ShoppinPal/loopback-example-access-control/commit/b9e408120a6b948a75a5b7651534d698aadfd9f6 

The real fix? hmm, is it inside loopback code?
So, pulkitsinghal has supplied a fix to the example code that can be reviewed.

**Comment by OwenBrotherwood** [comment] 2015-12-21 18:25
@superkhau 
https://github.com/ShoppinPal/loopback-example-access-control/blob/b9e408120a6b948a75a5b7651534d698aadfd9f6/server/boot/create-role-resolver.js
- does not seem to be in the current files of the example that was forked and used for this issue
https://github.com/strongloop/loopback-example-access-control/tree/master/server/boot

If @pulkitsinghal doesn't protest, this does not look like an issue and can be closed?

I will try and make a test case for the "where" _perhaps_ returning something strange, as per the issue, on my newly compiled node.js v4 that I have running on a mainframe os390x as I need to make something to test the node.js with.
If I find a "where" problem, I will open a new issue.

**Comment by superkhau** [comment] 2015-12-21 18:57
Let me confirm what you are saying:

1. A query using the where clause currently does not return null
- I believe the current implementation returns an empty array, why do you want it to return null (is it really null)?
2. You want it to return null
- I can't see this happening without a breaking change to the current impl without a config. Maybe this should be a feature request to set a config that allows all queries to return a custom type for empty query results.

Thoughts?

**Comment by OwenBrotherwood** [comment] 2015-12-21 19:08
@superkhau @pulkitsinghal is still active as far as I can see on his activity on github: he has to give the feedback

---

https://github.com/pulkitsinghal?tab=activity

**Comment by loay** [comment] 2016-04-07 17:13
@pulkitsinghal @OwenBrotherwood 
I will close the issue for now. If it is still ongoing, please feel free to leave a comment and I will re-open. Thanks.

**Closed by loay** 2016-04-07 17:13 UTC
Labels: triage
