### ISSUE TITLE
EmbedsMany relation throws ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by hotaru355** [strongloop/loopback#1171] opened 2015-03-05 00:24 UTC
I am getting the following error when making a `GET` or `POST` request to a simple REST endpoint:

    "ER_BAD_FIELD_ERROR: Unknown column '_children' in 'field list'"

The parent model is defined with this JSON:

    {
      "name": "Parent",
      "options": {
        "idInjection": false,
        "mysql": {...},
        "relations": {
          "children": {
            "model": "Child",
            "type": "embedsMany",  // <-- Cannot make this work
            "foreignKey": "parentId",
            "options": {
              "validate": true,
              "autoId": false
            }
          }
        }
      },
      "properties": {
        "parentId": {
          "id": 1,
          ...
        },
        "name": {...}
    }

And a child model as this:

    {
      "name": "Child",
      "options": {
        "idInjection": true,
        "mysql": {...},
        "relations": {
          "parent": {
            "model": "Parent",
            "type": "belongsTo",
            "foreignKey": "parentId",
          }
        }
      },
      "properties": {
        "childId": {
          "id": 1,
          ...
        },
        "parentId": {
          ...
        },
        "name": {...}
    }

My ultimate goal is to persist a parent along with its children by making a request to `POST /Parent` with the following request body:

    {
      "name": "parents name",
      "children: [{
          "first childs name"
      }, {
          "second childs name"
      }]
    }

Note that the database (MySql) is set up with auto-incrementing IDs and so I would like to omit them in the request. If this cannot be done by the generated REST API, I would like to build this using the programmatic approach outlined here: http://docs.strongloop.com/display/public/LB/Embedded+models+and+relations
Unfortunately, my attempts to follow the `parent.build()` and `parent.save()` approach were not successful either, with the parentId not getting propagated to the child or the child not getting persisted. I have researched most related issues here on github and on the google groups, but am not able to find a satisfying answer.
Here an example of what I am trying to achieve (although this example does provide explicit child IDs): 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L2751

Related(?):
https://github.com/strongloop/loopback/issues/781
https://github.com/strongloop/loopback/issues/705

**Comment by superkhau** [comment] 2015-03-05 05:32
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by hotaru355** [comment] 2015-03-05 23:29
I have created a repo on github to reproduce the issue. Please add valid connection information in the `server/datasources.json`, create the tables in MySql (CREATE statements are in the readme) and try to GET a parent model.

https://github.com/hotaru355/issue1171

**Comment by superkhau** [comment] 2015-04-07 16:39
Thanks! I will try it out and get back to you.

**Comment by superkhau** [comment] 2015-04-09 05:31
Did you try running DEBUG='loopback:relation'? I get `loopback:relations EmbedsMany property cannot be equal to relation name: forcing property _children for relation children`. Try renaming the `children` relation to something else and let me know if you still run into issues.

**Comment by hotaru355** [comment] 2015-04-13 06:54
Unfortunately, the warning generated from datasource-juggler is not related to this issue, but it seems to be more on the mysql-connector side. I had tried to rename the relation before, and all that changes is the error message (note the absence of the underscore):
`"ER_BAD_FIELD_ERROR: Unknown column 'children' in 'field list'"`
If you turn on mysql debugging
` DEBUG=loopback:connector:mysql,loopback:relations node server/server.js` 
you will see the offending query generated as:

    loopback:connector:mysql SQL: SELECT `parent_id`, `name`, `children` FROM `parent` ORDER BY `parent_id` +2s

I had not enough time so far to dig into the code to see which dependent package is responsible resolving the embedded relation, would that be the datasource-juggler or the connector?

**Comment by superkhau** [comment] 2015-04-21 16:05
Juggler - https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js

Let me know if you figure anything out.

**Comment by superkhau** [comment] 2015-05-12 08:03
@hotaru355 Did you make any progress on this?

**Comment by jfoliveira** [comment] 2015-06-14 11:50
I have the exact same issue. Looking at the generated SQL statement:
```sql
SELECT parent_id, name, children FROM parent
```
It could be translated in pseudo code as:
```sql
SELECT parentProperty1, ..., parentPropertyN, **relationName** FROM parentTable
```
Maybe I'm misunderstanding how embedsOne/embedsMany should work, but if it's assuming a field named **relationName** will be present in the parent table this just can't work.

Imagine these tables in the database:
`parent: id, name`
`child: parent_id, someOtherField`

I would expect a embedsOne relation to query for like:
```sql
select p.parentProperty1, ..., p.parentPropertyN from parentTable p
```
and when calling `children.create()` from `parentModel.js` another SQL statement would then be executed:
```sql
select c.parent_id, ..., c.someOtherField from child c
```
Am I mistaken here?
If this is not the right expectation from embedsOne relation, which relation type would allow me to have that?

**Comment by loay** [comment] 2016-02-24 19:14
If you create a column  called `_children` in  `parent` table, all the inserts will work fine. 
However, it is probably not an optimal solution since the isnerts will be an array of an object such as 
```
[{"childId":0,"parentId":0,"name":""}]
```

I suggest you do the posts via ` POST /Parents/{id}/children ` and once you do the GET, it will list all related children.

**Comment by loay** [comment] 2016-04-07 19:59
Hi @hotaru355 @jfoliveira 
does the previous comment help fixing the issue?
Thanks.

**Comment by loay** [comment] 2016-04-12 18:14
Hi, I am closing this issue. If you are still experiencing an issue, please feel free to leave a comment. Thanks.

**Closed by loay** 2016-04-12 18:14 UTC
Labels: triage, waiting

**Comment by dcolley** [comment] 2017-03-09 16:12
I'm trying to follow the example in the docs: https://loopback.io/doc/en/lb3/Embedded-models-and-relations.html
I can't get this to work - I have the same error, but the suggestions above don't help me to figure it out... 
I don't see any table schema, so I am trying to reverse-engineer this from the docs...

If I don't put the `customerId` or `billingAddress` fields in the tables then we get the ER_BAD_FIELD_ERROR error above. Of course, only one of the tables need to refer to the key of the other. In my case I tried from both tables, but I can't get the relation to populate.

Create some tables:
```sql
CREATE TABLE `Address` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `street1` varchar(100) DEFAULT NULL,
  `customerId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `Customer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `billingAddress` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_address` (`billingAddress`),
  CONSTRAINT `fk_address` FOREIGN KEY (`billingAddress`) REFERENCES `Address` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `Address` (`id`, `street1`, `customerId`)
VALUES
	(1, 'one', 1),
	(2, 'two', 2);

INSERT INTO `Customer` (`id`, `name`,`billingAddress`)
VALUES
	(1, 'Derek',2);


```

Configure the models:
```json
{
  "name": "Address",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "street1": {
      "type": "string"
    },
    "customerId": {
      "type": "string"
    }
  },
  "relations": {
    "customerTest": {
      "type": "belongsTo",
      "model": "Customer",
      "foreignKey": "id"
    }
  }
}

{
  "name": "Customer",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "relations": {
    "address": {
      "type": "embedsOne",
      "model": "Address",
      "property": "customerId",
      "options": {
        "validate": true,
        "forceId": true
      }
    }
  }
}
```

call the api http://0.0.0.0:3000/api/Customers/1

    // 500 Primary key is missing for the Customer model
    "address": {
      "type": "embedsOne",
      "model": "Address",
      "property": "id",
      "foreignKey": "customerId",
      "options": {
        "validate": true,
        "forceId": false
      }
    }

    // {"name":"Derek","id":1,"billingAddress":2}
    "address": {
      "type": "embedsOne",
      "model": "Address",
      "property": "billingAddress",
      "options": {
        "validate": true,
        "forceId": false
      }
    }

    // http://0.0.0.0:3000/api/Customers/1/address simply yields "2" - I would expect the full json of the address here.

Is there a schema for MySQL for the Customer and Address tables?
Where should the 'property' field go, in the address or the customer?
