### ISSUE TITLE
Loopback timeout when make a time consume request

### ISSUE THREAD

**Issue by wenkun-tonghui** [strongloop/loopback#2695] opened 2016-08-31 09:34 UTC
![image](https://cloud.githubusercontent.com/assets/20639548/18123555/f6997fb6-6fa0-11e6-9191-955798a0cff3.png)

It shows me gateway timeout. However, I can't find any configuration about socket timeout in the loopback project. Any suggestions?

Thanks.

**Comment by wenkun-tonghui** [comment] 2016-08-31 09:36
@raymondfeng Can you do me a favor? Thanks.

**Comment by davidcheung** [comment] 2016-08-31 14:31
@wenkun-tonghui you could perhaps use a middleware like [`connect-timeout`](https://www.npmjs.com/package/connect-timeout)

**Comment by wenkun-tonghui** [comment] 2016-09-01 02:16
@davidcheung The connect-timeout doesn't work for my case. The gateway time-out still happen. I have estimated the time, it's about 50 seconds.

**Comment by davidcheung** [comment] 2016-09-01 15:51
@wenkun-tonghui does your request take that long to process? maybe u can configure that in node itself https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback
not sure if this is a loopback issue or not

**Comment by shuckepco** [comment] 2016-09-06 11:27
We face intermittent occurences of 504 errors as well. Unfortunately, we were not able to track it down yet.

We can (somehow) reproduce it as follows:
- Do not call the API of our internal test installation for some hours
- Refresh the Angular client (it uses the generated SDK)
- Wait a long time (~1 min.) for the API calls to finish -> sometimes one of them responds a 504, sometimes not.
- Subsequent API calls / client refreshes work as expected (within milliseconds).

We use nginx as a reverse proxy. Presumably it generates the 504 due to a missing response of the loopback instance. As said before, we still need to confirm this.

**Comment by kartsims** [comment] 2016-10-20 08:04
Looks like a proxy error, you could :  
* log the requests (chrome devtools)
* replay them according to your scenario (wait some time etc.) [using CuRL](https://coderwall.com/p/-fdgoq/chrome-developer-tools-adds-copy-as-curl), except that you would *change the URL to use the direct URL to the loopback instance* if available

If direct access is not available, figure out a way to make it available, by lauching [ngrok](https://ngrok.com/) on the host machine for instance.

**Comment by davidcheung** [comment] 2016-11-03 20:54
@wenkun-tonghui this is likely not an issue the loopback repo can solve, closing this issue now, please reopen if you see fit.

**Closed by davidcheung** 2016-11-03 20:54 UTC
Labels: triage, waiting

**Comment by nellybaz** [comment] 2020-09-01 21:52
Hi there. Having the same issue when hitting my loopback APIs
