### ISSUE TITLE
Supertest is not compatiple with loopback.getCurrentContext

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#995] opened 2015-01-12 03:06 UTC
When i apply new patch of fixing "loopback.getCurrentContext()" and use it in the app, i get error when i run "npm test" in command line. Please help.
```html
Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test.assert (/var/www/nodejs/api/node_modules/supertest/lib/test.js:205:15)
      at Server.assert (/var/www/nodejs/api/node_modules/supertest/lib/test.js:132:12)
      at Server.g (events.js:180:16)
      at Server.emit (events.js:92:17)
      at net.js:1277:10
      at /var/www/nodejs/api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at /var/www/nodejs/api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at process._tickDomainCallback (node.js:486:13)
      at process.<anonymous> (/var/www/nodejs/api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
```

**Comment by raymondfeng** [comment] 2015-01-12 16:54
@bluestaralone Can you elaborate the steps to reproduce the problem?

**Comment by superkhau** [comment] 2015-02-02 18:36
@bluestaralone  Can you provide the code and steps to reproduce at https://github.com/strongloop.com/loopback-sandbox?

**Comment by Overdrivr** [comment] 2015-10-22 18:13
I believe I have the same issue. I use supertest with mocha

Here is my test script
```javascript
var supertest = require('supertest');
var app = require('../server/server.js');
var assert = require('expect.js')

describe('Perform GET on all courts', function() {
  it('error if server is not responding', function(done) {
    supertest(app).get('/api/Courts')
    .expect(200,done)
  });
});
```
I am using MySQL storage, here is my automigration script
``` javascript
module.exports = function(app){
  console.log('Automigration started...');
  app.dataSources.mysql.automigrate('Court', function(err) {
    if (err) throw err;
    app.models.Court.create([
      {court_number: 1, is_outdoor: true, surface: 'quick'},
      {court_number: 2, is_outdoor: false, surface: 'dirt'},
    ], function(err, courts) {
      if (err){
        console.log('...Automigration failed.');
        throw err;
      }
      console.log('Models created: \n', courts);
    });
  });
}
```
At first I thought I did not initialize properly the server but I receive the first console.log when running mocha.
Here is my console output
```bash
Swagger: skipping unknown type "geopoint".
Automigration started...


  Array
    #indexOf()
      V should return -1 when the value is not present

  Perform GET on all courts
Models created:
 [ { court_number: 1, is_outdoor: true, surface: 'quick', id: 2 },
  { court_number: 2, is_outdoor: false, surface: 'dirt', id: 1 } ]
    1) error if server is not responding


  1 passing (1s)
  1 failing

  1) Perform GET on all courts error if server is not responding:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at Test._assertStatus (C:\Users\Bart\Documents\GitHub\TennisServer\node_mo
dules\supertest\lib\test.js:232:12)
      at Test._assertFunction (C:\Users\Bart\Documents\GitHub\TennisServer\node_
modules\supertest\lib\test.js:247:11)
      at Test.assert (C:\Users\Bart\Documents\GitHub\TennisServer\node_modules\s
upertest\lib\test.js:148:18)
      at Server.assert (C:\Users\Bart\Documents\GitHub\TennisServer\node_modules
\supertest\lib\test.js:127:12)
      at net.js:1419:10
      at C:\Users\Bart\Documents\GitHub\TennisServer\node_modules\loopback\node_
modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31
      at process.<anonymous> (C:\Users\Bart\Documents\GitHub\TennisServer\node_m
odules\loopback\node_modules\continuation-local-storage\node_modules\async-liste
ner\index.js:19:15)
```

Any idea what is going on ? I'm pretty sure my test script is missing something but since I'm beginning with loopback and supertest can't figure it out
Thanks for your help

**Comment by Overdrivr** [comment] 2015-10-27 14:03
Please note that this issue is not reproducible computer to computer. I am not getting this issue on my second work computer, with the exact same codebase.
Is it possible it is related to mocha timeout ? Is 1 second the default ?

**Comment by superkhau** [comment] 2015-10-27 21:02
@Overdrivr Default for mocha is 2s.

**Comment by loay** [comment] 2016-02-11 03:22
Hi @bluestaralone @Overdrivr 
Has this issue being resolved?

**Comment by Overdrivr** [comment] 2016-02-11 08:55
@loay looking at my bootscript function signature, it is pretty obvious now that I forgot to make the boot function asynchronous.

Since there are calls to a mysql database which are I'm pretty certain are async, this means my boot script was finished before the automigration, most likely leading to the crash.

So entirely my fault sorry about that. In my case, it has nothing to do with loopback.

**Comment by loay** [comment] 2016-02-11 09:01
I will close the issue for now. If the problem persists, please leave a comment and I will re-open it. Thanks.

**Closed by loay** 2016-02-11 09:01 UTC
Labels: triage
