### ISSUE TITLE
Apparent bug in Strongloop API

### ISSUE THREAD

**Issue by daveland2** [strongloop/loopback#1695] opened 2015-09-23 14:06 UTC
This note contains a description of an apparent bug in the Strongloop API.

The following query filter when entered into the Strongloop API Explorer crashes the API server:

{"where":{"id":3},"fields":["courname","teacherid"],"include":{"relation":"teachers","scope":{"fields":"teachername"}}}

The error message that is reported is the following:

C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\lib\include.js:756
            var objList = objTargetIdMap[targetId.toString()];
                                                 ^
TypeError: Cannot read property 'toString' of undefined
    at linkOneToMany (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\lib\include.js:756:50)
    at C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
    at _each (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:156:9)
    at targetLinkingTask (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\lib\include.js:753:17)
    at C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:723:21
    at C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:391:17
    at C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
    at _each (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
    at async.each (C:\BrickWire\API\tests\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:156:9)

It seems that it should not be possible for an end user to formulate a query that crashes the server (no matter how ill formed the query may be).

However, the following query does NOT crash the server:

{"where":{"id":3},"fields":["courname","teacherid"],"include":{"relation":"teachers","scope":{"fields":["teachername"]}}}

The only difference is that the fields filter for teachername in the teachers model is enclosed within square brackets.  (It would seem that the square brackets should not be necessary since there is only a single value, rather than a list of values.)

Note:  although this query does not crash the server, it also does NOT limit the retrieved fields for the teachers model to be only teachername.  It also displays the id field for the teachers model.  Is this because the id value needs to be present in order to link the teachers model to the courses model?

**Comment by daveland2** [comment] 2015-09-23 14:27
The following zip file contains source code for the Loopback project, and documentation on our database in a Word document:

http://persistentendeavors.com/brickwire/tmp/test2db.zip

**Comment by superkhau** [comment] 2015-09-23 19:43
Can you provide a link to Git repo?

**Comment by daveland2** [comment] 2015-09-23 20:14
Sorry, do not presently have this project in a Git repo.

**Comment by superkhau** [comment] 2015-09-23 22:37
Can you scaffold a new project with only your use case in a new GitHub repo?

1. `slc loopback`
2. `slc loopback:model` to create your sample models
3. `slc loopback:boot-script fixtures` and then edit `server/boot/fixtures.js` to recreate your use case
4. List the steps to reproduce your issue

Please follow the procedure listed at https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by daveland2** [comment] 2015-09-23 23:10
I can get a repo set up, but I have been unexpectedly pulled off into a
"firedrill" project with a very tight deadline.  It may be a while until I
can get to this.

I would speculate that the problem I saw would manifest itself if you
replicated the form of the query filter that appears in my original message.

I appreciate your interest in tracking down the root of the problem that I
encountered, and will try to eventually do all I can to help you resolve
the issue.

**Comment by daveland2** [comment] 2015-09-23 23:30
Here is a question about setting up a Github repository for my project: how
do you deal with the fact that the data for my API is in a MySQL database?
The data models for the project were created using the Strongloop Arc GUI
tool, and the relation definitions were populated using a custom Node.js
application program that I wrote.  All of the resulting project code is in
the zip file I mentioned.  Putting that code into a skeleton project should
not be a huge problem, but how would you want to manage the MySQL database?

**Comment by superkhau** [comment] 2015-09-24 07:40
You can do a MySQL dump of your DB and include it in the sample repo. Or you can create a subset of the data using a boot script with (ie. `app.models.YOUR_MODEL.create([...], cb)`, which would narrow the focus down to the specific problem.

**Comment by loay** [comment] 2016-07-14 20:37
Hi @daveland2 
I used your zip file and connected your app to my mysql db, then setup the db using the sql code in your file `EntityRelationshipDiagrams.docx`
I tried the query that should crash the server and I couldn't reproduce the error. I tried few queries .. I am usually getting some 500 status error but the server hasn't crashed. 
I might have been doing something wrong or different, so If the issue isn't fixed on your side, can you please provide the exact steps that crashed the server? Thanks

**Comment by daveland2** [comment] 2016-07-15 16:05
Thanks for your note on this issue.

I have been pulled off into other more urgent projects since this issue was
shared with you, and at the moment, I am not available to pursue this
situation.

However, it my expectation that things will eventually shift back into this
arena, at which time I will let you know the latest update on this issue.

Dave Eland

**Comment by loay** [comment] 2016-09-20 17:18
Closing this issue. If problem is still persisting, please feel free to leave a comment and I will re-open the issue. Thanks.

**Closed by loay** 2016-09-20 17:18 UTC
Labels: triage
