### ISSUE TITLE
Concurrent requests are stalled in loopback server

### ISSUE THREAD

**Issue by cloudtronics** [strongloop/loopback#2291] opened 2016-05-04 06:05 UTC
Hello,

I was developing an API for my project. I hit one API that yields a large nos of data, twice to test concurrent access. It seems the Port is blocking till the 1st request completes.. Pls see the below  fig:

I was expecting a parallel processing to scale..

Thanks
-riv

![untitled](https://cloud.githubusercontent.com/assets/11921110/15006176/91e07286-11eb-11e6-8b31-0671b89b2460.png)

**Comment by richardpringle** [comment] 2016-05-04 13:58
@jannyHou, can you see if this is related to that other issue you were dealing with?

**Comment by jannyHou** [comment] 2016-05-04 15:24
thank you @richardpringle . And @cloudtronics it might be related to https://github.com/strongloop/loopback/issues/2246
I am looking into it. See if I can reproduce.

**Comment by raymondfeng** [comment] 2016-05-04 15:27
@cloudtronics You probably have APIs that produce a huge JSON payload which involves CPU-intensive `JSON.parse()/stringify()`. The event loop of Node.js is then blocked by the request. Please note the main loop is single-threaded. The scalability of Node is achieved by Async I/O.

To mitigate the problem, you should use pagination for your API so that the processing can be done in chunks and it yield CPU on the event loop. You can also use Node.js cluster so that multiple processes can handle requests, each per CPU core.

**Comment by cloudtronics** [comment] 2016-05-05 02:23
Thanks. I will try on a cloud..

**Comment by bosco-li** [comment] 2016-11-03 20:15
@cloudtronics we will close this issue for now since it's not active for a few months, if @raymondfeng suggestion doesn't work for you please feel free to reopen this.

**Closed by bosco-li** 2016-11-03 20:15 UTC
Labels: triage
