### ISSUE TITLE
User.email is not a protected property

### ISSUE THREAD

**Issue by gvillenave** [strongloop/loopback#3010] opened 2016-12-07 23:25 UTC
### Bug or feature request
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
From the documentation (https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#protected-properties) it appears that User.email should be a protected property, but it's not currently. Is that by design or is it a bug? Is there a way to override that in a model that extends User?

Thanks,
Gabriel

**Comment by superkhau** [comment] 2016-12-08 02:02
Not sure if it was intentional, but it's not protected in the source at https://github.com/strongloop/loopback/blob/master/common/models/user.json#L24. You can override whatever you want when you extend the User model. The intent of the doc I think is to show you how to use protected properties (meaning if we changed the User in the doc to any other model, it'll still be correct). @crandmck ^

@bajtos Do you know if this was by design? I think this is not a bug and that we should probably close this.

**Comment by superkhau** [comment] 2016-12-08 02:02
@Amir-61 Only assign the triage label if you respond to the user.

**Comment by Amir-61** [comment] 2016-12-08 02:11
>@Amir-61 Only assign the triage label if you respond to the user.
@superkhau I assigned to myself and was writing the answer to respond but after 5 minutes that I assign to myself and was preparing the answer you said this
Ok I leave this issue to you...

**Comment by bajtos** [comment] 2016-12-08 09:52
I don't see why `email` should be protected, thus I think the current status is intentional and we should fix the documentation.

While I was investigating this, I discovered that we have two similar flags: `hidden` (which is already used by [User model](https://github.com/strongloop/loopback/blob/63beaa21fe270d6dc2f0fa5d6cf17d13048a3065/common/models/user.json#L24)) and `protected`. 

Quoting from https://github.com/strongloop/loopback-datasource-juggler/pull/400:

> Protected properties allows you to define properties for an object which should not be included when nested.
> ...
>  It's like the "hidden" feature, but it's only hidden when nested

Perhaps while we are changing this part of our docs, it would be best to revisit documentation of both flags (hidden, protected)?

**Comment by superkhau** [comment] 2016-12-08 19:15
>I don't see why email should be protected, thus I think the current status is intentional and we should fix the documentation.

@bajtos I agree, we should clearly indicate the differences of the two. @crandmck Can you help with the above? Escalating this from triage to doc and reassigning to you.

**Comment by ritch** [comment] 2017-01-30 19:30
@gvillenave thanks for the issue. I think this is a matter of making the docs for `potected` more clear. Its "hidden while nested".

If someone has time a doc change would be an awesome PR for this.

**Closed by ritch** 2017-01-30 19:30 UTC
Labels: doc
