### ISSUE TITLE
Updating Model Instance containing Array of Objects w/PUT, inserts [object Object] or crashes server

### ISSUE THREAD

**Issue by krv783** [strongloop/loopback#1101] opened 2015-02-18 00:16 UTC
I'm having an issue when updating a model instance (PUT) which contains an array of objects. The model in question (Product) is persisted in MySQL. The "variations" property is an array of objects (other models), which in turn, are nested further. When I ```POST /Products``` a new Product through StrongLoop API Explorer, all is well, and the "variations" column in MySQL is populated with the correct data.

for example: ```[{"stockQuantity":12,"price":"17.99","variationCombination":[{"attributeId":1,"variationId":2},{"attributeId":2,"variationId":5}]}]```

Also, when I ```PUT /Products``` a new Product, that doesn't already exist, it works as expected as well.

However, when I ```PUT /Products``` an update to an existing Product instance, namely to the "variations" property, including the ```productId``` in the request payload, the request appears to complete successfully in StrongLoop API explorer, but when I check the value of the "variations" column in MySQL, it has inserted ```[object Object]```.

If I instead do a ```PUT /Products/{id}```, to update an existing instance, the server crashes with the following stack trace:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: could not create List from JSON string: "[object Object]"
    at new List (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/list.js:16:17)
    at List (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/list.js:9:12)
    at ModelConstructor.ModelBaseClass._initProperties (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/model.js:254:28)
    at ModelConstructor.ModelBaseClass (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/model.js:44:8)
    at ModelConstructor (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at ModelConstructor (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at new ModelConstructor (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/model-builder.js:176:22)
    at /home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/dao.js:1073:19
    at Array.forEach (native)
    at allCb (/home/sloop/loopbackTest/node_modules/loopback-datasource-juggler/lib/dao.js:1071:12)
```

The full STR can be viewed at:
https://groups.google.com/d/msg/loopbackjs/7KuovB2myFw/RGsbuyQoKowJ

My test Repo for this issue is at:
https://github.com/krv783/loopbackTest

**Comment by krv783** [comment] 2015-02-18 13:47
I have narrowed down the issue. When updating a Product instance via ```PUT /Products```, and including the ```productId``` in the request payload, it inserts ```[object Object]```, into the ```variations``` field in MySQL. I believe this shouldn't happen.

The server will crash with the above stack trace if using ```PUT /Products/{id}```, ONLY when updating a ```variations``` field that ALREADY contains a value of ```[object Object]``` in MySQL.

So to test this, you would first use ```POST /Products``` to insert a new instance, then use ```PUT /Products``` and include the ```productId``` to update this same instance (which will strangely insert ```[object Object]```), Then finally use ```PUT /Products/{id}``` to update yet again, and finally the server will crash.

If an instance is only ever updated using ```PUT /Products/{id}```, then you never have any problems.

My question then would be, is using ```PUT /Products``` and including the ```productId``` something that should be avoided? Or should this work anyways? I've never had any issues using this method, but that was until I started using model properties that are Arrays of Objects..

**Comment by raymondfeng** [comment] 2015-02-18 16:48
Thanks. We'll investigate.

**Comment by krv783** [comment] 2015-02-18 18:32
I found something that seems to fix the problem...in my case at least..

at line: 361 in ```/loopback-datasource-juggler/lib/dao.js```

```self.getDataSource().connector.updateOrCreate(Model.modelName, update, done);```

should be changed to:

```self.getDataSource().connector.updateOrCreate(Model.modelName, self._forDB(update), done);```

this corrected the issue with ```PUT /Product```, when I was updating an instance model which contained a property which is an array of objects. The Nested property wasn't getting enclosed in single quotes and escaped properly it seems. And because of that it was getting updated in the MySQL database as ```[object Object]```.

**Comment by raymondfeng** [comment] 2015-02-18 19:17
Actually, that seems to be a good fix. Do you want to submit a patch with tests?

**Comment by krv783** [comment] 2015-02-18 19:28
I'm really new to Github. I tried forking the loopback-datasource-juggler
Repo and pushing my changes but I'm stuck at ERROR: Permission to
strongloop/loopback-datasource-juggler.git denied to krv783. Forgive me for
my ignorance :/ Otherwise I probably would..

**Comment by raymondfeng** [comment] 2015-02-18 19:36
Here are the steps:

1. Fork the strongloop/loopback-datasource-juggler repo into your own account
2. `git clone your-repo-url`
3. Make changes
4. commit and push to your repo
5. Go to your repo and create a pull request

**Comment by Rikhart** [comment] 2015-04-17 04:42
I'm having the same issue with postgres connector.

**Comment by adrienthiery** [comment] 2015-04-30 11:44
Same here, updating a model with an array saves an Object in Postgres, so it crashes next time it tries to find it. Is it supposed to be merged soon ?

**Comment by bajtos** [comment] 2016-06-02 13:19
Closing as a duplicate of #2123.

**Closed** 2016-06-02 13:19 UTC
Labels: bug
