### ISSUE TITLE
Cannot access related models in afterSave operation hook

### ISSUE THREAD

**Issue by kamal0808** [strongloop/loopback#2793] opened 2016-09-27 05:59 UTC
I tried accessing related models in afterSave hook through the ctx object, but there seems to be no easy way of doing this. I have a model with HasMany relationship to another model, and access it through the following code.

`MyModel.find({include: 'relatedModel'}, func(){...});`

Could someone guide me as to how can I access the model instance with its relations in afterSave hook?

I need something like this:

```
MyModel.observe('after save', function(ctx, next){
  if(ctx.instance && !ctx.isNewInstance){    //in case if it is ItemModel.update()
    console.log('Here is the model instance', ctx.instance);
    console.log('Here is the related model instance', ctx.instance.relatedModel()); //this won't work, what would?
  }
}

```

**Comment by Amir-61** [comment] 2016-09-27 16:10
Hey @kamal0808,

AFAICT there is `after save` hook for any `find` methods. All the related instances are handled [here](https://github.com/strongloop/loopback-datasource-juggler/blob/24f000d9781cc93db5ccdd782bdc9b8507688f9e/lib/dao.js#L1863-L1899) in dao.js. Am I missing something here? To make the triage process easier, I would suggest that you provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue.

Thanks!

**Comment by Amir-61** [comment] 2016-11-03 20:07
Closing this issue, since it seems the previous comment answered the question. Please fee free to open the issue if you see any other problems.

Thanks!

**Closed by Amir-61** 2016-11-03 20:07 UTC
Labels: juggler-relations, triage
