### ISSUE TITLE
npm supertest intercepts middleware and does not run boot scripts

### ISSUE THREAD

**Issue by varunj90** [strongloop/loopback#1822] opened 2015-11-18 18:50 UTC
We are registering our middleware handler in server/middleware.json like the following:

![image](https://cloud.githubusercontent.com/assets/3495961/11250388/4ed468dc-8dfa-11e5-9d5a-ee502a84ad75.png)

When performing integration tests using supertest :

![image](https://cloud.githubusercontent.com/assets/3495961/11250550/e573288c-8dfa-11e5-9812-a68a3a6d8474.png)

the code does not go through our middleware which contains the error handler because of which we get errors like

here11111111111111111111111111111111111111111111:
{ [Error: Parse Error] bytesParsed: 9, code: 'HPE_INVALID_STATUS', response: undefined }

OR
here11111111111111111111111111111111111111111111:
[TypeError: Cannot read property 'header' of undefined]

We suspect that we have a missing configuration with supertest ; 
or 
We might need some code that starts up in server.js that links supertest properly using loopback.

Can you advice us on getting this to work as it is a major roadblock.

Thank you !

**Comment by raymondfeng** [comment] 2015-11-18 22:49
To customize error handling for LoopBack REST APIs, you need to register an error handler in server/config.local.js:
```js
module.exports = {
  remoting: {
    errorHandler: {
      handler: function(err, req, res, next) {
        console.log('err', err);
        res.status(500).send(err);
      }
   }
 }
}
```
Please note the REST handler doesn't pass control back to the middleware chain.

**Comment by varunj90** [comment] 2015-11-19 20:53
hi raymondfeng, we already have something similar defined in our server.js

![image](https://cloud.githubusercontent.com/assets/3495961/11284011/81b25832-8ed5-11e5-85ab-3ee6d15d5757.png)

and supertest is defined as the follwoing for the test case mentioned above

![image](https://cloud.githubusercontent.com/assets/3495961/11284029/9c528d4c-8ed5-11e5-8627-0271d7a02a9e.png)

________________

do you see anything missing?

**Comment by varunj90** [comment] 2015-11-19 20:53
@raymondfeng  - tag added.

**Comment by raymondfeng** [comment] 2015-11-19 22:56
Can you share the test file? I'm using the following one:
```
var request = require('supertest');
request = request('http://localhost:3000');

request
  .post('/api/notes')
  .set('Content-Type', 'application/json')
  .send('{"a: 1}')
  .expect(200)
  .end(function(err,res){
    console.log(err, res.body);
  });
```

**Comment by varunj90** [comment] 2015-11-20 15:05
@raymondfeng 

var supertest = require('supertest');
var app = require('../server/server.js');

function server(verb, url) {
  return supertest(app)[verb](url)
    .set('Content-Type', 'application/json')
    .set('Accept', 'application/json')
    .expect('Vary', 'Accept-Encoding');
}

  it('POST /fundstransfers with invalid payload - Fail', function (done) {
    console.log("here00000000000000000000");
    server('post', '/v1/fundstransfers')
      .set('Authorization', validToken)
      .set('Content-Type', 'application/json')
      .send(fundsTransfersInvalidData)
      .expect(500)
      .end(function (err, res) {
        if (err) {
          console.log("here11111111111111111111111", err);
          return done(err);
        }
        console.log("here2222222222222222222222222", res.header);
        res.status.should.equal(500);
        console.log(res.body);
        done();
      });
  });

**Comment by varunj90** [comment] 2015-11-20 21:10
@raymondfeng 

Another question - we are starting our server using the supertest app; i came across this thread and was wondering if its somehow related?

https://github.com/strongloop/loopback/issues/1538

If yes, can you shed some insight in what could be a fix and in which file.

Thanks again !

**Comment by varunj90** [comment] 2015-11-23 20:11
@raymondfeng 

Latest Finding:  if we add the following code snippet for the unit tests, they actually pass
 
![image](https://cloud.githubusercontent.com/assets/3495961/11348355/1ef2799e-91f4-11e5-9ea7-d8f0d8d572e5.png)

Reference in server.js : start function

![image](https://cloud.githubusercontent.com/assets/3495961/11348379/45f561be-91f4-11e5-8a50-6379cd04022e.png)

Reference in server.js : stopServer function

![image](https://cloud.githubusercontent.com/assets/3495961/11348385/4d186f90-91f4-11e5-89c9-0ae19dc95d64.png)


This is somewhat depicted from an issue posted on loopback github: https://github.com/strongloop/loopback/issues/1538

Although, we shouldn't be required to start and stop a server since that's the job of supertest; but this to some extent confirms the issue of 'res' being undefined because the supertest server shuts down early?  Is this a bug in supertest? Thoughts?

**Comment by richardpringle** [comment] 2015-12-08 18:21
@raymondfeng, did you see @varunj90's reply?

I would like to close this issue if the problem is really with supertest.

**Comment by vespertilian** [comment] 2015-12-16 15:43
So I ended up here because my boot scripts were also interfering with Supertest. 

My boot script was hanging because no company model had been setup in the database. The weird thing was, catch was not throwing an error and Supertest was still able to interact with the server and get responses, so some tests still worked. For anyone else happening upon this thread you should double check your boot scripts. I just added a line to skip the script when NODE_ENV=test and it is now working properly.

### Original

```

 console.log('02_seed_db_company.js');

    var Company = app.models.Company,
      FOO = {
        name: 'FOO'
      };

    Company.findOrCreate({where: {name: FOO.name}}, FOO)
      .then(function(company){
        console.log('found or created FOO');
        done();
      })
      .catch(done);

```

### Updated

```

module.exports = function(app, done) {

  var nodeEnv = process.env.NODE_ENV,
      isTestEnv = ((nodeEnv === 'test') || (nodeEnv === 'unittest'));

  if(isTestEnv)  {
    console.log('TestEnv - 02_seed_db_company.js - skipped');
    done()
  }
  else{
    console.log('02_seed_db_company.js');

    var Company = app.models.Company,
      FOO = {
        name: 'foo'
      };

    Company.findOrCreate({where: {name: FOO.name}}, FOO)
      .then(function(company){
        console.log('found or created FOO');
        done();
      })
      .catch(done);

  }
};

```

**Comment by richardpringle** [comment] 2016-01-28 02:33
@varunj90, I am closing this issue as it seems to be somewhat resolved. If you run into any new issues in the future, mention me in a comment and I'll try to help you at ASAP.

Cheers!

**Closed by richardpringle** 2016-01-28 02:33 UTC
Labels: triage, waiting
