### ISSUE TITLE
Freezing on the simplest commands

### ISSUE THREAD

**Issue by Y-Less** [strongloop/loopback#4050] opened 2018-10-29 17:03 UTC
# Description/Steps to reproduce

1) Type `lb`.
2) Use the default suggested name.
3) Wait.

I've never got past stage 3.  It seems to hang, with basically no CPU usage, or is just running insanely slowly.  I'd believe either, since it takes four seconds just to run `lb --version`, I'd hate to think how much slower something more complex than printing a simple string was.

# Link to reproduction sandbox

# Expected result

Do something.

# Additional information

`node -e 'console.log(process.platform, process.arch, process.versions.node)'

`win32_x64 10.9.0`

`npm ls --prod --depth 0 | grep loopback`

```
grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:29
+   npm ls --prod --depth 0 | grep loopback
+                             ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by littlepd** [comment] 2018-11-02 18:46
I have a similar issue. I just download Loopback and I'm working my way down the "Getting Started" page. I typed "lb" and pressed enter. Then entered "hello-world" for the first question. Pressed enter. Now it's just sitting there.

**Comment by raymondfeng** [comment] 2018-11-02 20:39
@littlepd Are you on Windows too?

**Comment by littlepd** [comment] 2018-11-02 21:03
Yep

**Comment by raymondfeng** [comment] 2018-11-02 21:41
Duplicate of https://github.com/strongloop/loopback-cli/issues/36

**Closed by raymondfeng** 2018-11-02 21:41 UTC
