### ISSUE TITLE
unable to update attributes when setting default scope

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1701] opened 2015-09-26 05:20 UTC
``` javascript
{
   "options": {
    "validateUpsert": true
  },
  "scope": {
    "where": {
      "deleted": false
    }
  },
  "properties": {
    "deleted": {
      "type": "boolean",
      "default": false
    }
  }
}

```

whenever you call updateAttributes/updateAll or via exposed restful api, you cannot update the `deleted` property. It always stays the same.

Here is the debug log:

```
 loopback:connector:postgresql SQL: UPDATE "public"."item" SET "deleted"=$1,"updated_at"=$2::TIMESTAMP WITH TIME ZONE WHERE ("id"=$3) AND ("deleted"=$4)
Parameters: ["false","2015-09-26T05:19:53.048Z",1,"false"] +1ms
```

**Comment by fabien** [comment] 2015-09-26 16:11
This is the intended behavior - it is used to enforced certain scoping attributes, and the user should not be able to bypass them. If you need more fine-grained control, look into the `access` operation hook, which allows you to filter out all items which have been deleted, without interfering with updates.

**Comment by Neil-UWA** [comment] 2015-09-27 00:16
@fabien I thought the default scope should only work on query statements by adding or merge the scope , should not modify the update statement. In addition, the real problem is that it's impossible to update the scoping attributes. I'v tested several times that when i try to update the scoping attribute 'deleted' to true, loopback will always enforce the update value to false.

**Comment by Neil-UWA** [comment] 2015-09-28 02:03
@fabien  thx for your solution, by using `access`operation hook saved me lots of time.

**Comment by bajtos** [comment] 2015-10-22 10:48
I am closing this issue as invalid per @fabien's comment mentioning the current behaviour is intended.

**Closed by bajtos** 2015-10-22 10:48 UTC
