### ISSUE TITLE
Change/Event Stream Errors

### ISSUE THREAD

**Issue by EmileSpecs** [strongloop/loopback#1825] opened 2015-11-19 07:37 UTC
![issue](https://cloud.githubusercontent.com/assets/7687212/11264961/dfa39abc-8ea0-11e5-800e-9157b3b0c30e.jpg)
Even when running the https://github.com/strongloop/angular-live-set-example example, I get console errors in Chrome console:
`net::ERR_INCOMPLETE_CHUNKED_ENCODING`

I don't have compression in my middleware stack, with compression it doesn't work at all. So the events work just fine, but the errors are annoying, because to filter through it all looking for other issues is problematic. Also it just doesn't look great when you have 100's of errors in the console after a couple of hours...

The error writes to console every 2 minutes it seems. So it would seem like at some point the EventSource connection to the loopback server times out and then automatically reconnects (since it still works even with the errors). I can also see that when the error occurs a new GET request is made to the change stream endpoint.

So in loopback, is there a way to send some "keep alive" packets to the client every minute or so?

If no one else is experiencing this issue, what causes it on my PC?

Any help would be appreciated!

**Comment by loay** [comment] 2015-12-01 15:05
Hi @EmileSpecs  
Thanks for reporting the issue. I am having a look to reproduce and getting back to you on that.

**Comment by EmileSpecs** [comment] 2015-12-01 19:03
Hi @loay, thanks!

I've now also found another problem caused by change streams. In my app I register 6 change stream listeners, when they're enabled all other requests remain pending until the EventSources throw the errors above and then they return responses.

So my app basically doesn't function when I have these 6 change streams registered. Do these change streams somehow block other responses? Are they using up all available event listeners for http traffic?

Is there somehow I can investigate this? To replicate you could perhaps also register 6+ change streams:
```
src = new EventSource(urlBase + url +'/change-stream?access_token='+ LoopBackAuth.accessTokenId);
```
And then see if other requests to the server is blocked like mine.

**Comment by loay** [comment] 2015-12-01 21:28
@EmileSpecs 
is your app somewhere on github so I can try reproducing using your app?
Thanks

**Comment by EmileSpecs** [comment] 2015-12-02 09:45
@loay, unfortunately I don't. Like I mentioned in the first comment, I get those errors with the example app as well. So that would be a good start.

I will try and also add a couple more models to the example app and then see if I have the same "blocking" issues as I have in my own app.

Figuring out why there are these `net::ERR_INCOMPLETE_CHUNKED_ENCODING` errors occur would be a good start and that I get with the example app.

**Comment by JonnyBGod** [comment] 2015-12-12 06:58
Also getting similar issues.

- `net::ERR_INCOMPLETE_CHUNKED_ENCODING`
- Connections timeout after 60 seconds of inactivity.

**Comment by loay** [comment] 2015-12-13 00:08
@EmileSpecs  @JonnyBGod 
I cannot reproduce the issue on my end. I did some search and I found that some people got that issue fixed once they disabled the Real time protection on the Anti-Virus. Others had that issue related to the Cache Control.

**Comment by JonnyBGod** [comment] 2015-12-13 00:41
I am on mac, no antivirus cache disabled on chrome when devtools are open.
My main problem is not related to the error though. I am concerned about the timeout after one minute of inactivity.

**Comment by loay** [comment] 2015-12-13 00:50
@JonnyBGod, Is your code on a repo that you can refer me to so I can try to reproduce?
Thanks

**Comment by JonnyBGod** [comment] 2016-01-12 02:10
@loay I am not doing anything special. The angular-live demo has the same behavior.

Tried a lot of different setups now.
- Nginx with a bunch of different configurations in front of loopback.
- Direct connection to the server.
- Cloudflare in front.
- SSL, no SSL.

The connections always times out after 60 seconds of inactivity.

**Comment by JonnyBGod** [comment] 2016-01-12 15:35
Another test suing curl and connecting direct to loopback server.

```
curl -H Accept:text/event-stream "http://192.168.1.75:52447/api/rides/change-stream?_format=event-source&access_token=vcuEpumlI0qC6mwWk2ZMvkeGKBLLYPpz"
:ok

curl: (18) transfer closed with outstanding read data remaining
```

**Comment by JonnyBGod** [comment] 2016-01-12 18:33
Ok. Just found out the problem.

What is causing the drop in connection is the default nodejs [http socket timeout](https://nodejs.org/dist/latest-v5.x/docs/api/http.html#http_server_timeout) of two minutes.

I did a quick work around with a middleware that changes the timeout and sets header for every route containing 'change-stream'.
```
app.middleware('routes:before', function (req, res, next) {
  if (req.path.indexOf('change-stream')) {
    console.log('change-stream');
    res.setTimeout(24*3600*1000);
    res.set('X-Accel-Buffering', 'no');

    return next();
  } else {
    return next();
  }
});
```

This is not the best way to fix the issue and should be considered a quick work around.
The PersistantModel createChangeStream function should deal with this.

**Comment by loay** [comment] 2016-01-12 20:23
@JonnyBGod 
Thanks I will have a look. I will get back to you as soon as I can.

**Comment by loay** [comment] 2016-04-25 21:51
Hi,

the issue has been reported to include a feature for a similar case: https://github.com/strongloop/angular-live-set/issues/11
Closing this issue for now.

**Closed by loay** 2016-04-25 21:51 UTC
Labels: triage, waiting

**Comment by lsroman** [comment] 2016-05-24 19:59
@EmileSpecs Hi. You solved problem 6 connections?

**Comment by imasif** [comment] 2017-09-05 13:59
@JonnyBGod this may sound stupid, where should I place your code?

**Comment by richardaum** [comment] 2019-07-12 01:18
I got this problem even not using Angular Live Set. Did you guys managed how to solve it?
