### ISSUE TITLE
How do I configure the timezone info?

### ISSUE THREAD

**Issue by nivincp** [strongloop/loopback#2143] opened 2016-03-14 12:07 UTC
I have been looking for this like since the last 2 - 3 hrs. Still I can't figure out how. I need to set it up as UTC+07 I see an option to specify it in the datasources.json

`"mydb": {
	"host": "127.0.0.1",
	"port": 3306,
	"database": "mydb",
	"username": "root",
	"password": "root",
	"name": "mydb",
	"connector": "mysql",
	"timezone": "UTC+07:00"
}`

It seems to have no effect.

I have two fields (date_add and date_upd) in a table. Also I am using this package "loopback-ds-timestamp-mixin": "^3.2.2", to map these fields as a mixin

Any help would be much appreciated.

**Comment by jannyHou** [comment] 2016-03-21 20:24
@nivincp I am trying to reproduce issue, for a better debug, could you fork this sandbox: https://github.com/strongloop/loopback-sandbox
and upload your code? thanks!

**Comment by nivincp** [comment] 2016-03-24 04:16
@jannyHou please check the commit

https://github.com/nivincp/loopback-sandbox/commit/5f499712a744e62f1b22531c0cbae66022357917

**Comment by jannyHou** [comment] 2016-03-24 15:08
@nivincp thank you I will update my test result later, and meanwhile, I find something might be helpful for you, could you check comment from this `node-mysql` issue: 
https://github.com/felixge/node-mysql/issues/620#issuecomment-26676851

**Comment by jannyHou** [comment] 2016-03-29 20:48
@nivincp I simplified your scenario:
https://github.com/jannyHou/loopback-sandbox/tree/simplify-app
from my test,
1. the timezone config in `server/datasource.json` wouldn't work, which is not surprised, explained in https://github.com/felixge/node-mysql/issues/620#issuecomment-26676851. 
And workaround from `node-mysql` side is:
>explicity call connection.query( "set time_zone = '+00:00'" )  
2. when I use `loopback-ds-timestamp-mixin` to define `createdAt` and `updatedAt`, the date is always 4 hours ahead of my local time (UTC-05:00), same result in memory and mysql.
3. you can try to define custom  timestamp mixin according to our doc:
https://docs.strongloop.com/display/public/LB/Defining+mixins#Definingmixins-Createamixinscript

**Comment by nivincp** [comment] 2016-03-30 03:50
@jannyHou 

Couldn't get it working the above way :-)

I see an option to set the "dateStrings": true in datasources.json here https://github.com/felixge/node-mysql#connection-options

That didn't worked either. As a workaround I am using date_add and date_upd in my mysql tables as type string in model.json and then formatting it using the moment.js with the timezone I have specified in the config.json 

`var date_add = moment().tz(app.get('timezone')).format("YYYY-MM-DD HH:mm:ss")`

Not quite sure if I'd end up in further issues especially when it comes to querying date_add or date_upd fields but for now this is what worked for me.

**Comment by jannyHou** [comment] 2016-03-30 17:45
@nivincp I am glad to know that you find a workaround.
We have an example repo about how to use the timestamp mixin: 
https://github.com/strongloop/loopback-example-mixins
but I got same result:
> when I use loopback-ds-timestamp-mixin to define createdAt and updatedAt, the date is always 4 hours ahead of my local time (UTC-05:00)

I will label it a bug then.

**Comment by jannyHou** [comment] 2016-03-30 18:06
@nivincp filed bug: https://github.com/clarkbw/loopback-ds-timestamp-mixin/issues/21
Can I close this issue now since the issue finds a solution? We can discuss further new problems if you still have concern 
> when it comes to querying date_add or date_upd fields

**Comment by nivincp** [comment] 2016-03-31 03:35
@jannyHou Yes and thanks for your help.

**Comment by jannyHou** [comment] 2016-04-05 20:33
I think the timezone difference happens due to loopback. It's 4 hours ahead even I don't use mixin. I will open another issue to explain it.

**Closed by jannyHou** 2016-04-05 20:33 UTC
Labels: triage
