### ISSUE TITLE
Inherit build-in User Model, ACLs wrong

### ISSUE THREAD

**Issue by an-ttt** [strongloop/loopback#1927] opened 2015-12-29 16:33 UTC
Hello
I made a Model Inherit build-in User Model：
{
  "name": "AppUser",
  "base": "User",
  "idInjection": true,
  "strict": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
]
}

But it can not deny the create or deleteById.
1.If I add these codes:
  {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "deleteById"
    },
It still allow deleteById by $owner.
2.If I add these codes:
  {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "deleteById"
    },
deleteById will be denied.

Please tell me that I did the wrong thing or it's a bug.

**Comment by 0candy** [comment] 2015-12-29 22:04
@an-ttt I am not able to reproduce this issue. Can you please provide a sample repo?

**Comment by an-ttt** [comment] 2015-12-30 07:14
@0candy 
Thanks for replying.
After reading ACL rule precedence(https://docs.strongloop.com/display/public/LB/Controlling+data+access),
I understand it's behavior.
But I think it's werid when inherit User model,
I must write a more specific rule to take precedence over the old one in User model.

**Comment by 0candy** [comment] 2016-01-04 17:09
Is there anything we can help you with on this issue? If not, let me know and I can close this. Thanks!

**Comment by an-ttt** [comment] 2016-01-05 08:36
@0candy
Sure, pls close it

**Closed** 2016-01-05 14:42 UTC
Labels: triage, waiting
