### ISSUE TITLE
Cannot change templating engine in User.verify() e-mails

### ISSUE THREAD

**Issue by mirow** [strongloop/loopback#1138] opened 2015-02-26 08:47 UTC
The ejs templating engine is hardcoded into the loopback core (loopback.template function), and User.verify() uses it when sending confirmation e-mail to users, so I cannot use any other templating engine.

**Comment by superkhau** [comment] 2015-02-26 21:53
Are you trying to use a different templating engine when using `User.verify`? Or for the entire app? Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report and I will verify your issue.

**Comment by mirow** [comment] 2015-02-27 19:54
I'm quite new to Loopback, so maybe I'm doing something wrong. I've tried to use different templating engines for the entire app (jade and handlebar so far), but they don't affect the e-mail sent from User.verify.

Correct me if I'm wrong, but it does look to me like this piece of code is hard-coded to always use ejs as a templating engine?:
https://github.com/strongloop/loopback/blob/master/lib/loopback.js#L176-L190

**Comment by stringbeans** [comment] 2015-05-08 17:47
+1

Not sure why loopback is hardcoded to use ejs with loopback.template()

**Comment by arne-s** [comment] 2015-06-28 19:20
Same problem here, I try to use Mandrill, which stores its templates on the server, however I can't get around these default settings.

**Comment by raabbajam** [comment] 2015-07-07 08:01
:+1: trying to use jade. Maybe check extension of template, or just default to whatever set in app `app.set('view engine', 'jade');`

**Comment by shbhsngh** [comment] 2015-11-24 08:42
facing the same problem.  don't know, why loopback is not giving option to change verification email body?

**Comment by Fabrik19SH** [comment] 2016-03-20 00:52
Hi, this point is still valid. Is there a workaround for using handlebars?

Many thanks

**Comment by loay** [comment] 2016-04-07 18:45
Hi, 
one of the possible reasons  that the template is hard-coded is for ease of use for many users. You can change the text of the email body in `models/user.js` .. If there is a better suggestion for the `loopback,template` function, please submit a PR. Thanks. 

For the possibility of using handlebars, jade, mandrill, I will get back to you on that.

**Comment by elbarto132** [comment] 2016-04-21 10:29
+1

**Comment by pmoelgaard** [comment] 2016-04-22 03:18
+1

**Comment by rpalacio86** [comment] 2016-06-13 03:05
+1

**Comment by adanmuguirofoo** [comment] 2016-06-28 00:07
+1

**Comment by jduhls** [comment] 2016-08-29 17:09
https://github.com/strongloop/loopback/compare/2.x...jduhls:patch-1

**Comment by kwuite** [comment] 2016-09-30 09:24
@loay 

> For the possibility of using handlebars, jade, mandrill, I will get back to you on that.

I am in the process of using Mandril as an e-mail service. But in now way it seems possible to use Mandril since I cannot pass the mandrill template via the options to user.verify().

Do we have a solution for this, or will I be implementing a custom verification script?

**Comment by zhenyanghua** [comment] 2016-09-30 12:14
@kwuite the user.verify() method calling the `Email.send()` to send the mail, the send method is implemented in the `User` model to use `nodemailer`. If you'd like to use another e-mail sender library, you can write just simply write your own verify method by using your own mailer. The verify method is just to send out an email with the `confirm` endpoint token, and then you may install write a `context.res.redirect(301, "path")` to your destination after sending out the verification email.

**Comment by kwuite** [comment] 2016-09-30 12:53
@zhenyanghua, thank you for your reply. 

I resolved the issue by generating the token and then calling user.save so I can proceed with the call to mandrill.
```javascript
context.req.app.models.Member.generateVerificationToken(member, function (err, token) {
    if (err) {
        return next(err);
    }

    member.verificationToken = token;
    member.save(function (err) {
        if (err) {
            next(err);
        }
        else {
            var verifyUrl = 'http://' + config.host + ':' + config.port + '/api/members/confirm?uid=' + member.memberId + '&redirect=/&token=' + token;

            Member.app.models.Email.send({
                    to: member.email,
                    from: 'admin@example.com',
                    subject: 'Thanks for registering.',
                    template: {
                        name: "verify-mail",
                        content: [
                            {
                                name: "firstname",
                                content: member.username
                            },
                            {
                                name: "verificationlink",
                                content: verifyUrl
                            }
                        ]
                    }
                },
                function(err, result) {
                    if(err) {
                        console.log(err);
                        return;
                    }
                    console.log(result);
                });
        }
        next();
    });
});
```

**Comment by adrien-k** [comment] 2016-11-11 14:24
+1, the way `verify()` generates the email's html body is very hard to extend as it can only relies on `loopback.template()`.

What would you think of a additional `templateFn` option ?

It would be especially useful when one has a template engine specific for email that can't rely on `loopback.template`(like https://github.com/crocodilejs/node-email-templates for CSS inlining)

**Comment by zhenyanghua** [comment] 2016-11-11 19:57
If you use es6 in node, you can really just use `${}` to write the
template, it is really flexible.

Zhenyang Hua

**Comment by ritch** [comment] 2016-11-29 22:27
This is possible now. Closing.

**Closed by ritch** 2016-11-29 22:27 UTC
Labels: feature
