### ISSUE TITLE
creating relation error "Getting started part II"

### ISSUE THREAD

**Issue by tktk8924** [strongloop/loopback#2312] opened 2016-05-09 04:02 UTC
I'm trying ["Getting started part II"](https://docs.strongloop.com/display/public/LB/Define+model+relations) and having a problem with creating relation between CoffeeShop and Review models.

I got the following error:

```
? Select the model to create the relationship from: CoffeeShop
? Relation type: has many
? Choose a model to create a relationship with: Review
? Enter the property name for the relation: (reviews)


/Users/takehiro/.nodebrew/node/v5.11.1/lib/node_modules/strongloop/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true
```

I followed the following steps:

```
$ git clone https://github.com/strongloop/loopback-getting-started-intermediate.git
$ cd loopback-getting-started-intermediate
$ git checkout step2
$ npm install
$ slc loopback:relation
```

Versions:
* Node.js: v5.11.1
* strongloop: 6.0.0

Thanks.

**Comment by tktk8924** [comment] 2016-05-09 04:13
same with #2292

**Comment by jannyHou** [comment] 2016-05-09 19:15
yep, duplicate of #2292, we will take a look into it as soon as possible

**Closed** 2016-05-09 19:15 UTC
Labels: duplicate
