### ISSUE TITLE
loopback-connector-mysql: dataSource.discoverSchema doesn't read the default value from db

### ISSUE THREAD

**Issue by enricop89** [strongloop/loopback#3212] opened 2017-02-20 15:34 UTC
# Description/Steps to reproduce
Hi all,

I am using the dataSource API discoverSchema.. Everything works well except for one thing... the model produced doesn't contain the default value (only for certain type of data). It seems like the API doesn't read the default property from Db.

Example:

Table 'COMPANY':

<img width="1107" alt="screen shot 2017-02-20 at 16 16 20" src="https://cloud.githubusercontent.com/assets/12508630/23131103/1568e51a-f789-11e6-9e48-a41b3b1cfcc6.png">

The default value for the field 'logo' is not imported in the Model.json created. Same thing for the creation date, I expected the json with the defaultFn: 'now' but the API doesn't do it.

I am using Node 6.9.2, Loopback 3.2.1, Loopback my sql connector 2.4.1,  loopback-datasource-juggler 3.2.0

**Comment by bajtos** [comment] 2017-03-01 15:23
While I am not familiar with the mysql connector code myself, it looks like the "discovery" query does not include any information about the `default` value - see [lib/discovery.js#L159-L186](https://github.com/strongloop/loopback-connector-mysql/blob/030f8f9dc152c56f348aeb45e4d7c14387b4a246/lib/discovery.js#L159-L186).

@enricop89 I think this should be an easy change, would you like to contribute it yourself?

**Comment by ssh24** [comment] 2017-08-17 15:34
Closing this. 

Duplicate of https://github.com/strongloop/loopback-connector-mysql/issues/320

**Closed by ssh24** 2017-08-17 15:34 UTC
Labels: feature, needs-priority, patch-welcome, team-apex
