### ISSUE TITLE
Property 'getIdOf' is missing in type 'typeof ..' in loopback 4

### ISSUE THREAD

**Issue by Mohit-Purbia** [strongloop/loopback#4075] opened 2018-11-20 05:05 UTC
I create a project with lb4 and add models then i make datasource with mysql and create repository it gives error Property 'getIdOf' is missing.

 
src/repositories/customer.repository.ts:7:3 - error TS2344: Type 'Customer' does not satisfy the constraint 'Entity'.
  Property 'getId' is missing in type 'Customer'.

7   Customer,
    ~~~~~~~~

src/repositories/customer.repository.ts:13:11 - error TS2345: Argument of type 'typeof Customer' is not assignable to parameter of type 'typeof Entity & { prototype: Customer; }'.
  Type 'typeof Customer' is not assignable to type 'typeof Entity'.
    Property 'getIdOf' is missing in type 'typeof Customer'.

13     super(Customer, dataSource);
 npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! todo-list@1.0.0 build: `lb-tsc es2017 --outDir dist`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the todo-list@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/parikshitsaini/.npm/_logs/2018-11-20T05_03_20_287Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! todo-list@1.0.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the todo-list@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/parikshitsaini/.npm/_logs/2018-11-20T05_03_20_798Z-debug.log

 
-->

**Comment by dhmlau** [comment] 2018-11-21 03:33
Closing as duplicate of https://github.com/strongloop/loopback-next/issues/2058.

**Closed by dhmlau** 2018-11-21 03:33 UTC
