### ISSUE TITLE
slc loopback produces unformatted json files

### ISSUE THREAD

**Issue by rmayhue** [strongloop/loopback#1474] opened 2015-06-20 22:23 UTC
I just updated strongloop to v4.0.5 and now all JSON files produced are un-formatted. Everything is now all on a single line (e.g.):

```javascript
{"_meta":{"sources":["loopback/common/models","loopback/server/models"," ... }
```

Even if you manually format a file, adding models, relations etc., via slc will place everything back on a single line.

**Comment by ghislainf** [comment] 2015-06-22 13:22
+1. Same problem

**Comment by OOPMan** [comment] 2015-06-22 17:42
Argh, me too! This is very annoying!

**Comment by ivishwas-s** [comment] 2015-06-23 16:26
+1 Very annoying indeed!!

**Comment by spacemonkey** [comment] 2015-06-23 19:11
+1

Going back to 4.0.4 until this is fixed, just not possible to make a useful screencast! :-(

**Comment by spacemonkey** [comment] 2015-06-23 19:18
Ok looks like it was something else, as going back to 4.0.4 also produces the pre-minified JSON.

Anybody got a quick fix for now?

**Comment by raymondfeng** [comment] 2015-06-23 19:41
Duplicate of https://github.com/strongloop/strongloop/issues/238

**Closed by raymondfeng** 2015-06-23 19:41 UTC
