### ISSUE TITLE
Prevent autoupdate dropping residual columns...

### ISSUE THREAD

**Issue by timneedham** [strongloop/loopback#1942] opened 2016-01-05 13:06 UTC
Hi,

_Love Loopback!_
Think I've hit a problem though, creating a model like:

```
var Model = dataSource.createModel (
   'myModel',
   {
      a: 'string',
      b: 'string',
      c: 'string'
   },
   {}
);
```

Followed by a ```dataSource.autoupdate('myModel', function (err) {});``` works perfectly, with the 3 columns all present-and-correct on the [Postgres] database table.

But running ```dataSource.autoupdate``` later, but this time with a slightly reduced model of:

```
var Model = dataSource.createModel (
   'myModel',
   {
      a: 'string',
      b: 'string'
   },
   {}
);
```

...will go right ahead and drop column ```c```, even if it has data in it (at least it does via the Postgres connector).

Is there a way we can retain ("preserve"?) column ```c``` in situations like this?

Closest I've found is #207 ?

This is quite important to my use-case, any help gratefully received!

Tim

**Comment by richardpringle** [comment] 2016-01-28 19:34
Hey @timneedham, thanks for the love!... and sorry for taking so long to get to this issue.

In the future, if you run into any bugs, the best way to get the fix in the quickest time possible is to fork the [LoopBack-sandbox](https://github.com/strongloop/loopback-sandbox) and try to reproduce the issue in a public repo and write the steps to reproduce in the README of your forked repo.
Check out [the LoopBack wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) for more details on the procedure.

So I can't guarantee that I've reproduced your issue since I don't know all the details... but what you have to remember is that `dataSource.createModel()` creates a model class right? So what you are doing is not updating a model class that already exists, but creating a new model class with the same name which will then replace the other model class attached to your app.

What I recommend doing is updating the `myModel.json` file associated with your model if you want to change the property structure.

I am closing this issue but feel free to carry on the discussion here, just make sure you mention me directly.

Hope that helps and happy developing!

**Closed by richardpringle** 2016-01-28 19:34 UTC
Labels: triage
