### ISSUE TITLE
Loopback is too big for browser usage (browserify)

### ISSUE THREAD

**Issue by bkniffler** [strongloop/loopback#1175] opened 2015-03-05 12:12 UTC
I was following the instructions on:
https://strongloop.com/strongblog/full-stack-javascript-isomorphic-loopback-browse/

Now I ran the browserify grunt task on loopback and was surprised to find out that the distributable file was 1,9mb in size, after minifying still 1mb. I'm sure the size could be further reduced by gzipping, but it's still too big for browser usage. I'm aware you got a client side library for angularjs, but I'm using reactjs and flux on server/browser and I'm extremely interested in isomorphic code, reusing the models would be very useful. The features of loopback are great, especially offline/sync from the client side, but at the current stage I'm not sure I should use it due to it's size.

Maybe we should create a new client side library that would be able to use loopback models with remote methods, consume data from the API and store in localstorage/memory. And it shouldn't be tied to a client-side framework. What do you think?

**Comment by pandaiolo** [comment] 2015-03-05 12:43
+10

I wanted to implement some sort of data layer on the client side, but had no time to do it. (I did a [PR](https://github.com/pandaiolo/loopback-sdk-angular/commits/feature/client-model-config) over angular-sdk to achieve some isomorphism but it was a bit messy and not aligned on LB roadmap)

In the meantime, [js-data](http://www.js-data.io/) has release interesting stuff and is now framework agnostic. Not sure how it can be used to achieve some isomorphism with LB in the server. I'll have a look but if you find a good setup on your side, please share !

**Comment by BerkeleyTrue** [comment] 2015-03-05 16:33
There is already an issue covering this [here](https://github.com/strongloop/loopback/issues/989). This is a huge problem, though and I hope there is a patch sometime soon.

**Comment by bajtos** [comment] 2015-03-06 17:29
Closing as a duplicate of #989

**Closed by bajtos** 2015-03-06 17:29 UTC
