### ISSUE TITLE
Question about mongodb native method

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#646] opened 2014-10-15 10:43 UTC
How can I use others mongodb native method(i.e $exists, $elementMatch)  expect the operators  the document mentioned ( like, nlike, gt, lt  and so on)?

In forum , I found someone use mongo native method to realize it , and I tried it , but it doesn't match the demand.

For example: If I want find something that have one property exists, and need some related model property,  How can I do?

```js
Post.find(
  {where: { exists: {title: true}}, include: author },
  function(err, function(err, posts){ console.log(posts); });
```

I think this could be work , but it doesn't .

I found in dao.js( line 597), the code:

```js
  // Coerce the array items
     if (Array.isArray(val)) {
       for (var i = 0; i < val.length; i++) {
         if (val[i] !== null && val[i] !== undefined) {
           val[i] = DataType(val[i]);
         }
       }
     } else {
       if (val !== null && val !== undefined) {
         val = DataType(val);
       }
     } 
```

which change the value not in "operators" to [object Object]，so the mongodb engine receive the "query" [object Object]  which is not i want.

Is it  a bug?

**Comment by yorkie** [comment] 2015-09-02 08:21
Does this bug get fixed now? I occurs the same problem :(

**Comment by superkhau** [comment] 2015-09-02 22:44
>Does this bug get fixed now? I occurs the same problem :(

If the issue is still open, the bug is not fixed.

**Comment by superkhau** [comment] 2015-09-21 20:05
@raymondfeng ^

**Comment by bajtos** [comment] 2016-12-08 08:57
Closing in favour of https://github.com/strongloop/loopback-datasource-juggler/pull/1180

**Closed by bajtos** 2016-12-08 08:57 UTC
Labels: #revisit, bug
