### ISSUE TITLE
The where clause is not an object

### ISSUE THREAD

**Issue by subchal** [strongloop/loopback#2414] opened 2016-06-09 01:45 UTC
Hi Good evening

I have a model called "Favorites" and the findOne method is exposed through StrongLoop Explorer
{
  "id": "string",
  "customerId": "string",
  "volunteereventsId": "string"
}

When I invoke

http://sairamvolunteer.mybluemix.net/api/Favorites/findOne?filter=%7B%22where%22%3A%5B%22customerId%22%2C%22c8f5ecf6d7d5fde3a580c5029d79d505%22%5D%7D&access_token=JdwAlaPuNr8FondEc0HJ2AFF0XibAe5hvaF180iEDqDlkoYBPzpoinSp59Ofl7ma

I am getting the following error

{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "The where clause [\"customerId\",\"c8f5ecf6d7d5fde3a580c5029d79d505\"] is not an object",
    "statusCode": 400
  }
}

I am not sure what I am doing incorrect with my where filter.  Any guidance is greatly appreciated.

**Comment by gunjpan** [comment] 2016-06-09 14:27
@subchal : Your `where` filter syntax is wrong, it should be of following format:
`filter={"where":{"customerID:"your_id_value"}}`

The API explorer accepts only a `stringified JSON` input in filter ([see here](https://docs.strongloop.com/display/public/LB/API+Explorer))
Above should resolve your issue. For future reference, please post your questions to our dedicated Questions' channels _([links](https://github.com/strongloop/loopback/wiki/Questions)).

Closing this now. Thank you.

**Closed by gunjpan** 2016-06-09 14:27 UTC
Labels: question, triage

**Comment by frankorama** [comment] 2016-09-23 15:32
I am having the same issue.  We have a database which contains several companies, and each company can create several tags such that the Tags model has a foreign key property "companyId".

We created a middleware to always add a filter so that the user only sees their company's tags.

The problem is when calling GET **/api/Tags**, the `req.filter.where` clause must be an object.  When calling **/api/Tags/count**, the `req.filter.where` must be a string, otherwise the count is for all the tags in the database, not just the current user's
