### ISSUE TITLE
Returning XML, CSV based on Accepts header or extension

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback#970] opened 2015-01-05 09:18 UTC
Is there any way to do this (say, inject a post-request, pre-response middleware)? Would really like to support `GET /model(.json)`, `GET /model.xml`, and `GET /model.csv`, as well as `GET /model` with an Accepts header.

**Comment by eugenehp** [comment] 2015-06-23 21:22
@STRML @superkhau 

```
roject.afterRemote("donations",function projectAfterRemoteDonations(ctx,error,next){
		console.log('projectAfterRemoteDonations');
		if( ctx.req.query.format != undefined )
			if( ctx.req.query.format.toLowerCase() == 'csv' ){
				ctx.res.setHeader("Content-Type", "text/csv");
				// TODO: Problem it escapes quotes
				console.log( ctx.result );
			}
		next( null, ctx.result );
	})
```

the problem is that it escapes quotes :(

**Comment by pthieu** [comment] 2016-11-03 21:20
@STRML are you okay it the solution above? Been over the year since this issue was opened. I am closing; please re-open if solution above does not work for you.

**Closed by pthieu** 2016-11-03 21:20 UTC
Labels: feature

**Comment by STRML** [comment] 2016-11-03 22:17
Yeah, we did something similar in the end:

```js
// Add CSV support.

// Yeah, really. Misspelled.
const resolveReponseOperation = HttpContext.prototype.resolveReponseOperation;
const csvReponse = { // trololol
  contentType: 'text/csv',
  sendBody: sendCSVBody
};
HttpContext.prototype.resolveReponseOperation = function(accepts) {
  if (accepts === 'text/csv' || accepts === 'csv') return csvReponse;
  return resolveReponseOperation.call(this, accepts);
};

function sendCSVBody(res: Response, data: Array<Object> | Object): void {
  if (!data.length || typeof data[0] !== 'object') {
    res.statusCode === 204;
  } else {
    res.send(json2csv({data}));
  }
}
```
