### ISSUE TITLE
"write after end" error when running tests

### ISSUE THREAD

**Issue by piscisaureus** [strongloop/loopback#641] opened 2014-10-13 16:35 UTC
master banch @ 0fda4c4193a6354dc5152c364b3e2c9bef87e8f2
node 0.10.32, Windows 8.1

```
D:\loopback>grunt mocha-and-karma --force
Running "mochaTest:unit" (mochaTest) task

  ...........................................................
  ...........................The configuration of `MyTestModel` is missing `data
Source` property.
Use `null` or `false` to mark models not attached to any data source.
.................................
  .............................................................
  ............................................................
  ..................................................................
  ............................................................
  .....................

  380 passing (7s)
  7 pending


Running "karma:unit-once" (karma) task
INFO [karma]: Karma v0.12.24 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.7 (Windows 8)]: Connected on socket wzeGPdsarQBE00hCVY96 wit
h id 90933166
.

  380 passing (23s)
  7 pending
  1 failing

  1) User "after each" hook:
     Uncaught Error: write after end
      at writeAfterEnd (D:\loopback\node_modules\browserify\node_modules\readabl
e-stream\lib\_stream_writable.js:161:12)
      at DestroyableTransform.Writable.write (D:\loopback\node_modules\browserif
y\node_modules\readable-stream\lib\_stream_writable.js:208:5)
      at DestroyableTransform.ondata (D:\loopback\node_modules\browserify\node_m
odules\readable-stream\lib\_stream_readable.js:572:20)
      at DestroyableTransform.emit (events.js:117:20)
      at readableAddChunk (D:\loopback\node_modules\browserify\node_modules\read
able-stream\lib\_stream_readable.js:195:16)
      at DestroyableTransform.Readable.push (D:\loopback\node_modules\browserify
\node_modules\readable-stream\lib\_stream_readable.js:162:10)
      at DestroyableTransform.Transform.push (D:\loopback\node_modules\browserif
y\node_modules\readable-stream\lib\_stream_transform.js:145:32)
      at afterTransform (D:\loopback\node_modules\browserify\node_modules\readab
le-stream\lib\_stream_transform.js:101:12)
      at TransformState.afterTransform (D:\loopback\node_modules\browserify\node
_modules\readable-stream\lib\_stream_transform.js:79:12)
      at DestroyableTransform.noop [as _transform] (D:\loopback\node_modules\bro
wserify\node_modules\through2\through2.js:26:3)
      at DestroyableTransform.Transform._read (D:\loopback\node_modules\browseri
fy\node_modules\readable-stream\lib\_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (D:\loopback\node_modules\browser
ify\node_modules\readable-stream\lib\_stream_transform.js:172:12)



Warning: Task "mochaTest:unit" failed. Used --force, continuing.

Done, but with warnings.
```

**Comment by bajtos** [comment] 2016-04-07 15:05
I checked with @0candy and @jannyHou, they are running on Windows and cannot reproduce the problem. I am closing this issue as no longer relevant.

**Closed by bajtos** 2016-04-07 15:05 UTC
Labels: bug, windows
