### ISSUE TITLE
passportConfigurator userModel not responding to change

### ISSUE THREAD

**Issue by ianseyer** [strongloop/loopback#1750] opened 2015-10-20 17:16 UTC
Hi there!

I am using the facebook passport component, to handle user signup via facebook.

It is fully functional, however:

despite my `server.js` containing:
```
passportConfigurator.setupModels({
 userModel: app.models.donor,
 userIdentityModel: app.models.userIdentity,
 userCredentialModel: app.models.userCredential
});
```

the users are still created in the standard `User` table.

How would I go about changing this?

**Comment by superkhau** [comment] 2015-10-21 23:50
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by ianseyer** [comment] 2015-10-22 01:37
This seems like an issue to me. The lack of documentation makes it hard to tell, but setting a `userModel` would seem to be the appropriate thing to change.

**Comment by ianseyer** [comment] 2015-10-22 17:39
Well, regardless, I made an issue here:
https://github.com/strongloop/loopback-component-passport/issues/95

**Comment by superkhau** [comment] 2015-10-22 17:52
@ianseyer What is missing from the docs?

@crandmck ^

**Comment by ianseyer** [comment] 2015-10-22 17:54
Well, so the documentation here: https://apidocs.strongloop.com/loopback-component-passport/#passportconfigurator-prototype-setupmodels is not very clear, but I believe I am using it correctly in the example above.

**Comment by crandmck** [comment] 2015-10-22 18:38
@ianseyer Have you read [Third-party login (Passport)](https://docs.strongloop.com/pages/viewpage.action?pageId=3836277)? That should provide better information than just the API doc.  Also, see https://github.com/strongloop-community/loopback-example-passport.

**Comment by ianseyer** [comment] 2015-10-22 18:40
Yes, I have read both. Both use the default user class, nor is there an explicit "here is how you use your own user model" section.

**Comment by ianseyer** [comment] 2015-10-22 18:43
Ah! Fixed. Turns out it creates `userIdentity` and `userCredential` based on initial configuration, and creates a relation in the DB that relates to a specific model. Since I had used this before with the default class, changing the userModel changes nothing.

Adding a note about that to documentation might be useful, or maybe I'm just slow!

Either way, thank you!

**Comment by crandmck** [comment] 2015-10-22 18:45
Thanks @ianseyer -- I will add a note to the docs to clarify.   Since you resolved your problem, I'll close this issue.

**Comment by ianseyer** [comment] 2015-10-22 18:46
Sorry, Misfire. Not fixed.

**Comment by ianseyer** [comment] 2015-10-26 17:11
@crandmck just want to make sure you see that this is NOT fixed. My mistake.

**Comment by crandmck** [comment] 2015-10-26 20:33
Thanks @ianseyer.   I'm not clear on whether this is a doc issue or if there is a problem with the passport component or the example app.

**Comment by ianseyer** [comment] 2015-10-26 20:53
The issue, at this point, is a passport component issue.

Though it is hard to tell, due to the sparse documentation around changing
the user model used by the component.

**Comment by crandmck** [comment] 2015-10-26 23:37
@raymondfeng Could you take a look at this, please?

**Comment by mrbatista** [comment] 2015-10-27 02:18
@crandmck The problem is hard-coded relation in models user-identity.json and user-credential.json. At the moment, for my experience, use of this component is strictly dependent to model User built-in loopback or custom model with the same name for model and foreing key for relation. @ianseyer if you use custom model, is necessary to define custom model for identity e credentials. In the fact copy de model that found in model and then modify relations properly.

**Comment by ianseyer** [comment] 2015-10-29 18:14
I see. So can I get confirmation that this is infact an issue, and `UserModel` is not functioning? @crandmck

**Comment by crandmck** [comment] 2015-10-29 19:08
@superkhau I believe this falls into triage?  IAC, I don't _think_ it's a doc issue, but someone in eng. should really have a look.

If this is a bug in `loopback-example-passport`, then this issue would more properly be in that repo.

**Comment by ianseyer** [comment] 2015-10-29 19:09
I made one there, but it was closed by Simon.

**Comment by superkhau** [comment] 2015-10-29 19:44
@ianseyer Which issue was this? Let's reopen it if you believe it to be a legitimate bug. Please provide a sample repo with steps to reproduce on my end to confirm it (if you have no already done so).

**Comment by ianseyer** [comment] 2015-10-29 19:45
Oh!

Sorry, it wasn't you. It was superkhau.

https://github.com/strongloop/loopback-component-passport/issues/95

I will make a repo soon.

**Comment by superkhau** [comment] 2015-10-29 19:54
LOL, I am superkhau. I marked that issue as a duplicate of this issue. Are you saying that issue is different from this one?

**Comment by ianseyer** [comment] 2015-10-29 19:56
XD

My email changes it to your name proper. It is the same issue, however, the
issue belongs in passport-component.

**Comment by superkhau** [comment] 2015-10-29 20:58
Haha, its all good. You are right though, we should reopen the other issue and close this one as the duplicate. Fixing.

**Comment by superkhau** [comment] 2015-10-29 20:59
Duplicate of https://github.com/strongloop/loopback-component-passport/issues/95.

**Closed by superkhau** 2015-10-29 20:59 UTC
Labels: triage
