### ISSUE TITLE
remote method context is wrong (serious)

### ISSUE THREAD

**Issue by benjaminhon** [strongloop/loopback#2691] opened 2016-08-30 07:11 UTC
i notice this problem when i call remote methods very quickly, for example:

```
Promise.map(bedSlots, actions.bedSlots.setLocation)
```

in my remote method

```
BedSlot.setLocation = function (data, callback) {

    lat     = parseFloat(data.lat);
    lng     = parseFloat(data.lng);
    mapId   = parseInt(data.mapId);
    id      = parseInt(data.id);

    BedSlot.findById(id, function (err, slot) {
      if(!err) {
        slot.location.destroy(function (err) {

          // CONTEXT WRONG HERE
          slot.location.create({lat, lng, mapId}, function (err) {
            if(!err){
              callback(null);
            } else {
              callback({status: 500}); 
            }
          })
        })
      } else {
        callback({status: 500});
      }
    })
  }
```

i did some console logging and found that the object **{lat, lng, mapId}** for both calls are the same, belonging to the later call, however the **data** object for both are correct

i had to recode it as follows to work but i don't know why each remote does not get its own context.

```
BedSlot.setLocation = function (data, callback) {
    BedSlot.findById(id, function (err, slot) {
      if(!err) {
        slot.location.destroy(function (err) {
          slot.location.create({
            lat:    parseFloat(data.lat),
            lng:    parseFloat(data.lng),
            mapId:  parseInt(data.mapId)
          }, function (err) {
            if(!err){
              callback(null);
            } else {
              callback({status: 500}); 
            }
          })
        })
      } else {
        callback({status: 500});
      }
    })
  }
```

**Comment by davidcheung** [comment] 2016-08-31 15:12
@benjaminhon thanks for bringing this up, could you please fork the [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) with a sample repo to reproduce your the bug? 

If you declared the variables on the top, I think it does make sense that it would be the same for both calls?

**Comment by benjaminhon** [comment] 2016-09-01 02:39
Hi David,
I was actually doing some data validation, of the *data* argument, however i was under the impression that the two REST calls would call the remote method twice with both having a separate context? But it seems  that the second call is setting the variables again:
```
lat     = parseFloat(data.lat);
lng     = parseFloat(data.lng);
mapId   = parseInt(data.mapId);
id      = parseInt(data.id);
```
at this point when the first call tries to use them, they have been changed.

How do i  use the sandbox? it doesnt seem to have loopback installed on it, do i need to do npm install loopback?

**Comment by davidcheung** [comment] 2016-09-01 15:11
Hi @benjaminhon,
yes you would have to do an npm install on the sandbox, the goal is so we can reproduce the issue/bug with the least logic so it can rule out other factors. in this case it requires calling the methods very quickly it might be hard to reproduce though, it is possibly a duplicate of https://github.com/strongloop/loopback/issues/1676 as well. 


does it also resolve the problem if you make the vairables local?  as the model class is not duplicated per call.
```js
var lat     = parseFloat(data.lat);
var lng     = parseFloat(data.lng);
var mapId   = parseInt(data.mapId);
var id      = parseInt(data.id);
```

**Comment by davidcheung** [comment] 2016-11-03 20:57
@benjaminhon closing this issue due to inactivity, please ping me here or reopen another issue and link to this one with a sandbox to reproduce the problem

**Closed by davidcheung** 2016-11-03 20:57 UTC
Labels: triage
