### ISSUE TITLE
loopback auth treats User.email case sensitive

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#1150] opened 2015-03-02 21:03 UTC
And it goes the same for User.username, but that depends on taste...

My use case: I can't login when my iOS automatically sets the first character to uppercase...but please look beyond this ;)

**Comment by esco** [comment] 2015-03-15 05:44
It looks like the findOne query that searches by username or email isn't case sensitive https://github.com/strongloop/loopback/blob/1cabd74308e8c57aa8033641c77bccfcf86e57f3/common/models/user.js#L196-L203

@raymondfeng is it possible to do a case-insensitive query?

**Comment by SLonoed** [comment] 2015-04-06 19:16
@Morriz, maybe good way to set autocapitalize="off" to your input.

**Comment by Morriz** [comment] 2015-04-06 19:29
Sure, that would be handy as well, but is not a solution to the (bigger) problem :)

**Comment by SLonoed** [comment] 2015-04-06 19:34
@Morriz, what problem?

In [rfc2821](http://www.faqs.org/rfcs/rfc2821.html)
```
The local-part of a mailbox MUST BE treated as case sensitive.
```

If you need case insensitive emails, you can use beforeRemote hook to change it on login and sign up.

**Comment by esco** [comment] 2015-04-06 19:53
@SLonoed @Morriz 

That quote is not referring to email addresses.

Case-insensitive emails make a lot of sense. Imagine if gmail addresses were case-sensitive, there would be so much confusion. Github also does case-insensitive email login.

**Comment by Morriz** [comment] 2015-04-06 19:59
Like I said it in the title: emails were not treated case insensitive when I said that. It does now?

**Comment by Morriz** [comment] 2015-04-06 20:00
Ha, I always thought emails were treated case insensitive. Learned something new today ;)

**Comment by SLonoed** [comment] 2015-04-06 20:30
@esco, I agree with you. Almost all mail services use case insensitive. But include it to loopback by default – bad idea. Loopback provide ability (with few lines of code) to make email insensitive. This is enough.

**Comment by esco** [comment] 2015-04-06 20:35
@SLonoed fair enough that its flexible, but my vote is for the most common use case to be the default with the ability to make it case-sensitive. :+1:

**Comment by Morriz** [comment] 2015-04-06 22:00
I agree, it's value (i.e. supporting majority of well known use cases) I am after mostly, and I bet most ppl are...

**Comment by SLonoed** [comment] 2015-04-06 22:05
Supporting majority well known use cases must be in new versions of specs. And after supporting in code. When software developers build soft based on use cases instead of specs, they build new internet explorer. Nah..

**Comment by esco** [comment] 2015-04-06 22:12
@SLonoed sometimes being pragmatic is good. This would cover 99% of use cases. Case-sensitive email lookups aren't very useful.

**Comment by technicallyfeasible** [comment] 2015-04-17 13:30
+1

I agree to supporting the most common usecase. No service I know of treats emails as case sensitive and if they do it leads to a lot of confusion with seemingly not being able to login.
I got infuriated by such behavior myself on several occasions.

**Comment by slonoed** [comment] 2015-04-22 23:49
@technicallyfeasible why you got infuriated? You read email specs?

**Comment by technicallyfeasible** [comment] 2015-04-23 07:22
Yes, I know the specs, I have implemented an email parser myself once but have you tried to explain that to a potential user? They usually just move on to the service that is more accommodating.

**Comment by OwenBrotherwood** [comment] 2015-05-03 13:40
https://github.com/strongloop/loopback/issues/1354 shows a way to hijack the access to a model and make the key case insensitive.
Is this a way out for the iOS users and lower case emails ...

**Comment by jlvdh** [comment] 2015-08-25 08:46
@OwenBrotherwood your code is working fine for me in user.js. I only had to change app.models.Users to app.models.User.

**Comment by esco** [comment] 2015-10-08 15:39
@OwenBrotherwood this solution breaks if you have a scope defined on the User model. The scope will create an `and` query which doesn't get detected by the if

```js
if (ctx.query.where && ctx.query.where.email) {
  ctx.query.where.email = ctx.query.where.email.toLowerCase();
} else if (ctx.query.where && ctx.query.where.and) {
  ctx.query.where.and = ctx.query.where.and.map(function(condition){
    Object.keys(condition).forEach(function(key){
      if (key === 'email') {
        condition[key] = condition[key].toLowerCase();
      }
    });
    return condition;
  });
}
```

**Comment by OwenBrotherwood** [comment] 2015-10-08 20:08
@superkhau Can something be done with this issue: currently triac and no assignee. @esco gave some input that should be understand. Currently, I have had to do a context switch from javascript to IBM Mainframe work which is hopefully finished soon. "I'll be back"

**Comment by superkhau** [comment] 2015-10-14 06:23
@OwenBrotherwood I can bump this up to major.

@raymondfeng ^

**Comment by OwenBrotherwood** [comment] 2015-10-15 06:21
@superkhau The issue seems to interest a lot of people, so it would be good to have a standpoint on it.
It is possible to support the normal use of email case sensitivity, as default or option, without going against the stated rfc's, in the framework

**Comment by superkhau** [comment] 2015-10-15 15:38
Duplicate of #1723.

@OwenBrotherwood I will bring this up during sprint planning. Otherwise, we accept PR's so feel free to submit a patch. ;)

**Comment by OwenBrotherwood** [comment] 2015-10-16 15:09
@superkhau PR: will do if I get there before sprint

**Comment by bajtos** [comment] 2015-10-22 10:35
I am proposing to add a new setting to the User model that would allow LoopBack apps to decide whether they want case-sensitive checks of emails or not.

**Comment by OwenBrotherwood** [comment] 2015-10-22 10:41
@bajtos sounds good.
This issue is in what way the user email is used in Authentication, ie strict case sensitive or not and that the framework is used to reduce load on the application

https://github.com/strongloop/loopback/issues/1723 is the other issue of interest, that seems to have a life of it's own but is "interesting" as to what is a valid user email, that is in turn used in Authentication

**Comment by ritch** [comment] 2015-11-06 21:19
+1 for `User.settings.caseInsensitveEmail`  ...we should probably default it to true in 3.0 IMO.

**Comment by superkhau** [comment] 2015-11-08 08:43
+1 for true in LB3

**Closed** 2015-12-08 11:47 UTC
Labels: #review, Beginner Friendly, major

**Comment by OwenBrotherwood** [comment] 2015-12-08 13:22
:+1:

**Comment by DucNguyenTHT** [comment] 2023-06-21 06:23
for any person who come later 
JUST OVER WRITE THE lib for case sensitive
it work for me 

```
const g = require('loopback/lib/globalize');
const debug = require('debug')('loopback:user');
model/user

module.export = (user) => {
...
  User.login = function(credentials, include, fn) {
    const self = this;
    if (typeof include === 'function') {
      fn = include;
      include = undefined;
    }

    fn = fn || utils.createPromiseCallback();

    include = (include || '');
    if (Array.isArray(include)) {
      include = include.map(function(val) {
        return val.toLowerCase();
      });
    } else {
      include = include.toLowerCase();
    }

    let realmDelimiter;
    // Check if realm is required
    const realmRequired = !!(self.settings.realmRequired ||
      self.settings.realmDelimiter);
    if (realmRequired) {
      realmDelimiter = self.settings.realmDelimiter;
    }
    const query = self.normalizeCredentials(credentials, realmRequired,
      realmDelimiter);

    if (realmRequired) {
      if (!query.realm) {
        const err1 = new Error(g.f('{{realm}} is required'));
        err1.statusCode = 400;
        err1.code = 'REALM_REQUIRED';
        fn(err1);
        return fn.promise;
      } else if (typeof query.realm !== 'string') {
        const err5 = new Error(g.f('Invalid realm'));
        err5.statusCode = 400;
        err5.code = 'INVALID_REALM';
        fn(err5);
        return fn.promise;
      }
    }
    if (!query.email && !query.username) {
      const err2 = new Error(g.f('{{username}} or {{email}} is required'));
      err2.statusCode = 400;
      err2.code = 'USERNAME_EMAIL_REQUIRED';
      fn(err2);
      return fn.promise;
    }
    if (query.username && typeof query.username !== 'string') {
      const err3 = new Error(g.f('Invalid username'));
      err3.statusCode = 400;
      err3.code = 'INVALID_USERNAME';
      fn(err3);
      return fn.promise;
    } else if (query.email && typeof query.email !== 'string') {
      const err4 = new Error(g.f('Invalid email'));
      err4.statusCode = 400;
      err4.code = 'INVALID_EMAIL';
      fn(err4);
      return fn.promise;
    }

    User.findOne({where: {email: {like: query.email, options: 'i' }}}, function(err, user) {
      const defaultError = new Error(g.f('login failed'));
      defaultError.statusCode = 401;
      defaultError.code = 'LOGIN_FAILED';

      function tokenHandler(err, token) {
        if (err) return fn(err);
        if (Array.isArray(include) ? include.indexOf('user') !== -1 : include === 'user') {
          // NOTE(bajtos) We can't set token.user here:
          //  1. token.user already exists, it's a function injected by
          //     "AccessToken belongsTo User" relation
          //  2. ModelBaseClass.toJSON() ignores own properties, thus
          //     the value won't be included in the HTTP response
          // See also loopback#161 and loopback#162
          token.__data.user = user;
        }
        fn(err, token);
      }

      if (err) {
        debug('An error is reported from User.findOne: %j', err);
        fn(defaultError);
      } else if (user) {
        user.hasPassword(credentials.password, function(err, isMatch) {
          if (err) {
            debug('An error is reported from User.hasPassword: %j', err);
            fn(defaultError);
          } else if (isMatch) {
            if (self.settings.emailVerificationRequired && !user.emailVerified) {
              // Fail to log in if email verification is not done yet
              debug('User email has not been verified');
              err = new Error(g.f('login failed as the email has not been verified'));
              err.statusCode = 401;
              err.code = 'LOGIN_FAILED_EMAIL_NOT_VERIFIED';
              err.details = {
                userId: user.id,
              };
              fn(err);
            } else {
              if (user.createAccessToken.length === 2) {
                user.createAccessToken(credentials.ttl, tokenHandler);
              } else {
                user.createAccessToken(credentials.ttl, credentials, tokenHandler);
              }
            }
          } else {
            debug('The password is invalid for user %s', query.email || query.username);
            fn(defaultError);
          }
        });
      } else {
        debug('No matching record is found for user %s', query.email || query.username);
        fn(defaultError);
      }
    });
    return fn.promise;
  };
...
}
```

**Comment by esco** [comment] 2023-06-21 14:29
@DucNguyenTHT a new setting was created in #1804 so that you can achieve this by updating the user model settings.

```json
"options": {
    "caseSensitiveEmail": false
 }
  ```
  
https://github.com/richardpringle/loopback/blob/2cca83c4fff718a7fbf0f69e009d985eb9be7c16/common/models/user.json#L33
