### ISSUE TITLE
Group by clause with a mysql datasource

### ISSUE THREAD

**Issue by arondn2** [strongloop/loopback#3357] opened 2017-04-12 15:29 UTC
Is there anyway to do a groupBy clause with a aggregate function in a model attached to a mysql datasource with the loopback's models?

**Comment by ssh24** [comment] 2017-08-17 15:32
Closing this.

Duplicate of https://github.com/strongloop/loopback-connector-mysql/issues/159

**Closed by ssh24** 2017-08-17 15:32 UTC
Labels: team-apex
