### ISSUE TITLE
PersistentModel.findOrCreate function callback and promise difference

### ISSUE THREAD

**Issue by emresebat** [strongloop/loopback#1959] opened 2016-01-14 20:23 UTC
Hi all

I'm trying to get used to findOrCreated method, the where clause was a little confusing and now I have a new confusion :)

If I call it with callback like this:

```javascript
Account.findOrCreate({
    where: {
        id: remoteObj.id
    }
}, remoteObj, function(err, instance) {
    //here instance is the found object either a new instance is created from remoteObj or not
});
```
If I call with promise like this:

```javascript
Account.findOrCreate({
        where: {
            id: remoteObj.id
        }
    }, remoteObj)
    .then(function(instance) {
        //here instance is an array, first element the instance, second element created flag
    })
    .catch(function(err) {});
```

So promise signature makes more sense but I don't see this anywhere on the documentation:

https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate

Any ideas why this difference exists?

**Comment by jannyHou** [comment] 2016-01-17 18:47
hey @emresebat I reproduced your issue and I believe you get different format of results because of this few lines in [definition of `findOrCreate`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L600):
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L783-L786
and
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L790-L793

I will confirm more details about why they are different tomorrow. And for the document part, the whole implementation of [**api primisify**](https://docs.strongloop.com/display/public/LB/Using+promises) is not complete. And we are working on updating the doc for everywhere that uses promise. This task would be done in the future then users can see promise doc everywhere. Thanks!

**Comment by jannyHou** [comment] 2016-01-19 18:02
We use array in promise callback because in function `createPromiseCallback`:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L480
data is resolved in this format:
```js
cb = function (err, data) {
      if (err) return reject(err);
      return resolve(data);
    };
```

**Closed** 2016-01-19 18:05 UTC
Labels: question, triage
