### ISSUE TITLE
Static file config in middleware.json is remove after update datasource

### ISSUE THREAD

**Issue by PhuongNL** [strongloop/loopback#1564] opened 2015-08-05 02:36 UTC
After i update datasource by use slc arc, all config static file in middleware.json is removed. I use strongloop v5.0.0 (node v2.4.0). Please fix it.

**Comment by ritch** [comment] 2015-08-06 22:37
This sounds like a serious issue. Are you saying that the `middleware.json` file is removed or something within the `middleware.json` is? Do you have some reproduction steps for this? Are you using arc and editing the file at the same time?

**Comment by PhuongNL** [comment] 2015-08-07 02:19
Only config static file in field **"files"** is remove. I use slc arc in my project then go to datasource choice **Test Connection** after that filed "files" in middleware.json is become  **"files": {}**. 

Are you using arc and editing the file at the same time?
**I only use arc**

**Comment by ritch** [comment] 2015-08-07 18:31
This sounds like an issue in the workspace API.

@raymondfeng can you take a look since you added middleware support recently?

**Comment by crandmck** [comment] 2015-08-07 20:17
I was unable to reproduce this.  I modified the `files` property in `middleware.json` then added a new datasource in Arc and tested it.  The `middleware.json` file was unaffected.

@PhuongNL By default the `middleware.json` created by `slc loopback` has 
```
  "files": {
  },
```
So unless you are manually editing `middleware.json`, that's what you _should_ see.
See http://docs.strongloop.com/display/LB/Add+a+static+web+page.

**Comment by PhuongNL** [comment] 2015-08-10 08:55
I know the problem. Here is my config static file in **middleware.json** (*i copy from my another project*):
```
"files": {
    "loopback#static": [
      {
        "paths": [
          "/"
        ],
        "params": "$!../client"
      },
      {
        "paths": [
          "/bower_components"
        ],
        "params": "$!../bower_components"
      }
    ]
  },
```
but in my current project doesn't have bower_components then when i choice test connection in **arc** all static file is remove.

One more thing, please support **iojs > 2.4**.

**Comment by raymondfeng** [comment] 2015-08-10 15:04
@PhuongNL It seems loopback#static entries pointing to non-existent files are removed. I'll check.

**Comment by crandmck** [comment] 2015-08-10 17:57
OK, I reproduced the problem with the above `"files"` entry.   As soon as I click **Test Connection** the entry disappears from `middleware.json`.  It didn't seem to matter if I had a `client` or `bower_components` directory.

**Comment by davidcheung** [comment] 2015-12-07 15:17
Possibly related #1833

**Comment by davidcheung** [comment] 2015-12-14 22:55
Hi @crandmck, I believe this(non-existing path `files` entry removed) is no longer as issue, would you be able to see if you also can no longer reproduce this issue, then this issue can be closed . Thanks!

**Comment by crandmck** [comment] 2015-12-17 00:32
@davidcheung  I tried it again and was not able to reproduce.  So, I assume the problem is fixed in the latest release.

**Closed by crandmck** 2015-12-17 00:32 UTC
Labels: #wip, beginner-friendly, bug, major
