### ISSUE TITLE
Overridden CRUD methods ignored when using nestRemoting

### ISSUE THREAD

**Issue by philippdhh** [strongloop/loopback#1866] opened 2015-12-08 18:38 UTC
Hello,

normally when overriding a default CRUD method I just use the following code:

GFile.findById = function(id, cb) {
      console.log('Overridden find method fired!');
      ...
    }

This works perfectly when calling the ressource directly, e.g. GET localhost:3000/api/GFile/1

But when using nestRemoting and calling GET localhost:3000/api/AppUser/1/Group/1/GFile/1 the original find method is used instead of my overriden find method.

Is this the intended behaviour? In my eyes the overriden method should be used instead.

**Comment by philippdhh** [comment] 2015-12-08 18:42
This might be related with the just before created issue #1865

**Comment by davidcheung** [comment] 2015-12-08 20:24
Hi @philippdhh, yes seems like they could be related, does your `non-overridden` remote methods work? If they don't then it is likely the same issue.

**Comment by philippdhh** [comment] 2015-12-08 20:59
Thats's correct, the non-overridden methods also don't work.

**Comment by davidcheung** [comment] 2015-12-10 15:46
@philippdhh, I believe then the root cause of this issue is the only default methods are nested through [`nestRemoting`](https://github.com/strongloop/loopback/blob/master/lib/model.js#L678), and listed as feature in #1865 
@ritch does this [commit](https://github.com/strongloop/strong-remoting/commit/195845ffc06a404263af61d86e9072973ce5ce0a) provide us ability to add this feature to model.js `nestRemoting` to nest the remote methods there too?

**Comment by davidcheung** [comment] 2016-11-17 22:19
closing duplicate in favor of #1865

**Closed by davidcheung** 2016-11-17 22:19 UTC
Labels: feature, remoting
