### ISSUE TITLE
How to access the current user from a model method

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#816] opened 2014-11-14 17:24 UTC
We should document the recommended way for accessing the current user from model methods.

See
 - https://github.com/strongloop/loopback/issues/569
 - https://groups.google.com/forum/#!topic/loopbackjs/2HaUzpFPmfQ

And the solution:
 - https://github.com/strongloop/loopback/pull/775

**Comment by jannyHou** [comment] 2015-12-03 22:42
hey @bajtos , I confirmed with Rand and this solution is already explained perfectly in doc:
https://docs.strongloop.com/display/public/LB/Using+current+context#Usingcurrentcontext-Usecurrentauthenticateduserinremotemethods

The same example snippet as you post in [comment](https://github.com/strongloop/loopback/issues/569#issuecomment-62690674) is applied. 

Since it's done, I will close it here. Thanks.

**Closed by jannyHou** 2015-12-03 22:42 UTC
Labels: #sprint85, Beginner Friendly, doc

**Comment by bajtos** [comment] 2015-12-04 10:45
> Since it's done, I will close it here.

:+1:

**Comment by jankcat** [comment] 2016-11-02 01:41
For those looking for a solution to finding out the authenticated user in a remote method (now that currentContext is deprecated), the groundwork is laid out at the following link: https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-HTTPmappingofinputarguments

Here is my example snippet:
```js
  MyObject.remoteMethod(
    'myMethod',
    {
      http: {path: '/myMethod', verb: 'get'},
      accepts: [
        {arg: 'someArgument', type: 'string'},
        {
          arg: 'accessToken',
          type: 'object',
          http: function(ctx) {
            return ctx.req.accessToken;
          }
        }
        ],
      returns: {arg: 'someResponse', type: 'string'}
    }
  );
  MyObject.myMethod = function(someArgument, accessToken, cb) {
    // ...
	// accessToken.userId
	// ...
    cb(null, "Response blah blah...");
  }
```

**Comment by jannyHou** [comment] 2016-11-02 15:27
@jankcat Thank you for looking into `context` issue and providing the sample code!

While the link you post is from our old doc site. Now it's migrated to new site and please check latest doc of proper usage of `context`:
http://loopback.io/doc/en/lb2/Using-current-context.html
It elaborates some warning, solution, ect....

**Comment by jankcat** [comment] 2016-11-02 15:34
Thanks, I updated my comment to the new documentation location.
