### ISSUE TITLE
Overriding model-plural endpoint is inconsistent

### ISSUE THREAD

**Issue by whysorfrans** [strongloop/loopback#2573] opened 2016-08-01 10:54 UTC
I am (trying to) use a mixin to change override the default {{apiroot}}/modelplural endpoint to not return all modelinstances but only those 'related' to the logged-in user through a has-many-through relation.

The mixin basically looks like

`model.listThrough = function(context, filter, callback){
...
}`

`model.remoteMethod("listThrough", {
        isStatic: true, http:{path: "/", verb:"get"}, ... }`

This works fine only for some models, while some models retain the original, builtin functionality, and I can not find what makes the difference.

Is this (overriding "/") supposed to be able to work at all and if so, what could make it fail? Is it a bug when overriding 'works' or when it 'fails'?

**Comment by davidcheung** [comment] 2016-08-03 18:58
Hi @whysorfrans, hope this solves your problem, normally its adviced to specific the [plural form](https://docs.strongloop.com/display/public/LB/Customizing+models#Customizingmodels-CustomizingamodelusingJSON) in your `model.json` (and when you specify relations you also get to name that relations for the relation name)
```js
//model.json
{
  "name": "myModel",
  "base": "PersistedModel",
  "plural": "mymodels",
  "properties": {
     // Properties listed here depend on your responses to the CLI
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

The `remoteMethod` `http.path` is relative to the model, [please see the following link](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Options).

**Comment by bajtos** [comment] 2016-08-04 09:45
> Is this (overriding "/") supposed to be able to work at all and if so, what could make it fail? Is it a bug when overriding 'works' or when it 'fails'?

First of all, you should disable the built-in `GET /` method if you want to replace it with your own implementation. See https://docs.strongloop.com/display/public/LB/Exposing+models+over+REST#ExposingmodelsoverREST-HidingmethodsandRESTendpoints

If that doesn't help, then we will need full instructions on how to reproduce the problem locally, see [the wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by richardpringle** [comment] 2016-08-04 13:27
@whysorfrans,

Can you fork a [loobpack-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce the issue in your fork? After, you can provide a link here and we can take a look. Otherwise, I can't help you figure out why some models are working and others aren't.

**Comment by whysorfrans** [comment] 2016-08-05 10:32
Hi all,

Thank you for taking the time for my issue.

Richard, I have forked the sandbox and will attempt to recreate the problem in the forked sandbox, this may take some time.

Bajtos, disableRemoteMethod seems to do the trick. Leaves the question as to why some endpoints were overridden without disabling their methods first. I'll try to reproduce starting with a clean api in sandbox

**Comment by davidcheung** [comment] 2016-11-03 20:22
Looks like this issue is resolved. Closing issue

perhaps we can open a feature request for "Disabling original remoteMethod upon method overriden"

**Closed by davidcheung** 2016-11-03 20:22 UTC
Labels: remoting, triage, waiting
