### ISSUE TITLE
Possible Bug: Remote methods don't work with strong-remoting

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#1597] opened 2015-08-15 00:10 UTC
I have a remote method:
1. https://github.com/ShoppinPal/warehouse/blob/develop/common/models/report-model.js#L53-L59
2. https://github.com/ShoppinPal/warehouse/blob/develop/common/models/report-model.js#L156

And it can be accessed on the server like so:
`ReportModel.getRows('55cc99bb3b52a6ebdeed394f',cb)`

But it fails to function when accessed via strong-remoting:

```
server:server GET /api/ReportModels/:id/rows?id=55cc99bb3b52a6ebdeed394f 
     token: {"id":"secret","ttl":1209600,"created":"2015-08-13T13:21:00.205Z","userId":"secret"}
```

Notice how the `:id` hasn't been substituted, instead the value has become a query parameter!

@ritch: Is this a possible bug?

**Comment by richardpringle** [comment] 2016-01-14 16:25
Hey @pulkitsinghal, I took a look at your code and I just want to clarify what's going on. Your remote method, `getRows` is returning a `ReportModel` instance? I would have thought that your REST endpoint should be `/api/ReportModels/getRows?id=55cc99bb3b52a6ebdeed394f`.

I think I'm missing something here...

Let me know so that I can verify that this is a bug.

**Comment by richardpringle** [comment] 2016-01-19 15:42
@pulkitsinghal, sorry I was confused above but I believe that I found the problem. Your `http` object in the remote method definition needs to include `:id`. 
```
http: {path: '/:id/getRows', verb: 'get'},
```
The path is relative to the model itself,  not the model instance.

Let me know if that works so I can either investigate further or close the issue.

Cheers!

**Comment by pulkitsinghal** [comment] 2016-01-19 18:39
Thanks, @richardpringle! When i ran the test based on which I filed this issue, I did do so ... see this commented line:
https://github.com/ShoppinPal/warehouse/blob/develop/common/models/report-model.js#L57

But practically I had to move on with my workaround which doesn't employ it, and I think you may be looking at that part of the code when advising me.

Have you setup a test to verify what I've reported? Let me know if there is a way I can setup such a sandbox easily, perhaps you have github template projects i can *fork* for reporting and reproducing such bugs?

**Comment by richardpringle** [comment] 2016-01-19 20:40
hmm... I see that you did.
I was not able to reproduce. As for a sandbox, we have something called [loopback-sandbox!](https://github.com/strongloop/loopback-sandbox). If you fork that repo, you can create an example model that reproduces the issue.
However, that is exactly what I tried to do and I didn't run into the same issue.

If you fork and are able to reproduce, post a link to the forked repo and I will take another look.

**Comment by richardpringle** [comment] 2016-01-26 19:25
@pulkitsinghal, are you setting the option `isStatic: false`? 
See the [API docs](https://apidocs.strongloop.com/strong-remoting/#sharedmethod) for reference.

**Comment by bosco-li** [comment] 2016-11-03 19:55
@pulkitsinghal We are closing this issue due to inactivity for 9 months and we were not able to reproduce this.  If you need this to open again please do so.  Thanks!

**Closed by bosco-li** 2016-11-03 19:55 UTC
