### ISSUE TITLE
User.confirm has 'redirect' as required argument

### ISSUE THREAD

**Issue by umbrella-ivan-zhukov** [strongloop/loopback#1065] opened 2015-02-04 08:48 UTC
User.confirm remote method shouldn't have `redirect` as required argument, because you can request this endpoint via ajax.

Also, the code allows to do this (from common/models/user.js)

```
var redirectUrl =
            params && params.redirect !== undefined ? params.redirect :
            body && body.redirect !== undefined ? body.redirect :
            query && query.redirect !== undefined ? query.redirect :
            undefined;

          // redirect user if path defined
          if (ctx.req.param('redirect'))
            ctx.res.redirect(redirectUrl);
          else
            ctx.res.sendStatus(200)
        } else {
          next(new Error('transport unsupported'));
```

**Comment by umbrella-ivan-zhukov** [comment] 2015-02-04 14:54
Me bad, above I posted code from my patch, but now it's in PR.
Now trying to pass tests...

**Comment by ritch** [comment] 2015-02-04 22:17
Agree for supporting `confirm()` without `redirect` set.

**Comment by bajtos** [comment] 2015-02-05 08:11
This issue is a duplicate of #416. I'll keep it open though since there is already a pull request associated with this issue.

**Comment by umbrella-ivan-zhukov** [comment] 2015-02-05 11:30
Setting Location header and calling `next()` (like @ritch says) is now triggering afterRemote hook (for duplicate issue).
But I have to make some change in strong-remoting repo. Please, take a look on PR (linked above).

**Comment by pthieu** [comment] 2016-11-03 20:52
Closing because issue has been resolved: https://github.com/strongloop/strong-remoting/pull/174 points to https://github.com/strongloop/strong-remoting/issues/175

**Closed by pthieu** 2016-11-03 20:52 UTC
Labels: feature
