### ISSUE TITLE
Failed to install strongloop

### ISSUE THREAD

**Issue by zhouhao27** [strongloop/loopback#2018] opened 2016-02-01 09:13 UTC
I got the following error message:

> npm WARN lifecycle strong-arc@1.8.8~preinstall: cannot run in wd %s %s (wd=%s) strong-arc@1.8.8 node .sl-blip.js /usr/local/lib/node_modules/.staging/strong-arc-e089ca568e2a49f714e3744a579cc8f1
> npm WARN install:depd@1.0.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/strongloop/node_modules/ast-types/node_modules/depd' -> '/usr/local/lib/node_modules/strongloop/node_modules/express-session/node_modules/depd'

Please help, thanks.

**Comment by superkhau** [comment] 2016-02-01 20:37
@zhouhao27 Are you on windows?

**Comment by 0candy** [comment] 2016-02-01 20:53
@sam-github Are you the right person to take a look at this issue?

**Comment by noderat** [comment] 2016-02-02 00:34
I've encountered an error like this in the past, which was caused by a very, very outdated npm. I suggest updating npm with `npm install -g npm` or `sudo npm install -g npm` depending on your machine.

**Comment by sam-github** [comment] 2016-02-02 15:13
@0candy Not really. Its an npm bug, nothing we can do about it but report upstream. But report is missing:
- node version
- npm version
- platform

As @noderat said, this is almost certainly Windows, and almost certainly on an outdated version of npm. Update npm, it was a rats nest of Windows bugs until npm v2. And still not great on Windows until npm v3.

**Comment by superkhau** [comment] 2016-02-02 22:32
@zhouhao27 Please follow @sam-github's suggestion and report it upstream at https://github.com/npm/npm. Closing this issue as it is not LoopBack specific.

**Closed by superkhau** 2016-02-02 22:32 UTC
Labels: triage, wrong-repo

**Comment by rikantro** [comment] 2016-10-05 16:43
I had the same issue, even if install  strong-arc separately without errors , only with npm install -g strongloop the same error appears.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\n
):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wan
:"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\nod
or\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wan
:"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 (node_modules\strongloop\node_mod
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 preinstall: `npm install node-pre
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 4294963214
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TCP4\\AppData\\Roaming\\npm\\no
-cli.js" "install" "-g" "strongloop"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\TCP4\npm-debug.log
npm ERR! code 1


node 6.7.0
npm 3.10.8
windows 10 x64

**Comment by tamitutor** [comment] 2016-10-05 20:10
+1  Same as @rikantro...starting today.

**Comment by tamitutor** [comment] 2016-10-05 20:14
FWIW: If I downgrade to node@6.6.0 and keep npm@3.10.0 I do not see this problem any more.

**Comment by rikantro** [comment] 2016-10-05 23:07
Actually, I downgrade as @tamitutor  said, but appears the same error

**Comment by superkhau** [comment] 2016-10-06 07:42
Please comment on the open issue at https://github.com/strongloop/loopback/issues/2714
