### ISSUE TITLE
Model property typed object validation

### ISSUE THREAD

**Issue by jsheely** [strongloop/loopback#3297] opened 2017-03-20 20:43 UTC
Model properties that are a typed objects with validations do not fire validation.

Take these models
```
// Product
{
    "name": "product",
    "properties": {
        "name": {
            "type":"string",
            "required": true
        },
        "part": {
            "type":"part",
            "required": true
        }
    }
}
// Part
{
    "name":"part",
    "properties": {
        "price": {
            "type": "number",
            "required": true
        }
    }
}
```

```
(POST) /api/products
{
    "name":"Hello",
    "part": {
    }
}
```

I would expect to be given a 422 error stating that price is required on ```part.price```

**Comment by padelagani** [comment] 2017-03-21 07:37
@jsheely Loopback is not supporting nested validation. I am also facing the same issue.

**Comment by bajtos** [comment] 2017-03-21 15:21
Exactly. I am closing this issue as a duplicate of #300

**Closed by bajtos** 2017-03-21 15:21 UTC

**Comment by mbana** [comment] 2017-05-15 22:24
I'm also suprised this doesn't work.
If you want I'd be willing to make some changes to do nested validation...
I presume a lot of people are having to hardcode - we do.
If it is planned, do you have an ETA?

Let me know, either way.

**Comment by bajtos** [comment] 2017-05-22 11:55
@mbana 

> If you want I'd be willing to make some changes to do nested validation...
> I presume a lot of people are having to hardcode - we do.
> If it is planned, do you have an ETA?

We don't have any plans to fix this issue in the near future. A contribution will be welcome!

Let's move further discussions to #300 please.
