### ISSUE TITLE
ID's being converted to scientific notation

### ISSUE THREAD

**Issue by GlennMurphy** [strongloop/loopback#1748] opened 2015-10-20 15:05 UTC
As mongo's generated ID's get larger loopback seems to convert mongo's auto generated ID's to scientific notation integers instead of keeping them as strings.

For instance. I have a document with the auto generated ID "562547717371313000366169"

If I request document via the endpoint:

/documents/562547717371313000366169

Loopback returns that it can not find the model. I hooked this call with the 'access' hook and logged the where query. 

query: 
   { 
where: { id: 5.62547717371313e+23 },
     limit: 1,
     offset: 0,
     skip: 0,
}

I can get around this by querying documents with the following URL:

/documents?filter={"where":{"id":"562547717371313000366169"}}

But now I can't use any of the generated endpoints for the item.

**Comment by superkhau** [comment] 2015-10-21 23:38
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Amir-61** [comment] 2015-12-16 23:51
Hey @GlennMurphy 

You are right if you are using `loopbacl-connector-mongodb` the IDs get coneverted to scientific notation integers; but in terms of the problem you encountered, could you please provide a sample repo using [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox), so then we can see what is the problem in your example repo...

Thanks so much!

**Comment by Amir-61** [comment] 2015-12-22 16:01
@GlennMurphy Any update on this?

**Comment by ryankennedyio** [comment] 2016-07-09 03:16
@Amir-61 We've just run into this issue too. I have about 30 models in my load testing account that now cannot be accessed nor deleted.

A sample repo shouldn't be needed for this issue -- fairly obvious as to the cause and solution, no ?

**Comment by superkhau** [comment] 2016-07-11 16:06
@ryankennedyio Would you like to submit a PR with the fix?

**Comment by GlennMurphy** [comment] 2016-07-26 10:31
Sorry, I've been extremely busy and haven't gotten around to replying here. I have solved this in my own project. Will submit a fix here shortly.

**Comment by ryankennedyio** [comment] 2016-07-26 11:48
Awesome @GlennMurphy 

I had a team member look into it, but it seems like there's a few core Loopback packages where the change might need to be submitted. @diesal11 any findings?

**Comment by diesal11** [comment] 2016-07-27 03:19
I did some digging in attempt to find a simple-ish solution that I could PR. But the bug pops up in a few places. So here's what i found:

I've created an [example repo](https://github.com/diesal11/loopback-sandbox) so you can follow along, instructions are in the readme.

To cut a long story short, all PersistedModel endpoints that accept an `id` argument have their type set to `'any'`. This means that whenever the given ID is a numeric string it gets converted/coerced into a JS number and our Scientific Notation bug comes up. So this is a [loopback](https://github.com/strongloop/loopback) package issue in my opinion.

A simple fix I found for this is to change the`ID` arg types to `String`. in [PersistedModel.js](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L689) Although i'm not sure what implications that might have on other connectors that only have numeric IDs?

However, this still leaves a bug where the id is coerced into a number when it is part of a filter on `find/fineOne` and any relevant endpoints. Im not 100% sure how to tackle this one, nor have i had the time unfortunately. I believe the issue would need to be solved in [strong-remoting](https://github.com/strongloop/strong-remoting) though, as any number types large enough will have the same bug. Which is more of a overall Javascript quirk.

Also worth noting that this bug will only happen once a DB/Connector generates an ID that is over 20 chars and only numbers.

**Comment by ryankennedyio** [comment] 2016-08-11 00:45
@Amir-61 @superkhau Any news?

Failing that, @GlennMurphy what was your solution?

**Comment by superkhau** [comment] 2016-08-11 01:01
@ryankennedyio Sorry for the late response, unfortunately I have not had time to look into it. @0candy Can you try to reproduce this and escalate it to a bug after confirmation with the sample repo provided by @diesal11? This will probably be a major issue once you confirm it.

**Comment by 0candy** [comment] 2016-08-11 15:10
Confirmed the bug with the sample repro provided.

**Comment by bajtos** [comment] 2016-09-15 14:45
This should be fixed by https://github.com/strongloop/strong-remoting/pull/343 in LoopBack 3.0 (alpha).

@0candy @superkhau could you please verify?

**Comment by superkhau** [comment] 2016-09-15 20:37
@0candy Confirm please? I remember talking to you about this.

**Comment by 0candy** [comment] 2016-09-15 22:55
Verified that it works with LB 3.0 (alpha). Closing issue.

**Closed by 0candy** 2016-09-15 22:55 UTC
Labels: #verify, bug, major
