### ISSUE TITLE
userInstance.createAccessToken not working properly

### ISSUE THREAD

**Issue by Ahmedkholaif** [strongloop/loopback#4271] opened 2019-10-22 09:18 UTC
## Steps to reproduce
 const tokenData = {
      ttl: 24 * 60 * 60,
      scopes: ['reset-password'],
    };
    const token  = await userInstance.createAccessToken(tokenData); // not working
  const  token1  = await userInstance.createAccessToken(tokenData,true); //  working
  const token2 = await userInstance.accessTokens.create(tokenData); // working

## Current Behavior
neither TTL or scopes are set
https://apidocs.strongloop.com/loopback/?_ga=2.22081534.45609913.1571482863-1905847376.1567583967#user-prototype-createaccesstoken

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by deepakrkris** [comment] 2019-10-24 22:29
duplicate of https://github.com/strongloop/loopback/issues/4271

**Closed by deepakrkris** 2019-10-24 22:29 UTC
Labels: bug
