### ISSUE TITLE
Where to place images and other components folder in loopback?

### ISSUE THREAD

**Issue by eramsa** [strongloop/loopback#3727] opened 2017-12-10 05:20 UTC
I want to add blog images and documents specific folder and get access to files in project, where should i make this folders and how can access in front end? I've tested images folder on common, server and project root folder but I couldn't access by something like : `http://localhost:3000/logo.jpg `or `http://localhost:3000/images/logo.jpg`

**Comment by jannyHou** [comment] 2017-12-11 01:21
Hi @eramsa LoopBack has several ways for static file support, hope these tutorials can help you:
- preconfigured with EJS out of box: https://loopback.io/doc/en/lb2/Tutorial-access-control.html#configure-server-side-views

- add static web page by defining static middleware: https://loopback.io/doc/en/lb2/Add-a-static-web-page.html 

- front-end framework SDK: https://loopback.io/doc/en/lb2/AngularJS-JavaScript-SDK.html

**Comment by eramsa** [comment] 2017-12-11 05:40
Great thanks @jannyHou, I got help to solve it by using `loopback-component-storage` i will try those solutions you suggested.

Thanks for your guiding.

**Comment by jannyHou** [comment] 2017-12-13 17:17
@eramsa You're welcome, glad to hear that you figure it out :) I am closing this issue since the problem is solved, feel free to reopen it if you still have questions.

**Closed by jannyHou** 2017-12-13 17:17 UTC
