### ISSUE TITLE
Extend Role and RoleMapping Models

### ISSUE THREAD

**Issue by vshgemini** [strongloop/loopback#2154] opened 2016-03-17 19:34 UTC
Hi

Using loopback CLI capability, I created two models 'role' and 'roleMapping' with their base class pointed to loopback built-in models Role and RoleMapping respectively. Added ACL to 'role' model programatically as follows :
               var Role = app.models.role;
               var RoleMapping = app.models.roleMapping;
               var aclToAdd = {};
                aclToAdd.accessType = "*";
                aclToAdd.principalId = "$everyone";
                aclToAdd.principalType = "ROLE";
                aclToAdd.permission = "DENY";
Role.settings.acls.push(aclToAdd);

created a role 'superadmin' and principals subsequently : 
Role.create({
      name: 'superadmin'
    }, function(err, myrole) {
      if (err) throw err;

      console.log('Created role:', myrole);

      //make bob an admin
      myrole.principals.create({
        principalType: RoleMapping.USER,
        principalId: users[0].id
      }, function(err, principal) {
        if (err) throw err;

        console.log('Created principal:', principal);

  
aclToAdd = {};
                aclToAdd.accessType = "READ";
                aclToAdd.principalId = "superadmin";
                aclToAdd.principalType = "ROLE";
                aclToAdd.permission = "ALLOW";
Role.settings.acls.push(aclToAdd);
 
      });
    });

**getting error that myrole.principals is undefined and cannot invoke create on it..**

role.json
{
  "name": "role",
  "base": "Role",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

role-mapping.json
{
  "name": "roleMapping",
  "base": "RoleMapping",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

why is myrole.principals undefined even when the base class of model 'role' is the loopback built-in model 'Role' ? Been stuck with this problem for hours .. :(

Thanks

**Comment by richardpringle** [comment] 2016-03-18 15:45
I don't think that relations get extended, just the properties and methods. 
Checkout the two JSON files for the built-in models:
https://github.com/strongloop/loopback/blob/master/common/models/role.json
https://github.com/strongloop/loopback/blob/master/common/models/role-mapping.json

**Comment by kwuite** [comment] 2016-10-05 09:52
+1 I have the exact same problem while generating a memberRole and memberRoleMapping model. I am unable to invoke the create method on the role object I get from :
```javascript
memberRole.create({
                name: 'admin'
            }, function(err, role) {
                if (err) throw err;

                console.log('Created role:', role);

                role.principals.create({ // TypeError: Cannot read property 'create' of undefined
```

**Comment by kwuite** [comment] 2016-10-05 10:02
Ok, well the solution was op course in front of my eyes, thank you @richardpringle. I created the relations in the extended role and mapping json model files and the problem is solved.

**Comment by richardpringle** [comment] 2016-10-05 13:57
@kwuite haha glad to have helped!

Closing the issue, please re-open if it persists.

**Closed by richardpringle** 2016-10-05 13:57 UTC
Labels: triage, waiting

**Comment by louisl** [comment] 2016-12-02 10:35
@richardpringle I'm having this problem too but I'm using built in models. It appears the guys above solved it basically by redefining the models with extended models therefore creating their own. I've tried getting the Role by id too as below. This is in an angular controller as part of a role manager I need to build.

Regards.

```
    function createTestRole() {
      Role.create({
        name: 'superUser'
      },
      function(role) {
        console.log('role', role);
        Role.findById(
          {
            id: role.id
          },
          function(res) {
            console.log('res', res);
            // Make User id 1 a superUser
            res.principals.create({ //TypeError: Cannot read property 'create' of undefined
              principalType: RoleMapping.USER,
              principalId: 1
            }, function(principal) {
              console.log('principal', principal);
            }, function(err) {
              console.log('error1', err);
            });
          },
          function(err) {
            console.log('error2', err);
          });
      },
      function(err) {
        console.log('error3', err);
      });
    }
```

**Comment by richardpringle** [comment] 2016-12-07 14:02
Hey @louisl, I'm not actually working on LoopBack anymore but I could still try to help. 

Are you just trying to create a role instance? Extending the Role model is a little more complicated.

**Comment by louisl** [comment] 2016-12-07 22:26
@richardpringle Apologies, I was unaware you've moved on. Thank you for your reply. Yes I'm just trying to create roles in the database for persistent use, Super User, Admin, Sales Team etc. But as explained above it's failing with ```TypeError: Cannot read property 'create' of undefined```

**Comment by richardpringle** [comment] 2016-12-08 14:46
checkout https://github.com/strongloop/loopback-example-access-control and https://loopback.io/doc/en/lb2/Defining-and-using-roles.html. If you've seen those already, my apologies. 

I think the reason that you might be seeing that error is because of where you're calling `Role.create`. I'm guessing that the script is running before all the models are finished initializing.

**Comment by mihaiserban** [comment] 2017-05-26 12:44
for some reason i needed to add both models in mode-config.js

  "RoleMapping": {
    "dataSource": "accountDS",
    "public": false
  },
  "roleMapping": {
    "dataSource": "accountDS",
    "public": false
  },
