### ISSUE TITLE
Error: Cannot GET /{}

### ISSUE THREAD

**Issue by JoeShi** [strongloop/loopback#2347] opened 2016-05-17 13:40 UTC
My loopback server sometimes emit the following error. From the error message, it says cannot `GET /{} error `. 

What is the meaning of `GET /{}`, is it same as 'GET /'?  There is something in my client root, so it should not return 404.

```
2016-05-17T12:59:50.998Z pid:5742 worker:14 Error: Cannot GET /{}
2016-05-17T12:59:50.998Z pid:5742 worker:14     at raiseUrlNotFoundError (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/loopback/server/middleware/url-not-found.js:15:17)
2016-05-17T12:59:50.998Z pid:5742 worker:14     at Layer.handle [as handle_request] (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/express/lib/router/layer.js:95:5)
2016-05-17T12:59:50.998Z pid:5742 worker:14     at trim_prefix (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/express/lib/router/index.js:312:13)
2016-05-17T12:59:50.998Z pid:5742 worker:14     at /var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/express/lib/router/index.js:280:7
2016-05-17T12:59:50.999Z pid:5742 worker:14     at Function.process_params (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/express/lib/router/index.js:330:12)
2016-05-17T12:59:50.999Z pid:5742 worker:14     at next (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/express/lib/router/index.js:271:10)
2016-05-17T12:59:50.999Z pid:5742 worker:14     at SendStream.error (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/serve-static/index.js:120:7)
2016-05-17T12:59:50.999Z pid:5742 worker:14     at emitOne (events.js:77:13)
2016-05-17T12:59:50.999Z pid:5742 worker:14     at SendStream.emit (events.js:169:7)
2016-05-17T12:59:50.999Z pid:5742 worker:14     at SendStream.error (/var/lib/strong-pm/svc/3/work/d1d4b05e0ed7989b1d97e26f45fefaea8fa04a09.1463481685858/node_modules/send/index.js:245:17)
```

**Comment by gunjpan** [comment] 2016-05-17 15:30
@JoeShi : Hey Joe, could you please post your `middleware.json` file or if possible, a sample repo would be the best to understand what's causing the error with your application. Thanks.

**Comment by JoeShi** [comment] 2016-05-17 15:49
Sure. @gunjpan  `middleware.json` & `middleware.production.json` are same and given in the following. My server is running `strong-pm`. with `NODE_ENV=production`.

```
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {},
    "cors": {
      "params": {
        "origin": true,
        "credentials": true,
        "maxAge": 86400
      }
    }
  },
  "session": {},
  "auth": {},
  "parse": {},
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
  "files": {
    "loopback#static": {
      "params": "$!../client"
    }
  },
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "loopback#errorHandler": {}
  }
}
```

**Comment by JoeShi** [comment] 2016-05-17 15:58
Hello, @gunjpan This is the [repo](https://github.com/JoeShi/Wechat). This error occurs quite often, but from the error message, I cannot figure out the reason.    Thank you for your help.

**Comment by gunjpan** [comment] 2016-05-17 16:00
@JoeShi : Looking into it. Thanks for the repo, makes my life easier! :)

**Comment by gunjpan** [comment] 2016-05-17 18:52
@JoeShi : Hey Joe, I cloned your repo and tried to reproduce the issue. I couldn't reach the error you were reporting. `strong-pm` seems to be working fine for me and was able to launch the app fine on my local machine.
Can you share the steps to reproduce the error you're getting? or any specific event where the error gets triggered.

**Comment by JoeShi** [comment] 2016-05-18 01:07
Hey @gunjpan, I am also trying to reproduce the error, but never get reproduced when I develop on my machine. It happens occasionally on the strong-pm server, I did not find any steps of reproducing it even after deploy it. 

But it do exists in the log file when I `log-dump` the service. I am very curious about what is `GET /{}`.

**Comment by gunjpan** [comment] 2016-05-18 14:14
@sam-github : Hey Sam, could you PTAL at this issue and provide your insight. Thanks.

**Comment by gunjpan** [comment] 2016-05-18 16:22
@JoeShi : this could be a route generated/accessed by angular?! try re-generating `lb-services.js`.
I'll close this issue now as we're unable to reproduce it. Please feel free to reopen if you're able to reproduce it and mention me, will be happy to help. Thank you :)

**Closed by gunjpan** 2016-05-18 16:22 UTC
Labels: triage, waiting

**Comment by hans118** [comment] 2017-05-12 09:40
Hi  @gunjpan, I can see this error.
Loopback
404 Error: Cannot GET /v1/Applications
   at raiseUrlNotFoundError (/home/augustins/backend/node_modules/loopback/server/middleware/url-not-found.js:20:17)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/home/augustins/backend/node_modules/express/lib/router/index.js:335:12)
   at next (/home/augustins/backend/node_modules/express/lib/router/index.js:275:10)
   at compression (/home/augustins/backend/node_modules/compression/index.js:219:5)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/home/augustins/backend/node_modules/express/lib/router/index.js:335:12)
   at next (/home/augustins/backend/node_modules/express/lib/router/index.js:275:10)
   at favicon (/home/augustins/backend/node_modules/serve-favicon/index.js:63:7)
   at Layer.handle [as handle_request] (/home/augustins/backend/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/augustins/backend/node_modules/express/lib/router/index.js:317:13)
   at /home/augustins/backend/node_modules/express/lib/router/index.js:284:7

This app was deployed into nginx.
How to fix it?

**Comment by askmsd07** [comment] 2018-05-24 06:13
Hi @gunjpan 
I am also facing this issue in server. 

`Unhandled error for request POST /: Error: Cannot POST /
    at raiseUrlNotFoundError (/var/www/html/purpleknot_backend/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/var/www/html/purpleknot_backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:275:10)
    at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:635:15
    at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/html/purpleknot_backend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:275:10)
    at /var/www/html/purpleknot_backend/node_modules/body-parser/lib/read.js:130:5`

How to fix this?

**Comment by hasnainhaider2663** [comment] 2019-05-03 10:39
Dudes, any resolution to this please?

**Comment by ericalves** [comment] 2019-07-01 14:04
Hi guys! I have the same problem. Sometimes '/' it's ok.. returns uptume.. and suddenly it's returns 404..

**Comment by viotile** [comment] 2021-06-09 06:31
> Hi @gunjpan
> I am also facing this issue in server.
> 
> `Unhandled error for request POST /: Error: Cannot POST / at raiseUrlNotFoundError (/var/www/html/purpleknot_backend/node_modules/loopback/server/middleware/url-not-found.js:21:17) at Layer.handle [as handle_request] (/var/www/html/purpleknot_backend/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:317:13) at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:335:12) at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:275:10) at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:635:15 at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:260:14) at Function.handle (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:174:3) at router (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/var/www/html/purpleknot_backend/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:317:13) at /var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:335:12) at next (/var/www/html/purpleknot_backend/node_modules/express/lib/router/index.js:275:10) at /var/www/html/purpleknot_backend/node_modules/body-parser/lib/read.js:130:5`
> 
> How to fix this?

Have you found any solution for this?
