### ISSUE TITLE
Ability to query nested documents/objects/arrays 

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#953] opened 2014-12-26 10:42 UTC
For example right now there doesn't seem to be an easy way to have equivalent of this mongodb query with loopback where filters:

```
{
    people : {
        $elemMatch : {
            id : ObjectId('546047f6118d30f014000001'),
            tags : { $in : ['alive'], $ne : 'rich' }
        }
    }
}
```

Do note that poeple is an array of objects that contains, tags which is an array of strings.

Note that this has been asked before on [mailing list](https://groups.google.com/forum/#!msg/loopbackjs/8c8kw8EMiPU/yev3lsmrTFUJ) and on [stackoverflow](http://stackoverflow.com/q/27251887/774086).

**Comment by fabien** [comment] 2015-01-08 14:39
With the PR in place, the above query should work as follows:

```json
{
    people : {
        elemMatch : {
            id : '546047f6118d30f014000001',
            tags : { in : ['alive'], ne : 'rich' }
        }
    }
}
```

It might have worked before, but not if you defined the people property as:

`people: { type: [Person] }`

**Comment by bajtos** [comment] 2015-02-23 18:27
This is possibly a duplicate of #517.

**Comment by AlmaasAre** [comment] 2015-08-10 19:02
+1 for support in the memory-connector aswell!

**Comment by kennethlynne** [comment] 2015-08-10 19:16
Yeah what @AlmaasAre said! 

For testing purposes

**Comment by eugenehp** [comment] 2015-10-14 16:06
hey @bajtos can you advise what is the best place in source code to start tickling this feature?
I saw 6+ months of support at https://github.com/strongloop/loopback/issues/517 and looks like I'm going to need this in couple of my productions...

so what would be your advise to implement this so it might get a chance to be merged to `master` branch.

Thanks. :+1:

**Comment by bajtos** [comment] 2015-10-15 06:32
@eugenehp 
> can you advise what is the best place in source code to start tickling this feature?
I saw 6+ months of support at #517 and looks like I'm going to need this in couple of my productions...

> so what would be your advise to implement this so it might get a chance to be merged to master branch

@raymondfeng @fabien do you have any thoughts on how to implement support for querying nested documents/objects/arrays? I am not familiar enough with this part of loopback to give a good advice.

**Comment by eugenehp** [comment] 2015-10-16 14:30
thanks @bajtos 
I'm particularly going to be interested to implement solution on top of the mongodb connector first, and then possibly MySQL.

Since you guys @raymondfeng @fabien have more experience with your code, please advise on the best way to pursue this.

Thank you.

Have a nice weekend ahead!

**Comment by pthieu** [comment] 2016-11-03 21:41
@eugenehp: Have you made any progress on this: https://github.com/strongloop/loopback-datasource-juggler/pull/1083/files allows this functionality but only for arrays.

**Comment by loay** [comment] 2017-03-14 16:12
@eugenehp Nested query is currently working with Mongodb. Please have a look at it. 
I am closing this issue in favor of https://github.com/strongloop/loopback/issues/517

**Closed by loay** 2017-03-14 16:12 UTC
Labels: feature
