### ISSUE TITLE
The server crashes because a specific filter [CRITICAL]

### ISSUE THREAD

**Issue by TwistedLogic** [strongloop/loopback#4028] opened 2018-10-15 10:09 UTC
I know you guys are really focused on Loopback v4 but the following bug in v3 is very disappointing. It's a critical issue, all servers now running are exposed and can be crashed by the first script kiddie. This is not acceptable. Please fix it as soon as possible. Thanks.

I've been using Loopback for the last two years in 3 different projects and I believe it's a great product but you should improve support, documentation, robustness, etc. I hope v4 will be a better product.

# Description/Steps to reproduce

The model `Login` has a hasMany relation to the model `Account`.

Calling the endpoint `/logins/{id}/accounts` and using the filter:

 `{"include": "accounts", "fields": ["accounts", "provider_name"]}`

does make the server crash.
Even if the filter parameter is wrong, the server SHOULD never crash.

# Expected result

The server SHOULD NOT crash.

# Additional information

```
TypeError: Cannot read property 'toString' of undefined
    at keyToString (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include_utils.js:69:48)
    at Object.set (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include_utils.js:75:13)
    at Object.buildOneToOneIdentityMapWithOrigKeys (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include_utils.js:26:11)
    at includeHasManySimple (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include.js:594:36)
    at processIncludeItem (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include.js:366:16)
    at /home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include.js:184:5
    at /home/ubuntu/api/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/home/ubuntu/api/node_modules/async/dist/async.js:1069:9)
    at eachOf (/home/ubuntu/api/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/home/ubuntu/api/node_modules/async/dist/async.js:3172:5)
    at Function.Inclusion.include (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/include.js:183:9)
    at /home/ubuntu/api/node_modules/loopback-connector/lib/sql.js:1449:44
    at /home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/observer.js:250:22
    at doNotify (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at MySQL.ObserverMixin._notifyBaseObservers (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at MySQL.ObserverMixin.notifyObserversOf (/home/ubuntu/api/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
```

**Comment by dhmlau** [comment] 2018-10-16 02:48
@strongloop/sq-lb-apex , looks like the error is coming from the juggler.  Could you please take a look? Thanks.

**Comment by bajtos** [comment] 2018-10-16 10:45
@TwistedLogic thank you for reporting this issue. I agree with you LoopBack should never crash the server and any errors should be reported gracefully (typically as an error response from the HTTP server).

Please create a small application reproducing the problem per our [Bug reporting](https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) instructions. It will save us time on guessing how exactly are your models and relations configured.

**Comment by TwistedLogic** [comment] 2018-10-16 14:48
@bajtos thank you.

Check this repository out: https://github.com/TwistedLogic/loopback-sandbox
You'll find the steps to reproduce the issue inside the README. Some additional info:

> Operating system version: macOS High Sierra Version 10.13.4
> Node.js version: v8.9.3
> All dependencies version are fixated inside the package.json

**Comment by bajtos** [comment] 2018-10-18 11:41
Thank you @TwistedLogic for the sample app, I am able to reproduce the problem on my machine now 👍 

@raymondfeng you are more familiar with juggler, relations and `nestRemoting` feature than I am, could you please take a look?

This view shows how the application was configured - notice there is no custom code besides database seeding:

https://github.com/strongloop/loopback-sandbox/compare/master...TwistedLogic:master

I find it worrisome that a LB app using the built-in features only can be crashed by a well-crafted request.

**Comment by bajtos** [comment] 2018-10-18 11:46
FYI, this simpler `filter` is crashing the server too:

```
{"include": "accounts", "fields": ["accounts"]}
```

**Comment by raymondfeng** [comment] 2018-10-18 17:33
@TwistedLogic Thank you for reporting it. A fix is ready for review - https://github.com/strongloop/loopback-datasource-juggler/pull/1642

**Comment by dhmlau** [comment] 2019-03-28 02:41
PR https://github.com/strongloop/loopback-datasource-juggler/pull/1642 has been merged.  Closing this issue as resolved.

**Closed by dhmlau** 2019-03-28 02:41 UTC
Labels: bug, major, p1
