### ISSUE TITLE
error parsing 'string' to 'number' when using 'application/json' to submit 'object' data

### ISSUE THREAD

**Issue by roytan883** [strongloop/loopback#2847] opened 2016-10-12 11:48 UTC
### Bug
- [x] Bug
### Description of bug

input arg with 'object' type error parse 'string' to 'number' when using 'application/json' to submmit data.**

### input:
```
{"jsonObj":{"string1":"123","string2":"s123"}}
```

### server:
```
//client use application/x-www-form-urlencoded input data:
//server got:
testjson jsonObj =  { string1: '123', string2: 's123' }

//client use application/json  input data:
//server got:
testjson jsonObj =  { string1: 123, string2: 's123' }
```
### Additional information (Node.js version, LoopBack version, etc)

nodejs 4.3.0 and 6.7.0
loopback@2.36.0

repo show this bug: [loopback-string-num-bug](https://github.com/roytan883/loopback-string-num-bug)

**Comment by loay** [comment] 2016-11-03 20:57
Hi @roytan883 
Can you please provide a sample repo so I can debug the issue?
Thanks.

**Comment by roytan883** [comment] 2016-11-04 05:03
@loay 
here is the repo:
[loopback-string-num-bug](https://github.com/roytan883/loopback-string-num-bug)

**Comment by roytan883** [comment] 2016-11-13 08:23
So it is a bug or not?

**Comment by roytan883** [comment] 2016-11-13 08:24
@loay @kjdelisle 
So it is a bug or not? Will it be fixed?

**Comment by kjdelisle** [comment] 2016-11-14 18:03
@roytan883 Sorry for the delayed reply! I've taken a look at your reproduction and I'm seeing the same thing, so I'll be marking this as a bug and taking a look. Thanks a ton for your report and for putting the effort into that reproduction. :D

**Comment by kjdelisle** [comment] 2016-11-14 18:08
reproduced on `loopback@2.36.0`

**Comment by kjdelisle** [comment] 2016-12-05 20:37
This issue has been fixed in the 3.0 release candidate, and because the fix was a large rewrite of the type coercion functionality, it will not be back-ported.

**Comment by roytan883** [comment] 2016-12-10 04:07
I think the bug is **fatal**.  
**application/json** is common way to input HTTP data.  
But so strange, no one report this bug before?
Why do you reopen it ? I havn't test it on 3.0, so I don't known if it was fixed.

**Also i think it should be fixed in 2.x, if not, means we can't use 'application/json' in 2.x** ? 

But i have test it with pure **Express** and **body-parser**, string and number are parsed correctly.

**Comment by kjdelisle** [comment] 2017-01-13 19:56
Sorry about the issue reopening, it was a side-effect of our ZenHub tooling and some experimentation with workflow. Unfortunately, the amount of work required to backport the fix from 3.x to 2.x is extreme. I do agree in principle that it should be fixed, and I sympathize, but we won't be backporting this fix.

**Closed by kjdelisle** 2017-01-13 19:56 UTC
Labels: bug, team-apex
