### ISSUE TITLE
userId NaN

### ISSUE THREAD

**Issue by AvivLander** [strongloop/loopback#1023] opened 2015-01-19 17:37 UTC
I'm getting an error of userId: NaN using the standard "getting started" project with no models -- just User. 

Strongloop v2.10.2 via NPM
Using a JugglingDB connector

The issue seems directly related to a previous issue: https://github.com/strongloop/loopback/issues/353

**Comment by superkhau** [comment] 2015-01-19 17:49
What step of getting started did you get to?

**Comment by AvivLander** [comment] 2015-01-19 18:06
I made sure that I had the latest version of StrongLoop, but here are the steps:


npm install -g strongloop
slc loopback
(Default answers)

Updated datasources.json to:

{
  "db": {
    "host": "localhost",
    "port": 28015,
    "database": "test",
    "name": "db",
    "defaultForType": "db",
    "connector": "jugglingdb-rethink"
  }
}


Then I ran the server with: slc run

Standard stuff.


The jugglingdb connector worked with version one of loopback, but with version two the issue happens. The library fails, but if you check the reason of the failure, it's due to userId being set as NaN. This happens before the request hits the connector -- so I'm rather certain the issue it outside of the connector. Also, I see that there were previous talks about a like issue not so long ago.


Please let me know if I can provide any further information.

**Comment by bajtos** [comment] 2015-02-03 17:16
Based on my discussion with @altsang, I am assigning this issue to @superkhau to investigate and fix.

**Comment by superkhau** [comment] 2015-02-17 03:14
@AvivLander I was able to reproduce your issue and I'm assuming you see something like:

```
{
  id: ...
  ttl: 1209600,
  created: Mon Feb 16 2015 19:09:19 GMT-0800 (PST),
  userId: NaN
}
```

I'm not sure why the error is there yet, but I will continue to dig deeper.

**Comment by AvivLander** [comment] 2015-02-17 04:44
@superkhau this is the issue I was getting. If you need any more information or help, please ask, and I will do my best to do so.

**Comment by superkhau** [comment] 2015-02-17 22:38
@AvivLander spoke to @raymondfeng regarding the issue and we suggest you resolve it by modifying `rethink.js` in the `jugglingdb-rethink` module (`your-project/node_modules/juggling-rethink/rethink.js`):

```
...
RethinkDB.prototype.getDefaultIdType = function() {
  return String;
};

RethinkDB.prototype.connect = function(cb) {
    cb(); // connection pooling handles it
};
...
```

Let me know if that works for you.

**Comment by superkhau** [comment] 2015-02-19 19:13
@AvivLander Did you get any further on this?

**Comment by fuwaneko** [comment] 2015-02-20 16:14
@superkhau There is no getDefaultIdType in JugglingDB. I've tried to define type for ID same way it's done in MongoDB module. You can try latest [code](https://github.com/fuwaneko/jugglingdb-rethink/blob/master/rethink.js#L94) from master branch on GitHub, but I doubt it'll work. Never did for me, that's why I didn't push it to npm.

**Comment by raymondfeng** [comment] 2015-02-20 16:22
@fuwaneko Thank you for chiming in. `loopback-datasource-juggler` was initially forked from `jugglingdb` but it has been evolved for a long time. Most of the contracts for connector implementations are still the same, but LoopBack does introduce additional things.  `getDefaultIdType` if one of the new things and it tells LoopBack what's the default type for `id`. 

Would you like to port `jugglingdb-rethink` to `loopback-connector-rethinkdb`? The key is to run tests against the common ones from `loopback-datasource-juggler`.

**Comment by fuwaneko** [comment] 2015-02-20 18:15
@raymondfeng Yeah, I try to pass all the tests and it seems there's a problem with [findByIds](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/basic-querying.test.js#L83) and [sorting](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L648). In this test you pass numbers but ids in Rethink are UUIDs (represented by strings), so it won't sort properly. Sorter needs to use getDefaultTypeId to convert ids I think.

**Comment by raymondfeng** [comment] 2015-02-20 18:17
Can you provide a link to your repo that runs tests with juggler? We can investigate a bit.

**Comment by fuwaneko** [comment] 2015-02-20 18:23
@raymondfeng https://github.com/fuwaneko/loopback-connector-rethinkdb sure, I've just started though.

**Comment by superkhau** [comment] 2015-05-12 08:01
@fuwaneko Did you get any farther on the test repo?

**Comment by fuwaneko** [comment] 2015-05-12 11:48
@superkhau Although I can't pass all tests as many of them seems to be made with MongoDB behaviour in mind (e.g. {gt: null} filter will be ignored by RethinkDB), the issue described here is fixed in master in loopback-connector-rethinkdb.

**Comment by superkhau** [comment] 2015-05-12 16:43
Sounds good, then I will close this issue as it is resolved in fuwaneko/loopback-connector-rethinkdb

@AvivLander Please use loopback-connector-rethinkdb and let me know if you run into any issues. I will reopen this issue if you are still having trouble.

**Closed by superkhau** 2015-05-12 16:43 UTC
Labels: #wip, triage, waiting
