### ISSUE TITLE
Logout fails for model based on User (other than model called "user")

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#398] opened 2014-07-24 09:32 UTC
If you create a model, say Appuser, based on User, when you call Appuser.logout, it fails with:

```
.../server/node_modules/loopback/lib/models/user.js:232
  this.relations.accessTokens.modelTo.findById(tokenId, function (err, accessT
                             ^
TypeError: Cannot read property 'modelTo' of undefined
```

**Comment by transedward** [comment] 2015-05-25 09:29
this issue still exist, the new user model based on user will not inherit the relation
add relation by hand can bypass this issue

**Comment by Silvercast** [comment] 2015-07-02 18:50
I'm suffering the same issue. I have `Appuser` model which has a `hasMany` relation to `accessTokens` model. And it doesn't work , giving error 500 when logout :(

**Comment by raymondfeng** [comment] 2015-07-02 18:52
@Silvercast Did you pass in `access_token` during login?

**Comment by Silvercast** [comment] 2015-07-02 19:00
Thanks. I managed to fix it by manually removing the `hasMany` relation in my custom `Appuser` model. Work as expected.
I was confused by comments above.

**Comment by sn-satyendra** [comment] 2016-02-02 09:16
Is this issue fixed. I am still getting the 500 error when I try to logout the user with access_token. I have a `appuser` which is extended from `user`. `appuser` has a `hasMany` relation to `accessToken`. 
@Silvercast I tried removing the `hasMany` relation in `appuser` but then I got the below issue:

TypeError: Cannot read property 'create' of undefined
    at ModelConstructor.User.createAccessToken (D:\zv\node_modules\loopback\common\models\user.js:100: 22)
    at D:\zv\node_modules\loopback\common\models\user.js:256: 22
    at D:\zv\node_modules\loopback\common\models\user.js:312: 9
    at D:\zv\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:261: 17
    at D:\zv\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:1198: 21
    at Immediate.next (D:\zv\node_modules\loopback\node_modules\bcryptjs\dist\bcrypt.js:1078: 21)
    at Immediate._onImmediate (D:\zv\node_modules\loopback\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188: 31)
    at processImmediate [as _immediateCallback] (timers.js:358: 17)

**Comment by superkhau** [comment] 2016-04-06 21:08
Are you guys still running into this issue? I'm closing it for now, ping and I will reopen.

**Comment by mcitdev** [comment] 2018-06-06 18:48
same here, 

```
TypeError: Cannot read property 'modelTo' of undefined
    at node_modules/loopback/common/models/user.js:350:58

// user.js:350:58
User.observe('before delete', function(ctx, next) {
    var AccessToken = ctx.Model.relations.accessTokens.modelTo;
    var pkName = ctx.Model.definition.idName() || 'id';
    ctx.Model.find({where: ctx.where, fields: [pkName]}, function(err, list) {
      if (err) return next(err);

      var ids = list.map(function(u) { return u[pkName]; });
      ctx.where = {};
      ctx.where[pkName] = {inq: ids};

      AccessToken.destroyAll({userId: {inq: ids}}, next);
    });
  });
```

I managed to fix it by manually wrapping the content in an "if() else" statement like so : 

```
User.observe('before delete', function(ctx, next) {

   if(ctx.Model.relations.accessTokens !== undefined) {

      var AccessToken = ctx.Model.relations.accessTokens.modelTo;
      var pkName = ctx.Model.definition.idName() || 'id';
      ctx.Model.find({where: ctx.where, fields: [pkName]}, function(err, list) {
        if (err) return next(err);
        var ids = list.map(function(u) { return u[pkName]; });
        ctx.where = {};
        ctx.where[pkName] = {inq: ids};
        AccessToken.destroyAll({userId: {inq: ids}}, next);
      });

   }
   else
      next();
  });

```
Hope this will be fixed soon, because the work arround listed in the comments above does not work for me ! Especially that the relation "accessTokens" already exists on User model, and it should be inherited by his children !!! things that seems not heppens here ??????

**Comment by bajtos** [comment] 2018-06-07 11:16
@mcitdev thank you for the update. If I understand your situation correctly, you have a custom `User` model that does not have any `accessTokens` relation configured, is that correct? That sounds more like a configuration problem of the application than a bug in the framework. We are trying to detect that at runtime and print a warning. See also our documentation on how to correctly setup custom User and/or AccessToken models: http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#preparing-access-control-models

Please pardon me if I have misunderstood your scenario, it's difficult to build a good understanding only from the code snippet you have provided.

To move this issue forward, I need either a small app reproducing the issue (see our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)) or if you are feeling brave then you can open a pull request to fix the issue and write unit-test reproducing the problem in that pull request.

**Comment by mcitdev** [comment] 2018-06-09 19:08
The situation is that I've created a custom user based on the User model, just for the test, and I didn't use the acl, so I can access the data in the database without needing to login. So, yes the user does not have any accessTokens. So when I try to delete some entries from the database, the hooks above `User.observe('before delete', function(ctx, next) ` search for accessTokens that actually not exists, and the error is thrown.

Tha's why I use the workaround above.
Maybe I needed just to create a custom user based on a persistedModel, because the User model forces you to use acl and to login to get the accessToken.

But I agree that a warning in this situation would be very nice than crashing the app, especially that I intentionally choose to not use acl.

**Comment by bajtos** [comment] 2018-06-15 13:28
> The situation is that I've created a custom user based on the User model, just for the test, and I didn't use the acl, so I can access the data in the database without needing to login. So, yes the user does not have any accessTokens. So when I try to delete some entries from the database, the hooks above User.observe('before delete', function(ctx, next) search for accessTokens that actually not exists, and the error is thrown.

Thank you for the explanation, it makes sense to me now.

Would you like to submit a pull request to fix the problem?

```js
User.observe('before delete', function(ctx, next) {
  // TODO for you: add comment explaining the use case
  if(!ctx.Model.relations.accessTokens) return next();

  var AccessToken = ctx.Model.relations.accessTokens.modelTo;
  // etc.
  // It's important to preserve the original implementation unchanged
});
```

**Comment by mcitdev** [comment] 2018-06-16 16:00
Ok, done #3917

**Comment by dhmlau** [comment] 2019-07-23 19:15
Resolved via PR https://github.com/strongloop/loopback/pull/3917.

**Closed by dhmlau** 2019-07-23 19:15 UTC
Labels: bug, good first issue, help wanted
