### ISSUE TITLE
TypeError during slc loopback:model

### ISSUE THREAD

**Issue by ianseyer** [strongloop/loopback#1579] opened 2015-08-08 21:17 UTC
Attempting to add a model to my LB application.

Here is where I get:

```
MacBook-Air:users ianseyer$ slc loopback:model cause
? Enter the model name: cause
? Select the data-source to attach cause to: postgres (postgresql)


/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'type' of undefined
    at /Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/objects/choices.js:27:13
    at arrayMap (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/lodash/index.js:1431:25)
    at Function.map (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/lodash/index.js:6693:14)
    at new Choices (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/objects/choices.js:26:20)
    at Prompt (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/base.js:52:24)
    at new Prompt (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/prompts/list.js:25:8)
    at PromptUI.fetchAnswer (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:92:16)
    at /Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:4599:20
    at tryCatcher (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/Users/ianseyer/.nvm/versions/node/v0.12.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:4806:43)
```

**Comment by superkhau** [comment] 2015-08-08 21:25
Can you try on node v0.10.x? Might be because you're using node v0.12.x.

**Comment by ianseyer** [comment] 2015-08-08 21:26
I would like to stay on v0.12.x.

Should that not be considered a bug in the application?

**Comment by superkhau** [comment] 2015-08-08 21:42
We do recommend using the latest stable versions of Node (see http://docs.strongloop.com/display/public/NODE/Frequently+asked+questions#Frequentlyaskedquestions-WhatversionofNodedoyousupport?), but I just wanted to see if was a difference between versions. That said, I need the steps to reproduce this bug before continuing. Can you try scaffolding a new app and see if you get an error still?

```
slc loopback test
cd test
slc loopback:model Todo
```

**Comment by ianseyer** [comment] 2015-08-08 21:46
No error on the new app, which leads me to believe it has something to do
with my db connector...

**Comment by superkhau** [comment] 2015-08-09 03:35
Now we're talking. ;) Which connector are you using?

**Comment by ianseyer** [comment] 2015-08-09 03:44
Postgres

**Comment by superkhau** [comment] 2015-08-11 01:31
Can you try with a fresh project using a new db?

```
slc loopback test
cd test
// add your db configs to `server/datasource.js`
slc loopback:model Todo // use your db config for the model datasource
```

**Comment by ernie58** [comment] 2015-08-13 11:13
Having the same issue.
Node version is v0.10.38

Any news on this?

**Comment by superkhau** [comment] 2015-08-13 21:46
No news yet, needs to be brought up during sprint planning. Can one of you guys provide the steps to reproduce please? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment] 2015-10-01 17:10
@ianseyer @ernie58 Are you guys still running into this issue?

**Comment by ernie58** [comment] 2015-10-08 09:39
@superkhau Sorry for my late response, still having this issue on my main project, meanwhile I use 0.12.7

I tried a new project, copied my datasources, one at a time, couldn't reproduce this issue
I also tried different environments (datasources.staging.json) and added the exact same datasources one at a time, couldn't reproduce either

**Comment by superkhau** [comment] 2015-10-14 06:37
@ernie58 That means it has something to do with the specifics of your project. I will close this for now until you can reproduce it. Not much we can do without the STR. Feel free to message again when you figure out your end.

**Closed by superkhau** 2015-10-14 06:37 UTC
Labels: triage
