### ISSUE TITLE
slc loopback:relation is broken

### ISSUE THREAD

**Issue by Industrial** [strongloop/loopback#2848] opened 2016-10-12 14:46 UTC
Hi!

There are no choices shown and when I press arrow down and enter I get the stack trace.

https://gist.github.com/Industrial/49cf6da2be8ecc4d65b2e31f280fc10f

**Comment by jannyHou** [comment] 2016-10-12 19:19
@Industrial I tried with the latest generator-loopback in npm, it works fine:
> generator-loopback@1.24.4


I saw your problem before but it is a very old bug we already fixed.


Could you give me the version of generator-loopback you are using?

**Comment by Industrial** [comment] 2016-10-12 20:56
Hi.

I've npm installed strongloop (-g) 6.0.3 and it uses 1.24.3 of generator-loopback

**Comment by jannyHou** [comment] 2016-10-12 21:09
@Industrial 1.24.3 should work well...Sometimes if you installed generator-loopback globally, it will not use the one inside strongloop but the global one, could you take a double check which generator-loopback is really invoked? And reinstall strongloop to see if the latest one fixes the bug.

If you are sure that 1.24.3 has the problem, please provide me the npm and node version you are using, I will try reproduce it on my local. Thanks!

**Comment by Industrial** [comment] 2016-10-12 21:16
I haven't installed generator-loopback separately.

Node: 6.7.0
NPM: 3.10.3

**Comment by jannyHou** [comment] 2016-10-14 20:13
@Industrial what's your OS? I tried with mac and node 6.8.0, it still works fine:

```
jannyhous-mbp:datatype jannyhou$ node -v
v6.8.0
jannyhous-mbp:datatype jannyhou$ npm -v
3.10.8
jannyhous-mbp:datatype jannyhou$ slc loopback:relation
? Select the model to create the relationship from: Test
? Relation type: has many
? Choose a model to create a relationship with: Note
? Enter the property name for the relation: notes
? Optionally enter a custom foreign key: 
? Require a through model? No
```

I don't think there is a big probability that the minor version of node and npm result in different behaviours..but maybe try the latest node 6.x

And also try reinstall strongloop too.

**Comment by jannyHou** [comment] 2016-11-04 20:31
still could not reproduce the issue and I didn't see other users report same ones..closing it here but will reopen it if others also run into same issues.

**Closed by jannyHou** 2016-11-04 20:31 UTC
Labels: major, triage, workspace-generator
