### ISSUE TITLE
Incorrect swagger definition for models with forceId:true

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2924] opened 2016-11-09 10:17 UTC
### Description of feature (or steps to reproduce if bug)

The swagger specification generated for LoopBack models with `forceId` set to `true` (the default in LoopBack 3.0) is incorrect. The model definition marks the `id` property as required, but the `create` operation is rejecting requests with `id` property set.

This causes problems in API Connect, where the sample request data generated by Editor contains `id` now.

### Expected result

The sample request generated by APIC Editor for `create` operation does not contain `id` property.

### Actual result (if bug)

The sample request generated by APIC Editor for `create` operation contains `id` property.

### Additional information (Node.js version, LoopBack version, etc)

 - loopback@3 
 - loopback-swagger@latest

The default value of `forceId` was changed to `true` in LoopBack 3.0 for security reasons, see https://github.com/strongloop/loopback-datasource-juggler/pull/982 and https://github.com/strongloop/loopback-datasource-juggler/issues/849

**Comment by bajtos** [comment] 2016-11-10 10:55
The petstore example shows the approach we can use too.

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-expanded.yaml

Check out their POST /addPet - it takes a body of type NewPet. GET /pet returns a type Pet, which is allOf NewPet, plus id.

**Comment by bajtos** [comment] 2016-11-15 13:17
Instead of hard-coding detection of `forceId`, we should come up with a property flag indicating whether a property may or may not be in `create` data. This flag then can be used e.g. for Cloudant's `_rev` field, see https://github.com/strongloop/loopback-connector-cloudant/issues/55

**Comment by ritch** [comment] 2016-12-15 22:16
This is not a blocker for 3.x because we can fix this in the swagger generator.

**Comment by bajtos** [comment] 2017-04-20 07:20
> Instead of hard-coding detection of `forceId`, we should come up with a property flag indicating whether a property may or may not be in `create` data. This flag then can be used e.g. for Cloudant's `_rev` field, see https://github.com/strongloop/loopback-connector-cloudant/issues/55

Similarly, we need to specify that `User.create` body must contain a required `password` property, that's otherwise hidden from all other payloads.

**Comment by bschrammIBM** [comment] 2017-05-24 18:20
This issue is producing a 422 error in the Testing a LoopBack project tutorial. It is causing confusion for the customers. Any chance it could get fixed?

**Comment by bajtos** [comment] 2017-05-25 15:22
@bschrammIBM Thank you for bringing this issue into our attention. Could you please give us the link to "Testing a LoopBack project tutorial" you have mentioned?

@raymondfeng @ritch @kjdelisle ping

**Comment by bschrammIBM** [comment] 2017-05-25 15:39
Here is the tutorial mentioned:
https://www.ibm.com/support/knowledgecenter/SSMNED_5.0.0/com.ibm.apic.toolkit.doc/tutorial_cli_project_test.html
 
I have added the following note which will be in a future release of the Knowledge Center (unless this issue gets fixed!):
 
The generated data sample requires editing in order to produce a sample response. Remove the line for "id" and the comma at the end of the previous line. The sample code will look similar to the following: { "type":"ATM", "phone":"(854)509-3813"}
 
Yours,
Barbara
----- Original message -----From: Miroslav Bajtoš <notifications@github.com>To: strongloop/loopback <loopback@noreply.github.com>Cc: bschrammIBM <barbara.schramm@ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [strongloop/loopback] Incorrect swagger definition for models with forceId:true (#2924)Date: Thu, May 25, 2017 8:22 AM 
@bschrammIBM Thank you for bringing this issue into our attention. Could you please give us the link to "Testing a LoopBack project tutorial" you have mentioned?
@raymondfeng @ritch @kjdelisle ping

**Comment by jannyHou** [comment] 2017-05-25 15:40
> Instead of hard-coding detection of forceId, we should come up with a property flag indicating whether a property may or may not be in create data. This flag then can be used e.g. for Cloudant's _rev field

@bajtos I agree with this solution, how about name the flag as `readOnly`? since those properties would be generated by database, user could only read it but not write.

**Comment by jannyHou** [comment] 2017-05-25 15:41
@bschrammIBM Thanks! I will work on the fix asap

**Comment by jannyHou** [comment] 2017-05-25 15:48
Task:

- [ ] Add a property flag, when turning on, swagger doesn't mark it as required.
- [ ] Make sure apic designer and loopback explorer don't show those fields with `flag: true` in `create`, `update`, `replace` methods. 
- [ ] Test cases
- [ ] Add the flag in our doc

**Comment by bajtos** [comment] 2017-05-25 15:56
> how about name the flag as `readOnly`? since those properties would be generated by database, user could only read it but not write.
> make sure apic designer and loopback explorer don't show those fields with flag: `true` in `create`, `update`, `replace` methods.

I am afraid this issue is more complex.

 - The fields `id` and `_rev` must not be present in the payload of `create` operation, but they must be present in the payload of `update` and `replace` methods. I feel `readOnly` is not capturing this intent very well. Perhaps `generated: true` may be better?

 - The field `password` must be present in `create`, but not in `update` and `replace`. I am not sure what flag name to use, maybe `createOnly`?

**Comment by dhmlau** [comment] 2017-05-25 20:29
Sorry that I might be new to this topic... 

From the documentation, https://loopback.io/doc/en/lb3/Embedded-models-and-relations.html, I thought `forceId` is to force the generation of id, so theoretically, it shouldn't be required in the `create` operation.  
It seems like that's not the case.  but wouldn't the solution be making sure the `forceId` option does what it's supposed to do?  

Unless we want to specify this kind of behavior beyond `id`, then I agree with @bajtos ' comment above.

**Comment by crandmck** [comment] 2017-05-25 20:58
@dhmlau I believe this is a _different_ `forceId` property that is part of the relation definition.  

It's unfortunate that it has the same name as the top-level `forceId` property being discussed here, which is documented in https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties.

**Comment by dhmlau** [comment] 2017-06-07 16:44
From @bajtos 
> I think the tutorial is referring to the following page: https://www.ibm.com/support/knowledgecenter/SSFS6T/com.ibm.apic.toolkit.doc/tutorial_cli_project_test.html

**Comment by dhmlau** [comment] 2017-06-30 13:25
@superkhau @strongloop/sq-lb-asteroid, PTAL.

**Comment by bschrammIBM** [comment] 2017-07-08 00:45
Please LMK if this issue is going to be resolved.

**Comment by superkhau** [comment] 2017-07-08 00:56
@rashmihunt PTAL when you get back

**Comment by superkhau** [comment] 2017-07-11 16:42
Timeboxed to 5, re-estimate after spike at

**Comment by rashmihunt** [comment] 2017-08-04 20:30
- Separated out the work done in Sprint 41 into https://github.com/strongloop-internal/scrum-asteroid/issues/275
-  keeping this item for next sprint sprint and re-estimated for the remaining work - mainly, adding few more tests, fixing test case regressions, PR review and npm publish all 3 repos.

**Comment by rashmihunt** [comment] 2017-08-07 23:59
Making it to 8 points based on the issue found during the review and left over work

**Comment by rashmihunt** [comment] 2017-08-23 05:13
Will be closing this issue since all the  PRs for this feature are merged and published to npm 
- https://github.com/strongloop/loopback-datasource-juggler/pull/1453
- https://github.com/strongloop/loopback/pull/3548
- https://github.com/strongloop/loopback-swagger/pull/92
- https://github.com/strongloop/loopback-sdk-angular/pull/276

@bschrammIBM  please open a doc issue to remove the workaround added in the documentation which talks about removing the 'id" field explicitly from the JSON input to avoid validation error.  @bajtos wondering if API designer picks up latest version of this from npm or it needs to change anything from the designer side (loopback-workspace version?)  to pick up latest version from npm?

**Comment by bajtos** [comment] 2017-08-23 07:25
> wondering if API designer picks up latest version of this from npm or it needs to change anything from the designer side (loopback-workspace version?) to pick up latest version from npm?

IIRC, API Connect locks down the dependencies to the latest version at the time a new APIC version is published. In which case a new release of `apiconnect` is need to ship this fix to our customers. Perhaps @kraman can help us here?

**Comment by crandmck** [comment] 2017-08-23 17:48
Since @bschrammIBM is on vacation atm, I created the doc issue https://github.ibm.com/apimesh/apiconnect-docs/issues/395.

**Comment by dhmlau** [comment] 2017-11-17 03:55
Per @crandmck 's comment, assign this to @bschrammIBM as well.

**Comment by bschrammIBM** [comment] 2017-11-20 19:15
@rashmihunt 
Can this be closed?

**Closed by bschrammIBM** 2017-11-20 19:15 UTC
Labels: customer, feature, p1, review
