### ISSUE TITLE
no way to protect nested relations

### ISSUE THREAD

**Issue by dtaylor7** [strongloop/loopback#2766] opened 2016-09-20 15:42 UTC
Consider the following problem:

There are three models:

 1. User
  - has many `Payment Details`
  - has many `Users` through `Contacts`
 2. Payment Details
  - belongs to `User`
 3. Contacts (User-to-User link table)
  - belongs to `User`
  - has one `User`

A `User` can get their `Payment Details` information:

`/users/{user_id}/payment_details`.

A `User` can also get their `Contacts`:

`/users/{user_id}/contacts`.

**But** a `User` can also get their `Contacts` `Payment Details`: 

`/users/{user_id}/contacts?filter={"include":"payment_details"}`

We need a way to restrict the `Payment Details` relation to the **$owner** of `User`.

**Comment by dtaylor7** [comment] 2016-09-20 16:16
for now i am manually checking to see if the owner is the one accessing the relation:

    PaymentDetails.observe('access', function restrict(ctx, next) {

      if(_.isObject(ctx.query.where) && ctx.query.where.user_id && ctx.query.where.user_id.inq){
        var id = app.models.user.getCurrentUserId();
        if(validate(ctx.query.where.user_id.inq[0] === id, 'Unauthorization Access', "UNAUTHORIZATION_ACCESS", 403, next)){return;}
      }

      next();

    });

**Comment by loay** [comment] 2016-09-20 18:08
Hi @dtaylor7, can you please provide a sample repo so I can test this issue? Thanks.

**Comment by dtaylor7** [comment] 2016-09-20 19:04
Hi @loay, Sure have put one together for you: [loopback-protected-relation.git](https://github.com/dtaylor7/loopback-protected-relation.git)

So if you login as user id: 1. Go to the explore [user_prototype_get_contacts](http://localhost:3000/explorer/#!/user/user_prototype_get_contacts) and use the filter `{"include":"payment_details"}`. In an ideal world you wouldn't be able to include `payment_details` as that relation is private and belongs to the user id. 1.

Cheers

**Comment by loay** [comment] 2016-09-21 15:02
Thanks a lot. I will have a look and get back to you ASAP.

**Comment by loay** [comment] 2016-09-30 18:37
Hi @dtaylor7 
Both user and user2 have the same email. 
when the code is changed to 
```
app.models.user.create({
    password: 'user',
    email: 'user1@test.com'
  }, function(err, user){
```
the expected error 401 is obtained.

**Comment by loay** [comment] 2016-10-07 14:32
Closing now. If the issue is not fixed, then please leave a comment and I will re-open. Thanks.

**Closed by loay** 2016-10-07 14:32 UTC
Labels: triage
