### ISSUE TITLE
When using a model type as return type in remote method, it becomes "object" unless set as root

### ISSUE THREAD

**Issue by l2fprod** [strongloop/loopback#2447] opened 2016-06-17 11:01 UTC
I have a remote method defined with this return:

```
    returns:
      {
        arg: "token",
        type: "AccessToken",
        root: true,
        description: "The token"
      }
```

With this, the explorer correctly shows the model of the AccessToken type as model schema for the return:

![image](https://cloud.githubusercontent.com/assets/12746550/16148637/32948bd8-348b-11e6-8c61-a564d048726a.png)

Now if I remove root: true, the explorer shows:

![image](https://cloud.githubusercontent.com/assets/12746550/16148663/57ded038-348b-11e6-926b-58af934f8484.png)

Notice the type of "token" is "object". I would expect to see "AccessToken" there.

The same type of issue happens with a returns defined as:

```
[
      {
        arg: "token",
        type: "AccessToken"
      },
      {
        arg: "user",
        type: "User"
      }
    ]
```

The model schema would show "object" for "token" and "user" instead of their actual Loopback types.

**Comment by gunjpan** [comment] 2016-06-23 21:29
I see that setting `root: true` returns results as a single object, not assigned to `arg` value in response
([see this](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-ReturningdataoutsideofaJSONfield)). Unfortunately, don't have enough info to drive to a conclusion why it happens.
@bajtos : Thoughts?

**Comment by bajtos** [comment] 2016-06-24 16:16
Here is the patch that added support for generating schema for non-root arguments: https://github.com/strongloop/loopback-swagger/commit/b23e08cfe110db539ae6c3b8a4ec82ad58a999e8 My guess is that we don't correctly recognize `AccessToken` as a known model and emit `object` instead.

**Comment by gunjpan** [comment] 2016-07-06 17:32
@l2fprod: Did Bajtos' answer help you?

**Comment by l2fprod** [comment] 2016-07-06 19:48
AFAIU the answer is more a pointer to the code for someone in the dev team to fix the issue rather than a solution for me, a loopback user. AccessToken is a loopback model so I guess there is a bug somewhere here.

**Comment by bajtos** [comment] 2016-07-27 14:23
This looks like a bug. @gunjpan could you please check if you are able to reproduce it on our side? After we have reproduced the problem, this github issue should be labelled as `bug`.

**Comment by gunjpan** [comment] 2016-08-10 22:11
@bajtos : Yes, I was able to reproduce it. Flagging as a bug.

**Comment by rashmihunt** [comment] 2017-06-28 20:47
Adding P1 label since a PR (https://github.com/strongloop/loopback-swagger/commit/b23e08cfe110db539ae6c3b8a4ec82ad58a999e8) seemed to have broken the current code and assigning to team-apex since @gunjpan was able to reproduce the issue.

**Comment by dhmlau** [comment] 2017-07-05 02:20
Removing `team-apex` label since `loopback-swagger` is owned by `asteroid`
cc @superkhau  @bajtos

**Closed** 2018-07-10 12:34 UTC
Labels: bug, p1, team-asteroid
