### ISSUE TITLE
Add support for regular expression in queries.

### ISSUE THREAD

**Issue by slawo** [strongloop/loopback#963] opened 2015-01-01 21:36 UTC
Is it possible to add a pendent to like (rlike) which would take regular expressions to run in the database?Today, it seems, all major databases accept regular expressions to query the content of the db.

**Comment by raymondfeng** [comment] 2015-02-06 00:06
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/385

**Closed by raymondfeng** 2015-02-06 00:06 UTC
Labels: feature
