### ISSUE TITLE
(node:6444) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by rizvanhaider** [strongloop/loopback#3090] opened 2017-01-11 09:12 UTC
` slc loopback:relation`
**Throws Error**

```
(node:6444) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'type' of undefined


events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'type' of undefined
    at C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\inquirer\lib\objects\choices.js:16:12
    at Array.map (native)
    at new module.exports (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\inquirer\lib\objects\choices.js:15:26)
    at Prompt.module.exports (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\inquirer\lib\prompts\base.js:43:24)
    at new Prompt (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\inquirer\lib\prompts\list.js:26:8)
    at PromptUI.fetchAnswer (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\inquirer\lib\ui\prompt.js:77:16)
    at tryCatcher (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.next (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:3547:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\DELL5110\AppData\Roaming\npm\node_modules\strongloop\node_modules\rx\dist\rx.js:5883:51)
```

**Comment by gunjpan** [comment] 2017-01-11 14:15
@rizvanhaider : Hi, could you please provide the steps to reproduce?
 I tried running `slc loopback:relation` and it works as intended on my end. 
Possibly, something messing up packages. I would recommend:
- first uninstall`strongloop` by `npm uninstall -g strongloop` and do `npm cache clean`.  
- reinstall `strongloop` globally : `npm install -g strongloop` and try the same command one more time.

If it doesn't work, please provide me with the sample repo to further assist you.

**Comment by rizvanhaider** [comment] 2017-01-12 09:47
@gunjpan : thanks for your response, I had tried same on my two local machines and also on VPS running ubuntu 16.04, all are generating the same error.

**Comment by gunjpan** [comment] 2017-01-20 21:23
@rizvanhaider : it's happening because you've this file [model-config.json](https://github.com/rizvanhaider/node-shop/blob/master/common/models/model-config.json), which is wrong place for it. It confuses `slc-relation` as it can't decide which one is correct: that one or the one in `server` dir (the correct one).
Delete this file and it should resolve it. Deleting worked for me. 

Closing this now. Should you need any assistance, please let me know. Thank you.

**Closed by gunjpan** 2017-01-20 21:23 UTC
Labels: triage, waiting
