### ISSUE TITLE
No validation occuring when updating (PUT) a document with the ID as a string

### ISSUE THREAD

**Issue by SumeetR** [strongloop/loopback#586] opened 2014-09-25 13:51 UTC
Hi,

I have discovered an issue when using the PUT method to update a record. We are using mongodb as the database and communicating with it through Loopback 2.0.

We have a model called Activity and its .json file looks like this, please note that both properties are set to required:

```
{
  "name": "Activities",
  "strict": true,
  "options": {
    "idInjection": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "type": {
      "type": "string",
      "required": true
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
``` 

When I GET an object from the server, it returns the following object:

``` 
{
   id: "5420902b5bab5bf00fd6339b",  
   name: "Joao", 
   type: "activityA"
}
``` 

Now if I update this object, deleting the name or type field (so they are blank or null) and send it back to the server, I get a 200 OK response and the data has been correctly updated, even though the strings are in blank or null.

I tested this on the Loopback explorer and found out that the issue is due to the formatting of the ID field. 

So, the first test I did, the data looked like this at first, with the ID as an object (mimicking what the explorer shows as 'model schema'):

``` 
{
  "name": "",
  "type": "activityA",
    "_id": {
        "$oid": "5420902b5bab5bf00fd6339b"
    }
}
``` 

This returns a 422 Validation Error message notifying that the name field cannot be blank. But, if I format the data as follows, I am able to carry out the PUT method. Notice the difference in the ID field, which is now a string:

``` 
{
  "name": "",
  "type": "activityA",
  "id": "5420902b5bab5bf00fd6339b"
}
``` 

The above returns a 200 OK message and checking the database, the record has been updated with an empty string for name. 

This is strange as the object above (ID as string) is exactly how data is returned by the server when carrying out a GET method, thus updating this returned object seems to bypass the validation if the ID is formatted as a string rather than an object. 

Can someone please advise how to proceed with this? Is there something wrong in the model definition or is it a loopback issue? Please note that this does not occur when creating a new document, only when updating an existing one (hence the attention given to ID formatting).

Thank you for your time,
Sumeet

**Comment by aarnaud** [comment] 2015-03-12 11:11
+1 same issue with id as uuid

**Comment by bananajohnny** [comment] 2015-03-21 16:02
+1

**Comment by shlomiassaf** [comment] 2015-03-24 18:57
+1, same issue here, POST works, PUT does not.

**Comment by shlomiassaf** [comment] 2015-03-24 18:59
@bajtos , @raymondfeng  I think you should look into this...

**Comment by bajtos** [comment] 2015-03-24 22:12
This is a duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/262, see also https://github.com/strongloop/loopback-datasource-juggler/blob/e13c0cdc12467aff5f347fa1112c03ba1dcdbb8b/lib/dao.js#L396-L398

**Comment by shlomiassaf** [comment] 2015-03-24 22:13
:+1:

**Comment by loay** [comment] 2015-12-02 19:40
Is this good to close? Are we still running into issues with validation?

**Comment by bajtos** [comment] 2015-12-04 16:09
I believe the issue was fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/565.

Note that backwards compatibility was preserved, you need to enable validations for PUT requests via a new model setting `validateUpsert: true`.

Example `common/models/my-model.json`:

```json
{
  "name": "MyModel",
  "validateUpsert": true
}
```

**Closed by bajtos** 2015-12-04 16:09 UTC
Labels: bug
