### ISSUE TITLE
auto validate property data type of model support?

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1282] opened 2015-04-06 14:07 UTC
I use mongo connector
My model has property type number
When client call Create api , post data of above field is a string "abc" , loopback create record success with null value of above field

**Comment by superkhau** [comment] 2015-04-06 17:14
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by nvcken** [comment] 2015-04-07 02:54
when I debug, I find out if my post data of that field (type number) is a string value ("abc")
At model.setup function, I get this.thatField = NaN
So I wonder seem loopback has not "native" catch wrong type data "not a number" then should return error , something like "this field can't blank".... 
Why still get NaN value

**Comment by agebrock** [comment] 2015-04-19 20:14
hi @superkhau,
you can review the bug here: 
https://github.com/agebrock/loopback-sandbox/blob/master/server/boot/feature_bug_typecheck.js

just run it.
i guess the problem is not to throw if casting failed.

**Comment by superkhau** [comment] 2015-04-19 20:31
You are you not creating a boot script correctly. You should have `module.exports = function` etc.

1. You can use our boot script generator to generate a synchronous or asynchronous boot script.
2. If you are trying to create sample models, you can do that using an asynchronous boot script like so:

```
module.exports = function(app, cb) {
  app.models.CartItem.create([
   {tax: ..., price: ...}
  ], cb)
}
```

This is assuming you created a CartItem model via `slc loopback:model CartItem`. I will dig a bit deeper later to see if I have any issues creating it manually like you did.

**Comment by nvcken** [comment] 2015-04-20 02:46
what about with normal created model ? No boot script

**Comment by agebrock** [comment] 2015-04-20 19:03
i just put it in the bootscript to show the error. You can reproduce it with any model at any position if you like.

**Comment by bajtos** [comment] 2015-04-28 08:53
LoopBack coerces values passed as model properties, so for example `"123"` is a valid value for a property of type `Number`.

The patch https://github.com/strongloop/loopback-datasource-juggler/pull/568 fixed the problem where the validation of `required:true` were accepting `NaN` values too.

Please modify your example and add `requred: true` to all number properties that should not support undefined/null values. Upgrade to the latest juggler version and let us known whether the problem is fixed for you.

**Comment by superkhau** [comment] 2015-05-12 07:13
@agebrock Did @bajtos's suggestion work for you? Can I close this?

**Comment by nvcken** [comment] 2015-05-12 09:29
OK, thanks for help

**Closed** 2015-05-12 16:45 UTC
Labels: #wip, triage, waiting
