### ISSUE TITLE
Swagger: skipping unknown type "$new_AccessToken".

### ISSUE THREAD

**Issue by agung-wete** [strongloop/loopback#3615] opened 2017-09-13 23:15 UTC
# Description/Steps to reproduce
Fresh install loopback, then run `node .`

# Expected result
No error

# Result
```
Swagger: skipping unknown type "$new_AccessToken".
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
```

# Additional information
Version:
loopback 3.11.1
loopback-swagger 4.3.0
loopback-explorer 2.0.2

win32 x64 6.11.3

**Comment by george-oakling** [comment] 2017-09-18 18:43
Same problem here

**Comment by iorlandini** [comment] 2017-09-18 20:54
Me too! I have the same problem with all hasMany relations!

**Comment by ArturoBurela** [comment] 2017-09-19 02:25
I have the same issue, but does not seem to cause malfunction.

**Comment by george-oakling** [comment] 2017-09-19 11:48
it causes malfunction when you generate swagger for external use, you get errors in parsing JSON/YAML definition

**Comment by fabiorecife** [comment] 2017-09-23 06:48
Me too!
Swagger: skipping unknown type "$new_AccessToken".
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

loopback@3.11.1
loopback-swagger@5.0.0

macOs Sierra
Darwin Kernel Version 16.7.0
Node v7.10.0

**Comment by septk** [comment] 2017-09-23 10:29
same here

**Comment by Balipeace** [comment] 2017-09-24 05:42
same

**Comment by gpzenpy** [comment] 2017-09-27 08:55
same

**Comment by vjtc0n** [comment] 2017-09-28 10:26
same here, dont' know what's going on?

**Comment by ahelliet** [comment] 2017-09-29 22:17
Solve this by update the package.json with "loopback": "3.2.1", i'm not sure this is the right way but it's works for me

**Comment by ArturoBurela** [comment] 2017-09-29 22:52
@ahelliet, I tried your solution and the message disappears, but running lb export-api-def still produces invalid definitions.

**Comment by agung-wete** [comment] 2017-09-30 23:30
Updated to
+ loopback@3.14.0
+ loopback-component-explorer@5.1.0

message still there

**Comment by maximedubois** [comment] 2017-10-06 11:58
same here... ??

**Comment by biskandar** [comment] 2017-10-07 05:18
Same here .

├── eslint-config-loopback@8.0.0
├─┬ loopback@3.14.0
│ ├── loopback-connector-remote@3.1.1
│ ├─┬ loopback-datasource-juggler@3.12.0
│ │ ├─┬ loopback-connector@4.3.0
│ ├─┬ loopback-phase@3.0.0
│ │ ├── loopback-datatype-geopoint@1.0.0
│ │ ├─┬ loopback-phase@1.4.1
├─┬ loopback-boot@2.26.2
├─┬ loopback-component-explorer@5.1.0
│ ├── loopback-swagger@5.0.0

**Comment by Praful-Mali** [comment] 2017-10-08 11:24
Swagger: skipping unknown type "$new_AccessToken".
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer

**Comment by Santiago-vdk** [comment] 2017-10-14 00:03
Same, using last version.

**Comment by FlorianBouron** [comment] 2017-10-14 18:51
Same issue here!
    "loopback": "^3.15.0",
    "loopback-boot": "^2.26.2",
    "loopback-component-explorer": "^5.2.0",
osX 10.12.6
Node: v6.11.3

**Comment by inyee786** [comment] 2017-10-16 20:00
i also face the same issue,
it happen when i abruptly close terminal where the running node is running,
i slove it by closing the all terminal, and run "node ." in fresh terminal

**Comment by jcurlier** [comment] 2017-10-18 04:48
Same problem here

**Comment by el-davo** [comment] 2017-10-18 15:49
same here

**Comment by danielbastos** [comment] 2017-10-21 19:54
Same here.

I tested with some versions and problem only appears in loopback >= 3.14.0

**Comment by el-davo** [comment] 2017-10-21 21:05
Not sure if its relevant to everyones situation, however i ran into this issue when running with docker. I had a docker-compose file that was running the container. In the docker-compose file I was running the container with user "Node". Removing this user and using the default user made the issue go away.

**Comment by george-oakling** [comment] 2017-10-25 13:14
Still present in 3.16.0... @bajtos - I would like to fix it, but I can't find any reference of where and what is this causing...

**Comment by maximedubois** [comment] 2017-10-25 13:31
not impressed by the non feedback on this...

**Comment by raymondfeng** [comment] 2017-10-25 14:13
I’ll take a look today.

**Comment by bajtos** [comment] 2017-10-26 14:36
From what I remember about our swagger spec generator, we are intentionally omitting type definitions that are not used by any publicly exposed methods, to prevent the swagger spec to be polluted with built-in models like `Role` and `ACL` that are known to LoopBack runtime, but that are not relevant for the REST API.

I suspect the code detecting relations (and deciding which models to include) does not know that `$new_AccessToken` definition is a part of `AccessToken` model. I may be wrong though, I'll leave it up to you @raymondfeng to investigate more.

**Comment by george-oakling** [comment] 2017-10-26 14:48
Thank you guys!

**Comment by agung-wete** [comment] 2017-11-04 12:29
works for me. Thank you @raymondfeng @bajtos

**Comment by twboc** [comment] 2017-12-06 14:42
I am still reproducing this error with dynamically created models on boot time.

PACKAGE:
{
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^3.17.0",
    "loopback-boot": "^3.1.0",
    "loopback-swagger" : "^5.5.0",
    "loopback-component-explorer": "^5.2.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  }

CODE: 

`'use strict';

var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback({localRegistry: true});

var ds = loopback.createDataSource('postgresql', {
  "host": "localhost",
  "port": 5432,
  "database": "db",
  "username": "user",
  "password": "pass"
});

var acceptedTables = [
  'users',
  'organisation',
  'expectation',
  'location',
  'tags',
  'telephone',
  'email',
  'experience',
  'project',
  'skill',
  'education',
  'language',
  'activity',
  'hobby',
  'social',
  'link',
  'document',
  'user_organisation',
  'users_data',
  'document_permissions',
  'tag_relations'
]

var modelDefinitionsConf = {views: true};
var modelConfig = { schema: 'public' };

function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

function generateModelName(modelName){
  var nameArr = modelName.split(/_|-/);
  var nameArr = nameArr.map(function(el){ return el[0].toUpperCase() + el.substr(1); });
  return nameArr.join('');
}

app.start = function() {
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    ds.discoverModelDefinitions(modelDefinitionsConf, function(err, data){
      for (var el in data) {
        (function(modelName){
          if (acceptedTables.indexOf(modelName) >= 0) {
              ds.discoverSchema(modelName, function (err, schema) {
                var model = ds.createModel(schema.name, schema.properties, schema.options);
                app.model(model, {public : true, dataSource: ds });
              })
          }
        })(data[el].name)
      }
    });
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
};

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) throw err;

  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});
`

**Comment by bajtos** [comment] 2017-12-08 14:50
@twboc could you please open a new issue for the problem you are experiencing and be more specific about the kind of error you are seeing? This issue is specifically about `$new_AccessToken`, which is not part of your discovered/auto-imported models AFAICT.

I am closing this issue as fixed.

**Closed by bajtos** 2017-12-08 14:50 UTC
Labels: bug, in-progress
