### ISSUE TITLE
 property name with `type`  is not working correctly with loopback complex model

### ISSUE THREAD

**Issue by PRAKASH-SIVAGURUNATHAN** [strongloop/loopback#4131] opened 2019-02-07 07:01 UTC
We have a model definition as follows
````
{
  "name": "accounts",
  "plural": "accounts",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "items": {
      "type" : {
          "itemname": { "type": "string"},
          "type": { "type": "string" }
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
````

In explorer the structure of the items is coming as shown below

<img width="439" alt="screen shot 2019-02-07 at 12 23 09 pm" src="https://user-images.githubusercontent.com/13993128/52395208-30ff1400-2ad3-11e9-861f-a834dd15ac9d.png">

When we test the model by providing the values for `items` property, the response does not have a valid structure for `items`
<img width="481" alt="screen shot 2019-02-07 at 12 29 30 pm" src="https://user-images.githubusercontent.com/13993128/52395444-3315a280-2ad4-11e9-8099-8919d7f176db.png">

**Comment by PRAKASH-SIVAGURUNATHAN** [comment] 2019-02-07 11:19
NOTE: If we have the property name as `type` in the top-level it works fine.  Loopback is behaving differently only when the `type` model property is defined within a complex structure.

**Comment by jannyHou** [comment] 2019-02-07 20:31
Hi @PRAKASH-SIVAGURUNATHAN could you fork https://github.com/strongloop/loopback-sandbox and provide some example code to reproduce your error? Thanks. I can help you investigate.

From your description, a property named "type" has conflict with some code in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js, it will be quicker for us to debug with a sample app.

**Comment by PRAKASH-SIVAGURUNATHAN** [comment] 2019-02-12 09:26
@jannyHou : I have created an forked branch of loopback-sandbox and pushed the model which our product is using. Please refer to the forked branch of 
https://github.com/PRAKASH-SIVAGURUNATHAN/loopback-sandbox

**Comment by hacksparrow** [comment] 2019-02-13 14:10
Thanks for the sample app @PRAKASH-SIVAGURUNATHAN. I can confirm it as a bug. Taking a look at the cause and trying to find a fix.

**Comment by hacksparrow** [comment] 2019-02-13 14:55
@PRAKASH-SIVAGURUNATHAN which connector are you using, by the way?

**Comment by hacksparrow** [comment] 2019-02-19 15:35
Bug is caused by the sub-property name `type` conflicting with internal Model properties.  Relevant files - https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-definition.js#L237, https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L886.

We are already not allowing `constructor` as a top level key. `type` works fine as a top level key, but causes conflict when used as a sub-key.

I am working on a solution.

**Comment by hacksparrow** [comment] 2019-02-27 14:35
@PRAKASH-SIVAGURUNATHAN it is fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1693.

**Closed by hacksparrow** 2019-02-27 14:35 UTC
Labels: bug, customer
