### ISSUE TITLE
slc loopback:relation` not working

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2345] opened 2016-05-16 23:10 UTC
$ slc loopback:relation
? Select the model to create the relationship from: note
? Relation type: belongs to
? Choose a model to create a relationship with: (other)
? Enter the model name: k8
? Enter the property name for the relation: (k8) h

/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true

**Comment by cgole** [comment] 2016-05-16 23:10
this is affecting apic loopback in production.

**Comment by superkhau** [comment] 2016-05-16 23:32
Closing as duplicate of https://github.com/strongloop/loopback/issues/2292#issuecomment-219378029. @bajtos reproduced it himself and is aware of the issue.

**Closed by superkhau** 2016-05-16 23:32 UTC
Labels: bug, major
