### ISSUE TITLE
verification token not getting removed on confirm

### ISSUE THREAD

**Issue by gshireesh** [strongloop/loopback#1848] opened 2015-12-02 00:10 UTC
https://github.com/strongloop/loopback/blob/master/common/models/user.js#L467

i hope the code here should be 
user.verificationToken = "";

**Comment by raymondfeng** [comment] 2015-12-02 03:43
It should be set to `null`. Patch please.

**Comment by gshireesh** [comment] 2015-12-02 05:28
when i tried the memory db, i could see that verification token is not getting removed. 
Do you want me to make a pull request for this.??

**Comment by Amir-61** [comment] 2015-12-04 21:25
@gshireesh Possibly duplicate of [this issue](https://github.com/strongloop/loopback/issues/414). I will be closing this ticket. Please comment there.

Thanks so much :-)

**Closed** 2015-12-04 21:27 UTC
Labels: Beginner Friendly, bug, triage
