### ISSUE TITLE
Inject ctx not work with update referente many

### ISSUE THREAD

**Issue by Nenifa** [strongloop/loopback#3567] opened 2017-08-15 13:13 UTC
In loopbackjs the follow api not working. PUT /Bookstore/{id}/books/rel/{fk} Add a related item by id for books.

I define in phase of boot

app.remotes().before('*.*', inject);
app.remotes().before('*.prototype.*', function(ctx, instance, next) {
   inject(ctx, next);
});
function inject add to options more information.

But in this case the first operation is Model.observe('access',.... define in mixin and not inject.

The api fail. Someone has already had the same problem?

**Comment by kjdelisle** [comment] 2017-08-15 17:14
@Nenifa Would you be able to make an example application that demonstrates this problem, and upload it as a repository to GitHub?

**Comment by Nenifa** [comment] 2017-08-16 11:15
I can't publish the code in github, can i send you in private?

**Comment by kjdelisle** [comment] 2017-08-16 17:20
@Nenifa I wouldn't want you to send me any sensitive code or information. What I'm asking for is an example repository that mirrors the _logic_ of what you're trying to accomplish, without needing to include any of your proprietary code, secrets and the like. Since you know what it is you're attempting to achieve, you should be able to make a sample application that behaves similarly.

**Comment by kjdelisle** [comment] 2017-08-16 17:20
Additionally, this app doesn't need to be a reflection of the entirety of your own app, just whatever's required to demonstrate the problem as you're experiencing it.

**Comment by Nenifa** [comment] 2017-08-17 09:21
@kjdelisle Here is repository https://github.com/Nenifa/exampleApp.git
There is a file data.json with data. If you call api
PUT /Queue/{id}/items/rel/{fk} 
this fail in operation hook access of mixin
Thank you very much

**Comment by Nenifa** [comment] 2017-08-19 15:35
@kjdelisle Have you also succeeded to reproduce the error?

**Comment by kjdelisle** [comment] 2017-08-22 02:03
@Nenifa I've been working through your provided example and I've been wondering a few things about it.

In the [base-model.js mixin](https://github.com/Nenifa/exampleApp/blob/master/server/mixins/base-model.js#L8), you're making reference to elements within the context object, but I wasn't certain how you were setting up that context in the first place.

Working through this, I assumed you wanted your context to be related to a User session, so I enabled the User model once more. While attempting to login, I ran into another error where the callback function wasn't set to anything. As it turns out, the arguments being passed to the `User.login` function were slightly askew:

If you look at [this code here](https://github.com/Nenifa/exampleApp/blob/master/server/boot/inject-ctx.js#L15), it actually breaks the format of the `User.login` method, because it alters the expected parameters of the function from a framework perspective, but the actual `User.login` code is not changed similarly, meaning the [User.login function](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L207) is receiving an Object instead of a callback:

<img width="374" alt="screen shot 2017-08-21 at 9 42 22 pm" src="https://user-images.githubusercontent.com/2053534/29544992-b1f5f2dc-86b9-11e7-9d70-fc0bbe2cff03.png">

If you fix this, and additionally, perform a login with a valid `User` instance (POST to /Users/login) before making your request, it should provide the context you need to avoid tripping [this userId/domainId check logic] (https://github.com/Nenifa/exampleApp/blob/master/server/mixins/base-model.js#L8).

There could be other context-related issues you'll run into as you work through this issue, but the ones I've found while debugging are as follows:
- You need to pass in the datasource for the `server/authentication.js` boot script. http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#preparing-access-control-models
- You need to make the User routes accessible so that logins can occur (which generates your AccessTokens and creates contexts which will avoid triggering your logic checks)
- You need to _avoid_ modifying the expected arguments of built-in Model functions. If you want to alter their behaviour in this way, then you should [extend them with your own CustomUser model](http://loopback.io/doc/en/lb3/Extending-built-in-models.html)

If you need more help, please don't hesitate to ask the community over here: https://groups.google.com/forum/#!forum/loopbackjs

**Comment by kjdelisle** [comment] 2017-08-22 02:04
I'll be closing this issue as it is not a bug. Thank you for your understanding.

**Closed by kjdelisle** 2017-08-22 02:04 UTC
Labels: triaging
