### ISSUE TITLE
AssertionError: false == true while connecting to mysql datasource

### ISSUE THREAD

**Issue by chandreshinf** [strongloop/loopback#2177] opened 2016-03-30 01:06 UTC
Hi All,

I am new to strongloop. Following the tutorials from api documentation. While creating model, I will get error because of selecting mysql datasource. I have already created datasource connection with mysql.

`Select the data-source to attach myModel to: mysqlDs (mysql)`
  `readline.js:924`

 `throw err;`
 `^`
`AssertionError: false == true`

> ```
> at Object.exports.getBaseModelForDataSourceName (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/lib/helpers.js:149:3)
> at null.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/model/index.js: 100:26)
> at module.exports (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/run-async/index.js:15:21)
> at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:42:5)
> at module.exports (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/run-async/index.js:15:21)
> at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:16:7)
> at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)
> at setDisposable (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5741:44)
> at AnonymousObservable.innerSubscribe [as _subscribe] (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5755:9)
> at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:1604:19)
> ```

any help would be appreciated.
thanks

**Comment by jannyHou** [comment] 2016-04-05 21:55
@chandreshinf I m trying to reproduce your error, if I understand correctly, you steps should be:
[1] `slc loopback` to create an app
[2] `npm install loopback-connector-mysql` to install connector
[3] `slc loopback:datasource` to create a mysql connector
[4] `slc loopback:model` to create a model and attach it to mysql datasource

But I tried above steps it works fine for me.
If you are not following above steps, could you fork a sandbox: https://github.com/strongloop/loopback-sandbox and replace it with your code? Or the steps to reproduce it? thanks

**Comment by jannyHou** [comment] 2016-11-04 20:02
I am closing this issue since I could not reproduce the bug. Feel free to reopen it with sample code or any updated info.

**Closed by jannyHou** 2016-11-04 20:02 UTC
Labels: triage, waiting
