### ISSUE TITLE
What is corresponding method to do referencesmany in lb4

### ISSUE THREAD

**Issue by noufalnoufu** [strongloop/loopback#4346] opened 2021-02-18 13:46 UTC
Can you explain how to do referencesmany in loopback 4

https://loopback.io/doc/en/lb3/Embedded-models-and-relations.html#referencesmany

I wanted to store categories and its products Ids as an array in the collection. On get method I need show category info as well as product details as mentioned below .Is there any best with relational model in loopback? I am new in Loopback and node js, please suggest best practice.

Category
{
    "id": "1",
    "Category": "Category 1",
    "products": [
      "1",
      "2"
    ]
},
{
    "id": "2",
    "Category": "Category 2",
    "products": [
      "2",
      "3"
    ]
}

Products
{
    "id": "1",
    "title": "Product 1"
},
{
    "id": "2",
    "title": "Product 2"
},
{
    "id": "3",
    "title": "Product 3"
}

Result 
{
    "Category": "Category 1",
    "products": [
        {
       "id": "1",
           "title": "Product 1"
    },
    {
       "id": "2",
           "title": "Product 2"
    }
    ]
},
{
    "Category": "Category 2",
    "products": [
        {
       "id": "2",
           "title": "Product 2"
    },
    {
       "id": "3",
           "title": "Product 5"
    }
    ]
}

**Comment by achrinza** [comment] 2021-02-18 17:00
@dhmlau I don't permissions to shift this issue to the [LoopBack 4](https://github.com/strongloop/loopback-next) repo. Could you please assist? Thanks

**Comment by dhmlau** [comment] 2021-02-20 16:12
I think it's a duplicate of https://github.com/strongloop/loopback-next/issues/7102. So I'm closing this issue as duplicate and let's continue the discussion over there. Thanks.

**Closed by dhmlau** 2021-02-20 16:12 UTC
Labels: question
