### ISSUE TITLE
some "slc loopback" commands cannot move selection

### ISSUE THREAD

**Issue by rsmamoru** [strongloop/loopback#1731] opened 2015-10-14 18:38 UTC
I don't know if I should submit an issue here. I've posted it in Google Groups.

When I execute "slc loopback:property" command, the program gives me step by step questions, but I cannot move selection with arrow keys, it stays on "ACL".
"slc loopback:relation" and "slc loopback:acl" also have the same problem :-(

But "slc loopback:model" command works fine.

So, is it a bug?

**Comment by superkhau** [comment] 2015-10-14 21:13
What OS are you on? Can you try it again with a new project and provide the step to reproduce the issue? Do the J/K keys work?

**Comment by superkhau** [comment] 2015-10-14 21:18
@rsmamoru I tried it on OSX 10.11 and I am not running into any issues. Can you try updating to the latest version of `slc` (`npm install -g strongloop`).

**Comment by rsmamoru** [comment] 2015-10-15 20:29
I use:
* Windows 8.1 64-bit.
* node-v4.1.1-x64.
* strongloop 5.0.1.

---
This problem occurs in any projects.

The difference between "slc loopback:model" and other commands is it begins with "type an answer" while other commands begin with "selection".

---
**slc loopback:datasource** (no problem)

1. `C:\_strongloop\my-project>slc loopback:datasource`
2. `? Enter the data-source name: mysqlDs`
3. I can choose a connector.

    ```
    ? Select the connector for mysqlDs:
      In-memory db (supported by StrongLoop)
      Email (supported by StrongLoop)
    > MySQL (supported by StrongLoop)
      PostgreSQL (supported by StrongLoop)
      Oracle (supported by StrongLoop)
      Microsoft SQL (supported by StrongLoop)
      MongoDB (supported by StrongLoop)
    (Move up and down to reveal more choices)
    ```

---
**slc loopback:model** (no problem)

1. `C:\_strongloop\my-project>slc loopback:model`
2. `? Enter the model name: Student`
3. I can choose a data-source.

    ```
    ? Select the data-source to attach Student to:
      (no data-source)
      db (memory)
    > mysqlDs (mysql)
    ```
4. I can choose a model's base class.

    ```
    ? Select model's base class:
      Role
      RoleMapping
      Scope
    > User
      (custom)
      Model
      PersistedModel
    (Move up and down to reveal more choices)
    ```
5. `? Expose Student via the REST API? (Y/n) `
6. `? Custom plural form (used to build REST URL): `
7. Add a property.

    ```
    Let's add some Student properties now.
    
    Enter an empty property name when done.
    ? Property name: regnum
    ```
8. I can choose a property type.

    ```
    (!) generator#invoke() is deprecated. Use generator#composeWith() - see http://yeoman.io/authoring/composability.html
       invoke   loopback:property
    ? Property type:
      geopoint
      any
      (other)
    > string
      number
      boolean
      object
    (Move up and down to reveal more choices)
    ```
9. `? Required? (y/N) y`

---
**slc loopback:property**

1. `C:\_strongloop\my-project>slc loopback:property`
2. I **cannot** choose a model. But I can type instead.

    ```
    ? Select the model: (Use arrow keys)
    > ACL
      AccessToken
      Application
      Change
      Checkpoint
      Email
      Role
    (Move up and down to reveal more choices)wow!
    ```
3. `? Enter the property name: birth-order`
4. I can choose a property type.

    ```
    ? Property type:
      any
      (other)
      string
    > number
      boolean
      object
      array
    (Move up and down to reveal more choices)
    ```
5. And so forth.

**Comment by superkhau** [comment] 2015-10-16 04:43
Can you try on node 0.10.x or 0.12.x? It might be a new issue with yeoman and node 4.

**Comment by rsmamoru** [comment] 2015-10-16 13:07
yes, the commands work fine with node 0.12.

2015-10-16 11.43 GMT+07.00, Simon Ho <notifications@github.com>:
> Can you try on node 0.10.x or 0.12.x? It might be a new issue with yeoman
> and node 4.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/strongloop/loopback/issues/1731#issuecomment-148603419


-- 
*Membangun Pasar Sunnah: Memerangi Riba*

Rule 1: Tidak diizinkan Riba
Rule 2: Berlakukan Uang Sunnah
Rule 3: Siapa yang tanam, dia panen. Siapa yang tidak tanam, dia tidak panen

(Syaikh Imran Hosein <http://imranhosein.org>)

**Comment by superkhau** [comment] 2015-10-16 15:42
@raymondfeng Any suggestions here? Should we just recommend users avoid node 4 on windows until yeoman fixes itself?

**Comment by rsmamoru** [comment] 2015-10-16 22:41
OK, I agree with that.

But we can use two versions however.
For example:
* I add Node v0.12 to the Path (environment variable) so it can be run anywhere (good for slc commands).
* I set Node v4 in my IDE settings to test if my apps are compatible with this version.

**Comment by superkhau** [comment] 2015-10-17 01:37
@rsmamoru That sounds like a good solution for now. I've escalated this issue to bug status so we can check it again after yeoman generator updates to a version beyond 0.20.3.

**Comment by superkhau** [comment] 2015-12-01 06:32
@Amir-61 Please follow up on this issue as you are the triage expert for this repo now.

**Comment by pureexe** [comment] 2015-12-27 02:39
same problem
Windows 10
Node 4.2.2

strongloop v6.0.0 (node v4.2.2)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by pureexe** [comment] 2015-12-27 06:50
update: after i have problem on `slc loopback:relation`
now i try to update node to 5.3.0 and everything work fine.

C:\Users\puree>slc -v
strongloop v6.0.0 (node v5.3.0)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by Amir-61** [comment] 2015-12-27 07:05
@pureexe Thanks for bringing this to our attention! Yes it seems it is buggy; I will move this ticket to the right repository and escalate it to resolve it ASAP. Also could you please confirm whether you use windows CLI or ...?

Thanks

**Comment by Amir-61** [comment] 2015-12-27 07:10
FYI; I created [a ticket](https://github.com/strongloop/generator-loopback/issues/131) in `gerenator-loopback` module and escalate it to resolve the issue.

**Comment by pureexe** [comment] 2015-12-27 08:01
@Amir-61  I'm using built-in cmd.exe 
![](http://www.mx7.com/i/c8a/54nADT.png)

**Comment by Webjin** [comment] 2016-01-27 17:01
Had the same problem on Win 10 x64. 
Tried everything posted above.

Upgrading van Node v4.2.3 to v5.5.0 solved it for me.

**Comment by superkhau** [comment] 2016-02-01 23:18
@rsmamoru Are you still running into issue? Can I close this?

**Comment by superkhau** [comment] 2016-02-03 02:26
Closing due to inactivity. Please open a new issue if you are still running into problems.

**Closed by superkhau** 2016-02-03 02:26 UTC
Labels: triage, wrong-repo

**Comment by imeninnik** [comment] 2016-03-25 20:15
```
strongloop v6.0.0 (node v5.9.1)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.0 (4197516)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.20.4 (ce2bd0c)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```
win 10, 
not stable working nor with `slc` nor with `yo`, tried in `far`, `webstorm`, `cmd`, `git bash` and `powershell`

_stable_ here is means that some times it works (one in 2 or so tries)
