### ISSUE TITLE
Too strict validation on User.email

### ISSUE THREAD

**Issue by daankets** [strongloop/loopback#1723] opened 2015-10-10 12:36 UTC
I get the following validation error when trying to persist a user in my local test environment:

```
ValidationError: The `User` instance is not valid. Details: `email` Must provide a valid email (value: **"test@localhost"**).
    at ...(not relevant)
```

According to me, this is a too strict validation for an email address. The spec states that an email address should comply to the pattern <userOrMailBox>@<smtpHostName>. There is no requirement whatsoever that the hostname must also contain a domain name. Of course it is possible to override this by re-implementing the User model, but it would be nice if the current validation was a bit less strict (it is always possible to add a more strict validation on top of it).

**Comment by vdust** [comment] 2015-10-13 18:56
I confirm this issue, but it goes beyond being too strict: it even accepts some invalid email addresses as valid. I created a fork of loopback-sandbox with some examples of addresses that should be accepted  (but aren't) and addresses that should be rejected (but aren't):

https://github.com/vdust/loopback-sandbox

The truth is that email addresses *can't* be validated by a single regular expression. RFC 822 and RFC 2822 describe what valid email addresses are (the 'addr-spec' definition in RFC 2822 covers both) and it's huge work to implement it properly. But some effort should be done in that direction as it would benefit a lot of projects.

**Comment by daankets** [comment] 2015-10-14 06:47
[This library](https://github.com/chriso/validator.js) comes pretty close I believe...

**Comment by superkhau** [comment] 2015-10-14 06:50
@daankets @vdust Would one of you guys like to contribute a patch?

**Comment by vdust** [comment] 2015-10-14 15:28
First, I must correct what i stated in my previous comment: It's [RFC5321](http://tools.ietf.org/html/rfc5321) and [RFC5322](http://tools.ietf.org/html/rfc5322) that define what valid email addresses are in the context that concerns us here. As a result, some of the *valid* addresses i added in my test code (e.g. ``local."quoted word"@example.com``) use deprecated syntax and are probably safe to reject since the semantics of such forms are the same as the recommended fully-quoted local part (``"local.quoted word"@example.com``).

@daankets I saw this library, it but makes some trivial mistakes like assuming a local part is always properly quoted as a single unit (see https://github.com/chriso/validator.js/blob/master/validator.js#L202 ), matching a lot of invalid addresses (i.e. ``"a test@example.com``)

@superkhau I'll see if i get some time to propose a patch in the upcoming weeks. I know of only one email validator that actually does what the RFCs expect ([It can be found here](https://github.com/dominicsayers/isemail)). It's written in PHP but is a strong reference to write an equivalent in javascript. The author also provides an extensive test suite to validate the implementation.

**Comment by vdust** [comment] 2015-10-28 15:28
At the time i commented on this ticket, a port of Dominic Sayers' is_email for node that i read about couldn't be found anywhere. It seems that it is back on here: https://github.com/hapijs/isemail/

    $ npm install isemail

It validates all the test cases of the original implementation and also has support for dns check (optional).
I'll take a look at it and write a patch to use it in loopback.

**Comment by bajtos** [comment] 2016-09-06 12:36
Fixed by #2716 and #2717

**Comment by bajtos** [comment] 2016-09-09 08:25
Released in `loopback@2.33.0`.

**Closed by bajtos** 2016-09-09 08:25 UTC
Labels: #tbr, feature

**Comment by barocsi** [comment] 2017-04-19 09:26
Why is email validation forcefully present during new user creation? Why is this must be coupled this tightly?

**Comment by bajtos** [comment] 2017-04-19 11:06
@barocsi please open a new issue, describe steps to reproduce the problem you are experiencing and actual vs. expected results.
