### ISSUE TITLE
Validation rules are applied in not required properties

### ISSUE THREAD

**Issue by onnoll** [strongloop/loopback#1588] opened 2015-08-13 10:04 UTC
When I define a property *not required* like "languages"
```
{
  "name": "guide",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "languages": {
      "type": [
        "string"
      ]
    },
```

And I define custom validation rules for this property like these:

```
Guide.validatesLengthOf('languages', {min: 1, message: 'You need to add 1 language at least'});
Guide.validate('languages', validatesLanguages, {message: 'Languages are not in supported languages'});
```

Loopback always try to check these rules even when I try to post a new guide without "languages" property, I remember "languages" is not required then whenever I try to create a guide without "languages" I think Loopback should not validate the non-exist property and should only do it when the property exists.

**Comment by superkhau** [comment] 2015-08-13 21:53
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by onnoll** [comment] 2015-08-14 10:08
I create the repository, the URL is: https://github.com/onnoll/loopback-sandbox

STP:
1) Run the project:
  ```
  node .
  ```
2) Go to StrongLoop API explorer. Type http://localhost:3000/explorer in your browser and go ahead.
3) Try to create a new guide without languages property. POST an empty object in */guides* endpoint.

As you can appreciate the validation rules have effect on "languages" property and the server rejects the request although I don't require this property to create a guide. I think that the validation rules should have effect just whenever you add the property to the payload.

**Comment by superkhau** [comment] 2015-09-02 22:43
I think this is a dupe of #1485. Can you confirm and close if that is the case?

**Comment by rkmax** [comment] 2015-09-11 17:38
I'm having the same issue, my users can sign up using his email either phone number, I want add uniqueness and format validations to both properties but only if they are in the payload

**Comment by superkhau** [comment] 2015-09-21 20:00
Closing, dupe of #1485.

**Closed by superkhau** 2015-09-21 20:00 UTC
Labels: duplicate, triage

**Comment by AlexYegupov** [comment] 2016-08-08 16:35
Despite this issue is marked as duplicate of #1485 and both of them are closed...

the problem is still seems unsolved. The test project sandbox (described above) is still shows that  validators are still applied to non-existing non-required fields :(
